### ISSUE TITLE
register BTE as an ARA with the ARS

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#104]
Trung described ARS system at a KGS call, recording here: https://drive.google.com/drive/u/0/folders/1wj0JHXK0RBpM3Pd1y7XpnXhhyse5Lktv

As far as I can see, there are three example wrappers around ARAs:
* https://github.com/NCATSTranslator/Relay/blob/master/tr_ara_simple.py
* https://github.com/NCATSTranslator/Relay/blob/master/tr_ara_rtx.py
* https://github.com/NCATSTranslator/Relay/tree/master/tr_sys/tr_ara_robokop

As I clarified [here](https://ncatstranslator.slack.com/archives/CTJAT0TN3/p1589473690126400), the first two examples above register themselves with the ARS when they are initialized, whereas the robokop wrapper is meant to be registered through the ARS UI.

Some technical discussion on Slack on this topic starting here (see May 13 - May 18): https://ncatstranslator.slack.com/archives/CTJAT0TN3/p1589383511112400

**DUE July 11, 2020**

**Comment by kevinxin90** [comment]
This feature has been implemented.

BTE ReasonerStdAPI instance up at: https://api.bte.ncats.io/ (documentation coming soon).

BTE is currently registered with ARS in documented in this pull request: https://github.com/NCATSTranslator/Relay/pull/15
