### ISSUE TITLE
valid input for Hint module

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#111]
See https://github.com/colleenXu/biothings_explorer/blob/CX_WIPs_Here/jupyter%20notebooks/CX_WIPs/CX_WIP.ipynb for the code and output that demonstrate these issues. 

A few related issues:

1) Abbreviations (e.g. GIST, CML) currently aren't recognized by the Hint module. Including synonym information when querying for BioThings objects (the Hint module) would help. 

2. Partial words (e.g. 'contract' to look for the phenotype contractures) currently aren't recognized by the Hint module. Perhaps this is fine, or perhaps we want to be able to handle these. 
> Note that a hyphenated term works (e.g. 'gastro' will return names with the word 'gastro-intestinal' BUT NOT with the word 'gastrointestinal'). 

3. There's unexpected behavior when singular versus plural words are included in query. See https://github.com/colleenXu/biothings_explorer/blob/CX_WIPs_Here/jupyter%20notebooks/CX_WIPs/CX_WIP.ipynb for an example where "gastrointestinal stromal tumor" (singular) and "gastrointestinal stromal tumors" (plural) give different results. 
> Note that both queries return the same top Disease result.

**Comment by kevinxin90** [comment]
Issue 1 is fixed in this commit: 99a2429115f8457b6a10711f2f1c560f256ade83

Issue 2 & 3 are not BTE issues. These are indeed related to the BioThings APIs (e.g. mygene.info, mydisease.info) which we maintain. Will create an issue over there.

**Comment by kevinxin90** [comment]
Test for GIST is also added as well. https://github.com/biothings/biothings_explorer/blob/master/tests/test_hint.py#L86

**Comment by colleenXu** [comment]
Since Kevin has commented all the issues raised here, I'm going to close this issue.
