### ISSUE TITLE
Disease(s) Treated By Drug

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#113]
see: https://github.com/NCATSTranslator/testing/issues/20

**Comment by kevinxin90** [comment]
We'll provide a temporary fix for the moment. 

Whenever we see a Drug node, we will expand it to include both Drug and ChemicalSubstance.

This logics will temporarily be placed in query graph handler module. But eventually, we need to place it in query graph modifier module to handle this.

**Comment by kevinxin90** [comment]
Fixed in: https://github.com/biothings/BioThings_Explorer_TRAPI/pull/114

**Comment by andrewsu** [comment]
also linking this commit in the query graph handler https://github.com/kevinxin90/bte_trapi_query_graph_handler/commit/697781ac4d1f9faa8cad32969a8dce5701f7f686
