### ISSUE TITLE
Accessing LINCS data portal API thru BTE

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#116]
Summary: I think BTE is making an error in setting up the API request for LINCS data portal API. We are required to provide the input ID as a curie, so I set it as a ChemicalSubstance with the id "LINCS:LSM-1023" (which is imatinib). The logs show that the LINCS API query is then (see the **bold** for the error): 
```
    {
      "timestamp": "2021-03-24T04:11:46.587Z",
      "level": "DEBUG",
      "message": "call-apis: Succesfully made the following query: {\"url\":\"http://lincsportal.ccs.miami.edu/dcic/api/drugindication\",\**"params\":{\"id\":\"LINCS:LSM-1023\"}**,\"method\":\"get\",\"timeout\":50000}",
      "code": null
    },
```
Looking at the [smartapi page for LINCS data portal](http://smart-api.info/ui/9ee398a738916a98b612068cc022454f#/query/get_drugindication), **the id field should not have a prefix**...it should only have the id "LSM-1023".      

---
The situation: I tried to query the [LINCS data portal API](http://smart-api.info/ui/9ee398a738916a98b612068cc022454f#/query/get_drugindication) thru [BTE's /v1/smartapi/{smartapi_id}/query endpoint](https://smart-api.info/ui/dc91716f44207d2e1287c727f281d339#/1.0.0/querySmartAPI). 

The smartapi_id is 9ee398a738916a98b612068cc022454f, the request body is:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "subject": "n00"
        }
      },
      "nodes": {
        "n00": {
          "category": "biolink:ChemicalSubstance",
          "id": "LINCS:LSM-1023"
        },
        "n01": {
          "category": "biolink:Disease"
        }
      }
    }
  }
}
```
It returns no hits.   

---
However, if I query [the LINCS Data portal endpoint](http://smart-api.info/ui/9ee398a738916a98b612068cc022454f#/query/get_drugindication) directly with the id as "LSM-1023", I get multiple results like:
```
{"documents": [
{
"lsm_id":"LSM-1023",
"efo_id":"Orphanet:44890",
"efo_term":"GASTROINTESTINAL STROMAL TUMOR",
"max_fda_phase_for_ind":"4",
"mesh_heading":"GASTROINTESTINAL STROMAL TUMORS",
"mesh_id":"D046152"
}
,
{
"lsm_id":"LSM-1023",
"efo_id":"EFO:0000691",
"efo_term":"SARCOMA",
"max_fda_phase_for_ind":"3",
"mesh_heading":"SARCOMA",
"mesh_id":"D012509"
}
```

Note: I'm not sure if the BTE Python client has an issue with this API too, since it accepts only LINCS IDs and I'm not sure if BTE will ever end up querying it.

**Comment by kevinxin90** [comment]
Good catch. I think that's exactly something we wish your new x-bte extension in SmartAPI can solve.
