### ISSUE TITLE
bug in semmed_phenotype API definition used by BTE?

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#125]
API calls to semmed_phenotype seem to be failing, as shown in this gist:

https://gist.github.com/andrewsu/c183b91118ba422d31aea9443c392ea3

The API itself seems to be working fine (e.g., https://biothings.ncats.io/semmedphenotype/phenotype/C1318130) but does return 404 on unknown phenotypes (e.g., https://biothings.ncats.io/semmedphenotype/phenotype/C0021051).  So perhaps the errors like `API 3.8 semmed_phenotype failed` in the gist refer to cases where a 404 is returned?

**Comment by kevinxin90** [comment]
Fixed in 55ad6af6adea35d91542ca9b937f508a124ec341
