### ISSUE TITLE
Add feature to queue user queries

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#125]
1. At maximum, only 5 queries should be handled concurrently.
2. Ideally, users who sent too many requests should be postponed.
3. shouldn't affect behavior of /predicates endpoint which respond fast.

**Comment by colleenXu** [comment]
not sure if this is still relevant or not

**Comment by andrewsu** [comment]
Since `/asyncquery` handles most of the requirements here, closing this issue...
