### ISSUE TITLE
prefix ID issue again (Protein -> Gene)

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#129]
Like #116 and #122, with MyGene.info, querying Protein -> Gene. 

When querying from **Protein -> Gene with a UNIPROTKB or ENSEMBL ID**, the query fails because the requested id in q sent to MyGene.info includes the prefix, which MyGene doesn't recognize. Compare the query message sent by BTE to the correct query for MyGene.info below:

---
1. What a successful query directly to MyGene.info looks like, **see the q doesn't have a prefix**:

```
fields: ensembl.gene
Request body:
{
  "q": "O15131",
  "scopes": "uniprot.Swiss-Prot"
}

OR

{
  "q": "ENSP00000396791",
  "scopes": "ensembl.protein"
}
```
---
2. Query sent by BTE: **see that the q has a prefix**. BTE doesn't get any results from doing this. 
```
    {
      "timestamp": "2021-03-26T05:03:13.019Z",
      "level": "DEBUG",
      "message": "call-apis: Succesfully made the following query: {\"url\":\"https://mygene.info/v3/query\",\"params\":{\"fields\":\"ensembl.gene\",\"species\":\"human\"},\"data\":\"q=UNIPROTKB:O15131&scopes=uniprot.Swiss-Prot\",\"method\":\"post\",\"timeout\":50000}",
      "code": null
    },

OR

    {
      "timestamp": "2021-03-26T05:08:24.280Z",
      "level": "DEBUG",
      "message": "call-apis: Succesfully made the following query: {\"url\":\"https://mygene.info/v3/query\",\"params\":{\"fields\":\"ensembl.gene\",\"species\":\"human\"},\"data\":\"q=ENSEMBL:ENSP00000396791&scopes=ensembl.protein\",\"method\":\"post\",\"timeout\":50000}",
      "code": null
    },
```

**Comment by kevinxin90** [comment]
You label UNIPROTKB wrong in MyGene SmartAPI. Should be UniProtKB
