### ISSUE TITLE
confirm TRAPI export is v1.0 compliant

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#133]
Translator consortium wants all teams to be compliant with TRAPI v1.0 by 2021-01-15.  Validator package available at https://github.com/NCATSTranslator/reasoner-validator

(Discussed in Architecture call 2020-11-10...)

**Comment by kevinxin90** [comment]
Implementation of the TRAPI interface is available in [this repo](https://github.com/kevinxin90/BioThings_Explorer_TRAPI)

BioThings Explorer TRAPI API that complies with the 1.0.0 standard is available at https://api.bte.ncats.io through /v1/query endpoint.
