### ISSUE TITLE
Examine ARS use case: Chemical substances that "down regulate" STK11

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#136]
Source issue: https://github.com/NCATSTranslator/testing/issues/28

Original query: 
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e01": {
          "object": "n0",
          "predicate": ["biolink:prevents",
            "biolink:negatively_regulates",
            "biolink:decreases_secretion_of",
            "biolink:decreases_secretion_of",
            "biolink:decreases_transport_of",
            "biolink:decreases_activity_of",
            "biolink:decreases_synthesis_of",
            "biolink:decreases_expression_of",
            "biolink:increases_degradation_of",
            "biolink:negatively_regulates__entity_to_entity",
            "biolink:disrupts",
            "biolink:directly_negatively_regulates",
            "biolink:inhibits",
            "biolink:inhibitor",
            "biolink:channel_blocker",
            "biolink:disrupts",
            "biolink:may_inhibit_effect_of"
          ],
          "subject": "n1"
        }
      },
      "nodes": {
        "n0": {
          "id": "HGNC:11389"
        },
        "n1": {
          "category": "biolink:ChemicalSubstance"
        }
      }
    }
  }
 }
```

Will track some basic findings below...

**Comment by kevinxin90** [comment]
@andrewsu  They use the wrong predicate. "biolink:negatively_regulates__entity_to_entity" is not a valid biolink predicate. It should be "biolink:entity_negatively_regulates_entity". See https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L2516

**Comment by andrewsu** [comment]
So far, a few findings:

* Syntactically, everything is working fine.  If we add `biolink:physically_interacts_with` to the list of predicates, BTE returns results as expected.  

*  The original query used STK11 (HGNC:11389) as input. Trying other genes (e.g., ITK, EGFR, KIT) also returns no `ChemicalSubstance`s.  So it seems to have something to do with our mapping files being at a different level of specificity / granularity?

* According to the ARS query, ARAX returns one result for Tozacertib, referencing DGIdb. 
![image](https://user-images.githubusercontent.com/2635409/112884323-3db09e80-9084-11eb-8bad-0311b58f5f97.png)

But if I search DGIdb for all compounds that inhibit STK11 (https://dgidb.genome.wustl.edu/genes/STK11#_interactions), it looks like Tozacertib is one of 23 compounds, and it's not clear to me why Tozacertib would be special. When I query our DGIdb API specifically (https://biothings.ncats.io/dgidb/query?q=subject.id%3NCBIGene%5C%3A6794&size=100), I see 25 hits.  Very similar to what we see on the DGIdb website (all using the predicate `physically_interacts_with`), but perhaps indicates that a minor refresh might be needed.

* As noted by @kevinxin90 it looks like the list of predicates in the query are not all predicates in the Biolink Model.  I was expecting all of them to be listed in https://biolink.github.io/biolink-model/docs/predicates.html, but this is what I found:
```
           "predicate": ["biolink:prevents",   #yes
            "biolink:negatively_regulates",    #no
            "biolink:decreases_secretion_of",  #yes
            "biolink:decreases_secretion_of",  #yes
            "biolink:decreases_transport_of",  #yes
            "biolink:decreases_activity_of",  #yes
            "biolink:decreases_synthesis_of",  #yes
            "biolink:decreases_expression_of",  #yes
            "biolink:increases_degradation_of",  #yes
            "biolink:negatively_regulates__entity_to_entity",    #no
            "biolink:disrupts",  #yes
            "biolink:directly_negatively_regulates",    #no
            "biolink:inhibits",    #no
            "biolink:inhibitor",    #no
            "biolink:channel_blocker",    #no
            "biolink:disrupts",  #yes
            "biolink:may_inhibit_effect_of"    #no
          ],
```

**Comment by colleenXu** [comment]
Closing because it's old. will open a newer issue if my review of open testing repo issues (standups) reveal anything we want to look into
