### ISSUE TITLE
Design a Query Builder which supports querying multiple fields in BioThings API in batch mode

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#147]
https://github.com/biothings/biothings.api/issues/49.

This ties into #136 

We need to have POST query to query based on association.predicate field as well as subject.SYMBOL field.

**Comment by colleenXu** [comment]
Related to https://github.com/biothings/call-apis.js/issues/26, and will likely be addressed by its PRs

**Comment by colleenXu** [comment]
closing this issue, will track in newly opened tickets or the issue above (call-apis 26)
