### ISSUE TITLE
MyVariant civic drug response query not working

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#148]
@kevinxin90 

**The problem:** 
When querying MyVariant through the endpoint for single apis  (smartapi id 09c8782d9f4027712e65b95424adba79), I cannot successfully do a SequenceVariant -> ChemicalSubstance query. I was using rs121913521, which should have results. 

The response message is: 
```
{
  "error": "TypeError: Cannot read property 'slice' of undefined"
}
```

I expected the results found from querying MyVariant directly: 
curl -X POST "https://myvariant.info/v1/query?fields=civic.evidence_items" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "q=rs121913521&scopes=dbsnp.rsid"

---

**Why:** 
- Perhaps this is related to how the SmartAPI registration for this [operation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/e20153242a6a4d69c1bce29b3af8d4265067596b/myvariant.info/openapi_full.yml#L427) uses the ChemicalSubstance [name (field civic.evidence_items.drugs.name)](https://github.com/NCATS-Tangerine/translator-api-registry/blob/e20153242a6a4d69c1bce29b3af8d4265067596b/myvariant.info/openapi_full.yml#L360). Rather than using an ID. 
- sometimes a civic.evidence_items.drugs will have multiple drugs in one response because a drug combination was tested. For the example rs# above, the direct MyVariant response's third entry has 3 elements in the drugs field: Regorafenib, Imatinib, Ponatinib.

**Possible to-do:** 
Change the operation to use the data's NCIT ID (field civic.evidence_items.drugs.ncit_id)....can MyChem resolve this kind of ID? I can see [NCIT drug IDs in MyChem with the unii.ncit field](http://mychem.info/v1/query?q=_exists_:%22unii.ncit%22)

---

EDIT:
While the following does happen for some rs# variants, I don't see this situation for the specific variant I was querying for: 
- Perhaps some results don't have a [drugs field within the evidence_items array element](https://github.com/NCATS-Tangerine/translator-api-registry/blob/e20153242a6a4d69c1bce29b3af8d4265067596b/myvariant.info/openapi_full.yml#L431), which is where we get our output entity.

**Comment by colleenXu** [comment]
Perhaps another reason for response issues: Sometimes a civic.evidence_items.drugs will have multiple drugs in one response because a drug combination was tested (look at the civic entry for dbsnp.rsid rs61764370): curl -X POST "https://myvariant.info/v1/query?fields=civic.evidence_items" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "q=rs61764370&scopes=dbsnp.rsid"

**Comment by kevinxin90** [comment]
Fixed in: https://github.com/biothings/BioThings_Explorer_TRAPI/pull/166
