### ISSUE TITLE
ChEMBL drug indications not being mapped to BTE results

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#149]
In the context of this issue https://github.com/NCATSTranslator/testing/issues/41, we are looking for an edge that states `Nitisinone` - `treats` - `Alkaptonuria`.  BTE currently returns that edge based on the SEMMED Disease API, but also alongside several of lower-quality answers.  mychem.info also reports this indication from ChEMBL http://mychem.info/v1/query?q=drugbank.name:nitisinone&fields=chembl.drug_indications (screenshot below). As a higher quality resource, we should also map ChEMBL drug indications into BTE.  (I assume it means adding `chembl.drug_indications.mesh_id` to https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/openapi_full.yml ?)

![image](https://user-images.githubusercontent.com/2635409/114213241-99e2b080-9917-11eb-9d1b-681d686e0d3b.png)

**Comment by kevinxin90** [comment]
Added in https://github.com/NCATS-Tangerine/translator-api-registry/commit/13cd5864b5109f95e1380fff0fa5ec8ff3974693.
Tested on local, everything works.
You should be able to see the new change tomorrow morning when SmartAPI refreshes itself.
