### ISSUE TITLE
BTE not resolving human-readable names for some UMLS identifiers

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#150]
In the response to [this query](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/must-have/akuCause.json), BTE returns several results.  A snippet of the nodes is shown below.  BTE tries to populate the "name" field with human-readable names, but it fails on several of the nodes with UMLS as the primary identifier.  I'm guessing that this is because BTE is using mychem.info to determine the human-readable name, and it appears that some UMLS-only compounds are not found in mychem.info.  For example, from the query results below, mychem.info does return results for `Homogentisic Acid` via http://mychem.info/v1/query?q=pharmgkb.xrefs.umls:C0173083, but trying to resolve the other UMLS identifiers does not return any results (e.g., http://mychem.info/v1/query?q=pharmgkb.xrefs.umls:C0001128).  So I'm guessing this also comes back to https://github.com/biothings/mychem.info/issues/10

```
        "knowledge_graph": {
            "nodes": {
                "MONDO:0008753": {
                    "category": "biolink:Disease",
                    "name": "alkaptonuria",
                    "attributes": [...]
                },
                "UMLS:C0001128": {
                    "category": "biolink:ChemicalSubstance",
                    "name": "UMLS:C0001128",
                    "attributes": [...]
                },
                "MESH:D006713": {
                    "category": "biolink:ChemicalSubstance",
                    "name": "Homogentisic Acid",
                    "attributes": [...]
                },
                "UMLS:C0243076": {
                    "category": "biolink:ChemicalSubstance",
                    "name": "UMLS:C0243076",
                    "attributes": [...]
                },
                "UMLS:C0450442": {
                    "category": "biolink:ChemicalSubstance",
                    "name": "UMLS:C0450442",
                    "attributes": [...]
                }
            },
```

**Comment by colleenXu** [comment]
May be related to #242, #246, #247

**Comment by colleenXu** [comment]
Note that switching to Eric's SRI-based node normalization will not fix the UMLS IDs listed above, since it also finds no mappings for it...

**Comment by colleenXu** [comment]
Closing. As noted above, the SRI-based node normalization will not fix this issue because it doesn't recognize the UMLS IDs pasted above
