### ISSUE TITLE
implement filtering/ranking based on PFOCR co-occurrence

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#151]
Per 2021-01-19 meeting, tagging @kevinxin90  and @ariutta

**Comment by ariutta** [comment]
@kevinxin90, do you already have a preference for how to do this co-occurrence, e.g., weights, co-occurrence of pairs or co-occurrence matrices?

**Comment by ariutta** [comment]
@andrewsu, you asked for a list of the types of data we can get or have gotten from PFOCR, so I'm adding that here.

Have gotten:
* genes
* amino acids
* metabolites / small molecules
* drugs
* diseases (the name of the disease is in the figure)
* bio-terms (e.g., cellular components)

Could get (or in progress or exploratory stage):
* phosphorylation and similar types of state data
* drug, disease and bio-term extraction could be enhanced
* maybe things like biologics (as opposed to conventional drugs)
* could work more with the figure titles, captions and the mentions of the figure in the body of the paper, e.g., "In Fig. 5, we illustrate ..."

Could possibly get:
* localization
* reactions
* cascades
* cycles
* co-factors
* interactions (some cases would be difficult)

Note that for diseases, Alex also did an additional analysis:
>Gene Ontology and disease annotations for pathway figures were determined by performing enrichment analysis on the sets of figure-extracted genes against ontology-associated gene sets.

**Comment by ariutta** [comment]
Closing in favor of new issue: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/451
