### ISSUE TITLE
allow users to specify which APIs to include (or exclude)

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#153]
Ideally, individual end users would be able to specify individual APIs which should be included or excluded relative to a set of defaults.  People may use this:

* because some APIs may only be relevant in a small subset of use cases (e.g., ICEES for clinical data), or 
* because users may want to ignore data from an individual source (e.g., text-mined results from SEMMED), or 
* because an API is not behaving well and somehow disrupting overall BTE execution.  

Unclear to me how one would pass in these user-specific, query-time parameters, but I think it would be useful...

Note, this is a mirror of https://github.com/biothings/biothings_explorer/issues/85 on the python client

**Comment by colleenXu** [comment]
Can be addressed in local instances using https://github.com/biothings/BioThings_Explorer_TRAPI/pull/255. 

Not sure about specifying this on a query level (where it would work on the prod server).

**Comment by colleenXu** [comment]
not sure how relevant this is, since I don't think there's an option to do this in the TRAPI query (aka BTE's input).

**Comment by tokebe** [comment]
I assume this would not be adequately covered by `reasoner_ids` in the TRAPI query specification, in which case the only way could adequately support this is by taking an optional parameter in the request body, which wouldn't be technically TRAPI-compliant?

**Comment by colleenXu** [comment]
@tokebe I think some things have changed since this issue was opened. 

Looks like TRAPI working group is looking at this a bit, but I don't know how far along they are. It looks like some ARAs implement this already. https://github.com/NCATSTranslator/ReasonerAPI/issues/318 

A related proposal also seems kinda complicated to me https://github.com/NCATSTranslator/ReasonerAPI/issues/324

**Comment by andrewsu** [comment]
~~off priority list for now~~ leaving open as new dev project

**Comment by colleenXu** [comment]
Theoretically this is how to specify what resources to include / exclude in a TRAPI query. However, it's not clear what happens with TRAPI 1.4 where the provenance isn't stored in the edge-attributes anymore... https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationRules.md#specifying-permitted-and-excluded-kps-to-an-ara

**Comment by andrewsu** [comment]
this one is of sufficiently low priority that I'm going to close it as not planned
