### ISSUE TITLE
Text Mining Co-occurrence KP returns too many results as a single-hop query resource, need to limit by ngd score

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#159]

**Comment by colleenXu** [comment]
would involve edits to x-bte annotation at least...

**Comment by colleenXu** [comment]
Text-Mining Provider has confirmed that they have a TRAPI instance for this, and they don't need the BioThings / Service Provider to host this going forward (internal Translator Slack [link](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1661969294889219?thread_ts=1661959801.035949&cid=C022EL8D3AB)). So the issue can be closed.
