### ISSUE TITLE
local smartapi_specs.json being overwritten with zero-length file

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#170]
My `data/smartapi_specs.json` file is an empty file. The relevant cron job appears to be (over)writing a zero-length file as scheduled.   `data/predicates.json` is not being overwritten, but it also looks like it's not being updated.

```
$ ll data
total 668
drwxr-xr-x  2 asu asu   4096 May  6 09:58 ./
drwxr-xr-x 15 asu asu   4096 May  6 09:47 ../
-rw-r--r--  1 asu asu 673099 Apr 28 10:53 predicates.json
-rw-r--r--  1 asu asu      0 May  6 10:00 smartapi_specs.json
```

### More details ###
In `updateSmartAPISpecs` [1], BTE should update a local file `data/smartapi_specs.json` with the latest metakg from smartAPI every 10 minutes.  The cron job is in the **Code block** below, and I think it should issue two debug commands -- "Updating local copy of SmartAPI specs..." and _either_ "Successfull updated the local copy of SmartAPI specs" _or_ "Updating local copy of SmartAPI specs failed".  For some reason however, I only see the first debug command in my console log (see the **Log** section pasted below), so it's not clear to me what's going on when `updateSmartAPISpecs()` is called.

#### Notes
* I don't think this is a permissions issue, because the time stamp on the `data/smartapi_specs.json` file does get updated every 10 minutes
* I can manually execute `curl -o smartapi_specs.json "https://smart-api.info/api/query?q=tags.name:translator&size=150&fields=paths,servers,tags,components.x-bte*,info,_meta"` and then BTE works as expected.  But this file will be overwritten with the next execution of the cron job
* `git status` tells me I am up to date with `origin/master`
* I see this behavior with both node versions `v12.16.3` and `v14.16.1`

#### Code block
```
module.exports = () => {
    cron.schedule('*/10 * * * *', async () => {
        debug(`Updating local copy of SmartAPI specs now at ${new Date().toUTCString()}!`);
        try {
            await updateSmartAPISpecs();
            debug("Successfull updated the local copy of SmartAPI specs.")
        } catch (err) {
            debug(`Updating local copy of SmartAPI specs failed! The error message is ${err.toString()}`)
        }
    });
}
```

#### Log
```
$ DEBUG=biothings-explorer-trapi:*,smartapi-kg:*,call-apis:*,biomedical-id-resolver:* npm start

> @biothings-explorer/single-hop-app@2.5.0 start /home/asu/Science/BioThings_Explorer_TRAPI
> nodemon src/server.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/server.js`
  biothings-explorer-trapi:EdgeReverse BioLink-model class is initiated. +0ms
App listening at http://localhost:3000
  biothings-explorer-trapi:cron Updating local copy of SmartAPI specs now at Thu, 06 May 2021 16:40:00 GMT! +0ms
[nodemon] restarting due to changes...
[nodemon] starting `node src/server.js`
  biothings-explorer-trapi:EdgeReverse BioLink-model class is initiated. +0ms
App listening at http://localhost:3000
```

[1]: https://github.com/biothings/BioThings_Explorer_TRAPI/blob/f60a0ceeb1fc691bf2c4c0defda86d36178ad4ff/src/controllers/cron/update_local_smartapi.js#L93

**Comment by andrewsu** [comment]
I've isolated the issue.  When `updateSmartAPISpecs` [1] goes to write the `smartapi_specs.json` file, the `nodemon` package immediately detects this change and then restarts the application, preventing the completion of the writing process on `smartapi_specs.json` and preventing the subsequent writing of the `predicates.json` file.  I can solve this by changing this line https://github.com/biothings/BioThings_Explorer_TRAPI/blob/f60a0ceeb1fc691bf2c4c0defda86d36178ad4ff/package.json#L7 from `nodemon src/server.js` to `nodemon --ignore './data/' src/server.js`.  On the assumption that this will not negatively affect anyone else's environment, I'll create a pull request shortly...

It's not clear to me why this is a new issue that seems to be popping up for me, and why this issue does not affect other instances.  Since I'm a node newbie, insights welcome! 

[1]: https://github.com/biothings/BioThings_Explorer_TRAPI/blob/f60a0ceeb1fc691bf2c4c0defda86d36178ad4ff/src/controllers/cron/update_local_smartapi.js#L93

**Comment by andrewsu** [comment]
Just realized that asking nodemon to ignore the `data` subdirectory is not a desirable behavior at all -- that is exactly the directory that we want nodemon to monitor the most.  So I've changed the pull request to instead use nodemon's `--delay` option, which (according to https://github.com/remy/nodemon#delaying-restarting) works as follows: 

> The delay figure is number of seconds (or milliseconds, if specified) to delay before restarting. So nodemon will only restart your app the given number of seconds after the last file change.

This change works on my local WSL / Ubuntu 20.04 instance...

**Comment by newgene** [comment]
PR #173 merged. Close #170.
