### ISSUE TITLE
How do I retrieve ChEBI Name ?

### ISSUE THREAD

**Issue by Carolina1396** [biothings/biothings_explorer#175]
Title: How do I retrieve ChEBI Name

Hello, 

I have a problem interpreting Chemical Substances results like `CHEBI:25512 ` ([neurotransmitter](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25512)) in BTE. 

I can not retrieve the actual ChEBI name when trying to find the representation of this ChEBI ID:
![Screen Shot 2021-02-26 at 9 33 34 AM](https://user-images.githubusercontent.com/69015275/109334546-b918f900-7815-11eb-8392-aa1b0dcb62fd.png)

**Is there a way I should search for the compound name once having the ChEBI ID?** 

Thank you!
Carolina Gonzalez.

**Comment by kevinxin90** [comment]
This is an issue related to MyChem.info data instead of BTE. See: https://github.com/biothings/mychem.info/issues/83. (If you're interested, you can also contribute to MyChem to add the missing data)

The CHEBI ID you provide is an ontology ID, instead of a ChemicalSubstance ID. Currently, BTE (relying on MyChem) can only resolve ChemicalSubstance IDs.

If you try query other CHEBI ChemicalSubstance ID, it should work:

```
In [1]: from biothings_explorer.hint import Hint

In [2]: ht = Hint()

In [4]: ht.query("CHEBI:8863")
Out[4]: 
{'Gene': [],
 'SequenceVariant': [],
 'ChemicalSubstance': [{'CHEMBL.COMPOUND': 'CHEMBL744',
   'DRUGBANK': 'DB00740',
   'PUBCHEM': 5070,
   'CHEBI': 'CHEBI:8863',
   'UMLS': 'C0073379',
   'MESH': 'D019782',
   'UNII': '7LJ087RS6F',
   'INCHIKEY': 'FTALBRSUTCGOEG-UHFFFAOYSA-N',
   'INCHI': 'InChI=1S/C8H5F3N2OS/c9-8(10,11)14-4-1-2-5-6(3-4)15-7(12)13-5/h1-3H,(H2,12,13)',
   'KEGG': 'C07937',
   'name': 'RILUZOLE',
   'CAS': '1744-22-5',
   'IUPAC': '[6-(trifluoromethoxy)-1,3-benzothiazol-2-yl]amine',
   'formula': 'C8H5F3N2OS',
   'primary': {'identifier': 'CHEBI',
    'cls': 'ChemicalSubstance',
    'value': 'CHEBI:8863'},
   'display': 'CHEBI(CHEBI:8863) CHEMBL.COMPOUND(CHEMBL744) DRUGBANK(DB00740) PUBCHEM(5070) MESH(D019782) UNII(7LJ087RS6F) UMLS(C0073379) name(RILUZOLE) CAS(1744-22-5) IUPAC([6-(trifluoromethoxy)-1,3-benzothiazol-2-yl]amine) formula(C8H5F3N2OS)',
   'type': 'ChemicalSubstance'}],
 'Disease': [],
 'PhenotypicFeature': [],
 'MolecularActivity': [],
 'BiologicalProcess': [],
 'CellularComponent': [],
 'Pathway': [],
 'AnatomicalEntity': [],
 'Cell': []}
```
