### ISSUE TITLE
Target landscape analysis use case

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#175]
From Christine Colvis in December Demo planning session 2021-05-11

* User input: an undruggable disease gene 
* Query: find genes in pathways related to the disease gene, or genes that modulate the disease gene, or genes the produce metabolites that affect the disease gene
* Filter: restrict gene list to druggable (e.g., enzymes from GO terms)

Would be good to develop a set of query templates

**Comment by colleenXu** [comment]
moving to on-hold / non-critical since it seems like this isn't being done in the december demo now...

**Comment by andrewsu** [comment]
this hasn't resurfaced as a consortium use case -- closing for now
