### ISSUE TITLE
mygene using association as predicate

### ISSUE THREAD

**Issue by cbizon** [biothings/biothings_explorer#176]
It looks like mygene.info is using biolink:functional_association as the relationship between gene and pathway, but that's a biolink association, not a predicate.    The upshot is that e.g. aragorn is not able to use BTE to find gene/pathway edges.

**Comment by kevinxin90** [comment]
Sure. I can update the SmartAPI spec for MyGene. @cbizon any recommendations for the predicate? Maybe [enables](https://biolink.github.io/biolink-model/docs/enables.html)?

**Comment by colleenXu** [comment]
@kevinxin90 
Would you like me to do this update?

And how about Gene - [participates in](https://github.com/biolink/biolink-model/blob/3985c060240cf838e485299c1e380ae4ba35a925/biolink-model.yaml#L3727) -> pathway. One of the narrow mappings is "NCIT:gene_product_is_element_in_pathway"

**Comment by colleenXu** [comment]
Okay. I'll make a PR in https://github.com/NCATS-Tangerine/translator-api-registry for these MyGene registry changes

**Comment by kevinxin90** [comment]
@cbizon Hi Chris, the above query is available through our TRAPI service now. Feel free to try it out:
```
curl --location --request POST 'https://api.bte.ncats.io/v1/query' \
--header 'Content-Type: application/json' \
--data-raw '{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "id": "NCBIGENE:1017",
                    "category":"biolink:Gene"
                },
                "n1": {
                    "category": "biolink:Pathway"
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicate":"biolink:participates_in"
                }
        }
        }
    }
}'
```
