### ISSUE TITLE
Use case: find chemical modulators that may influence DILI 

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#178]
DILI = drug-induced liver injury

For a certain type of DILI (Augmentin-induced), there are genetic variants in the genes ERAP2, PTPN22, and EXOC4 that increase the odds ratio of DILI. Let's try to use BTE to find chemical modulators of those three genes.  Potential metapaths might include:
* `Gene` - `Pathway` - `Gene` - `ChemicalSubstance`
* `Gene` - `ChemicalSubstance` (metabolite) - `ChemicalSubstance` (drug) 
* `Gene` - `Gene` - `ChemicalSubstance`.

This would be complementary to the phenotype-based approach currently being pursued by the clinical workgroup. DILI will also likely be part of the December 2021 demo.

For more details, see https://docs.google.com/presentation/d/1lrBIdldl4IB7GH8ydJmCBQMXdKM1vsT_iadDndd3yns/edit and https://docs.google.com/document/d/12N34vaYut3kymA_Y7G0q-G_2fifzlR8rxioqcjyu1-E/edit

**Comment by colleenXu** [comment]
Could also do one-hops 

set of Genes - ChemicalSubstance,
set of phenotypicFeatures -> ChemicalSubstance
set of phenotypicFeatures -> genes (show that you get the known answers)

Also find the background info that shows that modulators of these genes could be of interest. see pg. 7-8 of the google doc doc

**Comment by colleenXu** [comment]
the four hop? Mondo:0005339 DILI -(correlated_with)-> DiseaseOrPhenotypicFeature -(condition associated with gene)-> gene -(related to)-> chemicalsubstance

**Comment by andrewsu** [comment]
old use case -- closing...
