### ISSUE TITLE
[bug] Fix using name as id for Biocarta pathway entities

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#184]
Should fix https://github.com/biothings/biothings_explorer/issues/181 .

CX tried modifying code in https://github.com/biothings/biomedical_id_resolver.js/pull/55 , but AS reports that this might not fully fix the problem.

**Comment by marcodarko** [comment]
Issue has been resolved and prefix applied correctly on this PR https://github.com/biothings/biomedical_id_resolver.js/pull/55/commits/78f985e026d43eab856e93ecbe7e95b1a47aa3c7
from related issue https://github.com/biothings/biothings_explorer/issues/181
