### ISSUE TITLE
[bug] BTE isn't restricting output based on specified query-graph predicate

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#185]
QUERY: 

This [TRAPI v1.1 query](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.1/egfr.json) has the following predicates specified in the query-graph edge: 

```
"biolink:decreases_abundance_of", 
"biolink:decreases_activity_of", 
"biolink:decreases_expression_of", 
"biolink:decreases_synthesis_of", 
"biolink:increases_degradation_of", 
"biolink:disrupts", 
"biolink:entity_negatively_regulates_entity"
```
---

PROBLEM:

However, BTE's output includes nodes/edges/results that don't match those predicates or their children in Biolink. For example, these are some edges returned:

- CHEBI:49668-**biolink:related_to**-NCBIGene:1956
- DRUGBANK:DB07602-biolink:physically_interacts_with-NCBIGene:1956
- MESH:D008748-biolink:entity_positively_regulates_entity-NCBIGene:1956

---

EXPECTED BEHAVIOR:

BTE would process the query graph, **pick only the metaKG edges/operations with the specified biolink predicate or its children**, and run/process/return the output of those operations. 

In the query above, BTE should only pick one metaKG edge (entity_negatively_regulates_entity) from SEMMED Gene API. The logs should look like this:

```
        {
            "timestamp": "2021-05-25T05:57:39.101Z",
            "level": "DEBUG",
            "message": "call-apis: Succesfully made the following query: {\"url\":\"https://biothings.ncats.io/semmedgene/query\",\"params\":{\"fields\":\"negatively_regulated_by\"},\"data\":\"q=C1414313&scopes=umls\",\"method\":\"post\",\"timeout\":50000}",
            "code": null
        },
        {
            "timestamp": "2021-05-25T05:57:39.124Z",
            "level": "DEBUG",
            "message": "call-apis: After transformation, BTE is able to retrieve 345 hits!",
            "code": null
        },
```

HOWEVER: BTE only has 338 hits/edges. This seems to be because some hits did not actually resolve into recognized entities. I am exploring this further.

**Comment by andrewsu** [comment]
@colleenXu to help debugging, can you check if this issue applies to the v1.0 TRAPI endpoint (bte.ncats.io/v1/query) or only the V1.1 TRAPI endpoint (api.bte.ncats.io/v1/query)?  Once we determine this, going to punt this over to @marcodarko and @newgene to look into the fix.  Also going to label this as **high priority**, since predicate filtering is a commonly-used function.

**Comment by marcodarko** [comment]
Hi @colleenXu @andrewsu I have a question, I was trying to filter the results based on the predicates provided however I encountered 0 hits for them in the current results, is that expected? 

These are the unique predicates I found from this query and the current results:
`["related_to","affected_by","physically_interacts_with","interacts_with","directly_interacts_with","entity_negatively_regulated_by_entity","entity_negatively_regulates_entity","entity_positively_regulated_by_entity","entity_positively_regulates_entity"]`

Could it be that those predicates are only found in children nodes? or maybe the response SHOULD be empty. 
I know it's possible that the graph needs to be expanded further and still looking into that but right now I cannot find any matches with the current restrictions on the top level results.

Can you maybe provide me with a query I can test in which the results accurately represent the query to test against.

**Comment by colleenXu** [comment]
@marcodarko Yes, the above list would lead to 0 results and your list of unique predicates looks correct.

Change the last element of the list from "biolink:negatively_regulates_entity_to_entity" to **"biolink:entity_negatively_regulates_entity"**. Then I would hope for the expected behavior I mention in the original post above...

I'll edit my original comment to replace the predicate. Sorry for the confusion, there was some discussion in Translator on which predicate was "correct".

**Comment by colleenXu** [comment]
This appears to be working now. 

The example from the original post now works as expected (returning only edges with one of the listed predicates).

Another example also correctly returns edges that only have the specified predicate: 

```
{
    "message": {
        "query_graph": {
            "nodes": {
                 "n0": {
                    
                    "ids": [
                        "HGNC:6284"
                    ],
		    "categories":["biolink:Gene"]
                },"n1": {
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:gene_associated_with_condition"]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
Nodes/edges/results sections of message all look good YAY.

#195 is to update the logs to show that predicate restriction is being done.
#167 is because predicate expansion still isn't working
