### ISSUE TITLE
Deploy TRAPI 1.3

### ISSUE THREAD

**Issue by capasfield** [biothings/biothings_explorer#186]
https://arax.ncats.io/?smartapi=1 shows that Service Provider TRAPI and BioThings Explorer API have 1.2 in development (infores:service-provider-trapi and infores:biothings-explorer)

Please deploy 1.3 of these tools into development ASAP.

**Comment by andrewsu** [comment]
@capasfield can you recreate this issue in https://github.com/biothings/BioThings_Explorer_TRAPI please? (or let me know if you prefer I do it.)   This is an older, obsolete repo for the BTE project...
