### ISSUE TITLE
[bug / refactor] duplication in results

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#190]
### Problem

**BTE currently returns a lot of redundant items in the Results array of the TRAPI response.** 

This is related to how BTE handles edges. @andrewsu and I are currently discussing the format/handling of edges and results + the TRAPI standard, and plan to share what behavior we want from BTE with @newgene and @marcodarko . 

From what I can tell, identical/duplicated result objects occur when:
- multiple KP sub-queries (from metaKG) return the same output entity, with the same predicate. In this case, the duplicate results represent each sub-query and point to the same edge/nodes. This is illustrated [on slide 4 here](https://docs.google.com/presentation/d/1-vytY5-Wt1kOI1igWn9ZT-ja_MwodzGhQBn7Y_XEaR4/edit?usp=sharing) 
- a KP sub-query returns multiple instances of the same output entity. In this case, the duplicate results represent those instances.  This is the issue with [BTE's handling of OpenTargets here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/130)

### A bit of background

NCATS is looking at the results section of the [ARAX UI](https://arax.ncats.io/?source=ARS&id=c920b90c-7a59-41ab-8049-7a8dc8d72b79), which draws from the message.results section of the TRAPI response. This section is an array of "Result" objects. 

We therefore want our format of the "Results" object to play well with this UI in showing our answers. However, [users have commented](https://github.com/NCATSTranslator/testing/issues/35) that we're returning identical/duplicated items in the results section.

**Comment by andrewsu** [comment]
The translator-wide decision on how to handle edge/result merging was summarized in this PR https://github.com/NCATSTranslator/TranslatorArchitecture/pull/56

The query here https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.1/enalaprilDisease.json (results: https://arax.ncats.io/?source=ARS&id=509200a2-9e4d-490e-b93a-c67178b7b358; screenshot below) seems like an example where we need to examine BTE behavior (873 nodes and 872 edges, but 1744 results)

![image](https://user-images.githubusercontent.com/2635409/128374884-b6c502ca-9658-4a21-b138-d1f8e06d7616.png)

**Comment by colleenXu** [comment]
the result duplication should be handled by the querying + results handling refactoring done by Marco / Anders here: https://github.com/biothings/bte_trapi_query_graph_handler/pull/35

**Comment by colleenXu** [comment]
Handled by the refactor. closing
