### ISSUE TITLE
[refactor] predicate filtering on what queries to do (rather than post-query)

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#197]
Currently, when a predicate is specified in a query-graph step like in the query below...
BTE will ignore the predicate first and do all of the sub-queries between the node entity types. It will then filter nodes/edges/results based on the specified predicate.

It would be more efficient for BTE to use the specified predicate to decide what sub-queries to do in the first place (what metaKG edges to select and query along). There would then be less queries done / less processing done. 

```
{
    "message": {
        "query_graph": {
            "nodes": {
                 "n0": {
                    
                    "ids": [
                        "HGNC:6284"
                    ],
		    "categories":["biolink:Gene"]
                },"n1": {
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:gene_associated_with_condition"]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
Perhaps there is a way to have both pre-querying predicate filtering (for new queries that aren't cached) and post?

This would be a somewhat limited usefulness - since caching is short-term....

---

Since that the current "post-querying predicate filtering" is working well with cached queries. 

For example, if I query without any predicate restrictions first, and then run the SAME query but add a predicate restriction...BTE will correctly use the cached data and then run the predicate restriction code. 

This is likely faster and more efficient than querying twice (the second time looking only for edges with the matching predicate).

**Comment by andrewsu** [comment]
given @colleenXu's testing, this is ready to merge.  @newgene

**Comment by colleenXu** [comment]
will check that this is deployed to prod as-expected, when BTE prod is online...

**Comment by colleenXu** [comment]
checked and it's live
