### ISSUE TITLE
add default "score" property to each entry in Results

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#200]
The TRAPI standard defines a `score` property on `result` objects (https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L320). The current plan is that every ARA should return _some_ score by 2021-06-15.  So, in the short term, we should simply add that `score` property with a default score of `1.0`:

```
        "results": [
            {
                "node_bindings": {
                    "n1": [
                        {
                            "id": "NCBIGene:2911"
                        }
                    ],
                    "n0": [
                        {
                            "id": "CHEBI:43876"
                        }
                    ]
                },
                "edge_bindings": {
                    "e01": [
                        {
                            "id": "NCBIGene:2911-biolink:physically_interacts_with-CHEBI:43876"
                        }
                    ]
                },
                "score": "1.0"
            },
```

**Comment by colleenXu** [comment]
I think Marco has addressed this in the latest release. 

See the screenshot below where the default score of 1 is there for each result. 

The PK for BTE's response is 67713c24-9209-4d14-988d-b973cb8234cf; you can look at it [here](https://arax.ncats.io/?source=ARS&id=67713c24-9209-4d14-988d-b973cb8234cf). 

![Screen Shot 2021-06-16 at 4 30 42 PM](https://user-images.githubusercontent.com/43731687/122308079-7e1ffb80-cec0-11eb-9e24-763b2c02ee1e.png)
