### ISSUE TITLE
invalid TRAPI 1.1

### ISSUE THREAD

**Issue by cbizon** [biothings/biothings_explorer#202]
For this query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "a": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0004315"
                    ]
                },
                "b": {
                    "categories": [
                        "biolink:AnatomicalEntity"
                    ]
                }
            },
            "edges": {
                "ab": {
                    "subject": "a",
                    "object": "b",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        },
        "knowledge_graph": {
            "nodes": {},
            "edges": {}
        },
        "results": []
    }
}
```

to the text mining KP ("https://api.bte.ncats.io/v1/smartapi/5be0f321a829792e934545998b9c6afe")

I'm getting a validation error on the returned response:

```
On instance[0]:
    {'attribute_type_id': 'equivalent_identifiers',
     'type': 'biolink:id',
     'value': ['UBERON:0034925']}
```

`type` is not an allowed key for an attribute. (https://github.com/NCATSTranslator/ReasonerAPI/blob/master/docs/reference.md)

**Comment by colleenXu** [comment]
Note @cbizon:

- While the query above does return a response, I believe TRAPI queries don't include the empty "knowledge_graph" or "results" sections. Notice that the [standup meeting queries](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.1/kcnma1DiseaseOrFeature.json) don't include those fields. I linked an example. 
- We are aware that the responses we return aren't fully TRAPI v1.1 compliant. We are working on that.

**Comment by cbizon** [comment]
On the TRAPI query, the Query schema just says that it contains a Message and an optional log.  The knowledge graph and results (and query graph) are all marked nullable in Message.  So I interpret that as saying that either present but empty and absent are both valid for TRAPI Query.

**Comment by colleenXu** [comment]
okay. It looks like BTE handles this alright. However, it looks like there may generally be issues with having empty knowledge_graph and results in the query...see https://github.com/NCATSTranslator/ReasonerAPI/issues/258

**Comment by colleenXu** [comment]
@cbizon Please try the query again. We are seeing that queries to BTE now have TRAPI-compliant responses. 

There are issues that can happen like "too many requests" or "cannot handle a query formatted like this". We currently don't throw TRAPI-compliant output with error codes. My understanding is that the TRAPI group is still working on the set of error codes/expected TRAPI behavior for these scenarios.

**Comment by andrewsu** [comment]
... and for posterity, there is also some relevant info in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/171...
