### ISSUE TITLE
update smartAPI registry record for BTE 

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#211]
just realizing that the smartAPI registry record for BTE (https://smart-api.info/registry?q=dc91716f44207d2e1287c727f281d339) points to this OpenAPI file (https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/biothings_explorer/smartapi.yaml) which has paths for `/v1/meta_knowledge_graph/`, `/v1/query`, etc.  We should move that `v1` prefix to `servers.url`.

Doesn't affect usage of BTE, so lower priority...

**Comment by colleenXu** [comment]
as-of 6/24/21, the discussion was that there's a /metakg endpoint (no v1 in the path). So it wasn't clear whether to do this change then or not

**Comment by andrewsu** [comment]
@newgene going do defer this one to you.  We could either:

* delete the `/metakg` endpoint (because no one that we know really uses it), and then move the `v1` prefix on paths to `servers.url`
* close this issue with no changes since no one really consumes (that we know of) the BTE SmartAPI record

**Comment by newgene** [comment]
@andrewsu @colleenXu yes, I agree on both. `/metakg` is internal, no need to, also should not, be exposed publicly.

**Comment by colleenXu** [comment]
Should be addressed by the merged PR linked above. Closing issue.
