### ISSUE TITLE
BTE did not find a subset of DMDB edges

### ISSUE THREAD

**Issue by r76941156** [biothings/biothings_explorer#212]
There are 16 edges of <a href='https://github.com/biothings/BioThings_Explorer_TRAPI/issues/181'> DMDB </a> could not be found from SemMedDB APIs after validations with the latest copy of SemMedDB. After doing some studies, I found below issues/actions have to be addressed:

1. Review and update data in SemMed-related APIs
2. BTE did not (trigger to) find any edges for Drug (ChemicalSubstance in Biolink v.1.1)
3. Inconsistent (missing) mappings in the registry and API codes

<a href='https://github.com/r76941156/BTE_TRAPI_REPORT/blob/main/BTE_TRAPI_0623.pdf'>Full Report </a>

**Comment by andrewsu** [comment]
Let me add a bit more context.  Sander's work on #181 revealed a few things we will want to do with the semmed APIs.  I asked him to create this ticket to start discussions on prioritizations

* the Semmed APIs appear to be based on the 2020 data files -- would be good to update them to the latest 2021 files (related to https://github.com/biothings/pending.api/issues/25)
* we need to update the APIs to Biolink 2.0.2 (related to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/207)
* Right now, the mappings to Biolink Model happen in the parsers (see, for example, https://github.com/kevinxin90/semmedphen/blob/master/parser.py). We should consider whether it's possible for the APIs to more closely reflect the original source files, and then do the mappings to Biolink Model in the Smart API mapping files.

Let's discuss more at an upcoming internal Translator meeting...

**Comment by tokebe** [comment]
Is this issue still relevant/should it be added to the project tracker?

**Comment by andrewsu** [comment]
I think with the child issues that were created and resolved, this issue can be closed.

**Comment by colleenXu** [comment]
I agree, looks like it was related to the big push to update semmeddb https://github.com/biothings/pending.api/issues/30#issuecomment-910768268 . Which is done. Currently, I think work is being done for the new version of semmeddb + fixes...https://github.com/biothings/pending.api/issues/63
