### ISSUE TITLE
Migrate meta-KG from config.py to SmartAPI

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#22]
Currently, the meta-KG is based on data in [config.py](https://github.com/biothings/bte_schema/blob/master/biothings_explorer/config.py). All of these semantic annotations of inputs and outputs should be moved to SmartAPI.

**Comment by kevinxin90** [comment]
All semantic annotations of APIs integrated in BTE have been migrated to SmartAPI registry:

1. mygene.info API
[smartapi interface](http://smart-api.info/ui/59dce17363dce279d389100834e43648)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/mygene.info/openapi_full.yml)
2. myvariant.info API
[smartapi interface](http://smart-api.info/ui/09c8782d9f4027712e65b95424adba79)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/myvariant.info/openapi_full.yml)
3. mychem.info API
[smartapi interface](http://smart-api.info/ui/8f08d1446e0bb9c2b323713ce83e2bd3)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/mychem.info/openapi_full.yml)
4. mydisease.info API
[smartapi interface](http://smart-api.info/ui/671b45c0301c8624abbd26ae78449ca2)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/mydisease.info/smartapi.yaml)
5. SEMMED API
[smartapi interface](http://smart-api.info/ui/e99229fc6ccb9ad9889bcc9c77a36bad)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/semmed/smartapi.yaml)
6. MGIgene2phenotype API
[smartapi interface](http://smart-api.info/ui/77ed27f111262d0289ed4f4071faa619)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/MGIgene2phenotype/smartapi.yaml)
7. EBIgene2phenotype API
[smartapi interface](http://smart-api.info/ui/1f47552dabd67351d4c625adb0a10d00)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/EBIgene2phenotype/smartapi.yaml)
8. DISEASES API
[smartapi interface](http://smart-api.info/ui/a7f784626a426d054885a5f33f17d3f8)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/DISEASES/smartapi.yaml)
9. PFOCR API
[smartapi interface](http://smart-api.info/ui/edeb26858bd27d0322af93e7a9e08761)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/pfocr/smartapi.yaml)
10. BioLink API
[smartapi interface](http://smart-api.info/ui/d22b657426375a5295e7da8a303b9893)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/biolink/openapi.yml)
11. ROBOKOP API
[smartapi interface](http://smart-api.info/ui/4f7b6f661ac61ed64190d5b26d87aff5)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/robokop_extend/smartapi.yaml)
12. DGIDB API
[smartapi interface](http://smart-api.info/ui/e3edd325c76f2992a111b43a907a4870)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/dgidb/openapi.yml)
13. QUICKGO API
[smartapi interface](http://smart-api.info/ui/1f277e1563fcfd124bfae2cc3c4bcdec)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/quickgo/smartapi.yaml)
14. LITVAR API
[smartapi interface](http://smart-api.info/ui/dca415f2d792976af9d642b7e73f7a41)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/litvar/smartapi.yaml)
15. EBI Ontology Lookup Service API
[smartapi interface](http://smart-api.info/ui/1c056ffc7ed0dd1229e71c4752239465)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/ols/smartapi.yaml)
16. COHD API
[smartapi interface](http://smart-api.info/ui/2fcd08a5f4c45b10520b8f7d5c3417b4)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/cohd/smartapi.yaml)
17. Stanford Biosample API
[smartapi interface](http://smart-api.info/ui/553a49d112bb19306253942ebd6377a9)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/stanford_kp/smartapi.yaml)
18. ChEMBL API
[smartapi interface](http://smart-api.info/ui/71add13e7c8b26b0046cfb8cf5092395)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/chembl/smartapi.yaml)
19. CTD API
[smartapi interface](http://smart-api.info/ui/0212611d1c670f9107baf00b77f0889a)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/CTD/smartapi.yaml)
20. OpenTarget API
[smartapi interface](http://smart-api.info/ui/542ba165e1b4227854cf7c0a8addcc79)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/opentarget/smartapi.yaml)
21. RGD API
[smartapi interface](http://smart-api.info/ui/eb28713e2e23160e80e88f3a5dabcca4)
[Semantic Annotation](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/RGD/smartapi.yaml)
