### ISSUE TITLE
BTE sometimes fails, errors (id resolving + node updating)

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#220]
### To-do:
- figure out what is going on with this error and how to fix/manage it
- get BTE to return error/warning codes + TRAPI-compliant JSON when errors happen

---

### The error users see

When processing the query below, BTE sometimes errors, returning this response:
{
    "error": "TypeError: Cannot read property '0' of undefined"
}
This is not a TRAPI-compliant JSON response, so the ARAX UI shows that as a problem. 

---

### Logs Part 1

Consistently, the last logs (before stopping and returning the TypeError) look like this. This is when I’m running in debug mode and showing the dependencies logs.

So my interpretation is: the error is happening when the **phenotypicfeature ID resolution** fails. The last log implies that **BTE is trying to update the node attributes with the info from ID-resolution and then errors when it hits the failed PhenotypicFeature IDs…**

>   biomedical-id-resolver:Scheduler **Number of API queries made for semantic type PhenotypicFeature is 3** +1ms
>   biomedical-id-resolver:Scheduler Total number of API Query Buckets created is 2 +0ms
>   biomedical-id-resolver:Query **One API Query fails, reason is Error: Request failed with status code 503** +0ms
>   biomedical-id-resolver:Query **One API Query fails, reason is Error: Request failed with status code 503** +2ms
>   biomedical-id-resolver:resolver **Total number of Irresolvable curies are: 1** +22s
>   biomedical-id-resolver:resolver Total number of results returned are: 531 +22s
>   call-apis:query id annotation completes +12s
>   call-apis:query Query completes +0ms
>   biothings-explorer-trapi:batch_edge_query BTEEdges are successfully queried.... +21s
>   biothings-explorer-trapi:batch_edge_query Filtered results from 3276 down to 3276 results +39ms
>   biothings-explorer-trapi:batch_edge_query Total number of response is 3276 +0ms
>   biothings-explorer-trapi:batch_edge_query **Start to update nodes,hi.** +0ms

---

### Logs Part 2

I get more detail on the phenotypicfeature ID resolution fail when I look only at debug logs for the BTE TRAPI tool (not its dependencies). It looks like a weird async/axios/etc error…

>   biomedical-id-resolver:Scheduler Number of API queries made for semantic type PhenotypicFeature is 3 +1ms
>   biomedical-id-resolver:Scheduler Total number of API Query Buckets created is 2 +0ms
> (node:66810) **UnhandledPromiseRejectionWarning: Error: Request failed with status code 503**
**>     at createError (/Users/jay/Desktop/bte-trapi-workspace/node_modules/axios/lib/core/createError.js:16:15)**
>     at settle (/Users/jay/Desktop/bte-trapi-workspace/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/Users/jay/Desktop/bte-trapi-workspace/node_modules/axios/lib/adapters/http.js:260:11)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (internal/streams/readable.js:1327:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:66810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. **This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().** To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> (node:66810) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>   biomedical-id-resolver:Query One API Query fails, reason is Error: Request failed with status code 503 +0ms
>   biomedical-id-resolver:Query One API Query fails, reason is Error: Request failed with status code 503 +0ms
>   biomedical-id-resolver:Query One API Query fails, reason is Error: Request failed with status code 503 +0ms
>   biomedical-id-resolver:resolver Total number of Irresolvable curies are: 1 +28s
>   biomedical-id-resolver:resolver Total number of results returned are: 165 +28s
**> (node:66810) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)**

---

The query. This is a Translator standup query.

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["PUBCHEM.COMPOUND:3672","PUBCHEM.COMPOUND:1983"],
                    "categories":[
                        "biolink:ChemicalSubstance"
                       ]
                },
                "n1": {
                    
                    "categories":[
                        "biolink:DiseaseOrPhenotypicFeature"
                       ]
               }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates":["biolink:related_to"]

                }
            }
        }
    }
}
```

**Comment by andrewsu** [comment]
downprioritizing this issue because it's a sporadic error so is tough to reproduce.

**Comment by colleenXu** [comment]
shouldn't be an issue once we move to SRI-based ID resolution...

**Comment by colleenXu** [comment]
I have not noticed this issue using the new SRI-service based ID resolver. 

BTE prod (now updated to use this code) works on a biolink v2.2 / TRAPI v1.2 version of this query:

It returned a 7.19MB response in ~32 sec. This query is ibuprofen + acetaminophen -> DiseaseOrPhenotypicFeature

EDIT: on another query to the ARS, it returned a 15.2 MB response (again in a reasonable amount of time, maybe a minute or so)...

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["PUBCHEM.COMPOUND:3672","PUBCHEM.COMPOUND:1983"],
                    "categories":[
                        "biolink:ChemicalSubstance"
                       ]
                },
                "n1": {
                    
                    "categories":[
                        "biolink:DiseaseOrPhenotypicFeature"
                       ]
               }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates":["biolink:related_to"]

                }
            }
        }
    }
}

```
