### ISSUE TITLE
BTE unable to retrieve homologs and orthologs

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#222]
I am unable to retrieve homologs (and specifically orthologs) for Genes using the TRAPI query below.  This information is in mygene.info (http://mygene.info/v3/gene/1017?fields=pantherdb.ortholog). I believe BTE attempts to retrieve this info under `pantherdb.ortholog.MGI` as indicated in https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mygene.info/openapi_full.yml#L876, but I'm unclear whether the syntax has changed. 

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "NCBIGene:1017"
                    ],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:Gene"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:homologous_to",
                        "biolink:orthologous_to",
                    ]
                }
            }
        }
    }
}
```

Per discussion here: https://ncatstranslator.slack.com/archives/CSS752SB0/p1626294694050500

**Comment by newgene** [comment]
@andrewsu I was able to get the expected result, but need to remove trailing comma from `"biolink:orthologous_to",` line.

**Comment by andrewsu** [comment]
argh, that was a last second edit to the TRAPI that I didn't explicitly test.  But I could have swore I tested `biolink:homologous_to` and `biolink:orthologous_to` individually with no results.  Must have done something different, thanks for catching my mistake!
