### ISSUE TITLE
handle TRAPI v1.2 "operations" in query

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#226]
TRAPI v1.2 queries/requests will include a "workflow" field like this:
```
{
    "message": ...,  // query_graph is in here
    "workflow": [
        {"id": "lookup"}
    ]
}
```

BTE's behavior: we plan to only support doing the "lookup" operation of a workflow (Translator documentation [here](https://github.com/NCATSTranslator/OperationsAndWorkflows/wiki/How-to-%22do%22-operations))

<br>

### Case 1

BTE either:
A. Gets a TRAPI query/request like the example above. There's 1 object in the workflow's array, and the id is "lookup"...
B. Gets a TRAPI query/request with no workflow field

Desired behavior:
-  BTE can do its normal behavior using the message.query_graph...
- BTE's response should include the same workflow info that was in the query. So it should look like this:

```
{
    "message": ...,  // query graph, knowledge_graph, results are in here
    "workflow": [
        {"id": "lookup"}
    ]
}
```

<br>

### Case 2

BTE encounters situations different from the two above. Maybe the object in the workflow array isn't {"id:lookup"}; or maybe there are multiple objects in the workflow array other than {"id:lookup"}.  

Desired behavior:
- Don't go forward with parsing the message.query_graph. 
- Return something like the JSON in the code block below:
    - no workflow field. since BTE didn't do anything
    - status field should be "400" (I'm still clarifying which error code to use)
    - description field can be anything. We could put something like "HTTP error code 400: BTE doesn't perform one or more of the operations specified in the query's workflow field"
    
```
{
    "message": {
         "query_graph": ...,                                   // the query graph that was in the submitted query
         "knowledge_graph": { "nodes": {}, "edges": {} },      // empty objects since we didn't do anything
         "results": []                                        // empty array since we didn't do anything
    },
    "status": "400",
    "description": "HTTP error code 400: BTE doesn't perform one or more of the operations specified in the query's workflow field"
}
```

**Comment by andrewsu** [comment]
I think to make it backward compatible with our other example queries, what do people think about this behavior: (UPDATED 2021-08-04)

* If `workflow` is specified and `"id": "lookup"` is the only value, **--OR--** no `workflow` is specified: follow case 1 described in @colleenXu's comment above
* If `workflow` is specified but `"id": "lookup"` is NOT included **--OR--** `workflow` is specified and there are multiple values: follow case 2 above

**Comment by colleenXu** [comment]
@andrewsu @ericz1803 I'm updating the comment with Andrew's feedback and what I know from Translator so far. 

I think the Translator [guidance](https://github.com/NCATSTranslator/OperationsAndWorkflows/wiki/How-to-%22do%22-operations) says that if a tool is given a query with MULTIPLE operations (including lookup), and the tool can only do lookup, it shouldn't do anything - it should return an error.

So that's the caveat I would add to what Andrew has said above...

**Comment by andrewsu** [comment]
Great, I updated my previous comment to better align with the case that Colleen mentioned above for multiple operations. @ericz1803, please confirm your PRs follow the rules above (or adjust accordingly), then post a comment here.  

Completion deadline of 2021-09-01, but would be great to get this done far before then.

**Comment by ericz1803** [comment]
Yup, it will return an error if the length of the `workflow` array is anything other than 1.

**Comment by colleenXu** [comment]
confirmed the following correct behavior using a local instance + the dev url:
- a TRAPI query without the workflow field works normally, returns a Response with the workflow field ({id: lookup})
- a TRAPI query with the workflow field ({id: lookup}) works normally, returns a Response with the workflow field ({id: lookup})
- a TRAPI query with the workflow field with multiple elements (like two {id: lookup}) or 1 element that isn't {id:hi}...doesn't work normally + does returns empty knowledge_graph / results, status code 400, and description: "WorkflowError: BTE doesn't handle the operations specified in the workflow field."
