### ISSUE TITLE
BTE and "reverse" semmed operations

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#227]
When issuing this query for ChemicalSubstances related to cyclic vomiting, we expect BTE to return a result for (at least) isopropyl alcohol.  Currently BTE returns no results.

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "HP:0002013"
                    ],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

`HP:0002013` should get translated to `UMLS:C0042963` via http://pending.biothings.io/hpo/phenotype/HP:0002013, and then we should be able to get that `UMLS:C0042963` is treated by isopropyl alcohol (`UMLS:C0022237`) via http://pending.biothings.io/semmedchemical/query?q=treats.umls:C0042963&limit=500&fields=name.

Source issue: https://github.com/NCATSTranslator/testing/issues/91

**Comment by andrewsu** [comment]
There are three options for solving this:

1. adding in all reverse triples into the semmed APIs via the semmed parsers
2. adding in reverse operations in `x-bte`
3. adding logic within BTE to understand inverse edges and query appropriately

After discussion with @colleenXu, we will go forward with option 2 above -- Colleen will update `x-bte` for the semmedchemical API to test that this fixes this issue.  Colleen will also consult their annotations of missing reverse edges to look at making sure we are (relatively) exhaustive.

**Comment by colleenXu** [comment]
After talking with Andrew Su today, this ticket is on hold for two reasons. 
1. It involves more work than expected (refactoring BTE's code for [processing the SEMMED APIs' responses](https://github.com/biothings/api-respone-transform.js/blob/main/src/transformers/semmed_transformer.ts))
2. A separate [effort](https://github.com/biothings/pending.api/issues/30) is underway to update the SEMMED APIs and use a different structure and querying capabilities...

Details below:

---

The original inspiration for this ticket was "reverse" operations for SEMMED apis. However, only annotating the operations in x-bte did not result in successfully-executed operations (the saved yaml with these reverse operations added is [here](https://github.com/NCATS-Tangerine/translator-api-registry/commit/872ae0e0dd52d78d3c608927c657b91953d451bc))...BTE looks to execute the query correctly, but doesn't seem to process it correctly to pick out the output IDs. One can try it themselves by converting the yaml to json, then saving it to the [test/smartapi.json in bte-trapi](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/test/smartapi.json), compiling their local instance, and then sending queries (POST) to the test/query endpoint of the local instance. 

It looks like BTE's code for [processing the SEMMED APIs' responses](https://github.com/biothings/api-respone-transform.js/blob/main/src/transformers/semmed_transformer.ts) would need refactoring (recognizing the two different structures for reverse vs forward querying and processing them differently?). 

Example: to get from the Disease "Congenital pectus carinatum" (UMLS:C0158731) to the chemicals that treat it, we can do this "reverse" query to SEMMED chemical API:

POST to https://biothings.ncats.io/semmedchemical/query?fields=umls 
```
{
    "q":"C0158731",
    "scopes": "treats.umls"
}
```

The response looks like this:

```
[
    {
        "query": "C0158731",
        "_id": "C0027996",
        "_score": 7.2889276,
        "umls": "C0027996"
    },
    {
        "query": "C0158731",
        "_id": "C0074758",
        "_score": 7.254178,
        "umls": "C0074758"
    },...
]
```

This is a different structure compared to what BTE "sees" with forward querying, and I think it's being processed incorrectly by BTE's current code for handling SEMMED API responses...

**Comment by colleenXu** [comment]
need to check that this query works before closing...

**Comment by colleenXu** [comment]
I've confirmed that we are now able to do this query with semmeddb (after modifying it to use ChemicalEntity)....and get the expected result. This is because semmeddb is annotated with the reverse operations. 

The SRI-ID resolver does equate HP:0002013 to UMLS:C0042963. However, it currently does not recognize [UMLS:C0022237](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=UMLS%3AC0022237&conflate=true), so BTE does not have its name as isoproyl alcohol...

The query

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["HP:0002013"],
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n1": {
                    "categories": ["biolink:ChemicalEntity"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
    }
}
```

Returns a node
```
                "UMLS:C0022237": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ],
                    "name": "UMLS:C0022237",
```

with this edge:
```
                "986fb6ffa0d0ad88e0fb6fbd15ab4bbe": {
                    "predicate": "biolink:treated_by",
                    "subject": "HP:0002013",
                    "object": "UMLS:C0022237",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:translator-biothings-explorer"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:primary_knowledge_source",
                            "value": [
                                "infores:semmeddb"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-semmeddb"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "publications",
                            "value": [
                                "PMID:15632723",
                                "PMID:30108075"
                            ]
                        },
                        {
                            "attribute_type_id": "biolink:original_object",
                            "value": "C0042963"
                        },
                        {
                            "attribute_type_id": "biolink:original_predicate",
                            "value": "TREATS"
                        },
                        {
                            "attribute_type_id": "biolink:original_subject",
                            "value": "C0022237"
                        },
                        {
                            "attribute_type_id": "original_object_name",
                            "value": "Vomiting"
                        },
                        {
                            "attribute_type_id": "original_subject_name",
                            "value": "Isopropanol"
                        }
                    ]
                },
```
