### ISSUE TITLE
Support for Service Provider handling of updated KGX file format for Text Mining Provider

### ISSUE THREAD

**Issue by bill-baumgartner** [biothings/biothings_explorer#229]
Hi BTE,

During the Data Modeling call on 7/22, Chris Mungall presented several proposals for updating the KGX file format to handle the new attribute/provenance model. One of the formats (Option 4) was the consensus pick for moving forward during the call. We have worked through an example of expressing provenance of our text-mined assertions using this new format (see the bottom of [this issue](https://github.com/biolink/kgx/issues/174#issuecomment-885836172)). I'm hoping to get some feedback on that example in case I've made any errors in the representation, but in general I think our plan is to modify our KGX serialization code to produce that format. 

I know BTE is also working on implementing the provenance standard internally. I thought this might be a good time to start a conversation about the Service Provider potentially consuming the updated KGX format, and to make sure we are all on the same page.

I think the code currently used for parsing our KGX files might be [here](https://github.com/kevinxin90/text_mining_targeted_association/blob/master/parser.py) & [here](https://github.com/kevinxin90/text_mining_cooccurrence_kp/blob/master/parser.py) although I'm not certain of that. Let me know what you see as the best path forward. For example, would it make sense for us to handle modifications to the parsing code (allowing us to update things with minimal work on your end)? Thanks!

**Comment by andrewsu** [comment]
@bill-baumgartner As we ramp up to the December demo, we don't have the bandwidth to add another import format to our BioThings SDK.  Does the current file export contain all the necessary provenance (or can it be easily extended to include that)?  Alternatively, your team would be welcome to adjust the specific parser used for the text mining API.

**Comment by bill-baumgartner** [comment]
The current file format does not support the new provenance standard, though I'm guessing it can be extended (note that the links above go to Kevin's personal github as he wrote the original parser). In order to update it I think I would need some guidance on how to integrate with BTEs support for the provenance model. Alternatively, what process is used to import the Multiomics KP? Does that process support the new provenance model and if so, would it make sense for us to use the same process?

**Comment by andrewsu** [comment]
tagging @newgene on whether this is still relevant and how to prioritize

**Comment by bill-baumgartner** [comment]
I think this issue has since been resolved, or is in the process of being resolved by Edgar and the ServiceProvider team. @edgargaticaCU can you confirm?

**Comment by edgargaticaCU** [comment]
Yes, this has been resolved

**Comment by andrewsu** [comment]
Great!  In the interest of doing a little cleanup I'm going to close this issue, but feel free to re-open if it's helpful in the future!
