### ISSUE TITLE
Refactor BTE client to read meta-KG from SmartAPI

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#23]
currently, the meta-KG is read from [config.py](https://github.com/biothings/bte_schema/blob/master/biothings_explorer/config.py). Need to change this to read from smartAPI.

**Comment by kevinxin90** [comment]
This feature is implemented in 6d65f2d9a7fc3bcfa102991eec56f3744b51e22b

**Comment by kevinxin90** [comment]
The feature allows BTE to periodically fetch smartAPI specs from the smartAPI registry at https://smart-api.info/registry through its API. 

Additional features to parse SmartAPI specs and convert them into API meta graph is also implemented.
