### ISSUE TITLE
populated knowledge_graph nodes and edges but no results

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#236]
The two queries below return a response with a populated `knowledge_graph` but a zero-length `results` section.

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "MONDO:0004975"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:BiologicalProcessOrActivity"
                    ]
                },
                "n2": {
                    "ids": [
                        "PUBCHEM.COMPOUND:1935"
                    ],
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "NCBIGene:43"
                    ],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:BiologicalProcessOrActivity"
                    ]
                },
                "n2": {
                    "ids": [
                        "PUBCHEM.COMPOUND:1935"
                    ],
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

Original behavior and examples from https://github.com/NCATSTranslator/testing/issues/93

**Comment by colleenXu** [comment]
Note that both of these are Explain-type queries (n0 with ID -> n1 with category <- n2 with ID). Should be handled with Marco/Anders work. 

Also, I've edited them to use SmallMolecule instead, below

---

Query 1: 
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0004975"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:BiologicalProcessOrActivity"]
                },
                "n2": {
                    "ids": ["PUBCHEM.COMPOUND:1935"],
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

Query 2:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["NCBIGene:43"],
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "categories": ["biolink:BiologicalProcessOrActivity"]
                },
                "n2": {
                    "ids": ["PUBCHEM.COMPOUND:1935"],
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
Related to #112

**Comment by andrewsu** [comment]
Here is another query (a PREDICT query) with the same behavior (from https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.2_RHOBTB2_twohop.json).  So not strictly an issue with EXPLAIN.

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "object": "n0",
                    "subject": "n1",
                    "predicates": [
                        "biolink:entity_regulates_entity"
                    ]
                },
                "e02": {
                    "object": "n1",
                    "subject": "n2",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            },
            "nodes": {
                "n0": {
                    "ids": [
                        "NCBIGene:23221"
                    ],
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n2": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
This query may be handled oddly by BTE because of the directions of the query edges. It looks like this: Gene ID <-(e01)- Gene <-(e02)- SmallMolecule. 

It looks to me that something does go wonky in the results assembly step.

[EDIT] Marco's current query-logic code fails on this query because of the e02 edge. It tries to query in the specified direction from SmallMolecule -> Gene when there's no IDs for SmallMolecule. 

---

Additionally, I can see a separate bug that I've noticed before...BTE is not passing IDs correctly for the second query step (e02) if ID resolution failed for that ID. This is how I can tell, using the logs:


- BTE filtered down to 8 Gene IDs for the e01 step. 
  ```
        {
            "timestamp": "2021-08-12T21:35:16.088Z",
            "level": "DEBUG",
            "message": "query_graph_handler: Successfully applied post-query predicate restriction: 181 down to 8 results.",
            "code": null
        },
  ```
- then BTE starts using those 8 Gene IDs for the e02 step. 
- This e02 subquery for 8 UMLS IDs is formatted incorrectly for 3 of the IDs...they shouldn't have the UMLS prefix. It's like BTE doesn't recognize the prefix is there for those 3 IDs...
  ```
        {
            "timestamp": "2021-08-12T21:35:16.218Z",
            "level": "DEBUG",
            "message": "call-apis: Succesfully made the following query: {\"url\":\"https://biothings.ncats.io/semmedgene/query\",\"params\":{\"fields\":\"affected_by\"},\"data\":\"q=C3147205,UMLS:C4085573,C0812258,C1366500,UMLS:C1418864,C1418893,C1421286,UMLS:C0079427&scopes=umls\",\"method\":\"post\",\"timeout\":50000}",
            "code": null
        },
  ```
- This e02 subquery uses only 5 NCBIGene IDs. This implies that NCBIGene IDs weren't found for 3 other IDs - probably the 3 UMLS IDs noted above...
   ```
        {
            "timestamp": "2021-08-12T21:35:16.286Z",
            "level": "DEBUG",
            "message": "call-apis: Succesfully made the following query: {\"url\":\"https://biothings.ncats.io/dgidb/query\",\"params\":{\"fields\":\"object.CHEMBL_COMPOUND,association\",\"size\":1000},\"data\":\"q=100616101,1869,5241,5555,7332&scopes=subject.NCBIGene\",\"method\":\"post\",\"timeout\":50000}",
            "code": null
        },
  ```

**Comment by colleenXu** [comment]
should revisit with Eric/Marco/Anders work on query handling and SRI-based ID resolution. 

And Jackson's work on templating API calls (may fix issues with the querying and prefixes)

**Comment by ariutta** [comment]
With the latest updates, the sample queries provided above appear to be working now.

**Comment by andrewsu** [comment]
If easy, can someone also try this query out? https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.1/soxGenes.json

The current prod is giving that same behavior (documented in https://github.com/NCATSTranslator/testing/issues/111), and it would be nice to confirm that it's fixed in the latest changes...

**Comment by colleenXu** [comment]
That's expected because Eric/Marco/Anders work hasn't been merged to main / implemented yet...

**Comment by colleenXu** [comment]
That's expected because Eric/Marco/Anders work hasn't been merged to main / implemented yet...

When I used their code, it worked correctly and as-expected...I've included the file of the response here (github won't let me post json so it's txt)....
[explain-8-30-21.txt](https://github.com/biothings/BioThings_Explorer_TRAPI/files/7103473/explain-8-30-21.txt)

that can be pasted in arax under import -> json and visualized like the included screenshot
![Screen Shot 2021-09-02 at 10 20 31 PM](https://user-images.githubusercontent.com/43731687/131954484-bd2f618b-90c5-492b-8594-22ee3e002836.png)

**Comment by colleenXu** [comment]
Updates now that the new code is on BTE-prod (https://api.bte.ncats.io/v1/query):

I'm going to post some info from each of the queries listed in this issue.

---

Query 1: 
Disease MONDO:0004975 -> BiologicalProcessOrActivity <- SmallMolecule PUBCHEM.COMPOUND:1935 

We find 2 results! 
![Screen Shot 2021-09-10 at 8 49 03 PM](https://user-images.githubusercontent.com/43731687/132935411-55a1472b-751a-4efa-85f2-697d12060592.png)

Knowledge graph:
![Screen Shot 2021-09-10 at 8 51 15 PM](https://user-images.githubusercontent.com/43731687/132935454-363a9354-1dd8-428f-97c0-9bb6cbc5ac41.png)


```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0004975"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:BiologicalProcessOrActivity"]
                },
                "n2": {
                    "ids": ["PUBCHEM.COMPOUND:1935"],
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}

```

**Comment by colleenXu** [comment]
Continued updates (queries going to BTE-prod (https://api.bte.ncats.io/v1/query):

Query 2:
Gene NCBIGene:43 -> BiologicalProcessOrActivity <- SmallMolecule PUBCHEM.COMPOUND:1935

we find 3 results!
![Screen Shot 2021-09-10 at 8 54 05 PM](https://user-images.githubusercontent.com/43731687/132935515-583612ac-9d89-4e0a-81ed-59a520b07832.png)

knowledge graph:
![Screen Shot 2021-09-10 at 8 53 43 PM](https://user-images.githubusercontent.com/43731687/132935516-5f000ae3-d4df-4f8a-bac6-b2d8e629c12b.png)

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["NCBIGene:43"],
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "categories": ["biolink:BiologicalProcessOrActivity"]
                },
                "n2": {
                    "ids": ["PUBCHEM.COMPOUND:1935"],
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}

```

**Comment by colleenXu** [comment]
Continued updates (queries going to BTE-prod (https://api.bte.ncats.io/v1/query):

Query 3:
Gene NCBIGene:23221 <-(entity_regulates_entity OR genetically_interacts_with)- Gene <- SmallMolecule. Edited due to the current [mini-hackathon query](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.2_RHOBTB2_twohop.json). 

PK: 49a2bd2b-7a20-40f3-9168-c54d7358b9e3
Seemed to run at an okay speed (~1/2 a min), 4.6 MB, 802 results). 

There are 2 genetically_interacts_with edges between genes; they are coming from Automat Hetios API...one can see this by searching within the dev-info tab. 

An example result:
![Screen Shot 2021-09-10 at 9 42 30 PM](https://user-images.githubusercontent.com/43731687/132936491-f76db3d0-1770-4905-bf65-97b30656f730.png)

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n1",
                    "object": "n0",
                    "predicates": ["biolink:entity_regulates_entity",
                                   "biolink:genetically_interacts_with"]
                },
                "e02": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["NCBIGene:23221"],
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                },
                "n2": {
                    "categories": ["biolink:SmallMolecule"]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
Continued updates (queries going to BTE-prod (https://api.bte.ncats.io/v1/query):

Query 4's output (21 results) looks the same as what was previously posted: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/236#issuecomment-912263477

Note that SRI's ID resolver service doesn't resolve some of the UMLS IDs (the previous BioThings API based ID resolver didn't do great at resolving these IDs also). 

EDIT: PK: 79a5e048-483c-4a69-8406-15ae6430a51a
![Screen Shot 2021-09-10 at 9 53 46 PM](https://user-images.githubusercontent.com/43731687/132936724-1b33a968-ab92-4ecf-9ba4-340c46ec9d54.png)

**Comment by colleenXu** [comment]
Closing; I provided updates for all the queries involved in this issue. I also addressed and linked the related issues in the Translator repos.
