### ISSUE TITLE
incorporate homolog/ortholog relationships into December demo queries?

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#237]
I don't recall that many of the December demo queries take advantage of homology relationships, particularly orthology in model organisms.  BTE does that reasonably well for mouse genes and associated diseases/phenotypes using https://biothings.ncats.io/mgigene2phenotype, so it could be a distinguishing feature.  For example, here is a query that starts with human PAX6 and asks for related homologs and then related diseases:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": "biolink:Gene",
                    "ids": "NCBIGene:5080"
                },
                "n1": {
                    "categories": "biolink:Gene"
                },
                "n2": {
                    "categories": "biolink:Disease"
                }
            },
            "edges": {
                "e00": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:homologous_to"]
                },
                "e01": {
                    "subject": "n1",
                    "object": "n2"
                }
            }
        }
    }
}
```

NOTES 
* The above query leverages this API call https://biothings.ncats.io/mgigene2phenotype/gene/MGI:97490, which also returns associated phenotypes (not just diseases).  Phenotypes are represented using `MP` (Mammalian Phenotype), but we don't have any knowledge source that traverses MP to HPO.
* We may be able to also incorporate links between genes in other model systems and human diseases by building/annotating related APIs from Rat Genome Database, WormBase, Flybase, etc.

**Comment by andrewsu** [comment]
tagging @colleenXu to keep an eye out for opportunities to use these edges in use cases.

also linking https://github.com/biothings/pending.api/issues/28, which should expand the number of human diseases linked to those orthologs in model organisms.

**Comment by sierra-moxon** [comment]
https://www.alliancegenome.org/downloads#orthology <-- this represents the set of orthologs (derived via both curated and computed sources) that has been agreed upon as the source of orthology for AGR (Alliance of Genome Resources: yeast, worm, fly, zebrafish, rat, mouse, and human).

**Comment by andrewsu** [comment]
closing as no longer relevant
