### ISSUE TITLE
MEDDRA nodes not resolving human-readable names

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#242]
The **query** below identifies many adverse events related to the drug ENALAPRIL, I think all via the mychem.info API (related to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/217). However, the MEDDRA IDs do not resolve to human-readable names.  For example, see **screenshot** from the ARAX viewer (https://arax.ncats.io/?source=ARS&id=0ec48c05-fa32-4b91-b6c8-dfc37f14d326), or the **JSON snippet** below.  For example, per http://purl.bioontology.org/ontology/MEDDRA/10009192 I would have expected `MEDDRA:10009192` to use `Circulatory collapse` in the `name` field.

**Query**:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "PUBCHEM.COMPOUND:40466924"
                    ],
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ]
                },
                "n1": {
		             "categories":[
                         "biolink:Disease"
                        ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates":["biolink:causes","biolink:causes_adverse_event"]
                }
            }
        }
    }
}
```

**Screenshot**
![image](https://user-images.githubusercontent.com/2635409/128384975-e6ef9567-62e8-46d4-a6a4-67cef4f6390f.png)

**JSON snippet**
```
        "knowledge_graph": {
            "nodes": {
                "MEDDRA:10009192": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "MEDDRA:10009192",
                    "attributes": [
```

**Comment by colleenXu** [comment]
I don't see the meddra term names in MyDisease.info (https://mydisease.info/v1/metadata/fields). 

we would need the field for meddra names, and would need to add it to the [disease names](https://github.com/biothings/biomedical_id_resolver.js/blob/da6df549d54837d340501a8424e7a7166be241a0/src/config.ts#L182)

**Comment by colleenXu** [comment]
Related to #246, #247?

**Comment by colleenXu** [comment]
BTE should be able to handle this (or would push the issue to SRI node normalization team..) after migrating to use Eric's SRI-based ID resolver. 

Example with the meddra ID in the opening comment: https://nodenormalization-sri-dev.renci.org/1.1/get_normalized_nodes?curie=MEDDRA%3A10009192

**Comment by colleenXu** [comment]
BTE should be able to handle this now. I sent this query and it looks like most meddra IDs were mapped to other IDs (with prefixes in higher priority), have corresponding names, and have correct semantic types (PhenotypicFeature or Disease)

Note that the query MUST encompass SmallMolecule on the node where the chemical ID is, because the underlying IDISK operation uses SmallMolecule <-> Disease as its annotation

updated query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["PUBCHEM.COMPOUND:40466924"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
		             "categories":["biolink:Disease"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates":["biolink:causes","biolink:causes_adverse_event"]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
However, the SRI-based ID resolver will have issues with finding equivalent IDs or names for some IDs. 

For example, these 17 nodes continue to not have equivalent IDs or human-readable names:
* MEDDRA:10000220
* MEDDRA:10001488
* MEDDRA:10001854
* MEDDRA:10064385
* MEDDRA:10006924
* MEDDRA:10018875
* MEDDRA:10034660
* MEDDRA:10036556
* MEDDRA:10050729
* MEDDRA:10061105
* MEDDRA:10066338
* MEDDRA:10069326
* MEDDRA:10040914
* MEDDRA:10043458
* MEDDRA:10049414
* MEDDRA:10056407
* MEDDRA:10038749
