### ISSUE TITLE
Translator Demo Workflow B - Exploring Agent queries

### ISSUE THREAD

**Issue by karafecho** [biothings/biothings_explorer#244]
This issue is to kindly request that Exploring Agent tests [Workflow B](https://github.com/NCATSTranslator/minihackathons/tree/main/2021-12_demo/workflowB). Here is an example [TRAPI query](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowB/B.1c_DILI_three-hop-from-disease-or-phenotypic-feature_trapi.json) that runs when sent through the ARS, but the only ARA that returns responses is ARAX. The ARS issue is apparently related to time-out errors that will be resolved with the release of TRAPI 1.2 and support for asynchronous queries, but that will not happen until early September. Thus, Hao and I would like to test direct ARA queries, and we are requesting your help. Note that we are also testing direct ARA queries using multihop.py, but BTE tests would be helpful, as multihop.py doesn't support sophisticated features like ranking, etc.

The README file provides an overview of the workflow, including suggested input CURIES. Note that the first predicate will be changed from biolink:correlated_with to biolink:has_real_world_evidence_of_association_with, but I will be sure to alert you to this change after clinical KPs implement the new predicate. 

We are also testing query constraints, such as replacing biolink:related_to with biolink:interacts_with and biolink:Gene with biolink:BiologicalProcessOrPathway. Other options are welcome. Andrew and I discussed alternative workflow paths, too, so that's another option.

We realize that you all are extremely busy, but we would greatly appreciate a few quick tests. Please feel free to reach out to me or Hao Xu with questions.

**Comment by andrewsu** [comment]
@karafecho I was assuming that all of Workflow B was dependent on either ICEES or COHD being hooked up, but I realize now that I never confirmed that assumption.  Am I right?

If yes, then completion of workflow B queries is dependent on us solving https://github.com/biothings/BioThings_Explorer_TRAPI/issues/213 and/or https://github.com/biothings/BioThings_Explorer_TRAPI/issues/223.  #213 is being actively worked on now...

**Comment by karafecho** [comment]
You are partially correct, Andrew. The first hop is intended to target clinical KPs, but because we are currently using the predicate biolink:correlated_with, it only hits COHD and ICEES. However, that will change with adoption of the new Biolink 2.2.1 predicate biolink:has_real_world_evidence_of_association_with, in which case the first hop should return results from COHD, ICEES, Multi-omics EHR Risk Provider, and CHP. The clinical KPs have not yet implemented this predicate, but I will be sure to alert you after they have.

And yes, I realize that you all are actively working on the issues you note. Just thought I'd post this ticket as a possible task to accomplish after those issues have been resolved.

Many thanks!

**Comment by karafecho** [comment]
BTW, I've been working with the ICEES+ CAM KP team to explore the alternative workflow that you, Andrew, suggested. Specifically, we've been exploring biolink:Gene -> biolink:GeneOrGeneProduct (up/downstream genes) and biolink:Gene -> biolink:BiologicalProcessOrActivity connections, beginning with the five genes that are known/suspected to be causally related to DILI (listed in the README file). While these queries address a different question, I think we may be able to use them to provide additional support for the overall workflow and associated narrative. Just an FYI...

**Comment by andrewsu** [comment]
completed use case -- closing
