### ISSUE TITLE
MeSH nodes not resolving to human-readable names

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#246]
The TRAPI query below (for diseases related to benzene) currently returns 222 nodes in the response.  Of these, there are 20 nodes for which the MeSH IDs do not resolve to human-readable names in the `name` field, 66 nodes for which the UMLS IDs do not resolve to human-readable names.  Desired behavior would be that human-readable names would be shown in the `name` field.  Examples below.  I suspect the solution has to do with loading more MeSH xrefs to mydisease.info.

**This issue tracks the resolution of the the MeSH issue.**  The UMLS issue is tracked at #247: 

Query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "PUBCHEM.COMPOUND:241"
                    ],
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

**Desired behavior:**

```
                "MONDO:0018881": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "myelodysplastic syndrome",
                    "attributes": [
```

**UMLS not resolving**

```
                "UMLS:C0016658": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "UMLS:C0016658",
```

**MeSH not resolving**

```
                "MESH:D009336": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "MESH:D009336",
                    "attributes": [
```

**Comment by colleenXu** [comment]
Related to #242, #247

**Comment by colleenXu** [comment]
BTE should be able to handle this (or would push the issue to SRI node normalization team..) after migrating to use Eric's SRI-based ID resolver.

Example with the IDs in the opening comment: https://nodenormalization-sri-dev.renci.org/1.1/get_normalized_nodes?curie=UMLS%3AC0016658
https://nodenormalization-sri-dev.renci.org/1.1/get_normalized_nodes?curie=MESH%3AD009336

**Comment by colleenXu** [comment]
I've run the query above, and I do see that the MESH ID D009336 is now resolved to have the name Necrosis (and semantic type PhenotypicFeature). 

Another MESH IDs with human-readable name is:
* MESH:D048629 (Micronuclei, Chromosome-Defective / CellularComponent)

**Comment by colleenXu** [comment]
With the new SRI-based ID resolver, this query no longer returns nodes with "name": "MESH..." or "name": "UMLS..." based on my quick search of the response.

However, the SRI-based ID resolver will have issues with finding equivalent IDs or names for some IDs.
