### ISSUE TITLE
UMLS nodes not resolving to human-readable names

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#247]
The TRAPI query below (for diseases related to benzene) currently returns 222 nodes in the response.  Of these, there are 20 nodes for which the MeSH IDs do not resolve to human-readable names in the `name` field, 66 nodes for which the UMLS IDs do not resolve to human-readable names.  Desired behavior would be that human-readable names would be shown in the `name` field.  Examples below.  I suspect the solution has to do with loading more MeSH xrefs to mydisease.info.

**This issue tracks the resolution of the the UMLS issue.**  The MeSH issue is tracked at: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/246

Query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "PUBCHEM.COMPOUND:241"
                    ],
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

**Desired behavior:**

```
                "MONDO:0018881": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "myelodysplastic syndrome",
                    "attributes": [
```

**UMLS not resolving**

```
                "UMLS:C0016658": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "UMLS:C0016658",
```

**MeSH not resolving**

```
                "MESH:D009336": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "MESH:D009336",
                    "attributes": [
```

**Comment by colleenXu** [comment]
BTE should be able to handle this (or would push the issue to SRI node normalization team..) after migrating to use Eric's SRI-based ID resolver.

Example with the IDs in the opening comment: https://nodenormalization-sri-dev.renci.org/1.1/get_normalized_nodes?curie=UMLS%3AC0016658
https://nodenormalization-sri-dev.renci.org/1.1/get_normalized_nodes?curie=MESH%3AD009336

**Comment by colleenXu** [comment]
Note: I no longer find the example UMLS ID (C0016658) in the TRAPI response. 

However, with the new SRI-based ID resolver, this query no longer returns nodes with "name": "MESH..." or "name": "UMLS..." based on my quick search of the response.

However, the SRI-based ID resolver will have issues with finding equivalent IDs or names for some IDs.
