### ISSUE TITLE
A better mechanism for updating locally cached smartapi-kg (e.g. multiple server processes)

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#252]
In production deployment, we will likely deploy multiple BTE server processes for better throughput: either multiple docker containers or multiple server processes on the same server.

The current caching mechanism for local smartapi-kg happens on each server process as a cron-like job. When multiple processes are running, they can cause conflicts and duplicate the caching tasks. In multi-container deployment scenario, local cached smartapi-kg can be inconsistent between containers (each keeps cache locally).

We need a better mechanism to save and load cached smartapi-kg across multiple processes.

**Comment by newgene** [comment]
The first thing we can do is to add an ENV variable, e.g. `DISABLE_SMARTAPI_SYNC`, to disable the cron job for routine updates of the local SmartAPI metadata. This will allow us to spawn multiple server processes to handle queries, but leave only one of processes handles the local metadata caching, avoiding repeated cron jobs and potential conflicts from multiple processes.

**Comment by tokebe** [comment]
@newgene I've created the env variable and related behavior (see #266).

As for a better long-term solution, we could create a launch script which specifically sets this variable on each 'non-main' instance? For the Docker scenario, I'm thinking a launch script which creates a shared volume for the cache, and then creates each container, with all but one having the environment variable set, and a new environment variable to point to the cache location to look for cached files. It may not be the most elegant solution, but it should be relatively simple.

**Comment by colleenXu** [comment]
@newgene @tokebe Is this issue ready to close?

**Comment by newgene** [comment]
Implemented in e54ced6df4c83dae1e9783af8bce804ec7f97e69. Now on our production server, PM2 starts multiple processes, but on the first process will handle the smartapi-kg data file caching.
