### ISSUE TITLE
Make query_results.js use generalize_query_handling

### ISSUE THREAD

**Issue by ariutta** [biothings/biothings_explorer#254]
@marcodarko has been updating the query handling code in this branch:
https://github.com/biothings/bte_trapi_query_graph_handler/tree/generalize_query_handling

This code uses a new data structure and needs new method(s) for calling the [query_results.js](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/src/query_results.js) code.

**Comment by ariutta** [comment]
In a change from the current code, the new generalize_query_handling  code calls `update` just once with all records, so it's now necessary to inspect the records to deduce the query graph.

**Comment by colleenXu** [comment]
Close since Marco and Anders merged their code.

**Comment by ariutta** [comment]
FYI: I added some tests for assembling large numbers of records into query results, but I disabled them, because they take a long time:
https://github.com/biothings/bte_trapi_query_graph_handler/blob/generalize_query_handling/__test__/integration/QueryResult_2.test.js#L1332-L1711

Here are the approximate times for different numbers of records per edge for a simple query graph `n0 -e0-> n1 -e1-> n2`:
1. e0 has 500 records, and e1 has 50k: **40 sec**
2. e0 has 1k records (500 connected, 500 not), and e1 has 100k (50k connected, 50k not): **80 sec**
3. e0 has 1k connected records, and e1 has 100k: **200 sec**
