### ISSUE TITLE
Update config list to use SmartAPI IDs instead of API name

### ISSUE THREAD

**Issue by ericz1803** [biothings/biothings_explorer#258]
In the `config.js` file, use SmartAPI IDs instead of API name.

Options:
1. Config list will include objects in the shape of 
```
{
  id: SMARTAPI_ID
  name: API_NAME
}
```
Also include validation where a warning is raised if the api name in the config doesn't match what we get using the smartapi id.

~~2. List of SmartAPI IDs with names as comments~~

**Comment by colleenXu** [comment]
The question is whether other packages import names / use stuff from this file. It is known that other packages do use the api names (that they get from....somewhere) to do stuff depending on what API the data comes from (call_apis, query handler, api response transform are some that I can think of)

**Comment by ericz1803** [comment]
As far as I can tell, nothing uses this file other than when `v1/query` is hit and it passes the `API_LIST` from bte-trapi -> query-graph-handler -> smartapi-kg.

**Comment by colleenXu** [comment]
does the query_graph_handler module need a PR / update as well?

**Comment by ericz1803** [comment]
Nope, I didn't need to change any of that code since it passes the options unchanged to smartapi-kg

**Comment by colleenXu** [comment]
@ericz1803 could you update your work based on the [updated list] from this PR #262 ?

The changes:
- removes some APIs that were recently taken offline
- adds a replacement API (Automat CORD19)
- adds some commentary on the "commented out" APIs
- adds some commentary on Automat APIs that we could add

**Comment by ericz1803** [comment]
Updated. I left out the APIs that are no longer useful but I fixed the CORD 19 and also added in the other Automat APIs as comments.
