### ISSUE TITLE
integrate new AGR API for gene-disease relationships into BTE

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#260]
Involves:
- writing SmartAPI yaml with x-bte operations (for gene <-> disease associations)
- registering the yaml with SmartAPI Registry
- changing the list of APIs BTE ingests to include this new API

**Comment by mnarayan1** [comment]
I can start working on this issue.

**Comment by colleenXu** [comment]
### Current situation

- AGR yaml is [written](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/AGR/agr.yaml) and [registered in SmartAPI registry](https://smart-api.info/registry?q=68f12100e74342ae0dd5013d5f453194)
- **However**, I haven't successfully tested >50% of the operations (ones that have DOID or MGI input), due to [bugs](https://github.com/biothings/biothings_explorer/issues/756). So I haven't made a PR to add this API to BTE's config list yet. 
- Related infores stuff is ready:
    - updated [infores page for agrkb](https://github.com/NCATSTranslator/Translator-All/wiki/Alliance-of-Genome-Resources) (primary knowledge source)
    - EDIT: [new infores catalog entry for `biothings-agr` in this PR](https://github.com/biolink/biolink-model/pull/1429) but this may not be important (UI doesn't show because it's not the primary knowledge source?) 
    - created [placeholder infores page for biothings-agr](https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-AGR-API)

**Note for the future**: It may be useful to update the [BioThings AGR](https://biothings.ncats.io/agr) data/parser? It looks like the last updates may be from 2021, based on the /metadata endpoint + source code. And new data like Xenbase was added in 2022 (https://www.alliancegenome.org/about-us), which would involve checking/probably-adding x-bte annotation.

---

#### Notes on writing the SmartAPI yaml

* lots of prior discussion in the original PR https://github.com/NCATS-Tangerine/translator-api-registry/pull/127
* my latest edits were direct commits: https://github.com/NCATS-Tangerine/translator-api-registry/commit/e067feb424298cbdd0e1d9c008f61cb8aa8acebd to https://github.com/NCATS-Tangerine/translator-api-registry/commit/5bdd73b9d5b3252e3c9a376b66a61631445d42c4
* I didn't end up using qualifiers:
    * unclear how to handle for the "via orthology" data: is the species context from another field like `with_orthologs`? 
    * not necessary for direct data? (the gene node/ids/symbols is species-specific) 
* [Madhumita noted in the yaml comments that there were Xenbase and GO _id values, but I didn't see any](https://github.com/NCATS-Tangerine/translator-api-registry/blob/5bdd73b9d5b3252e3c9a376b66a61631445d42c4/AGR/agr.yaml#L612). I only found 7 species in the data, as noted in the yaml comments (no Xenopus from Xenbase). I used [this query](https://biothings.ncats.io/agr/query?q=NOT%20(agr.species_name:Homo%20OR%20agr.species_name:Mus%20OR%20agr.species_name:Rattus%20OR%20agr.species_name:Danio%20OR%20agr.species_name:Drosophila%20OR%20agr.species_name:Caenorhabditis%20OR%20agr.species_name:Saccharomyces)) in my search.

**Comment by colleenXu** [comment]
Because of the [bug fix](https://github.com/biothings/biothings_explorer/issues/756#issuecomment-1839117638), I was able to test the x-bte annotation locally and confirm that it all worked. 

<details><summary>Test query: start with MGI</summary>
<p>

Start with Gene MGI:109384 (Atf3), based on this [operation's example](https://github.com/NCATS-Tangerine/translator-api-registry/blob/3ca57d15f1e7ca8c0fb4b41d3cbf888f7d5680c6/AGR/agr.yaml#L829)

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MGI:109384"],
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:biomarker_for"]
                }
            }
        }
    }
}
```

Should retrieve this edge linked to prostate cancer (`DOID:10283` in original API, `MONDO:0008315` in TRAPI)

```
                "543f7cb2ec69057e885f3a90b50f1705": {
                    "predicate": "biolink:biomarker_for",
                    "subject": "NCBIGene:11910",
                    "object": "MONDO:0008315",
                    "attributes": [],
                    "sources": [
                        {
                            "resource_id": "infores:agrkb",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:biothings-agr",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:agrkb"
                            ]
                        },
                        {
                            "resource_id": "infores:service-provider-trapi",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:biothings-agr"
                            ]
                        }
                    ]
                },
```

</p>
</details> 

<details><summary>Test query: start with DOID</summary>
<p>

Start with Disease DOID:10629 (microphthalmia), based on this [operation's example](https://github.com/NCATS-Tangerine/translator-api-registry/blob/3ca57d15f1e7ca8c0fb4b41d3cbf888f7d5680c6/AGR/agr.yaml#L1483)

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["DOID:10629"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:condition_associated_with_gene"]
                }
            }
        }
    }
}
```

Should retrieve this edge linked to CYC3 (`SGD:S000000037` in original API, `NCBIGene:851192` in TRAPI)

```
                "37b3244f58abee6b388df2686e2f4571": {
                    "predicate": "biolink:condition_associated_with_gene",
                    "subject": "MONDO:0021129",
                    "object": "NCBIGene:851192",
                    "attributes": [],
                    "sources": [
                        {
                            "resource_id": "infores:agrkb",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:biothings-agr",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:agrkb"
                            ]
                        },
                        {
                            "resource_id": "infores:service-provider-trapi",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:biothings-agr"
                            ]
                        }
                    ]
                },
```

</p>
</details> 

So I made a PR to add it to BTE's regular use. https://github.com/biothings/bte-server/pull/3

**Comment by colleenXu** [comment]
Closing this issue since the changes have been deployed to Prod with the Feb 2024 release. 

I've confirmed that I can query BioThings AGR through BTE prod `https://bte.transltr.io/v1/team/Service Provider/query` with the examples in https://github.com/biothings/biothings_explorer/issues/260#issuecomment-1842239399 and get the expected response.
