### ISSUE TITLE
update to biolink 2.2.x

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#265]
Per the [weekly Translator email](https://mailchi.mp/6a3ac940bb4d/translator-weekly-recap-august-23-2021?e=31882597bb), we need to update to [Biolink 2.2.x](https://github.com/biolink/biolink-model/releases/).  There should be no breaking changes so it should be a straightforward update, but needs to be tested. 

For reference, #207 tracked update to v2.1.x

**Comment by colleenXu** [comment]
These are the changes I see from v2.2.0 onward (current version is v2.2.3):

@andrewsu please confirm what we want to do going forward...

- introduced in v2.2.1:
  - new predicates ["has real world evidence of association with"](https://github.com/biolink/biolink-model/blob/602373ab0991993746197fc36fbdde71d0d9b77f/biolink-model.yaml#L1567) and its inverse for clinical KPs (so multiomics KPs will need x-bte annotation change?)
    - using v2.2.3 updated description. 
- introduced in v2.2.2:
  - new predicate "mixins" to support? [increases amount or activity of](https://github.com/biolink/biolink-model/blob/e37280594b84718e778b2db2b1b5979a5aab076e/biolink-model.yaml#L1904) and the "decreases" version. 
    - the "increases" mixin links to predicates like "increases abundance of", "increases activity of", " increases expression of", etc...

---

Doesn't really affect us:
- introduced in v2.2.3: new predicate inverses
  - ["contains process"](https://github.com/biolink/biolink-model/blob/602373ab0991993746197fc36fbdde71d0d9b77f/biolink-model.yaml#L4587) for "occurs in"
  - ["capability of"](https://github.com/biolink/biolink-model/blob/602373ab0991993746197fc36fbdde71d0d9b77f/biolink-model.yaml#L5118) for "actively involves"
  - ["taxon of"](https://github.com/biolink/biolink-model/blob/602373ab0991993746197fc36fbdde71d0d9b77f/biolink-model.yaml#L5956) for "in taxon"

**Comment by andrewsu** [comment]
x-bte changes to use "has real world evidence of association with" seems reasonable to me.  My guess is that predicate will be used in workflow B queries?

On the new predicate mixins, are you saying that we need new code to query those mixins, similar to how we do predicate expansion in the predicate subclass hierarchy?

**Comment by colleenXu** [comment]
I'm not sure whether we currently handle predicate mixins...that involves asking Marco?

And the predicate is being used in workflows B and C. I agree that it involves talking to multiomics provider about what operations to change the predicate on...

**Comment by andrewsu** [comment]
@colleenXu on predicate mixins, do you agree that this only affects queries in which a mixin predicate is directly used in the predicate list?  I.e., queries with only non-mixin predicates will not be affected by the new mixin predicates? If yes, are you aware of any demo queries that use mixin predicates?  This info would be useful for prioritization...

**Comment by colleenXu** [comment]
I agree that predicate mixins will only come up when they are directly used. 

I am not aware of any demo queries that use mixin predicates right now. I can imagine Workflow A queries that could use them - but I don't know if they will change or not...

**Comment by andrewsu** [comment]
I created a new issue for mixin predicates [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/268), so let's ignore that aspect from this issue.

In this issue, I think the main things to address are 

- [ ] update https://github.com/biothings/biolink-model.js/blob/main/data/biolink.yaml to the [latest biolink release](https://github.com/biolink/biolink-model/releases/) (currently 2.2.3)
- [ ] update smartAPI annotations for clinical KPs to use new "has real world evidence of association with" predicate

**Comment by colleenXu** [comment]
Actually the second thing for "clinical risk kp api" was done already (~ 2 weeks ago). But there are many other issues with clinical risk kp api's x-bte annotations that I'm addressing in a PR [here](https://github.com/Hadlock-Lab/clinical_risk_kp/pull/9)

I'm not sure if other APIs from multiomics provider also need a predicate change...

**Comment by tokebe** [comment]
Updating the file failed a test on account of a predicate being renamed (test has been updated). I diffed the files to check for anything else that might be relevant, just in case:

- A number of `is_a` definitions were updated for various predicates.
- `relation` has been deprecated
- A few new predicates were added, such as `taxon of`
- A few new association slots were added, such as `original_subject`
- Some mappings, ID prefixes, aliases changed/added

**Comment by colleenXu** [comment]
Pushed to prod server. 

I've confirmed that the following queries to clinical risk kp api using the new predicates work: POST to https://api.bte.ncats.io/v1/smartapi/d86a24f6027ffe778f84ba10a7a1861a/query

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n01",
                    "object": "n00",
                    "predicates": ["biolink:has_real_world_evidence_of_association_with"]
                }
            },
            "nodes": {
                "n00": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0005301"
                    ]
                }
            }
        }
    }
}
```

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": ["biolink:associated_with_real_world_evidence"]
                }
            },
            "nodes": {
                "n00": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0005301"
                    ]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
Closing this issue. Note that biolink model also has mixins that we currently don't support. Tracking that issue here #241 . currently considered low priority since it isn't coming up in Translator queries.
