### ISSUE TITLE
shall we disable SmartAPI metadata auto-sync on dev server?

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#271]
For now, just to put some notes here for feedbacks from the team.

How about this:

* Only enable automated smartapi sync (as a schedule job) when `NODE_ENV=production` (therefore only enabled for production server)
* Add a `npm run smartapi_sync` script to manually trigger sync when needed.

Pros:
* no local smartapi metadata changes during the development
* can still test with the latest local metadata cache by manually triggering the sync
* less unnecessary merging conflicts caused by the auto-updated local metadata cache files

Cons:
* Works differently comparing to the prod server, will need to remember to test against latest metadata when relevant (but we will always test against the latest metadata during automated tests and tests before deployment)

Your thoughts?

**Comment by andrewsu** [comment]
This seems like a very good idea to me.  I can see the "con" of this being the root cause of some mysterious issue sometime in the future, but hopefully clear documentation (including this ticket) will help us solve the mystery quickly.

**Comment by colleenXu** [comment]
My requests are:
- the prod server url has regular updates from the Registry/trapi-endpoints (like every hour or so?)
- the local instances we start up have an option for manually refreshing from the registry/trapi-endpoints

**Comment by newgene** [comment]
@tokebe let's implement this issue as described on my first comment:

* Only enable automated smartapi sync (as a schedule job) when NODE_ENV=production (therefore only enabled for production server)
* Add a `npm run smartapi_sync` script to manually trigger sync when needed.

But also add a third-item: 
* Modify this issue : https://github.com/biothings/BioThings_Explorer_TRAPI/issues/252, to allow a `SMARTAPI_SYNC=true|false` ENV variable to manually trigger syncing (override the default behavior of the default behavior when needed)

What do you think?

**Comment by tokebe** [comment]
@newgene For the third term, do you mean using it to manually allow repeated syncing, or just to sync once at server start?

**Comment by newgene** [comment]
@tokebe previously you implemented `DISABLE_SMARTAPI_SYNC` for disabling syncing when syncing is always on. Now we can control syncing on or off for our server, we might want to change `DISABLE_SMARTAPI_SYNC` to just `SMARTAPI_SYNC`, which can be used to override the default behavior, like `SMARTAPI_SYNC=true` will toggle syncing on regardless, and `false` value will toggle syncing off. It might just be the naming change of this ENV variable.

**Comment by colleenXu** [comment]
@newgene @tokebe Can this issue be closed now?

**Comment by tokebe** [comment]
I believe so.
