### ISSUE TITLE
Add Gene - has_sequence_variant - SequenceVariant operation to myvariant.info smartAPI annotation

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#272]
In the [SmartAPI metadata for myvariant.info](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/myvariant.info/openapi_full.yml), we annotate the `SequenceVariant` - `is_sequence_variant_of` - `Gene` edge (see **Block 1** below), but not (currently) the reverse `Gene` - `has_sequence_variant` - `SequenceVariant`.  Would be good to annotate the reverse direction.  More details at https://github.com/NCATSTranslator/testing/issues/108#issuecomment-907323733

**Block 1**:
```
    variantAssociatedWithGene:
    - supportBatch: true
      inputSeparator: ","
      parameters:
        fields: dbsnp.gene.geneid
      predicate: is_sequence_variant_of
      source: "infores:dbsnp"
      requestBody:
        body:
          q: "{inputs[0]}"
          scopes: dbsnp.rsid
        header: application/x-www-form-urlencoded
      inputs:
      - id: DBSNP
        semantic: SequenceVariant
      outputs:
      - id: NCBIGene
        semantic: Gene
      response_mapping:
        "$ref": "#/components/x-bte-response-mapping/variant-gene"
```

**Comment by colleenXu** [comment]
The new [x-bte operation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/4a61d04a05583d3616b874fcfd18f57b7cfb0951/myvariant.info/openapi_full.yml#L399) has been added and I can get results from a query like this

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"],
                    "ids": ["NCBIGene:3778"]
                },
                "n1": {
                    "categories": ["biolink:SequenceVariant"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
