### ISSUE TITLE
Caching occasionally fails due to undefined records

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#280]
Some queries fail due to an exception in caching, where `cache_handler._copyRecords()` receives an object where `$input.obj` is `undefined`

Example query:
```json
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "categories": ["biolink:Gene"],
          "ids": ["NCBIGene:3778"]
        },
        "n1": {
          "categories": ["biolink:Gene"]
        },
        "n2": {
          "categories": ["biolink:SmallMolecule"]
        }
      },
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1"
        },
        "e02": {
          "subject": "n1",
          "object": "n2"
        }
      }
    }
  }
}

```

**Comment by tokebe** [comment]
This seems to happen inconsistently, with the same query failing and then succeeding after a subsequent request, implying a possible issue with one of the APIs.

**Comment by colleenXu** [comment]
Can this issue now be closed? @tokebe @newgene

(Also is this related / a dupe of #325 )
