### ISSUE TITLE
biomedical ID resolver: migrate test suites to use new resolver?

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#289]
currently, it looks like only the __tests__/integration/sri_resolver.test.ts has tests that use the new code

perhaps the rest of the test suite should either be updated to use the new code, or considered obsolete (not run with the "npm test" command).

**Comment by ericz1803** [comment]
Correct (edit: looks like @marcodarko set all the old tests to skip). I remember I looked through the old testing code and migrated some of the useful ones. A lot of it was testing the old internals which is now being handled by the SRI node normalizer.

**Comment by colleenXu** [comment]
in that case, is this issue unnecessary / already done? @marcodarko @ericz1803

**Comment by marcodarko** [comment]
This package needs to be revised if we intend on only using SRI, if that's the case I think we need to remove all old code similar to query handler.

**Comment by andrewsu** [comment]
codecov reports we are good here,,,
