### ISSUE TITLE
checking / updating: test suites

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#291]
with the recent large code update, we may want to check that the tests for modules use the new code and are updated.

This would involve modules that were updated + those that depend on them...like
- biomedical id resolver (directly updated)
- call-apis
- api-response-transform
- bte-trapi
- query-graph-handler

This is related but larger in scope than #290 #289. This may also be affected by #288

**Comment by andrewsu** [comment]
closing as not relevant to current testing framework
