### ISSUE TITLE
BTE providing edge_attribute_source without infores id information

### ISSUE THREAD

**Issue by vgardner-renci** [biothings/biothings_explorer#293]
See the most recent version of the workflow progress tracker --> edge attribute source sheet.

https://docs.google.com/spreadsheets/d/1O1cMmYGxoIqP6xbzj6FG5owiKQVg57wx2O_XIA_hN_A/edit#gid=1151550648

Rows at the top indicate in which workflows BTE is returning edge attribute sources without infores id information.

**Comment by colleenXu** [comment]
This is related to #208, we are working on it

**Comment by colleenXu** [comment]
Should be fixed now.
