### ISSUE TITLE
pagination handling error for BioThings APIs

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#300]
From the BTE logs:
```
1|bte-trapi  | 2021-09-20T21:05:19.209Z bte:call-apis:query Failed to make to following query: {"url":"https://biothings.ncats.io/text_mining_co_occurrence_kp/query","params":{"fields":"object,association","q":"subject.MONDO:\"MONDO:0004335\" AND object.type:Gene","size":1000,"from":324000},"method":"get","timeout":50000}. The error is Error: Request failed with status code 400
1|bte-trapi  | 2021-09-20T21:05:19.209Z bte:call-apis:query The request failed with the following error response: {"code":400,"success":false,"error":"Bad Request","keyword":"from","max":10000,"num":324000,"alias":"skip"}  
```

With BioThings API , `from` greater than 10000 will receive 400 error. Large query hits are not recommended to use `from`+`size` pagination, either we can stop by `10000` or switch to use `fetch_all` streaming feature of the Biothings APIs.

**Comment by newgene** [comment]
Looks like the relevant logic is in this block:

https://github.com/biothings/call-apis.js/blob/2059a93f1a36e8b1d764c6bc21ac72fb334b043f/src/builder/query_builder.js#L116-L141

**Comment by colleenXu** [comment]
Also involved:
* changing the x-bte annotation's specification of the sub-query to have a cut-off. then less records would match and be returned

Keep in mind:
* BTE currently does not ingest this API (text mining co-occurrence) for its normal sub-querying. This query was likely done directly to the Text Mining co-occurrence API, either by someone on that team or the ARS

**Comment by newgene** [comment]
PR https://github.com/biothings/call-apis.js/pull/33 merged and deployed to prod.
