### ISSUE TITLE
Adding node attributes module

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#302]
After talking with Andrew, here are the current ideas:
* this module can be "executed alone / independently", aka it can take an arbitrary TRAPI response with a message.knowledge_graph.nodes section and return the TRAPI response with node attributes added to the nodes
* we would plan to use this module internally (probably as a step at the end of the query process, like results assembly)

Here are some topics we may want to work through:
* what info we want as node attributes (from what is available in biothings APIs...)
* How will we retrieve this info, starting from the node IDs / semantic types? 
* ideally the node attributes will have "attribute_type_id" values that match what Translator expects. This will have to be set somewhere in the new code...and This involves some review with @colleenXu.

**Comment by colleenXu** [comment]
Note that the code will likely be very similar to the old ID resolver, but focused on node attributes rather than finding equivalent IDs

**Comment by colleenXu** [comment]
I believe this is linked to these PRs:
* https://github.com/biothings/biomedical_id_resolver.js/pull/78
* https://github.com/biothings/call-apis.js/pull/34

**Comment by colleenXu** [comment]
@marcodarko some feedback: I'd like clear documentation (here on the issue, a README, a doc, something) on how to add / edit node attributes. I think that would make it easier for me and Andrew to contribute.

**Comment by andrewsu** [comment]
node attributes are handled in https://github.com/biothings/biomedical_id_resolver.js/blob/main/src/config.ts with the mappings under `additional_attributes_mapping`

**Comment by marcodarko** [comment]
Also related to this issue: https://github.com/biothings/call-apis.js/pull/34 linking for ref.

**Comment by colleenXu** [comment]
I'm closing this ticket since it's been deployed. 

However, I plan to open a new ticket for reviewing the node attributes / perhaps adding some more...
