### ISSUE TITLE
Support callback link to retrieve verbose logs for a given query

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#304]
We can save verbose logs to a file/cache using a query hash as the index, and provide a link as part of the query response to a new endpoint with that hash. If the user opens said link, the server returns the verbose log file. Log files may be routinely cleaned as part of a cron job based on their age (keeping a given log for no longer than, say, 5 minutes). To further save space, we could choose to only save and provide verbose logs in the event of a query failure (termination or internal server error).

This would save us some time in tracking down the reason for failed queries submitted by users, who could save the log and send it to us, and would allow for less verbose logging in the usual query response, saving on response length.

At the moment this is a low-priority issue.

**Comment by newgene** [comment]
Let's implement this as part of the current `/check_query_status/<jobid>` endpoint for async query.

Reference on how to add job logs and retrieve job logs:

https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#joblog

Options can be `/check_query_status/<jobid>?logs` to retrieve logs together with the normal query response, 

or

`/check_query_status/<jobid>/logs` for logs only

**Comment by colleenXu** [comment]
note that there's a diff between console logs + TRAPI response logs:
* whatever we want to save / have for every query, we should have it in the TRAPI response log

**Comment by tokebe** [comment]
@newgene @colleenXu Given recent discussion in #328, this may be less relevant as we're now considering streamlining TRAPI logs overall and including a summary as part of them.

I could still implement the endpoint for just grabbing TRAPI logs if there's still a reason to do so?

Alternately, the point of this issue could largely return to its original idea of providing console-level logs on an endpoint exclusively in the case of query failure, perhaps being accessible only with a password to keep console-level log access restricted to the dev team?

**Comment by tokebe** [comment]
Closing due to #328's implementation making this redundant.
