### ISSUE TITLE
Remove Gene SYMBOL-based operations, or add support for SYMBOL

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#308]
Results from running [query D.1](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/D.1_parkinsons-crohns.json) on a local instance can be found here: https://www.dropbox.com/s/x78xatt48inggrz/response_d1.json?dl=0

Those results includes these two objects under `message.knowledge_graph.nodes`:

```
                "NCBIGene:120892": {
                    "categories": [
                        "biolink:Gene"
                    ],
                    "name": "LRRK2",
                    "attributes": [
                       ...
                    ]
                },
```

```
                "SYMBOL:LRRK2": {
                    "categories": [
                        "biolink:Gene"
                    ],
                    "name": "SYMBOL:LRRK2",
                    "attributes": [
                       ...
                    ]
                },
```

These two nodes _should_ be combined as far as I can tell...

**Comment by colleenXu** [comment]
@andrewsu this is happening because some operations still use SYMBOL but the SRI-based ID resolver doesn't recognize and do ID resolution on SYMBOL. 

We could remove those operations...

**Comment by andrewsu** [comment]
Right, thanks.  Have we asked the SRI folks about whether adding symbol as another "identifier" for genes and proteins is possible?

**Comment by colleenXu** [comment]
@andrewsu we haven't...It looks like the biolink model adds symbol as a node property....https://github.com/biolink/biolink-model/blob/d77172050122bf4d5b48cd1d487fb58a8b163620/biolink-model.yaml#L8119

**Comment by andrewsu** [comment]
Some slack discussion here: https://ncatstranslator.slack.com/archives/C0125JTMDHA/p1632779182001700

I think within https://github.com/biothings/biomedical_id_resolver.js, we _could_ hack in a bit of logic to take `id.label` from the Node Normalizer output and add an entry under `equivalent_identifiers`. Prioritization a bit depends on which API operations use gene symbols as their primary key.  @colleenXu can you easily retrieve those?

**Comment by colleenXu** [comment]
@andrewsu

Only 1 API uses SYMBOL IDs: multiomics TCGA mutation freq API. This can really only be fixed on the data / parser side for that API. 

I've updated all other APIs that did use SYMBOL to use another valid ID (NCBIGene, UniProtKB, ENSEMBL).....theoretically after refreshing the registry, only the API above will be giving SYMBOLs...

**Comment by andrewsu** [comment]
The ARS results for query D.1 are here (from asyncquery): https://arax.ncats.io/?r=99419778-90df-4d55-b6f5-e1f78ec2bfd2 (**screenshot 1** below).  The BTE result fails TRAPI 1.2 validation because it contains nodes with `biolink:null` for some node categories (**screenshot 2** below).  Full results should be able to be downloaded here: https://arax.ncats.io/api/arax/v1.2/response/99419778-90df-4d55-b6f5-e1f78ec2bfd2

**Screenshot 1**:
![image](https://user-images.githubusercontent.com/2635409/135338446-81d5705e-ddc9-4ab9-a368-5a88ea7cd7af.png)

**Screenshot 2**:
![image](https://user-images.githubusercontent.com/2635409/135339160-424825de-ff56-4ec3-a426-3e8e4a9d9378.png)

**Comment by colleenXu** [comment]
Err @andrewsu should this be a different ticket?

**Comment by colleenXu** [comment]
Note that BTE currently doesn't ingest the TCGA mutation freq API + the multiomics team have been [informed](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1631655573078500?thread_ts=1631644745.072400&cid=C022EL8D3AB) of the issue and said they would remove SYMBOL / use a diff ID namespace for a future release

Therefore I'm closing this issue
