### ISSUE TITLE
Time to make the new query algorithm the default one

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#310]
The new iterative query algorithm (https://github.com/biothings/bte_trapi_query_graph_handler/pull/35 and https://github.com/biothings/BioThings_Explorer_TRAPI/pull/273) has been merged and running on production for a while. Time to make it "THE" `query` function, instead of the `query_2` function.

**Comment by colleenXu** [comment]
closing since it's linked PRs were merged
