### ISSUE TITLE
bug: seeing "biolink:null" for node categories 

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#311]
The ARS results for query D.1 are here (from asyncquery): https://arax.ncats.io/?r=99419778-90df-4d55-b6f5-e1f78ec2bfd2 (**screenshot 1** below).  The BTE result fails TRAPI 1.2 validation because it contains nodes with `biolink:null` for some node categories (**screenshot 2** below).  Full results should be able to be downloaded here: https://arax.ncats.io/api/arax/v1.2/response/99419778-90df-4d55-b6f5-e1f78ec2bfd2

**Screenshot 1**:
![image](https://user-images.githubusercontent.com/2635409/135338446-81d5705e-ddc9-4ab9-a368-5a88ea7cd7af.png)

**Screenshot 2**:
![image](https://user-images.githubusercontent.com/2635409/135339160-424825de-ff56-4ec3-a426-3e8e4a9d9378.png)

**Comment by colleenXu** [comment]
I'm also wondering if something is off with the logic for setting the category (if this ID doesn't return a semantic type from SRI ID resolver, I thought it was supposed to use the semantic type of the operation it came from). 

But also...
something is odd with the edges for these nodes as well...there should be some edge attribute with a value? like saying the underlying api this edge came from?
![Screen Shot 2021-09-29 at 1 01 13 PM](https://user-images.githubusercontent.com/43731687/135340522-2c781af6-3bb3-4bbc-8f97-b6e8ced0bdfb.png)

**Comment by colleenXu** [comment]
examples of Ids involved. I think this is coming from some API that's using odd IDs...

BFO:0000001
BFO:0000002
OGMS:0000031

**Comment by colleenXu** [comment]
I believe this is a sporadic issue or an issue with the prod instance, since I ran the query just now on a local instance and didn't have an issue...

**Comment by colleenXu** [comment]
currently not seeing. Closing this issue
