### ISSUE TITLE
raise timeout threshold for asyncquery

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#315]
Currently, we have a 10 sec timeout for TRAPI APIs, and a 50 sec timeout for non-TRAPI APIs.  Let's try raising that threshold for TRAPI APIs to 50 sec.  If easy, let's do that specifically for the `asyncquery` endpoint.  If not, doing it for both `query` and `asyncquery` seems fine at this point...

Motivated by timeouts on Translator Workflow Query B.1, as described at https://ncatstranslator.slack.com/archives/C02F8GX5YTG/p1633670465222500?thread_ts=1633656429.221800&cid=C02F8GX5YTG

**Comment by newgene** [comment]
increased from 10s to 50s in https://github.com/biothings/call-apis.js/commit/926ff55ad0616a7b6183748b988ee293d7f22b87, this will be the same for both sync and asyncquery endpoints.

**Comment by newgene** [comment]
deployed to prod.
