### ISSUE TITLE
Async query endpoint seems to be calling APIs not in config.js list (RTXKG2 API, Automat Robokop, etc.)

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#321]
RTXKG2 KP API (https://smart-api.info/registry?q=acca268be3645a24556b81cc15ce0e9a) is not listed in 

https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/routes/v1/config.js

But this query appears calling this API during the execution:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["CHEBI:3309", "CHEBI:5147"],
                    "categories":["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories":["biolink:Disease"]
               }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
There seems to be a difference in the apis being called through the query endpoint vs the asyncquery endpoint.

Query endpoint seems to be correctly using the config list. Asyncquery endpoint seems to not use this config list and instead hits everything in the metakg…..including APIs like rtxkg2, multiomics drug response, automat robokop, etc.

**Comment by colleenXu** [comment]
closing since this is on prod now, and should be handled correctly. 

will reopen if this issue reappears
