### ISSUE TITLE
Remove all instances of cloneDeep()

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#323]
After investigation of the below query, it's become apparent that the use of `cloneDeep` in any function which is expected to be called many times in quick succession, or is expected to perform transformations on large objects, i.e. `_createBTEEdges()`, is more-or-less bound to cause performance issues (both in responsiveness and overall resource use). 

It would probably be worthwhile to figure out how best to change the internal flow of data such that any current uses can be removed. Currently all uses are in [qedge2bteedge](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/src/qedge2bteedge.js).

The following query causes server crash due to out-of-memory exception while cloning:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                     "ids": ["MONDO:0005359", "SNOMEDCT:197354009"],
                     "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n1": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n2": {
                    "categories": ["biolink:Gene"]
                },
                "n3": {
                    "categories": ["biolink:Drug", "biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:has_real_world_evidence_of_association_with"]
                },
                "e02": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates": ["biolink:gene_associated_with_condition"]
                },
                "e03": {
                    "subject": "n3",
                    "object": "n2",
                    "predicates": ["biolink:affects", "biolink:interacts_with"]
                }
            }
        }
    },
    "submitter": "WorkflowBNotebook",
    "stream_progress": false,
    "query_options": {
        "kp_timeout": 1800
    }
}
```

**Comment by tokebe** [comment]
Tests show that removing `cloneDeep` improves memory usage, but does not prevent the above query from crashing BTE.

**Comment by colleenXu** [comment]
@tokebe @newgene Can this be closed or is this an ongoing task?

**Comment by tokebe** [comment]
This can be closed.
