### ISSUE TITLE
implement redis-backed log retrieval for async queries

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#327]
Currently, the TRAPI response contains a very verbose "log" object.  That log is not very useful for most BTE users, but _very_ useful for developers and experts to debug.  This ticket proposes to completely replace the current "log" object with a single URL, which is where the current log can be downloaded from.  Based on a conversation with @newgene, the log can be stored in an existing redis object that tracks async jobs.  Redis can be configured to wipe the log after 10 mins.  For simplicity, this feature can be limited to the `/asyncquery` endpoint.

Separately, I'll be creating a ticket to create a more user-friendly log for direct inclusion in the TRAPI response.

**Comment by tokebe** [comment]
Related to #304

**Comment by andrewsu** [comment]
Gah, I _knew_ I saw this somewhere before.  Closing this one as a duplicate of #304...
