### ISSUE TITLE
Review / add node attributes

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#344]
I'll record what mappings I think would be useful to add to BTE in this ticket. This builds off of #302 

This involves editing this file: https://github.com/biothings/biomedical_id_resolver.js/blob/main/src/config.ts

Of the top of my head:
* MyChem has route info for chemicals (chembl.oral, chembl.parenteral (IV, injection), chembl.topical) and whether or not this is a natural product (chembl.natural_product). This has been asked for by UAB users....
    * one issue is the values and the lack of clarity: natural product uses 0/1 (I guess 1 is yes?) and the others use true / false (whether the drug is available for administering via that route?)

**Comment by colleenXu** [comment]
Now can be done due to #302 being addressed

**Comment by colleenXu** [comment]
### From MyDisease

[UPDATED 2023-06-08]

Fields are listed in alphabetical order
ask people responsible for core Biothings APIs like Chunlei if you have questions about these fields or how to query the BioThings APIs

#### Description

* disease_ontology.def: Disease ontology definition (nice overview for someone who doesn't know what it is)
* mondo.comment: perhaps. haven't reviewed this field
* mondo.definition: nice overview for someone who doesn't know what it is
* mondo.label
* mondo.subset: seems to characterize what this disease is (example values: n_of_one, predisposition, gard_rare, ordo_clinical_subtype)
    
#### Extra info on disease

* hpo.course (are HP curies....no name included to understand what this is)
* hpo.inheritance
* hpo.modifier 
* mondo.has_modifier.mondo (this is a mondo term though....no name included to understand what this is)
* mondo.never_in_taxon.ncbitaxon

#### Names

* disease_ontology.name
* disease_ontology.synonyms.exact (vs disease_ontology.synonyms.related ?)
* disgenet.xrefs.disease_name
* mondo.synonym.exact
* mondo.synonym.related

**Comment by colleenXu** [comment]
### From MyGene

[UPDATED 2023-06-08]

Fields are listed in alphabetical order
ask people responsible for core Biothings APIs like Chunlei if you have questions about these fields or how to query the BioThings APIs

#### Descriptions

* ensembl.type_of_gene
* generif.text
* interpro.desc
* summary (nice overview for someone who doesn't know what it is)
* symbol
* taxid (NCBITaxon)
* type_of_gene

#### Names

* alias
* name
* other_names

**Comment by colleenXu** [comment]
### From MyChem

[UPDATED 2023-06-08]

I have bolded some fields I think are particularly interesting for a UI/user.
Fields are listed in alphabetical order
ask people responsible for core Biothings APIs like Chunlei if you have questions about these fields or how to query the BioThings APIs

#### description

* chebi.definition (overview)
* chembl.biotherapeutic.description 
* chembl.atc_classifications (codes / ids?)
* **chembl.natural_product** (not clear what values mean, looks like it 0=No/1=Yes) 

#### approval info

<details><summary>click here to expand and see lists</summary>

* chembl:
    * chembl.first_approval (it's a year)
    * **chembl.max_phase** (across indications? worldwide? not sure)
    * chembl.withdrawn_class
    * chembl.withdrawn_country
    * **chembl.withdrawn_flag** (probably all records have this; the other chembl.withdrawn... fields only exist if it was withdrawn somewhere)
    * chembl.withdrawn_reason (similar to class above but somewhat diff info / somewhat useful)
    * chembl.withdrawn_year
* drugcentral
    * drugcentral.approval.agency
    * drugcentral.approval.company
    * drugcentral.approval.date
    * drugcentral.approval.orphan
* fda_orphan_drug
    * fda_orphan_drug.approval_status
    * fda_orphan_drug.approved_labeled_indication
    * fda_orphan_drug.designated_date
    * fda_orphan_drug.designation_status
    * fda_orphan_drug.exclusivity_end_date
    * fda_orphan_drug.exclusivity_protected_indication
    * fda_orphan_drug.marketing_approval_date
    * fda_orphan_drug.orphan_designation.original_text
    * fda_orphan_drug.sponsor
* ginas.status (maybe?)
* ndc
    * **ndc.deaschedule** (I think this field exists when the drug is a DEA scheduled drug, and states what classification it is)
    * ndc.endmarketingdate
    * ndc.labelername
    * ndc.startmarketingdate

</details> 

#### other clinical info 

<details><summary>dose and administration</summary>

* chembl.dosed_ingredient  (not clear what values mean, looks like values are false / true?)
* **chembl.oral** (same as above, for being able to administer orally)
* **chembl.parenteral** (same as above, for being able to adminster parenterally (IV / injection))
* **chembl.topical** (same as above, for being able to administer topically)  
* drugcentral.drug_dosage.dosage (goes with the other drugcentral.drug_dosage fields)
* drugcentral.drug_dosage.route (O means oral, not sure about other values)
* drugcentral.drug_dosage.unit
* ndc.active_ingred_unit
* ndc.active_numerator_strength
* ndc.dosageformname
* ndc.routename (has values like ORAL, NASAL)
* pharmgkb.dosing_guideline

</details> 

<details><summary>used to treat, contraindicated, side-effects</summary>

* **chembl.black_box_warning**  (not clear what values mean, looks like it 0=none/1=has some)
* chembl.indication_class
* chembl.therapeutic_flag (same as above, for being used therapeutically) 
* drugcentral.drug_use.contraindication.concept_name
* drugcentral.drug_use.contraindication.snomed_full_name
* drugcentral.drug_use.diagnosis.concept_name
* drugcentral.drug_use.diagnosis.snomed_full_name
* drugcentral.drug_use.indication.concept_name
* drugcentral.drug_use.indication.snomed_full_name
* drugcentral.drug_use.off_label_use.concept_name
* drugcentral.drug_use.off_label_use.snomed_full_name
* drugcentral.drug_use.reduce_risk.concept_name
* drugcentral.drug_use.reduce_risk.snomed_full_name
* drugcentral.drug_use.symptomatic_treatment.concept_name
* drugcentral.drug_use.symptomatic_treatment.snomed_full_name
* sider.indication.name
* sider.side_effect.name

</details>  

<details><summary>pharma class</summary>

* drugcentral.pharmacology_class.chebi.description
* drugcentral.pharmacology_class.mesh_pa.description
* ndc.producttypename (might say human vs nonhuman prescription drug? I dunno)
* chembl.prodrug (looks like it 0=No/1=Yes, for being a prodrug) 
* drugcentral.pharmacology_class.fda_chemical/ingredient.description
* drugcentral.pharmacology_class.fda_cs.description
* drugcentral.pharmacology_class.fda_epc.description
* drugcentral.pharmacology_class.fda_moa.description
* drugcentral.pharmacology_class.fda_pe.description
* ndc.pharm_classes

</details> 

#### other chemical and pharm class info

<details><summary>click here</summary>

* chebi.relationship.has_role (values are CHEBI CURIEs)
* other chebi fields like....(values are CHEBI CURIEs)
    * chebi.relationship.has_functional_parent
    * chebi.relationship.has_part
    * chebi.relationship.is_conjugate_base_of
    * chebi.relationship.is_enantiomer_of
    * chebi.relationship.is_substituent_group_from
    * chebi.relationship.is_tautomer_of
* chembl.molecule_type (not biolink-model)
* chembl.structure_type (keyword, that aren't immediately clear what they are?)
* pharmgkb.type (drug vs just a chem??)
* ginas.substanceClass

</details> 

#### connections to other things (references, pathways, reactions

<details><summary>click here</summary>

 * chebi.xrefs.patent
* chebi.xrefs.reactome (pathways this chem is in?)
* chebi.xrefs.rhea (reactions this chem is in?)
* pharmgkb.xrefs.clinicaltrials.gov 

</details> 

#### name

<details><summary>click here</summary>

* aeolus.drug_name
* chebi.brand_names
* chebi.name
* chebi.synonyms
* chembl.molecule_synonyms.molecule_synonym (with the kind of synonym chembl.molecule_synonyms.syn_type)
* chembl.pref_name
* chembl.xrefs.dailymed.name
* chembl.xrefs.drugcentral.name
* chembl.xrefs.tg-gates.name
* drugbank.name
* drugbank.synonyms
* fda_orphan_drug.generic_name
* fda_orphan_drug.trade_name
* ginas.names_list
* ginas.preferred_name
* ndc.nonproprietaryname
* ndc.proprietaryname
* ndc.substancename
* pharmgkb.brand_mixtures
* pharmgkb.generic_names
* pharmgkb.name
* pharmgkb.trade_names
* umls.name
* unii.preferred_term

</details>

**Comment by colleenXu** [comment]
MyVariant:

only exists for a few variants...civic.description https://myvariant.info/v1/query?q=_exists_:%22civic.description%22

* chrom, 
* clinvar.type, cadd.type, dbsnp.vartype, exac.type, exac_nontcga.type
* cadd.consequence

Interesting:
* dbnsfp.mutpred.pred

**Comment by colleenXu** [comment]
closing in favor of #482

**Comment by colleenXu** [comment]
Reopening because Andy Crouse / UI team is interested in using info curated by this issue, related to an SRI/UI-related annotation service for starting and end/answer nodes...

Discussed between @newgene, me, and Andy Crouse on this last day of the June 2023 Relay.

So particularly MyChem (chem answer nodes for disease -> drug, and gene -> chem) and MyGene (answer nodes for chem -> gene) and MyDisease (disease starting node). I've updated all 3 of these posts based on a quick look at the API's /metadata/fields endpoints

**Comment by colleenXu** [comment]
Do we want to close this issue? It's now a record of some info that could be useful to the annotator service (which I'm not really a part of developing). 

But it's not clear to me if we're planning to add node-attributes to BTE's functions, or if this issue needs to stay open

**Comment by andrewsu** [comment]
tagging @newgene in case any of the notes above are useful for the Annotator service.  But agreed, this issue can be closed.
