### ISSUE TITLE
Threading refactor: disable threading with ENV variable

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#346]
It's possible that threading may cause/obfuscate certain problems in the future, which would be difficult to test without reverting the threading code (as it currently stands). In addition, the current threading code is somewhat convoluted.

We should refactor threading to use [threads.js](https://threads.js.org/) and make it toggle-able with an ENV variable.

**Comment by colleenXu** [comment]
I'm not sure if this can be closed or not...
