### ISSUE TITLE
[quick fix] handling publications edge attribute

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#347]
* change to "biolink:publications"
* remove it from edge attributes list when it's empty

**Comment by colleenXu** [comment]
note that right now x-bte annotations uses the response-mapping "pubmed" key to specify the field that should be used for publications. 

We may want to change that in the future...

**Comment by marcodarko** [comment]
@colleenXu can you clarify what the current attribute name is that needs to change to "biolink:publications"? and as always if there's any queries to test that's appreciated. I might need more background on this issue.

**Comment by colleenXu** [comment]
@marcodarko sorry I definitely didn't describe this in enough detail. 

Below is an example of an edge from BTE.

The edge attribute with the attribute_type_id "publications" is always present, even when it is empty (either nothing is mapped to it for that meta-edge or nothing was returned from the mapped field). 

I'd like the attribute_type_id to change to "biolink:publications" and remove it from the edge attribute list when it's empty...

This edge appears to grab whatever is annotated in the x-bte-response-mapping with the key pubmed. I've wondered about changing this behavior in the future, but that would involve some editing of x-bte annotations:
* remove special handling for the publications edge attribute
* x-bte annotation would need to be something like "pmid", "pubmed", "biolink:publications", etc...
* I'm not sure how biolink model is handling publication info when it's not pmid (like pmc, urls, etc...)

```
                "1d326d3b58caed428df5d548d7ae6b20": {
                    "predicate": "biolink:physically_interacts_with",
                    "subject": "NCBIGene:3778",
                    "object": "PUBCHEM.COMPOUND:9951995",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:translator-biothings-explorer"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:primary_knowledge_source",
                            "value": [
                                "infores:dgidb"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-dgidb"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "publications",
                            "value": []
                        },
                        {
                            "attribute_type_id": "relation",
                            "value": "activator"
                        },
                        {
                            "attribute_type_id": "score",
                            "value": "3.16"
                        },
                        {
                            "attribute_type_id": "source",
                            "value": "ChemblInteractions"
                        }
                    ]
                },
```

**Comment by marcodarko** [comment]
Got it, I think I know what to do now, thanks!

**Comment by marcodarko** [comment]
Will be addressed in this PR https://github.com/biothings/bte_trapi_query_graph_handler/pull/70

**Comment by colleenXu** [comment]
shoud be addressed now that PR is merged
