### ISSUE TITLE
caching error - returning zero results on repeated query (unknown source)

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#348]
I'm seeing an issue with caching.  For example, when I execute this query

```
{
   "message": {
       "query_graph": {
           "edges": {
               "e01": {
                   "subject": "n0",
                   "object": "n1"
               },
               "e02": {
                   "subject": "n2",
                   "object": "n1"
               }
           },
           "nodes": {
               "n0": {
                   "ids": ["MONDO:0019391"],
                   "categories": ["biolink:Disease"]
               },
               "n1": {
                   "categories": ["biolink:Gene"]
               },
               "n2": {
                   "ids": ["UMLS:C0043369", "CHEMBL.COMPOUND:CHEMBL96783"],
                   "categories": ["biolink:SmallMolecule"]
               }
           }
       }
   }
}
```

I get non-zero results.  When I immediately execute it again, I see zero results.  (Adding/removing IDs from the ID list apparently causes BTE to bypass the cache, which is how I'm testing.)  I do not think I see the `undefined` issue seen in #325 and #280, so creating a new issue.  And FWIW it looks like I can reproduce this on my local instance with caching turned on.

**Comment by andrewsu** [comment]
hmm, the original query above gives zero results for me now (both on prod and local).  The query below gives non-zero results on local, and caching appears to be working as expected (same results, returns within seconds).  However, the same query on prod currently gives me zero results.  Guessing the difference is the meta_kg, or some server time out?  Jotting down these notes now -- will try again later...

```
{
   "message": {
       "query_graph": {
           "edges": {
               "e01": {
                   "subject": "n0",
                   "object": "n1"
               },
               "e02": {
                   "subject": "n2",
                   "object": "n1"
               }
           },
           "nodes": {
               "n0": {
                   "ids": ["MONDO:0019391"],
                   "categories": ["biolink:Disease"]
               },
               "n1": {
                   "categories": ["biolink:Gene"]
               },
               "n2": {
                   "ids": ["UMLS:C0043369", "CHEMBL.COMPOUND:CHEMBL96783", "UMLS:C0037688", "PUBCHEM.COMPOUND:5780"],
                   "categories": ["biolink:SmallMolecule"]
               }
           }
       }
   }
}

```

**Comment by tokebe** [comment]
I get results for the first query on local, with caching working as expected, however I also get 0 results on prod. The second query returns non-zero results on local for me but I also get 0 results on prod.

**Comment by tokebe** [comment]
Confirmed that wiping the prod cache now has non-zero results returning from each query, matching cached results from subsequent queries, and cached results expire after 10 minutes. What was likely happening was some results were cached and somehow not set to expire, causing weird results in testing. This issue should be resolved.
