### ISSUE TITLE
Speed up results assembly with tree constraint

### ISSUE THREAD

**Issue by ariutta** [biothings/biothings_explorer#359]
Andrew said we can assume our query graphs will be trees -- no cycles. That means, ignoring directionality, no node will have a path back itself without traversing the same edge more than once. Using this constraint, assemble results using tree traversal instead of using the cartesian product in [query_results.js](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/src/query_results.js).

**Comment by colleenXu** [comment]
re-opening the PR under a new branch: https://github.com/biothings/bte_trapi_query_graph_handler/pull/77

**Comment by AlexanderPico** [comment]
@ariutta PR failed merge checks?  Is this on your plate? Is this need for Dec demo?

**Comment by ariutta** [comment]
@AlexanderPico, this issue is completed and can be closed:
https://github.com/biothings/bte_trapi_query_graph_handler/pull/77
