### ISSUE TITLE
write functional behave tests that demonstrate data retrieval using BTE in the Translator Testing framework

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#36]
Translator Testing Framework repo: https://github.com/NCATS-Tangerine/translator-testing-framework

**Comment by kevinxin90** [comment]
@andrewsu Could you elaborate on what test cases you're looking for?

Current tests are: https://github.com/NCATS-Tangerine/translator-testing-framework/blob/master/features/biothings_explorer.feature

**Comment by andrewsu** [comment]
The latter two examples in that feature file look great.  

```
  Scenario: (Predict) Predict plausible relationships between one entity and an entity class
     Given a valid disease named "hyperphenylalaninemia"
      When we query biothings explorer for drugs that are associated with genes which are invovled in the disease
      Then we expect "DROXIDOPA" is one of the chemicals in the results

  Scenario: (Explain) Identify plausible reasoning chains to explain the relationship between two entities
     Given a valid disease "chronic myelogenous leukemia" and a valid chemical named "imatinib"
      When we query biothings explorer to identify plausible reasoning chains to explain the relationship between two entities
      Then we expect gene "ALK" is one of the explanations that may link the two entities
```

If those tests currently pass, I think we can close this ticket...

**Comment by andrewsu** [comment]
Also relevant to this ticket -- we have introduced many unit tests in https://github.com/biothings/biothings_explorer/tree/master/biothings_explorer/tests and have set up continuous integration with Travis (https://travis-ci.org/biothings/biothings_explorer).
