### ISSUE TITLE
Query on async endpoint failing where sync endpoint succeeds

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#360]
When I run the query pasted below on my local instance using the sync endpoint, I get a file with 7293 results, 691 nodes, 9927 edges.  The query completes in ~18 minutes.  The timing and the result/node/edge counts are consistent -- exact same results 3 times over 2 days.  However, when I run the query via my local asyncquery endpoint, the query fails.  This is the tail end of the console output:

```
  bte:biothings-explorer-trapi:UpdatedExeEdge (7) Collecting Types: "["ProteinIsoform","Protein","Gene"]" +0ms
  bte:biothings-explorer-trapi:UpdatedExeEdge Collected entity ids in results: ["Gene","Protein"] +346ms
  bte:biothings-explorer-trapi:NewQNode Node "n1" intersecting (179)/(714) curies... +347ms
  bte:biothings-explorer-trapi:NewQNode Node "n1" kept (172) curies... +235ms
  bte:biothings-explorer-trapi:main (10) Edge successfully queried. +14m
  bte:biothings-explorer-trapi:edge-manager (11) Collecting results... +2s
  bte:biothings-explorer-trapi:edge-manager (11) 'e0' keeps (487) results! +0ms
  bte:biothings-explorer-trapi:edge-manager ---------- +0ms
  bte:biothings-explorer-trapi:edge-manager (11) 'e1' keeps (12467) results! +0ms
  bte:biothings-explorer-trapi:edge-manager ---------- +0ms
  bte:biothings-explorer-trapi:edge-manager (11) 'e2' keeps (1091) results! +0ms
  bte:biothings-explorer-trapi:edge-manager ---------- +0ms
  bte:biothings-explorer-trapi:edge-manager (12) Collected results for: ["e0","e1","e2"]! +0ms
  bte:biothings-explorer-trapi:edge-manager (12) Collected (14045) results! +0ms
  bte:biothings-explorer-trapi:edge-manager (13) Edge Manager reporting combined results... +0ms
  bte:biothings-explorer-trapi:Graph Updating BTE Graph now. +0ms
  bte:biothings-explorer-trapi:edge-manager (13) Edge Manager reporting organized results... +209ms
  bte:biothings-explorer-trapi:QueryResult Updating query results now! +0ms
  bte:biothings-explorer-trapi:main (14) TRAPI query finished. +55s
err Error: Missing lock for job JG0R89wD7r failed
    at Object.finishedErrors (/home/asu/Science/bte-trapi-workspace/node_modules/bull/lib/scripts.js:189:16)
    at Job.moveToFailed (/home/asu/Science/bte-trapi-workspace/node_modules/bull/lib/job.js:342:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Query (should be the same as [Query D.6](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/D.6_metformin-ferritin.json)): 
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["CHEMBL.COMPOUND:CHEMBL1431"],
          "categories": ["biolink:SmallMolecule"]
        },
        "n1": {
          "categories": ["biolink:Protein"]
        },
        "n2": {
          "categories": ["biolink:Protein"]
        },
        "n3": {
          "ids": ["UniProtKB:P02794", "UniProtKB:P02792"],
          "categories": ["biolink:Protein"]
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "n1"
        },
        "e1": {
          "subject": "n1",
          "object": "n2"
        },
        "e2": {
          "subject": "n2",
          "object": "n3"
        }
      }
    }
  }
}
```

NOTE: My local environment has the main branch of all repos, *except* for commenting out the text mining provider from the config.  (Incidentally I did run it once with text mining provider included, and it actually returned successfully in 3.5 hours with a 150 MB file, 52250 results.)  

```
$ git diff config.js
diff --git a/src/routes/v1/config.js b/src/routes/v1/config.js
index a46a8d7..3b16e62 100644
--- a/src/routes/v1/config.js
+++ b/src/routes/v1/config.js
@@ -98,10 +98,10 @@ exports.API_LIST = [
     },
     // Text Mining Provider collab, annotated with x-bte
     // - removed Text Mining Co-occurrence API since there were issues using it with BTE (too many answers)
-    {
-        id: '978fe380a147a8641caf72320862697b',
-        name: 'Text Mining Targeted Association API'
-    },
+ //   {
+//        id: '978fe380a147a8641caf72320862697b',
+//        name: 'Text Mining Targeted Association API'
+//    },
     // Automat APIs, ingested through TRAPI
     {
     // this API overlaps with our Biolink API registration, but we have bugs with our ingest...
```

May be relevant to slack thread here: https://suwulab.slack.com/archives/CC218TEKC/p1637610694124100

**Comment by tokebe** [comment]
Some information I've gathered so far:
- The missing lock error occurs at the very end of async response handling -- when a callback is provided, the error does not occur until after the callback server sends its response (the response statuscode/body has no bearing on the error occuring)
- The error occurs after the query response is successfully assembled
- The error occurs regardless of the response being assembled from queries or from edges pulled from the cache
- It seems that this can occur with either an error `Missing lock for job failed` or `Missing lock for job finished`

**Comment by andrewsu** [comment]
The `async_process` branch solves this issue for me on my local instance.  I get the same results (7293 results, 691 nodes, 9927 edges) in ~15 minutes of execution.  So this looks great to me.  

Minor note that the first time I ran it I got the error below.  Two successive queries completed successfully and identically, so I'm going to assume it was a sporadic issue with the SRI node normalizer.  But noting it here just in case it recurs. 

```
{
  "id": "kV0eoEJz7X",
  "state": "completed",
  "returnvalue": {
    "response": {
      "error": "Error",
      "message": "getaddrinfo EAI_AGAIN nodenormalization-sri.renci.org"
    },
    "status": 200,
    "callback": "Callback url was not provided"
  },
  "progress": 0
}
```

**Comment by tokebe** [comment]
I'm considering this issue still open. #361 partially addressed the issue, however it appears that this issue can occur due to multiple causes. 

As #361 moved job processing to a child process, we know it's not due to synchronous execution blocking the event loop and causing the lock to be lost, at least not from the main execution of the job.

This issue still centers around [bull](https://github.com/OptimalBits/bull)'s losing the lock, and as it only seems to occur with longer queries, must have something to do either with execution time, response size, etc, though this error occurs after successful callbacks and well before the lock timeout.

**Comment by tokebe** [comment]
This issue seems to be caused by the size of the response as it is being returned from the bull worker process and stored in redis -- with redis not being meant for large items such as ~200mb responses, it is likely redis failing to handle this and bull subsequently failing to get the job key from redis. 

An attempt to use redis 6's new multithreaded I/O would not appear to fix this issue. I'm testing splitting the response into parts which are stored separately to reduce the strain of any one call on redis. This *should* work, at the cost of slower retrieval of job responses (slower by how much remains to be seen).

**Comment by tokebe** [comment]
Testing with compression using [lz4](https://www.npmjs.com/package/lz4) yields very good compression ratios, at the cost of significantly increased retrieval time from the `/v1/check_query_status` endpoint (better than simply splitting up the response and storing over multiple calls).

Further testing to follow on demotests to see if it fixes the issue, and then testing using a cutoff after which compression is used to avoid performance costs on smaller responses which wouldn't benefit greatly from compression.

**Comment by tokebe** [comment]
Testing on the dev server shows that just simple compression still results in redis crashing/large responses failing -- it seems that even with compression, redis is very quickly overwhelmed with multi-MB responses being cached. 

Next up: a combination of splitting and compression, to try and keep objects sent to redis in a single request under a set limit.

**Comment by tokebe** [comment]
The above fix (#384) should fix this issue. A summary of problems which compounded to cause this:

- Redis running out of memory due to non-expiring job results
- BTE making calls to redis with very large data to store (>10MB seems to cause trouble) via bull job return values

We should keep an eye out for any unexpected behavior/continued problems relating to this issue for a little while before marking this issue as closed.

**Comment by tokebe** [comment]
@andrewsu Performance overall seems to be better. Over the past couple of days I've noted one error specific to the new code, which seems to have happened only once (no other errors seem to have occurred recently):

```
2|bte-trapi  | Async job mbT2f8age5 failed with error The "iterable" argument must be an instance of Iterable. Received undefined
2|bte-trapi  | Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "iterable" argument must be an instance of Iterable. Received undefined
2|bte-trapi  |     at new NodeError (node:internal/errors:371:5)
2|bte-trapi  |     at from (node:internal/streams/from:36:11)
2|bte-trapi  |     at Function.Readable.from (node:internal/streams/readable:1374:10)
2|bte-trapi  |     at /home/ubuntu/opt/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/async/asyncquery.js:55:36
2|bte-trapi  |     at Array.map (<anonymous>)
2|bte-trapi  |     at storeQueryResponse (/home/ubuntu/opt/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/async/asyncquery.js:54:52)
2|bte-trapi  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|bte-trapi  |     at async exports.asyncqueryResponse (/home/ubuntu/opt/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/async/asyncquery.js:128:13)
2|bte-trapi  |     at async jobToBeDone (/home/ubuntu/opt/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/async/processors/async_v1.js:17:20)
2|bte-trapi  |     at async module.exports (/home/ubuntu/opt/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/async/processors/async_v1.js:22:10) {
2|bte-trapi  |   code: 'ERR_INVALID_ARG_TYPE'
2|bte-trapi  | }
2|bte-trapi  |     at Queue.<anonymous> (/home/ubuntu/opt/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/async/asyncquery_queue.js:26:21)
2|bte-trapi  |     at Queue.emit (node:events:390:28)
2|bte-trapi  |     at Object.module.exports.emitSafe (/home/ubuntu/opt/bte-trapi-workspace/node_modules/bull/lib/utils.js:50:20)
2|bte-trapi  |     at /home/ubuntu/opt/bte-trapi-workspace/node_modules/bull/lib/queue.js:1117:13
2|bte-trapi  |     at runMicrotasks (<anonymous>)
2|bte-trapi  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

~~I'll investigate this.~~ This should be a very quick fix.

**Comment by tokebe** [comment]
After several days of monitoring on production I believe this update is stable and the issue is resolved.

Further related work remains regarding #367 however this appears to be a much less common problem.
