### ISSUE TITLE
Check async query status fails for by_team and by_api

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#365]
Checking query status via `/v1/check_query_status/:id?by=team` or `/v1/check_query_status/:id?by=api` fails validation due to the query parameter `by` not being expected in [/docs/smartapi.yaml](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/smartapi.yaml).

**Comment by colleenXu** [comment]
is this supposed to work? I wasn't aware that this was possible or what this would do...

**Comment by tokebe** [comment]
This is used for checking the status of async queries made to `/v1/smartapi/:smartapi_id/asyncquery` (async equivalent of `/v1/smartapi/:smartapi_id/query`), and `/v1/team/:team_name/asyncquery` (equiv. `/v1/team/team_name/query`).

Each endpoint has a separate queue -- the `by` query parameter supports selecting the appropriate queue to get the job status from.

**Comment by colleenXu** [comment]
Is there an example of exactly what the GET url is and what the response will look like? 

It sounds like I could add the needed info into the smartapi spec if I know this...

**Comment by tokebe** [comment]
An example GET URL would be `https://api.bte.ncats.io/v1/check_query_status/0VjwhsxPib?by=team` (example ID, wouldn't actually pull anything up), which I would expect to return the job status of an asynchronous query (exactly the same as a normal check_query_status), like this: https://api.bte.ncats.io/v1/check_query_status/f5jhKt9dtH

**Comment by colleenXu** [comment]
so it would definitely say `by=team` rather than say a specific team like `by=Service Provider`?

**Comment by tokebe** [comment]
`by` is only ever be equal to the string `team` or the string `api`, and never anything else.

**Comment by colleenXu** [comment]
I have confirmed locally: 
* starting BTE w/ redis (`REDIS_HOST=localhost REDIS_PORT=6379 RESULT_CACHING=false npm run debug --workspace='@biothings-explorer/bte-trapi'`)
* sending a query to `http://localhost:3000/v1/smartapi/671b45c0301c8624abbd26ae78449ca2/asyncquery` 
* the query completes (I can see the log), but trying to check the job leads to this response:
```
{
    "error": "Your input query graph is invalid",
    "more_info": [
        "query should NOT have additional properties 'by'"
    ]
}
```

I'm going to look into changing the smartapi specs now...

**Comment by colleenXu** [comment]
so this branch's commit should address this issue: https://github.com/biothings/BioThings_Explorer_TRAPI/commit/0a9a5cc93e992de232d6ee6fe5867470658ce06a

However, I have questions on smartapi annotation of the response to this endpoint, which I detail here: https://suwulab.slack.com/archives/CC218TEKC/p1638934317332400

**Comment by tokebe** [comment]
Confirmed on my local that this branch does fix this issue. Depending on the Slack discussion, we can wait for any other changes to be made and then start testing a PR on the dev instance.

**Comment by colleenXu** [comment]
I've pushed a new commit to this repo. If it continues to work well....do we want this as an after-demo change or before?

**Comment by tokebe** [comment]
@colleenXu I imagine this is going to be a post-demo fix as it shouldn't affect anything in the demo (@andrewsu can confirm?). 

I'll run this on dev tomorrow so we can have it ready to go.

**Comment by andrewsu** [comment]
definitely should not be deployed before the demo...

Also, it's not entirely clear to me what `?by=team` and `?by=api` are meant to accomplish?  Can someone point to the relevant discussion/rationale, or add that here to this issue if it isn't already organized elsewhere?

**Comment by tokebe** [comment]
@andrewsu As far as I understand this was as originally implemented for async. I don't know if there was any discussion, however the rationale seems to be the following:

- There are separate queues for each async endpoint (I'm not sure why..this could be a separate discussion)
- In order to check the status of a given job, the correct queue must be checked, and there's no way to tell this from the jobId (JobIds could be changed to support this, however they would be "less anonymous" in that case, carrying specific information...though not much of impact...)
- By giving the user a query parameter in their URL to check the query status, it's easy to tell which queue to check

I think that's really all there is to it...

**Comment by tokebe** [comment]
@colleenXu @andrewsu requirement for this query parameter is removed by updates made in the [above PR](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/369)

**Comment by colleenXu** [comment]
@tokebe should this issue be closed then?
