### ISSUE TITLE
BTE not expanding GO terms to children

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#366]
In https://github.com/NCATSTranslator/testing/issues/153, we execute an "explain" query that goes `multiple sclerosis (MONDO:0005301)` - `[Gene]` - `central nervous system myelination (GO:0022010)`.  One of the results goes through the gene `MAG` (see screenshot below) and the edge between `MAG` and `central nervous system myelination` is reported by `infores:automat-human-goa`.  

It was surprising that we didn't get this same edge from mygene.info.  The mygene.info object for `MAG` is at http://mygene.info/v3/gene/4099?fields=go, and shows that MAG as an annotation to `central nervous system myelin formation (GO:0032289)`, which is a child of the original query term `central nervous system myelination (GO:0022010)`.  It appears that we need to enable/implement node-level expansion for Gene Ontology to retrieve this result from mygene.info through BTE.  Related: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/196

![image](https://user-images.githubusercontent.com/2635409/145075620-6c3f72f4-c8ab-48ea-8c89-fb718967c656.png)

**Comment by andrewsu** [comment]
Looks like this issue depends on resolution of #196 (not just "related")

**Comment by andrewsu** [comment]
potentially do node lookup in [ontology lookup service](https://www.ebi.ac.uk/ols/)

**Comment by ericz1803** [comment]
The relation between `central nervous system myelination (GO:0022010)` and `central nervous system myelin formation (GO:0032289)` is `part_of`. If we take the conservative approach and only use `is_a` relations, then this original example may not be fixed.

**Comment by colleenXu** [comment]
New example: myelination (GO:0042552) is a [parent](http://amigo.geneontology.org/amigo/term/GO:0042552#display-lineage-tab) of central nervous system myelination (GO:0022010). 

Using the current PRs https://github.com/biothings/bte-trapi-workspace/pull/17 and https://github.com/biothings/bte_trapi_query_graph_handler/pull/113

<details>
<summary>Query is multiple sclerosis (MONDO:0005301)  ->  [Gene]  <-  myelination (GO:0042552)</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"],
                    "name": "multiple sclerosis"
                },
                "n1": {
		             "categories":["biolink:Gene"]
                },
                "n2": {
                    "ids":["GO:0042552"],
                    "categories":["biolink:BiologicalProcess"],
                    "name": "myelination"
               }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1"
                }
            }
        }
    }
}
```

</details> 

In the console logs, I see:

```
  bte:biothings-explorer-trapi:main Expanded ids for node n0: (1 ids -> 9 ids) +0ms
  bte:biothings-explorer-trapi:main Expanded ids for node n2: (1 ids -> 3 ids) +0ms
```



<details>
<summary>The response shows a QGraph with mutated QNodes that include the descendant IDs</summary>

```
   "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "MONDO:0005301",
                        "MONDO:0005284",
                        "MONDO:0005314",
                        "MONDO:0012956",
                        "MONDO:0012957",
                        "MONDO:0012958",
                        "MONDO:0000450",
                        "MONDO:0000451",
                        "MONDO:0000452"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "multiple sclerosis"
                },
                "n1": {
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n2": {
                    "ids": [
                        "GO:0042552",
                        "GO:0022010",
                        "GO:0022011"
                    ],
                    "categories": [
                        "biolink:BiologicalProcess"
                    ],
                    "name": "myelination"
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1"
                }
            }
        },
```

</details>

You can get results like this, where n0 and n2 are both children of the original QNode IDs
![Screen Shot 2022-09-22 at 1 16 38 PM](https://user-images.githubusercontent.com/43731687/191842736-5359915a-9343-45e0-a182-d27c06ad3136.png)

Regarding the original [post](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/366#issue-1073593339) asking about the gene `MAG`. It does show up in the results, but it doesn't have an Edge to "central nervous system myelination"....instead, it has an Edge to "myelination" (the parent term)

![Screen Shot 2022-09-22 at 1 18 16 PM](https://user-images.githubusercontent.com/43731687/191843104-e2ef4943-a282-4903-b051-5342fafab4b6.png)

**Comment by colleenXu** [comment]
I explore this same query but using `is_set: true` on expanded QNodes https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255512783

**Comment by colleenXu** [comment]
Jackson says the related PRs have been pushed to ITRB Prod instances, so we can close these issues https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issuecomment-1404139480
