### ISSUE TITLE
Async Jobs fail to callback (or restart?) with error on unexpected child process exit

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#367]
Async jobs are handled in a child process by [bull](https://github.com/OptimalBits/bull). If the child process exits unexpectedly, [such as with `SIGABRT`](https://api.bte.ncats.io/v1/check_query_status/gvklhUnFcE) (presumably due to out-of-memory exception), the job is marked as failed with the appropriate error, however no callback is made, meaning that the client server is never notified of the job failure.

Additionally, it appears that jobs that fail in this manner might not be restarting properly.

In the case of ARS, this means that the job is left marked as 'running' indefinitely.

**Comment by tokebe** [comment]
Mistakenly closed, reopening

**Comment by tokebe** [comment]
Fix merged+deployed, closing issue.

**Comment by tokebe** [comment]
Reopening as cases such as SIGABRT still do not callback correctly

**Comment by tokebe** [comment]
Moving to on hold / non-critical as the situations where this arise would appear to be exceedingly rare (no noted instances in several months).

**Comment by rjawesome** [comment]
@tokebe Do you know how this can be reproduced, the webpage from your original comment gives a 404 and ``process.abort`` is apparently not allowed in a child process?

**Comment by tokebe** [comment]
No, I currently don't have a means of reproducing this. Possibly worth just leaving (or even closing) this issue, as it is evidently very rare and hard to debug.

**Comment by tokebe** [comment]
Closing as this issue is extremely rare and hard to reproduce/debug, while other issues are much higher priority.
