### ISSUE TITLE
create script to assemble simple version of the BTE metaKG

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#370]
I would like a file with four columns -- `api_name`, `subject_type`, `predicate`, and `object_type`, with one row/record for every relation that is queried by BTE.  I _think_ that should be based on the `packages/@biothings-explorer/bte-trapi/data/predicates.json` file, but reality checking on that would be useful too.  My guess is that a script to generate this file would be generically useful, so perhaps we should add it to `packages/@biothings-explorer/bte-trapi/scripts/` (or similar)?

**Comment by andrewsu** [comment]
I created a script to parse both the `predicates.json` file (which I think has the TRAPI APIs), and to parse the `smartapi_specs.json` file cross referenced with `/src/routes/v1/config.js` (which is mostly non-TRAPI APIs). The paths are written from the perspective of `/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/scripts`, but in thinking about this now, I don't think it's appropriate to check it in there.  So for the moment, just storing it here as a gist: 
https://gist.github.com/andrewsu/aa40d8c6ae133eb5dade8cc343f24eb5 (EDIT: Also just added the output files to the gist...)

A summary of the output files shows that BTE is querying 58 unique APIs that collectively claim 83441 operations (where an operation is defined by a unique API, a subject type, a predicate, and a node type). 

`cat predicates.csv smartapi.csv | sort -u | gawks '{print $2}' | sort | uniq -c | sort -k1nr`

![image](https://user-images.githubusercontent.com/2635409/146097267-b189860e-3666-46d5-b862-fd2d6567be2c.png)

**Comment by colleenXu** [comment]
Above, it sounds like the config.js list was used to parse the file....but the screenshot includes APIs that aren't on the config list...

for example, I think we aren't ingesting the top 5 items in the screenshot list...

**Comment by andrewsu** [comment]
Ahh, I was under the assumption that the APIs in `predicates.json` were called regardless of whether they were specified in `config.js`, but now that I think about it, that doesn't make sense.  *Both* sets of APIs (TRAPI and non-TRAPI) need to be cross referenced with the `config.js`.  With that change (updated the corresponding [gist](https://gist.github.com/andrewsu/aa40d8c6ae133eb5dade8cc343f24eb5)), @colleenXu does this look like a more realistic list of what BTE queries?

![image](https://user-images.githubusercontent.com/2635409/146108025-cbee4cce-fd76-4209-a8b7-002e1979be44.png)

**Comment by colleenXu** [comment]
yes, this looks correct

**Comment by andrewsu** [comment]
great, I updated [the gist](https://gist.github.com/andrewsu/aa40d8c6ae133eb5dade8cc343f24eb5) with the latest code and output files.  

For future reference, my current understanding is this. `config.js` drives everything in terms of what is consulted by BTE.  All entries in `config.js` can be found in `smartapi_specs.json`, but only the non-TRAPI APIs will actually have information on the relations that comprise the meta-kg (under the `components` key).  For TRAPI APIs, information on relations will come from the `predicates.json` file (under the `predicates` key).
