### ISSUE TITLE
add query.submitter field when querying TRAPI resources

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#374]
The TRAPI standard defines an optional [submitter](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L201) property, meant for callers to self-identify so resource owners can quickly/easily contact someone if needed.  When BTE calls downstream TRAPI resources, we should populate this field with "BTE (sync)" or "BTE (async)".

**Comment by tokebe** [comment]
As this is already [partially implemented](https://github.com/biothings/call-apis.js/blob/e584f3883a835702e0e7913f1fc6fb5a0060cf1f/src/builder/trapi_query_builder.js#L70), should this issue be closed?

**Comment by andrewsu** [comment]
yes, I think this feature already seems to be implemented, so let's close. Thanks!
