### ISSUE TITLE
investigate addition of RTX KG2 to BTE config file

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#377]
Currently, BTE does not issue subqueries to [RTX KG2](http://smart-api.info/registry?q=acca268be3645a24556b81cc15ce0e9a). Enabling that should, in theory, be as simple as adding an entry to our [config.js file](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/routes/v1/config.js).  Let's test this to see if this is feasible from both the BTE side and RTX side (with the help of @edeutsch and @saramsey).

**Comment by saramsey** [comment]
Glad to help!  Our resident experts on the RTX-KG2 API are Eric Deutsch and Amy Glen, and our resident expert on the custom graph database underlying the RTX-KG2 API and on the  algorithm that we use to "canonicalize" our knowledge graph, is Amy Glen (who wrote the graph db). I can lend my expertise on any matters pertaining to the pre-canonicalized RTX-KG2 knowledge graph, and of course, I'm willing to facilitate finding an answer for any RTX-KG2-related question for which I don't know the answer.

**Comment by colleenXu** [comment]
Closing; track in https://github.com/biothings/biothings_explorer/issues/865#issuecomment-2372978205 and later issues instead
