### ISSUE TITLE
checking if query-graph is a cycle, graceful exit if it's a cycle

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#378]
Our faster results-assembly algorithm uses an assumption that the query-graph is not a cycle (so instead it's like a tree). In general, a query-graph that is a cycle is likely problematic - it might be unclear where to stop execution...

We therefore want to be able to check whether a query-graph is a cycle before building sub-queries / executing. Like a validation step. 

Previous work on this is incomplete https://github.com/biothings/bte_trapi_query_graph_handler/pull/75

@marcodarko @ariutta , feel free to assign this to yourselves...

**Comment by colleenXu** [comment]
Example of a recent query to ARAX that was a cycle (Point 3 in this [comment](https://github.com/NCATSTranslator/testing/issues/185#issuecomment-1095578045)). We didn't handle it gracefully; we seem to have hit a 500 error but I'm not sure what happened. https://arax.ncats.io/?r=6c9c1e01-fd7b-4b0c-8398-249f773a428b

We'd want to run this query locally to see what happens...

![Screen Shot 2022-04-21 at 12 19 45 AM](https://user-images.githubusercontent.com/43731687/164400342-24a69008-669c-4ed1-b1be-b26c553eee49.png)

<details>
<summary>I think this is the query in TRAPI format....I might be slightly off</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["PUBCHEM.COMPOUND:222284"],
                    "categories":["biolink:ChemicalEntity"]
                },
                "n1": {
                    "ids":[
                        "MONDO:0005267",
                        "MONDO:0005542",
                        "MONDO:0005311",
                        "MONDO:0005542",
                        "MONDO:0004995"
                        ],
                    "categories":["biolink:DiseaseOrPhenotypicFeature"]
               },
                "n2": {
                    "ids":["MONDO:0100096"],
                    "categories":["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n3": {
                    "categories":["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                },
                "e02": {
                    "subject": "n1",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                },
                "e03": {
                    "subject": "n0",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                },
                "e04": {
                    "subject": "n3",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
    }
}
```
</details>

**Comment by ariutta** [comment]
It would be technically possible for the results assembler to handle query graphs with cycles, but before taking the effort to make that happen, I'd like to see some examples of good use cases that require a cycle.

**Comment by andrewsu** [comment]
> It would be technically possible for the results assembler to handle query graphs with cycles, but before taking the effort to make that happen, I'd like to see some examples of good use cases that require a cycle

agreed, I think the bar here continues to be very high to actually allow execution of query graphs with cycles.  I think the example above might support the implementation of a _check and graceful exit_, but even so I think cases like this are still rare enough "in the wild" that this is not a high priority at the moment...

**Comment by rjawesome** [comment]
To confirm, is the problem with the existing PR (https://github.com/biothings/bte_trapi_query_graph_handler/pull/75) that it doesn't detect all cycles? Also if I were to work on this could I just add to that branch or should I create separate one?

**Comment by ariutta** [comment]
pinging @colleenXu and @marcodarko for the status on that PR...

**Comment by colleenXu** [comment]
Hmm...the work here is a bit old (hard to remember what happened). 

I think I tested the PR (mid-December posts) and it didn't seem to work as-expected. I provide some example QGraphs in this issue...

There were also some questions on "what counts as a cycle" regarding edge-directionality (internal [Slack](https://suwulab.slack.com/archives/CC218TEKC/p1639003324355400)). I think the conclusion is that the edge-directionality doesn't matter aka "when you ignore edge-directionality, is there a cycle in the QGraph"?

**Comment by colleenXu** [comment]
Also @tokebe may be good to ping here, in case he remembers anything from that period of time

**Comment by tokebe** [comment]
I seem to recall the issue was that it failed to detect certain cycle types, and then development was dropped for higher priorities, however I wasn't heavily involved in this issue IIRC.

**Comment by rjawesome** [comment]
Alright I believe that I have made a better cycle-detection algorithm so I'll make a separate PR for that soon. I chose to ignore edge directionality as that is what seemed to be mentioned in the earlier PR.

**Comment by tokebe** [comment]
Resolved by biothings/bte_trapi_query_graph_handler#111
