### ISSUE TITLE
Prevent biolink model from initializing in threads that don't require it.

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#387]
Currently, the biolink model is re-initialized for every thread. Some threads, such as instances of `check_query_status` don't need this and should avoid doing so.

A fix likely involves conditional import statements.

**Comment by colleenXu** [comment]
adding a comment from Jackson that was in Slack:

> Just something that caught my attention a while ago and I finally got around to testing: Every time a thread is started, the biolink model is initialized for that thread, even for endpoints that don't use it like check_query_status. I finally tested it and this only adds ~90ms to execution time, while it would take multiple conditional import refactors across a couple packages to fix, so I think it can safely be ignored for now

**Comment by colleenXu** [comment]
may be related to https://github.com/biothings/BioThings_Explorer_TRAPI/pull/389

**Comment by tokebe** [comment]
Closing due to reasons stated above - the complexity of a refactor would affect readability due to multiple conditional imports in multiple modules, and simply isn't worth the ~90ms performance benefit.
