### ISSUE TITLE
finalize an initial Translator version of DrugMechDB

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#39]
needs harmonization to [BioLink Model](https://biolink.github.io/biolink-model/docs/)

Current version of DrugMechDB at https://github.com/SuLab/DrugMechDB and https://doi.org/10.5281/zenodo.3516335

**Comment by andrewsu** [comment]
Issues created by @mmayers12 for new BioLink Model node and edge types at https://github.com/biolink/biolink-model/issues/314 (and linked therein).

**Comment by mmayers12** [comment]
Latest version with updated biolink-model information for currently mappable concepts and relationships available at http://doi.org/10.5281/zenodo.3708278

**Comment by mmayers12** [comment]
[DrugMechDB repo](https://github.com/SuLab/DrugMechDB) has been updated with code to automatically convert to the biolink model SuLab/DrugMechDB@3eb7a909bc939e7c1edc762a38d733e0e079ec4d 

This includes [a csv mapping file](https://github.com/SuLab/DrugMechDB/blob/master/dmdb_to_bl_map.csv) and [python script for producing the Zenodo output](https://github.com/SuLab/DrugMechDB/blob/master/convert_to_biolink.py)
