### ISSUE TITLE
Not retrieving WIKIPATHWAYS:WP4312 -- Gene

### ISSUE THREAD

**Issue by ariutta** [biothings/biothings_explorer#399]
Should we be able to query with a WikiPathways ID specified in `ids`? I'm not getting results for the following query:
```json
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n0",
          "object": "n1"
        }   
      },  
      "nodes": {
        "n0": {
          "ids": [
            "WIKIPATHWAYS:WP4312"
          ],  
          "categories": [
            "biolink:Pathway"
          ]   
        },  
        "n1": {
          "categories": [
            "biolink:Gene"
          ]   
        }   
      }   
    }   
  }
}
```
![image](https://user-images.githubusercontent.com/1296771/151474932-df297238-2705-4890-82ff-4e36e7e9dab2.png)

There appears to be an error thrown in `nodeUpdateHandler`:
![image](https://user-images.githubusercontent.com/1296771/151474467-18f3eff7-4e21-4327-958e-44beb7f7039c.png)

I know data satisfying the query above exists, because the query below returns `WIKIPATHWAYS:WP4312` in the results:
```json
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n0",
          "object": "n1"
        }   
      },  
      "nodes": {
        "n0": {
          "categories": [
            "biolink:Pathway"
          ]   
        },  
        "n1": {
          "ids": [
            "NCBIGene:23221"
          ],
          "categories": [
            "biolink:Gene"
          ]   
        }   
      }   
    }   
  }
}
```

![image](https://user-images.githubusercontent.com/1296771/151474699-ce77c404-458e-494b-b71e-66650c991c92.png)

I tried the failing query on https://api.bte.ncats.io/v1/query as well as locally with the code in `main` and the code in `is_set2_pr86`, with seemingly the same issue every time.

**Comment by colleenXu** [comment]
probably has to do with ID resolution. There's this issue @tokebe raised: https://github.com/TranslatorSRI/NodeNormalization/issues/113

SRI ID resolver doesn't recognize wikipathway ids I think

**Comment by colleenXu** [comment]
should be resolved, since Jackson pushed a fix for handling the empty responses that SRI ID resolver gives...

**Comment by tokebe** [comment]
Closing as this issue has been resolved.

**Comment by colleenXu** [comment]
Yup it works now. This is what I get for the response to the original query in the issue:

[response.txt](https://github.com/biothings/BioThings_Explorer_TRAPI/files/8683031/response.txt)
