### ISSUE TITLE
command to see all modules' status (branch / changed files) at once

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#404]
[EDIT] This would run from the top directory (bte-trapi-workspace)

perhaps something like `npm run status`, and then the following would be printed to console:
* what branch the user is currently on for all 7 BTE modules (maybe `git branch | grep '*'`)
* what changes there are for each module. 
    * Would be nice if it included added changes, committed changes (not pushed yet), and changes not staged for commit (so....info in `git status`?)
    * We might want to exclude the bte-trapi's data files since those change w/ every cron job...

likely involves git and npm

**Comment by tokebe** [comment]
Currently, `npm run git <git subcommand>` will run the given git subcommand in all module directories. For the case of this issue, `npm run git status` should give this information for all modules.

It does output echos of the commands in the script, which takes up plenty of extra space, however I haven't found a way to disable this...

**Comment by tokebe** [comment]
I've made a [PR for the workspace](https://github.com/biothings/bte-trapi-workspace/pull/7) to make the output a bit more friendly (really this was a minor thing that was bugging me).

**Comment by colleenXu** [comment]
https://github.com/biothings/bte-trapi-workspace/pull/7

**Comment by colleenXu** [comment]
addressed by https://github.com/biothings/bte-trapi-workspace/pull/7, maybe it can be closed now @tokebe ?
