### ISSUE TITLE
Handle nodes with multiple IDs and no category

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#406]
As seen in the Monday relay meeting, when BTE is provided with a node with no categories, it will attempt to infer the category, but if the node has more than one ID, it will immediately give up on attempting to do so. This was relatively obtuse when looking at the logs.

There are two parts to this issue:
- Most importantly, BTE needs to infer categories from multi-ID nodes.
- Secondarily, the TRAPI logging around this point could stand to be clear about why this fails in the new cases created by the code addressing the first point.

**Comment by colleenXu** [comment]
related discussion here: https://suwulab.slack.com/archives/CC218TEKC/p1644261637627879
