### ISSUE TITLE
Make a new test for proper edge merging

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#411]
[As noted](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/390#issuecomment-1043107895) by @andrewsu, #390 is a good issue to turn into a module-level test for proper edge merging.

<details>
  <summary>This query is a good test query to create simplified internal objects for this test</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": ["biolink:affects_risk_for"]
                }
            },
            "nodes": {
                "n00": {
                    "categories": ["biolink:SmallMolecule"],
                    "ids": ["UMLS:C0040329"]
                },
                "n01": {
                    "categories": ["biolink:Disease"],
                    "ids": ["UMLS:C0242379"]
                }
            }
        }
    }
}
```

</details>

**Comment by rjawesome** [comment]
@tokebe What exactly is a simplified internal object and how would I go about creating/testing it?

**Comment by tokebe** [comment]
@rjawesome You can save `Record` objects, which are created from the responses of queried APIs and used throughout results-assembly, etc., by running BTE with the environment variable `DUMP_RECORDS=path/to/fileToCreate.json` (or by pausing execution after `Records` have been created+annotated and using built-in `Record` methods, though this is a little more complicated).

You'll want to write this test in the query_graph_handler test files -- The behavior you'll be testing was fixed by [this PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/88), which hopefully gives an idea of where to start. If not, shoot me a message and I can try to clarify what part of query execution this test should be focused on.

From here you can write a test which supplies these records and expects specific edge-merging behavior (as shown in the original issue). You'll need to import the [Record class](https://github.com/biothings/api-respone-transform.js/blob/main/src/record.ts) and "un-freeze" your saved objects.

**Comment by rjawesome** [comment]
@tokebe To confirm, these are the two things to test:
1. Test the behavior of the ``is_set`` parameter
2. Test that same records with different predicates aren't merged?

Is there anything else that I am missing?

**Comment by tokebe** [comment]
You only need to test that records that are otherwise the same but have different predicates are not merged into one response edge/result. No worries for `is_set` as far as this issue is concerned.
