### ISSUE TITLE
Inferring node categories for QNodes that come with IDs and categories

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#418]
During the investigation into #406 , we found that BTE is not using category info from ID resolution to find metaEdges when there's a QNode with >=1 ID and >=1 category on it already. AKA the user has picked >= 1 semantic type to classify the IDs. see https://github.com/biothings/bte_trapi_query_graph_handler/pull/91#issuecomment-1043708480 and example below

<details>
<summary> another example query </summary>
Send to http://localhost:3000/v1/smartapi/d22b657426375a5295e7da8a303b9893/query (Biolink/Monarch API thru BTE only)

setting a Gene ID as a Disease leads to no successful sub-querying. 
 ```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": [
                        "NCBIGene:3620"
                        ]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```
</details>

This can lead to cases where some / all of the QNode's IDs are ignored when picking metaEdges, so they aren't actually used in the query. It may be problematic because a user does not always know whether the semantic type they pick to go with an ID is "right" or not. Picking a term that is too specific or in a completely different branch of the biolink-model hierarchy can be problematic, as seen above.

But on the other hand, the following behavior has gone okay so far:
* usually picking a more-general/ancestral/parent term is okay
* sometimes picking a term in a different branch is helpful (the smallmolecule/molecularmixture issue or the gene/protein conflation we already have)
* sometimes picking a sibling/closely related term is okay (setting a UMLS ID as Disease but the SRI ID resolver thinks it's a PhenotypicFeature)

We may want to try amending this behavior and adding the suggested semantic type from ID resolution to the set of finding metaEdges...

**Comment by tokebe** [comment]
The main question I think this brings up is how do we want BTE to act with respect to user intent. Obviously, there are potential cases where the user-given category simply does not map to any ID they've provided, however, as stated above, sometimes picking a more specific term/a term from another branch (which may limit available operations from the full potential set) can be useful and probably(?) has a use case.

I see a few options:
1. Ignore user intent, and simply add applicable categories using the multi-ID inference behavior.
2. Ignore user intent only when their choice of category completely mismatches the ID(s) provided.
3. Never ignore user intent, but provide a warning-level log suggesting additional valid categories from multi-ID inference.
4. A mix of 2 and 3.

I lean toward 3 or 4, however I'm not sure what is most in-line with BTE's intended usage and behavior.

Tagging @colleenXu @andrewsu @newgene for discussion.

**Comment by colleenXu** [comment]
I was thinking something like 1 but keeping the category that the user had given as well...is that an option?

**Comment by tokebe** [comment]
That would definitely be an option (we can call that option 1a for now). I'm just a little concerned that something like that might rule out certain use-cases on the part of the user, such as if they specify one category for a set of IDs which might have multiple categories, and for some reason intended to do so?

**Comment by colleenXu** [comment]
Hmmmm....I see what you mean. At the moment though, I think "using more categories than the user originally gave" is fine...

That seems to be the direction that things are going in for Translator right now, partially because of the "messiness" of biomedical knowledge sources...
* The Gene/Protein conflation (rather than letting people say "I want Protein only or Gene only")
* "Expanding categories" so that children/descendants are included when looking for metaEdges to execute a qEdge
* People using "ChemicalEntity" a lot rather than a more specific chemical semantic type like SmallMolecule or MolecularMixture
