### ISSUE TITLE
Better handle the ID-to-object mapping for UMLS identifiers

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#42]

**Comment by kevinxin90** [comment]
BioThings Explorer utilize core BioThings APIs (e.g. MyGene.info, MyChem.info, MyDisease.info) as well as pending BioThings APIs to perform ID-to-object mapping task.

Gene/Protein UMLS IDs have been loaded to MyGene.info (example query: http://mygene.info/v3/gene/1017?fields=umls)

ChemicalSubstance UMLS IDs have been recently loaded to MyChem.info (example query: http://mychem.info/v1/chem/CHEMBL744?fields=umls).

Disease UMLS IDs have been recently loaded into MyDisease.info (example query: http://mydisease.info/v1/disease/MONDO:0016575?fields=umls).

PhenotypicFeature UMLS IDs can be accessed through BioThings HPO API (example query: https://biothings.ncats.io/hpo/phenotype/HP:0004478?fields=xrefs.umls).

Anatomical Entity UMLS IDs can be accessed through BioThings Uberon API (example qeury: https://biothings.ncats.io/uberon/anatomy/UBERON:0000010?fields=xrefs.umls).
