### ISSUE TITLE
update ICEES APIs / Problem with ICEES Asthma

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#421]
The team that develops ICEES APIs for Translator recently announced that they moved their instances to a new setup. See discussion here https://ncatstranslator.slack.com/archives/CSS752SB0/p1646261107496999

It sounds like we should update the ICEES DILI and ICEES Asthma registrations that we use, to use the prod instances here:
https://smart-api.info/registry?q=bb806f5c81e86fe12660fa307d4b0a97
https://smart-api.info/registry?q=749c8f527fa07964de692e0969b71a4e

**Comment by colleenXu** [comment]
I tried updating the registrations in this branch https://github.com/biothings/BioThings_Explorer_TRAPI/commit/f55b1cf754cdc975c8f08f18950f654e852e5054. The DILI stuff looks fine but...

it looks like ICEES Asthma's api response is not getting transformed correctly....so it's not showing up in the TRAPI response for BTE...

----

INFO BELOW

<details>
<summary>This is the query to run in BTE or directly through ICEES Asthma</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": ["biolink:correlated_with"]
                }
            },
            "nodes": {
                "n00": {
                    "ids": ["MONDO:0004766"],
                    "categories": ["biolink:Disease"]
                },
                "n01": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}
```
</details>

This is what I see in the console logs for the TRAPI response from BTE. Maybe the records from ICEES Asthma are being removed during the "filtering out undefined items" step? Notice how there are 23 records from the Asthma API, then the filtering out step makes the number of records go from 91 -> 68 (difference of 23)....And maybe this is due to a transformation issue?
```
  bte:api-response-transform:index api name ICEES Asthma Instance API +2s
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-asthma-dev.apps.renci.org (1 ID): Disease > correlated_with > Disease +2s
  bte:call-apis:query After transformation, BTE is able to retrieve 23 records! +0ms


  bte:biothings-explorer-trapi:batch_edge_query APIEdges are successfully queried.... +3s
  bte:biothings-explorer-trapi:batch_edge_query Filtering out any "undefined" items in (91) records +0ms
  bte:biothings-explorer-trapi:batch_edge_query Total number of records is (68) +0ms
```

<details>
<summary>And this is what I see in the TRAPI logs</summary>

```
        {
            "timestamp": "2022-03-09T06:57:55.053Z",
            "level": "DEBUG",
            "message": "call-apis: Successful POST https://icees-asthma-dev.apps.renci.org (1 ID): Disease > correlated_with > Disease",
            "code": null
        },
        {
            "timestamp": "2022-03-09T06:57:55.054Z",
            "level": "DEBUG",
            "message": "call-apis: After transformation, BTE is able to retrieve 23 records!",
            "code": null
        },

        {
            "timestamp": "2022-03-09T06:57:55.683Z",
            "level": "INFO",
            "message": "Execution Summary: (66) nodes / (68) edges / (66) results; (3/15) queries returned results from (2) unique APIs ",
            "code": null
        },
        {
            "timestamp": "2022-03-09T06:57:55.683Z",
            "level": "INFO",
            "message": "APIs: Automat Cord19 (trapi v-1.2.0), COHD TRAPI 1.2",
            "code": null
        }
```
</details>

**Comment by colleenXu** [comment]
update from meeting: lower priority, but we do want a dev to look into this. Is the raw API response not being transformed into records correctly - hence the "undefined" items log?

**Comment by colleenXu** [comment]
Maybe the issue is that we asked for asthma with a mondo ID (expand the query in one of the previous posts), but the edges of the response use the preferred ID of the KP which seems to be a MESH ID...


These are screenshots of ICEES Asthma's raw response
![Screen Shot 2022-03-09 at 10 39 27 AM](https://user-images.githubusercontent.com/43731687/157509061-bd7d13b9-deb0-4b3d-8ee9-55fa10282300.png)

![Screen Shot 2022-03-09 at 10 40 25 AM](https://user-images.githubusercontent.com/43731687/157509212-fc8e5b11-8a5a-4183-8738-d7b2fd79f215.png)

**Comment by colleenXu** [comment]
note: it looks like the old icees registrations are no longer there or valid. And the current registered ICEES APIs are having issues, see https://github.com/biothings/BioThings_Explorer_TRAPI/issues/422#issuecomment-1063295178

I'm going to remove the ICEES APIs from BTE for the moment as a result
https://github.com/biothings/BioThings_Explorer_TRAPI/commit/99ede62198faa7b369c49b064cd3001264192d0b

**Comment by colleenXu** [comment]
update: I suggest waiting to work on this issue, due to the problems those APIs are having. we can return to this once those APIs are fixed

**Comment by colleenXu** [comment]
update: Kara from ICEES team has reported that the APIs are now fixed and ready. 

However, I'm still encountering the issue I described above, where the records from this API seem to be undefined in some way, so they are removed. This is happening for ICEES Asthma and ICEES PCD.

I'm still using the example query from this comment https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1062611415 

relevant logs from call-apis
```
  bte:call-apis:query call-apis: Successful POST https://icees-asthma.renci.org (1 ID): Disease > correlated_with > Disease (obtained 23 records, took 2s) +0ms
  bte:call-apis:query query success, transforming hits->records... +1s
  bte:api-response-transform:index api name ICEES PCD Instance API - production +1s
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-pcd.renci.org (1 ID): Disease > correlated_with > Disease (obtained 46 records, took 4s) +0ms
```

So that's 23 + 46 = 69 records. 

relevant logs at the end of the one-hop
```
  bte:biothings-explorer-trapi:batch_edge_query APIEdges are successfully queried.... +4s
  bte:biothings-explorer-trapi:batch_edge_query Filtering out any "undefined" items in (298) records +0ms
  bte:biothings-explorer-trapi:batch_edge_query Total number of records is (229) +0ms
  bte:biothings-explorer-trapi:batch_edge_query Start to update nodes... +0ms
  bte:biothings-explorer-trapi:batch_edge_query Update nodes completed! +0ms
  bte:biothings-explorer-trapi:QueryExecutionEdge (6) Storing records... +5s
```

so...298 - 229 = 69. And there are no edges with ICEES infores in the response. So all the ICEES records were removed during the step of "filtering out any undefined items".

**Comment by colleenXu** [comment]
~I'm going to add the ICEES DILI API back to BTE for now since that seems to be working.~

I'm finding a query where ICEES DILI has the same problem as the others...note that I had another query to this API that worked without issues...


<details>
<summary>Query that worked without issues</summary>


```
{
    "message": {
        "query_graph": {
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0005359"],
                    "name": "drug-induced liver injury"
                },
                "n1": {
                    "categories": ["biolink:Disease"],
                    "name": "Disease"
                }
            }
        }
    }
}
```
</details>

<details>
<summary>Workflow B.2e: has issues</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["PUBCHEM.COMPOUND:5865"],
                    "categories": [
                        "biolink:ChemicalEntity"
                    ],
                    "name": "Prednisone"
                },
                "n1": {
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats", "biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```
</details>

Relevant call-api logs. Shows 15x2 + 73x2 + 88x2 = 352 records
```
  bte:api-response-transform:index api name ICEES DILI Instance API - production +4ms
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-dili.renci.org (1 ID): ChemicalEntity > has_real_world_evidence_of_association_with > Disease (obtained 15 records, took 4s) +0ms
  bte:call-apis:query query success, transforming hits->records... +14ms
  bte:api-response-transform:index api name ICEES DILI Instance API - production +14ms
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-dili.renci.org (1 ID): SmallMolecule > has_real_world_evidence_of_association_with > Disease (obtained 15 records, took 4s) +0ms

  bte:api-response-transform:index api name ICEES DILI Instance API - production +545ms
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-dili.renci.org (1 ID): ChemicalEntity > has_real_world_evidence_of_association_with > PhenotypicFeature (obtained 73 records, took 5s) +1ms
  bte:call-apis:query query success, transforming hits->records... +421ms
  bte:api-response-transform:index api name ICEES DILI Instance API - production +422ms
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-dili.renci.org (1 ID): SmallMolecule > has_real_world_evidence_of_association_with > PhenotypicFeature (obtained 73 records, took 5s) +1ms

  bte:api-response-transform:index api name ICEES DILI Instance API - production +623ms
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-dili.renci.org (1 ID): SmallMolecule > has_real_world_evidence_of_association_with > DiseaseOrPhenotypicFeature (obtained 88 records, took 5s) +0ms
  bte:call-apis:query query success, transforming hits->records... +20ms
  bte:api-response-transform:index api name ICEES DILI Instance API - production +20ms
  bte:api-response-transform:index api tags: translator,trapi,bte-trapi +0ms
  bte:call-apis:query call-apis: Successful POST https://icees-dili.renci.org (1 ID): ChemicalEntity > has_real_world_evidence_of_association_with > DiseaseOrPhenotypicFeature (obtained 88 records, took 5s) +0ms
```

Filtering out undefined at the end: 10519 - 10167 = 352 records! and ICEES DILI doesn't show up in the list of APIs contributing to the results
```
  bte:biothings-explorer-trapi:batch_edge_query APIEdges are successfully queried.... +22s
  bte:biothings-explorer-trapi:batch_edge_query Filtering out any "undefined" items in (10519) records +0ms
  bte:biothings-explorer-trapi:batch_edge_query Total number of records is (10167) +1ms
  bte:biothings-explorer-trapi:batch_edge_query Start to update nodes... +0ms
  bte:biothings-explorer-trapi:batch_edge_query Update nodes completed! +8ms
```

**Comment by colleenXu** [comment]
note: this is the stuff I'm adding to the config file to look at these apis

```
    // ICEES APIs
    {
        id: '749c8f527fa07964de692e0969b71a4e',
        name: 'ICEES DILI Instance API - production'
    },
    {
        id: 'bb806f5c81e86fe12660fa307d4b0a97',
        name: 'ICEES Asthma Instance API - production'
    },
    {
        id: '4153c947a32e2e2a55a320d0bee22077',
        name: 'ICEES PCD Instance API - production'
    },
```

**Comment by colleenXu** [comment]
Updating: I'm still seeing this issue. I'll describe what I'm going again:
* put only ICEES DILI in the config file
```
 exports.API_LIST = [
    {
        id: '749c8f527fa07964de692e0969b71a4e',
        name: 'ICEES DILI Instance API - production'
    },
];
```
* Compare ICEES DILI (use the same queries and POST to https://icees-dili.renci.org/query) to BTE (console logs and response) 
<details>
<summary>DILI Disease-> Disease: ICEES DILI returns only 29 results when queried directly, BTE seems to handle this fine</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0005359"],
                    "name": "drug-induced liver injury"
                },
                "n1": {
                    "categories": ["biolink:Disease"],
                    "name": "Disease"
                }
            }
        }
    }
}
```
</details>

<details>
<summary>Prednisone chem -> DiseaseOrPheno: ICEES DILI returns 88 results when queried directly, PROBLEM: BTE removes all records and terminates without any results</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["PUBCHEM.COMPOUND:5865"],
                    "categories": [
                        "biolink:ChemicalEntity"
                    ],
                    "name": "Prednisone"
                },
                "n1": {
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```
</details>

Screenshot of BTE's console logs, showing the removal of "undefined records"

![Screen Shot 2022-04-26 at 9 23 35 PM](https://user-images.githubusercontent.com/43731687/165440360-74cc9877-8738-49a3-8276-b9ae498f2cfd.png)

**Comment by colleenXu** [comment]
And I'll describe what I'm seeing with ICEES Asthma again:

* put only ICEES Asthma in the config file
```
 exports.API_LIST = [
    {
        id: 'bb806f5c81e86fe12660fa307d4b0a97',
        name: 'ICEES Asthma Instance API - production'
    },
];
```
* Compare ICEES Asthma (use the same queries and POST to https://icees-asthma.renci.org/query) to BTE (console logs and response) 

<details>
<summary>Prednisone chem -> DiseaseOrPheno: ICEES Asthma returns 57 results when queried directly, PROBLEM: BTE removes all records and terminates without any results</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["PUBCHEM.COMPOUND:5865"],
                    "categories": [
                        "biolink:ChemicalEntity"
                    ],
                    "name": "Prednisone"
                },
                "n1": {
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```
</details>

Screenshot of BTE for the prednisone query:
![Screen Shot 2022-04-26 at 9 32 49 PM](https://user-images.githubusercontent.com/43731687/165441300-a780e008-f001-47ec-acaf-8d8e5d8a87cb.png)


<details>
<summary>Asthma -> Disease: ICEES Asthma returns 23 results when queried directly, PROBLEM: BTE removes all records and terminates without any results</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": ["biolink:correlated_with"]
                }
            },
            "nodes": {
                "n00": {
                    "ids": ["MONDO:0004766"],
                    "categories": ["biolink:Disease"],
                    "name": "asthma"
                },
                "n01": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}
```
</details>

Screenshot of BTE's console logs, showing the removal of "undefined records"
![Screen Shot 2022-04-26 at 9 35 02 PM](https://user-images.githubusercontent.com/43731687/165441483-52a5a905-96e1-4bd7-a891-128d1cdbafed.png)

**Comment by tokebe** [comment]
Regarding the ICEES DILI example, it would appear that each edgeBinding returned by the query gives the subject `CHEBI:4187`, which doesn't match the query, causing the transformer to not transform that edge binding. (Incidentally, in some cases, these edge bindings would appear to bind from subject `CHEBI:4187` to just... `D`, like so:

```
{
  subject: "CHEBI:41879",
  object: "D",
}
```

This implies to me this issue may be with DILI's response rather than our handling of it?

I'll update with an investigation into the Asthma API soon.

**Comment by tokebe** [comment]
Similarly, for ICEES Asthma, the first query results in all `MESH:C001892` which doesn't match, with some objects being just `D`, like so:

```
{
  subject: "MESH:C001892",
  object: "D",
}
```

The second query results in all `MESH:C018460` for the subject, which also results in mismatches causing the records to be undefined.

**Comment by colleenXu** [comment]
I've confirmed that:
* the working queries have a response where the QNode ID is used in the expected way: it's used in edges' subject fields and a node's primary ID / key. 
* the "not working" queries have a response with an unexpected structure: the QNode ID is instead in the equivalent_identifiers / `biolink:synonym` (always the first?) attribute of a (always the first?) node in `knowledge_graph.nodes`. Another ID is used as the primary-ID/key of this node and is used in the edges' subject fields. 
    * This isn't happening all the time (since some queries work)
    * The "other ID" isn't consistent between APIs. Prednisone [PUBCHEM.COMPOUND:5865](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A5865&conflate=true) was converted to [CHEBI:41879 (Node Normalizer says this is a different thing)](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=CHEBI%3A41879&conflate=true) by ICEES DILI and to [MESH:C001892 (Node Normalizer says this is different from the other two + obsolete)](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=MESH%3AC001892&conflate=true) by ICEES Asthma. 
* the APIs seem to have an [ongoing](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/213#issuecomment-904316142) [issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/213#issuecomment-924585237) around the intended concepts (which seem to be the names of their nodes) vs the IDs they use (primary ID and equivalent ones). Some IDs are just odd / not aligned to biolink; the "D" node is one example (pasted below). Others have primary IDs or equivalent IDs that don't seem to match the intended concepts; for example, I saw [CHEBI:35474 (a chemical entity, anti-anxiety agents)](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=CHEBI%3A35474&conflate=true) as the primary ID for a Disease "AnxietyDx" (seems to be "anxiety diagnosis"). 
```
                "D": {
                    "name": "RESPONDER_STATUS",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:synonym",
                            "value": [
                                "U",
                                "M",
                                "Y",
                                ":",
                                "0"
                            ]
                        }
                    ],
                    "categories": [
                        "biolink:PhenotypicFeature"
                    ]
                },
```

**Comment by colleenXu** [comment]
Some thoughts I have:
* I'm not clear on how we process TRAPI responses. Do we only look at knowledge_graph.edges - and do we expect Edge subject/object fields to use the exact ID provided by the QNode? 
* when we encountered [something](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/213#issuecomment-904316142) [like](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/213#issuecomment-924585237) this before (although it didn't involve the QNode with IDs), it looks like we didn't do anything about this issue. We let the ICEES team know, and we kept their APIs in our config file. It was up to the ICEES team to handle issues with their IDs and how they respond to queries. 
* Perhaps "special handling logic" (described below) could recover these edges. It would also work in cases where we query TRAPI APIs with their non-preferred ID - and the KG response uses their preferred ID. 
    * catch when no edges match the query
    * then check if the first node in the KG has the QNode's ID in its "biolink:synonym" attribute -> if it does...continue. If it doesn't, then continue the "undefined" records behavior
    * look at that node's key / primaryID. Use it as a "placeholder QNode ID" to process the edges / results correctly...then replace it in the processed stuff (records?) with the QNode ID.
    * maybe now everything aligns properly, so the record won't be undefined?
* However, I am a bit concerned about doing this, because it assumes that the QNode ID and the Node returned by ICEES are on a basic level "the same thing" - so it's okay to stitch the QNode ID to the edges that use the ID ICEES is using. But I'm not sure that this is the case (see my examples above).

**Comment by tokebe** [comment]
- Currently, the TRAPI transformer (to Records) expects the returned subject curie to match the query subject curie (accounting for reversing).
- I agree -- I'm a little reluctant to do special handling for this case, as currently the cases I've seen involve the returned subject resolving to a separate entity according to the node normalizer. This in combination with other examples of odd seeming incorrect "concept conflation" implies to me that we're better off not propagating this behavior downstream?

I think it's probably best to contact the ICEES team with these issues and see if they can resolve it on their end.

**Comment by colleenXu** [comment]
@tokebe to clarify....the returned subject curie that you're referring to 
> * Currently, the TRAPI transformer (to Records) expects the returned subject curie to match the query subject curie (accounting for reversing).

is in the message.knowledge_graph.edges of the response ICEES gives? 

AKA the answer to my question below is "Yes, we only look at edges" and "yes we expect the edge subject/object to use the exact CURIE given by the QNode ID"?

> I'm not clear on how we process TRAPI responses. Do we only look at knowledge_graph.edges - and do we expect Edge subject/object fields to use the exact ID provided by the QNode?

**Comment by tokebe** [comment]
The TRAPI transformer looks specifically at the edge_bindings and node_bindings of the results (`message.results[n].edge_bindings` and `message.results[n].node_bindings`).

(QNode ID being a confusing term here...that would typically refer to something like `n01`)

So, we're looking at the edge_bindings, the node_bindings, and the edges, and we're expecting the curie provided by the node_binding subject to exactly match a curie (as there can be multiple) within the sub-query edge's subject/input. The object is, at least at this stage where the issue is occurring, not checked.

**Comment by karafecho** [comment]
FYI: Max W. and I posted comments in Translator's # bte slack channel.

Thanks for everyone's efforts on this ticket.

**Comment by colleenXu** [comment]
@tokebe I see! I was mistaken....so we're reading the elements of the message.results array. Using TRAPI vocab, when we process a `Result` object for the one-hops in the [above](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1110524035) [comments](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1110530471), we expect the curie in the node_binding for `n00` to be the same as the curie in the subject field of the edge specified in the edge_binding for `e00`. 

As for vocab, I see where this is confusing. Hmmmm

One example: I think I've been referring to the ID/curie in the ids field of a qNode in some cases (which we do use to figure out "what biological entity" this qNode is representing)...but this actually isn't the same as "qNodeID". As you said above and [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/379#issuecomment-1068057622), qNodeID refers to the "key" of the node in the query graph.

**Comment by colleenXu** [comment]
@tokebe However...your [explanation](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1143918566) doesn't seem to match up with my check. Here's the ICEES response for the "not working" query  for [DILI](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1110524035) (Prednisone chem -> DiseaseOrPheno):

It's a JSON but github requires me to save as txt. 
[icees-dili.txt](https://github.com/biothings/BioThings_Explorer_TRAPI/files/8829205/icees-dili.txt)

Looking at the results section, it looks like the node_binding `n00` curie **does match** the curie in the subject field of the edge specified in the edge_binding for `e00`....

And this curie doesn't match the "curie in the ids field of the qNode" (for the message we sent as a query). 

So....maybe the "undefined"/"problem" is happening at a different point?

**Comment by colleenXu** [comment]
Closing: based on Kara's Slack post in Translator's internal Slack (pasted below), these APIs are now non-Translator and are replaced by automat-icees-kg (Translator service) which we already ingest as of October. 

> Kara Fecho (Exposures Provider, SRI)
>   [2:14 PM] Jan 5 2023
> channel: I wanted to alert folks to a few changes to ICEES. Specifically, shortly before the September relay, we deployed a new service, icees-kg, to the ITRB production environment. (I had announced this, but I think my message was lost in pre-relay preparations. :slightly_smiling_face:) icees-kg provides a graphical representation of four ICEES datasets, asthma, PCD, DILI, and COVID, each containing one or more years of integrated patient + exposures data. icees-kg is intended to replace icees-asthma, icees-pcd, and icees-dili as the sole ICEES-related Translator KP. The fully featured icees-asthma, icees-pcd, icees-dili, and icees-covid services remain available, just not as Translator services.
> Note that icees-kg should represent an improvement in our previous approach in that: (1) it provisions new data on COVID; (2) response time should be super quick and reliable; and (3) it is fully compliant with all regulatory and institutional requirements for ITRB cloud deployment.
> Please feel free to reach out to me, should you have questions.
> Thanks! (edited)
