### ISSUE TITLE
add ICEES PCD API / Problem with that API

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#422]
The team behind ICEES APIs recently released a "PCD" (primary ciliary dyskinesia?) API. perhaps we would want to incorporate it into BTE?

https://smart-api.info/registry?q=4153c947a32e2e2a55a320d0bee22077

Example query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0009061"],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ],
                    "name": "Cystic Fibrosis"
                },
                "n1": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
This is what I'm adding to the config file

```
    {
        id: '4153c947a32e2e2a55a320d0bee22077',
        name: 'ICEES PCD Instance API - production'
    },
```

when I try to add PCD to the config file and run this query, I get console + TRAPI logs saying that the query failed and they're odd (very long with the whole api response inside). 

It looks like the PCD API (Post the query below directly to https://icees-pcd.renci.org/query) is returning something that isn't proper JSON, and maybe that's the issue...
![Screen Shot 2022-03-08 at 11 20 49 PM](https://user-images.githubusercontent.com/43731687/157392269-74e8091a-5e69-407e-8f61-332598904179.png)

<details>
<summary>Here's the query I'm actually using for testing</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0009061"],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ],
                    "name": "Cystic Fibrosis"
                },
                "n1": {
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```
</details>

The log: it includes a TypeError...

  bte:call-apis:query Failed to make to following query: {"url":"https://icees-pcd.renci.org/query","data":{"message":{"query_graph":{"nodes":{"n0":{"ids":["MONDO:0009061"],"categories":["biolink:DiseaseOrPhenotypicFeature"]},"n1":{"categories":["biolink:Disease"]}},"edges":{"e01":{"subject":"n0","object":"n1","predicates":["biolink:has_real_world_evidence_of_association_with"]}}}},"submitter":"infores:bte"},"method":"post","timeout":50000,"headers":{"Content-Type":"application/json","User-Agent":"BTE/dev Node/v16.10.0 darwin"}}. The error is TypeError: Cannot use 'in' operator to search for 'message' in {"terms and conditions":"The Translator Integrated Clinical and Environmental Exposures Service (ICEES)

**Comment by colleenXu** [comment]
Update from lab meeting: no need for a dev yet, need to talk to Translator team developing ICEES and figure out what's going on with this API

messaged Kara here https://ncatstranslator.slack.com/archives/CSS752SB0/p1646850267215489?thread_ts=1646261107.496999&cid=CSS752SB0

**Comment by colleenXu** [comment]
update: seems to be related to this https://github.com/NCATS-Tangerine/icees-api/issues/225

**Comment by colleenXu** [comment]
update: I suggest waiting to work on this issue, due to the problems those APIs are having. we can return to this once those APIs are fixed

**Comment by colleenXu** [comment]
note update here https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1092140340. All ICEES APIs are having the same issues

**Comment by colleenXu** [comment]
And I'll describe what I'm seeing with ICEES PCD again:

* put only ICEES PCD in the config file
```
 exports.API_LIST = [
    {
        id: '4153c947a32e2e2a55a320d0bee22077',
        name: 'ICEES PCD Instance API - production'
    },
];
```
* Compare ICEES PCD response (use the same queries and POST to https://icees-pcd.renci.org/query) to BTE (console logs and response) 

<details>
<summary>Fever -> Disease: ICEES PCD returns 46 results when queried directly, BTE seems to handle this fine</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["UMLS:C0424755"],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ],
                    "name": "Fever"
                },
                "n1": {
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
</details>

<details>
<summary>Cystic Fibrosis -> chem: ICEES PCD returns 121 results when queried directly, PROBLEM: BTE removes all records and terminates without any results</summary>

Note that some sub-queries fail, so BTE skips the rest of the sub-queries. 

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0009061"],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ],
                    "name": "Cystic Fibrosis"
                },
                "n1": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```
</details>

Screenshot of BTE's console logs, showing the removal of "undefined records"

![Screen Shot 2022-04-26 at 9 44 01 PM](https://user-images.githubusercontent.com/43731687/165442370-dc8aeaf9-9660-46f6-b364-e5267ff265a7.png)

**Comment by tokebe** [comment]
Similarly to my [other findings](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1134941251), the issue here seems to be that the subject coming back is a mismatch - in this case `MESH:C026422`, which resolves to `cystic fibrosis serum factor` instead of `cystic fibrosis`. If this is expected/intended behavior, then we may need to add additional special handling for these sorts of cases?

Note that this query also returns the occasional object `D`, which I doubt is intended.

**Comment by colleenXu** [comment]
oops I only now realized that I didn't provide the right query for Fever -> Disease >.<. Now fixed.

**Comment by colleenXu** [comment]
Just providing more info to what Jackson said above: the QNode ID MONDO:0009061 (cystic fibrosis) is in the ICEES PCD response as a Node with the primary ID [MESH:C026422, which Node Normalizer says is a chemical entity called cystic fibrosis serum factor](https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=MESH%3AC026422&conflate=true). 

Vs for the fever query, the QNode ID is used in the expected way: it's used in edges' subject fields and a node's primary ID / key.

**Comment by colleenXu** [comment]
I have the same response as I had on the related issue: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/421#issuecomment-1136546681

**Comment by colleenXu** [comment]
Closing: based on Kara's Slack post in Translator's internal Slack (pasted below), these APIs are now non-Translator and are replaced by automat-icees-kg (Translator service) which we already ingest as of October. 

> Kara Fecho (Exposures Provider, SRI)
>   [2:14 PM] Jan 5 2023
> channel: I wanted to alert folks to a few changes to ICEES. Specifically, shortly before the September relay, we deployed a new service, icees-kg, to the ITRB production environment. (I had announced this, but I think my message was lost in pre-relay preparations. :slightly_smiling_face:) icees-kg provides a graphical representation of four ICEES datasets, asthma, PCD, DILI, and COVID, each containing one or more years of integrated patient + exposures data. icees-kg is intended to replace icees-asthma, icees-pcd, and icees-dili as the sole ICEES-related Translator KP. The fully featured icees-asthma, icees-pcd, icees-dili, and icees-covid services remain available, just not as Translator services.
> Note that icees-kg should represent an improvement in our previous approach in that: (1) it provisions new data on COVID; (2) response time should be super quick and reliable; and (3) it is fully compliant with all regulatory and institutional requirements for ITRB cloud deployment.
> Please feel free to reach out to me, should you have questions.
> Thanks! (edited)
