### ISSUE TITLE
unexpected loss of results when going from `NamedThing` to specific categories

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#427]
The query from https://github.com/NCATSTranslator/testing/issues/178 (**Query 1** below) asked for nodes joining subutex (`PUBCHEM.COMPOUND:644073`) and dry mouth (`HP:0000217`) with one intermediate node of type `biolink:NamedThing`. Among the results were genes (`biolink:Gene`) `IRF5` and `CD69`, and proteins (`biolink:Protein`) `"Mitogen-Activated Protein Kinases` and `Na(+)-K(+)-Exchanging ATPase`.  However, when I execute **Query 2** below that simply changes `NamedThing` to `Gene` and `Protein`, I still get `IRF5` in the results but lose the other three entities mentioned previously.  This behavior is unexpected enough that I'm going to label this as a bug for now...

**Query 1**:
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e01": {
                    "subject": "n01",
                    "object": "n02",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            },
            "nodes": {
                "n00": {
                    "ids": [
                        "PUBCHEM.COMPOUND:644073"
                    ],
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:NamedThing"
                    ]
                },
                "n02": {
                    "ids": [
                        "HP:0000217"
                    ],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                }
            }
        }
    }
}
```

**Query 2**

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e01": {
                    "subject": "n01",
                    "object": "n02",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            },
            "nodes": {
                "n00": {
                    "ids": [
                        "PUBCHEM.COMPOUND:644073"
                    ],
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:Gene","biolink:Protein"
                    ]
                },
                "n02": {
                    "ids": [
                        "HP:0000217"
                    ],
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
Looks like these are from SEMMEDdb...

Perhaps what is happening is that the association (underlying data used in the API) uses a SEMMED semantic type that doesn't map to biolink Gene or Protein:
* [CD69](https://uts.nlm.nih.gov/uts/umls/concept/C2744535) (C2744535) is sometimes an [Immunologic Factor](https://uts.nlm.nih.gov/uts/umls/semantic-network/T129), which we map to chemical entity. It's also sometimes an [Amino Acid, Peptide, or Protein](https://uts.nlm.nih.gov/uts/umls/semantic-network/T116), which we map to Polypeptide (a parent of Protein). 
* [Mitogen-Activated Protein Kinases](https://uts.nlm.nih.gov/uts/umls/concept/C0752312) (C0752312) and [Na(+)-K(+)-Exchanging ATPase](https://uts.nlm.nih.gov/uts/umls/concept/C0001479) (C0001479) are sometimes an [Amino Acid, Peptide, or Protein](https://uts.nlm.nih.gov/uts/umls/semantic-network/T116), which we map to Polypeptide (a parent of Protein).

**Comment by colleenXu** [comment]
Findings:
* I get CD69 when I set the query's n01 to Polypeptide, so all the records likely have "Amino Acid, Peptide, or Protein" as CD69's SEMMED semantic type
* I get Mitogen-Activated Protein Kinases and Na(+)-K(+)-Exchanging ATPase when I set the query's n01 to [Polypeptide, Protein]. This means that some records use "Amino Acid, Peptide, or Protein" (maps to Polypeptide) and others use "Enzyme" (which maps to Protein). 

---

Looking at the first hop only...subutex (PUBCHEM.COMPOUND:644073) -> something

<details>
<summary>query</summary>

```
{
    "message": {
      "query_graph": {
        "edges": {
          "e00": {
            "subject": "n00",
              "object": "n01",
          "predicates":["biolink:related_to"]
          }
        },
        "nodes": {
          "n00": {
            "ids": ["PUBCHEM.COMPOUND:644073"],
            "categories": ["biolink:ChemicalEntity"]
          },
          "n01": {
              "categories": ["biolink:Protein"]
          }
        }
      }
    }
  }
```
</details>

When I set n01 to Protein, I can get Mitogen-Activated Protein Kinases and Na(+)-K(+)-Exchanging ATPase. 

But for the second hop...dry mouth (HP:0000217) -> something

<details>
<summary>query</summary>

```
{
    "message": {
      "query_graph": {
        "edges": {
          "e01": {
            "subject": "n01",
              "object": "n02",
          "predicates":["biolink:related_to"]
          }
        },
        "nodes": {
          "n01": {
              "categories": ["biolink:Protein"]
          },
          "n02": {
            "ids": ["HP:0000217"],
            "categories": ["biolink:DiseaseOrPhenotypicFeature"]
          }
        }
      }
    }
  }
```
</details>

When I set n01 to Protein, I don't get those two...
When I set n01 to Polypeptide, I can get Mitogen-Activated Protein Kinases and Na(+)-K(+)-Exchanging ATPase.

**Comment by colleenXu** [comment]
In summary:
* semmeddb doesn't consistently use the same SEMMED semantic type for a UMLS ID
* semmeddb uses SEMMED semantic types that map to more general biolink classes (node categories). For example, a lot of data on genes or proteins is under "Amino Acid, Peptide, or Protein".....and that really maps to Polypeptide.

**Comment by andrewsu** [comment]
Closing this issue for now -- thank you @colleenXu for the detailed analysis... Going to tag @cbizon as potentially another example to consider when looking at conflation.  Perhaps `biolink:Protein` should be automatically mapped up to `biolink:Polypeptide` to handle cases like this?
