### ISSUE TITLE
Query returns KG but no results

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#430]
The following query would appear to return a complete KG with nodes and edges but no results:

```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n01",
          "object": "n00"
        },
        "e01": {
          "subject": "n01",
          "object": "n02"
        },
        "e02": {
          "subject": "liver",
          "object": "n00"
        }
      },
      "nodes": {
        "liver": {
          "ids": [
            "UBERON:0002107"
          ],
          "categories": [
            "biolink:GrossAnatomicalStructure"
          ]
        },
        "n00": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        },
        "n01": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n02": {
          "ids": [
            "NCBIGene:211"
          ],
          "categories": [
            "biolink:Gene"
          ]
        }
      }
    }
  }
}
```

**Comment by tokebe** [comment]
An update:
- This query can be tested significantly more quickly by disabling all but `semmeddb`, `mydisease`, and `text mining targeted` (Courtesy of @colleenXu's testing). This outputs a smaller KG but still retains the behavior of having a KG but no results.
-  No `queryGraphSolutions` are being generated, despite there being 1242 `e00` records, 4 `e01` records, and 2478 `e02` records -- though `e01` only having 4 records might stand out?
- Removing `e02`, `e00` gets 3055 records and `e01` retains 4, and in this case 3020 `queryGraphSolutions` are generated, with results appearing in the response
- Removing only `e00` also ends with no results and no queryGraphSolutions

**Comment by colleenXu** [comment]
Notes:
* I take the config file and comment out every entry except semmeddb / mydisease / text mining targeted. This allows the query to run in under 30 sec. 
* When all APIs are kept, this query took me > 55 min to run o_0.

**Comment by colleenXu** [comment]
@tokebe 

I'm working from this query that works (gives 365 results) and looking at intermediates between it and the original query to see what will create "no results". 

<details>
<summary>query that works</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n0",
                    "object": "n1"
                },
                "e01": {
                    "subject": "n1",
                    "object": "n2"
                },
                "e02": {
                    "subject": "n2",
                    "object": "n3"
                }
            },
            "nodes": {
                "n0":
                {
                    "ids": ["UBERON:0002107"],
                    "categories": ["biolink:GrossAnatomicalStructure"]
                },
                "n1": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n2": {
                    "categories": ["biolink:Gene"]
                },
                "n3": {
                    "ids": ["NCBIGene:211"],
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```
</details>


Queries that still work (adding these changes up):
* removing the categories from the QNodes that have IDs
* renaming the QNodes so that they're "liver", "n00", "n01", "n02"
* flipping the direction for e01 so that it's Gene -> DiseaseOrPhenotypicFeature

---

EDIT: The problem seems to come from setting e00 (the first QEdge) with the middle QNodes (n00 and n01). 

Looks like the issue comes from the ordering/direction of QEdges when specifying the QGraph. I tried:
* all possible orderings from the query that works above: so liver -> n00, n00 -> n01, and n01 -> n02 
* all possible orderings from the original query that doesn't work: so liver -> 00, n01 -> n00 (flipped direction), and n01 -> n02

What didn't work (no results):

<details>
<summary>n00 -> n01, liver -> n00, n01 -> n02</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01"

                },
                "e01": {
                    "subject": "liver",
                    "object": "n00"
                },
                "e02": {
                    "subject": "n01",
                    "object": "n02"
                }
            },
            "nodes": {
                "liver":
                {
                    "ids": ["UBERON:0002107"]
                },
                "n00": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n01": {
                    "categories": ["biolink:Gene"]
                },
                "n02": {
                    "ids": ["NCBIGene:211"]
                }
            }
        }
    }
}
```
</details>

<details>
<summary>n00 -> n01, n01 -> n02, liver -> n00</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01"

                },
                "e01": {
                    "subject": "liver",
                    "object": "n00"
                },
                "e02": {
                    "subject": "n01",
                    "object": "n02"
                }
            },
            "nodes": {
                "liver":
                {
                    "ids": ["UBERON:0002107"]
                },
                "n00": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n01": {
                    "categories": ["biolink:Gene"]
                },
                "n02": {
                    "ids": ["NCBIGene:211"]
                }
            }
        }
    }
}
```
</details>

<details>
<summary>n01 -> n00 (flipped like it is in the original), liver -> n00, n01 -> n02</summary>

Basically the original query, but exchanging what's in e01 and e02

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01"

                },
                "e01": {
                    "subject": "liver",
                    "object": "n00"
                },
                "e02": {
                    "subject": "n01",
                    "object": "n02"
                }
            },
            "nodes": {
                "liver":
                {
                    "ids": ["UBERON:0002107"]
                },
                "n00": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n01": {
                    "categories": ["biolink:Gene"]
                },
                "n02": {
                    "ids": ["NCBIGene:211"]
                }
            }
        }
    }
}
```
</details>

And the original query, of course.

**Comment by ariutta** [comment]
If it's the ordering, my guess is the issue could be with the query execution. I haven't verified 100%, but I suspect the ordering wouldn't matter to the results assembly.

**Comment by colleenXu** [comment]
what I haven't tried yet: what if I don't rearrange items in the QEdge array? what if I just rename the QEdges?

EDIT: doesn't seem to change what "works" vs what "doesn't":

<details>
<summary>example of what still doesn't work even with renamed QEdges</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e07": {
                    "subject": "n01",
                    "object": "n00"
                },
                "e10": {
                    "subject": "n01",
                    "object": "n02"
                },
                "e08": {
                    "subject": "liver",
                    "object": "n00"
                }
            },
            "nodes": {
                "liver":
                {
                    "ids": ["UBERON:0002107"]
                },
                "n00": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                },
                "n01": {
                    "categories": ["biolink:Gene"]
                },
                "n02": {
                    "ids": ["NCBIGene:211"]
                }
            }
        }
    }
}
```
</details>

**Comment by tokebe** [comment]
Comparing the base query to the working query, as the records appear in `recordsByQEdgeID` in `query_results.js`:

- Base: 
  - e00 (1242 records) connected to e01, e02
  - e01 (4 records) connected to e00
  - e02 (2478 records) connected to e00

- Working:
  - e00 (2478 records) connected to e01
  - e01 (1242 records) connected to e00, e02
  - e02 (4 records) connected to e01

Both have the same number of nodes and edges in the KG, but the base query has no results.

While the edge ordering certainly is different, it would appear that these records are the same once they appear in `query_results`. I have yet to fully confirm this, however I have confirmed that the 4 records are the same between each query.

**Comment by colleenXu** [comment]
Look into EdgeExecution order for queries that work vs don't

**Comment by ariutta** [comment]
@tokebe, I don't think it should matter, but do `initialQEdgeID` and `initialQNodeIDToMatch` change for your Base vs. Working test cases? If the data is identical other than the directionality being flipped, `TrapiResultsAssembler` shouldn't care, but it could be worth checking.

We may want to change this block of code:
https://github.com/biothings/bte_trapi_query_graph_handler/blob/a150d6551bf38b3f85517f4aa84416028774b5a2/src/query_results.js#L242-L280

**Comment by tokebe** [comment]
I've refactored the test queries to use consistent node names, for reference they are below:

<details>
<summary>base query</summary>

```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n2",
          "object": "n1"
        },
        "e01": {
          "subject": "n2",
          "object": "n3"
        },
        "e02": {
          "subject": "n0",
          "object": "n1"
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "UBERON:0002107"
          ],
          "categories": [
            "biolink:GrossAnatomicalStructure"
          ]
        },
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        },
        "n2": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n3": {
          "ids": [
            "NCBIGene:211"
          ],
          "categories": [
            "biolink:Gene"
          ]
        }
      }
    }
  }
}
```

</details>

<details>
<summary>working query</summary>

```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n0",
          "object": "n1"
        },
        "e01": {
          "subject": "n2",
          "object": "n1"
        },
        "e02": {
          "subject": "n2",
          "object": "n3"
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "UBERON:0002107"
          ],
          "categories": [
            "biolink:GrossAnatomicalStructure"
          ]
        },
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        },
        "n2": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n3": {
          "ids": [
            "NCBIGene:211"
          ],
          "categories": [
            "biolink:Gene"
          ]
        }
      }
    }
  }
}
```

</details>

Note that no directions are flipped between the two queries, only the order of the edges.

Between these two:

Base:

- `initialQEdgeID`: `e00`
- `initialQNodeIDToMatch`: `n1`

Working:

- `initialQEdgeID`: `e00`
- `initialQNodeIDToMatch`: `n0`

I'm still working on getting the actual records comparisons.

**Comment by ariutta** [comment]
This looks suspicious:
```
initialQNodeIDToMatch: n1
```

The `initialQNodeIDToMatch` should only have a single QEdge (it should be a leaf or a root with a single child).

**Comment by tokebe** [comment]
Stepping through the code to see where this decision is made, I'm just going to naively ask questions about things that might look odd to me.

Is the array in [this line](https://github.com/biothings/bte_trapi_query_graph_handler/blob/ec579da2524ef07cb8a729197d28820b27e78781/src/query_results.js#L263) supposed to be the same two items?

(note: if so, changing this does not appear to fix the issue)

**Comment by ariutta** [comment]
No, that looks wrong. I think it's supposed to be `inputQNodeID_1, outputQNodeID_1`

**Comment by tokebe** [comment]
I'm not sure, but I think what may be happening is that the code is selecting the first instance of a node not used in the _next_ edge, but not the first instance of a node confirmed to not be used in _all other_ edges. I'll have to spend some more time staring at the code and possibly testing an alternate implementation to be sure.

**Comment by ariutta** [comment]
I think you're right.

**Comment by ariutta** [comment]
We want `initialQNodeIDToMatch` to be a leaf (ignoring directionality, a root with a single child can be thought of as a leaf). If there are multiple leaves, any of them would work, but I suspect we might get the best performance if we choose the one that would give us an `initialQEdgeID` with the fewest records.

**Comment by colleenXu** [comment]
Sounds like the selection of the initialQEdgeID / initialQNodeIDToMatch could be an issue? I wonder if it's related to "the QEdge order in the QGraph"...

**Comment by colleenXu** [comment]
EDIT IN PROGRESS. Looking at stuff...

base query (no results):
* execution order is e02 (n0 --> n1), e01-reversed (n2 <-- n3), e00 (n2 --> n1). 
* initialQEdgeID: e00, initialQNodeIDToMatch: n1 +0ms

working query (results):

**Comment by colleenXu** [comment]
deleted my comment above, to say here....

I think the initialQEdgeID / initialQNodeIDToMatch is taking the "first" QEdge of that object, as its starting point. And this is an issue for the base query, since that QEdge happens to be "in the middle" - without IDs on either QNode....

This would mean that the QEdge execution isn't the issue....

**Comment by colleenXu** [comment]
I find it easier if each edge has a name, like A (n0 -> n1) / B-flip (n2 --> n1) / C (n2 -> n3)....and then reorder them to make the diff QGraphs. 

<details>
<summary>The base query then is B-flip / C / A</summary>

```
{
  "message": {
    "query_graph": {
      "edges": {
        "B-flip": {
          "subject": "n2",
          "object": "n1"
        },
        "C": {
          "subject": "n2",
          "object": "n3"
        },
        "A": {
          "subject": "n0",
          "object": "n1"
        }
      },
      "nodes": {
        "n0": {
          "ids": ["UBERON:0002107"],
          "categories": ["biolink:GrossAnatomicalStructure"]
        },
        "n1": {
          "categories": ["biolink:DiseaseOrPhenotypicFeature"]
        },
        "n2": {
          "categories": ["biolink:Gene"]
        },
        "n3": {
          "ids": ["NCBIGene:211"],
          "categories": ["biolink:Gene"]
        }
      }
    }
  }
}
```
</details>

* Edge execution: A, then C (reversed), then B-flip.
* initialQEdgeID: B-flip, initialQNodeIDToMatch: n1

<details>
<summary>The working query then is A / B-flip / C</summary>

```

  "message": {
    "query_graph": {
      "edges": {
        "A": {
          "subject": "n0",
          "object": "n1"
        },
        "B-flip": {
          "subject": "n2",
          "object": "n1"
        },
        "C": {
          "subject": "n2",
          "object": "n3"
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "UBERON:0002107"
          ],
          "categories": [
            "biolink:GrossAnatomicalStructure"
          ]
        },
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        },
        "n2": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n3": {
          "ids": [
            "NCBIGene:211"
          ],
          "categories": [
            "biolink:Gene"
          ]
        }
      }
    }
  }
}
```
</details>

* Edge execution: C (reversed), A, B-flip
* initialQEdgeID: A, initialQNodeIDToMatch: n0

---

Other queries that work:
* A / C / B-flip (ends up with same behavior as working query): 
    *  Edge execution: C (reversed), A, B-flip
    * initialQEdgeID: A, initialQNodeIDToMatch: n0
* C / A / B-flip:
    *  Edge execution: A, C (reversed), B-flip
    * initialQEdgeID: C, initialQNodeIDToMatch: n3
* C / B-flip / A (same as the one above):
    *  Edge execution: A, C (reversed), B-flip
    * initialQEdgeID: C, initialQNodeIDToMatch: n3
    
Other query that doesn't work:
* B-flip / A / C:
    * Edge execution: C (reversed), A, then B-flip.
    * initialQEdgeID: B-flip, initialQNodeIDToMatch: n1

**Comment by colleenXu** [comment]
(deleting comments and summarizing here)

TDLR: the pattern I found by trying out permutations (comment above) is that the initialQEdgeID / initialQNodeIDToMatch is taking the "first" QEdge of the set of QEdges as its starting point. 

And this is an issue for the base + other-not-working query, since that QEdge is "in the middle" of the QGraph - without IDs on either QNode....

In comparison, the working queries are taking QEdges at the "ends" of the QGraph as their starting point, and they can set initialQNodeIDToMatch to the QNode that has an ID on it (n0 or n3).

From what I can tell, the "QEdge execution order" isn't causing this problem.

**Comment by tokebe** [comment]
I've written an experimental replacement for the `initialQNodeIDToMatch`/`initialQEdgeID` selection code, and it seems to have solved the problem. In both the base and working query it selects edge C (the edge with 4 records) and `n3`, and in both cases returns the same number of nodes/edges/results.

This code is somewhat thrown together and operates on a few assumptions; I'll be re-writing it for readability and efficiency and then will make a PR with a list of assumptions made so we can make sure it's not missing anything from the previous implementation.
