### ISSUE TITLE
Simplify/shorten console logs where applicable

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#436]
With the closing of https://github.com/biothings/BioThings_Explorer_TRAPI/issues/328, it's worth creating a separate issue outlining an objective to simplify and shorten console logs, which often aren't particularly readable, and sometimes take up a lot of space.

This would be best covered by each dev taking a look at their own areas of expertise in the codebase and simplifying what they can, however a dedicated pass by someone with a fresher view of code execution may help to remove some of the logs which have just become 'noise'.

This isn't just a case of removing unnecessary logs and shortening others, however; It's also worth taking stock of some internal information that would be useful to have during execution for debugging, especially summaries of different stages of execution.

**Comment by tokebe** [comment]
Closing as this issue is more of a broad coding goal than a specific issue to be addressed. Additional concerns can be addressed case-by-case.

Tagging @colleenXu in case their opinion is that this should be re-opened (or a new issue with specific changes be made)

**Comment by colleenXu** [comment]
I'm fine with closing this for now
