### ISSUE TITLE
implement TidBit 2 as a notebook 

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#44]
Tidbit 2 https://ncats.nih.gov/tidbit/tidbit_02.html was highlighted in the orientation slides as something Translator should be able to do.  Seems well aligned with BTE capabilities.  Would be great to create a notebook to demonstrate this use case

https://github.com/biothings/biothings_explorer/tree/master/jupyter%20notebooks

Can probably also look through the other tidbits for other example notebooks...

**Comment by kevinxin90** [comment]
Available at: https://github.com/biothings/biothings_explorer/blob/master/jupyter%20notebooks/TIDBIT%2002%20Finding%20New%20Uses%20for%20Existing%20Drugs%20to%20Treat%20Parkinson%E2%80%99s%20Disease.ipynb

**Comment by kevinxin90** [comment]
Note:
This query is huge and time-consuming. 
PD is not a rare disease. It has 475 unique genes associated with it and then a total of 11391 chemicals associated with these genes.
