### ISSUE TITLE
Error: "TypeError: Promise.allSettled is not a function"

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#44]
On initial installation in WSL, I got the following error when executing a test query: "TypeError: Promise.allSettled is not a function"

**Comment by andrewsu** [comment]
Per consultation with @kevinxin90, nodejs version needs to be at least v12.  I had v10.19.0 (default from `sudo apt install nodejs`).  Upgraded to v14.15.4 (latest LTS release) using `nvm` instructions at https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2

**Comment by andrewsu** [comment]
@kevinxin90 should we update the version information in the README? https://github.com/biothings/BioThings_Explorer_TRAPI/blob/master/README.md#node

**Comment by kevinxin90** [comment]
Yes. It's currently documented in the development branch: https://github.com/biothings/BioThings_Explorer_TRAPI/blob/development/README.md. I will merge it to master soon.
