### ISSUE TITLE
investigate addition of SPOKE to BTE config file

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#447]
Currently, BTE does not issue subqueries to SPOKE.  Given [SPOKE's SmartAPI entry](https://smart-api.info/registry?q=7f70cdfaeb801501da08dacc294e8b9f) it should be as simple as adding an entry to our [config.js file](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/routes/v1/config.js).  Creating this ticket to track discussion around feasibility/desirability. 

Similar to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/377...

**Comment by colleenXu** [comment]
Closing; track in https://github.com/biothings/biothings_explorer/issues/865#issuecomment-2372978205 and later issues instead
