### ISSUE TITLE
allow BTE to consume ReasonerStdAPI resources

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#45]
Create a generic transformer that allows BTE to ingest data from APIs that implement both the BiolinkModel and the ReasonerStdAPI.

Q: What resource currently exists that we can import? Robokop? RTX?

**Comment by kevinxin90** [comment]
This feature is implemented in a0149bc371ac7b5314e22fa1c7de3606c830cdc1

**Comment by kevinxin90** [comment]
Currently, BTE is able to consume the ROBOKOP API developed in the translator program. And the infrastructure of BTE could integrate any API implementing ResasonerStdAPI in the future.
