### ISSUE TITLE
update BTE UI to use node types and predicates from BioLink Model

### ISSUE THREAD

**Issue by khanspers** [biothings/biothings_explorer#452]
The BTE UI (https://biothings.io/explorer/advanced) doesn't have SmallMolecule as a node type. The closest is ChemicalSubstance but it doesn't seem to work the same way.

**Comment by andrewsu** [comment]
Yes, this seems to indicate that the BTE UI linked above is drawing from a hard-coded list of node categories instead of reading from the biolink model (https://github.com/biothings/biolink-model.js or https://github.com/biolink/biolink-model).  I will update the title of this issue accordingly...

**Comment by ericz1803** [comment]
Fixed.

**Comment by ericz1803** [comment]
Relevant commits:
https://github.com/biothings/bte_schema_web_react/commit/77994e6ac6c2d23f694d7969f84fc4be681c863e
https://github.com/biothings/biomedical-id-autocomplete.js/commit/90b6d52c687189fc19ce3b70860fdd2b112c5ee0
