### ISSUE TITLE
update how we generate /meta_knowledge_graph endpoints

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#454]
### Issues:
* The `nodes` section doesn't seem to match the actual smartapi edges / x-bte annotations (ID prefixes and biolink semantic types) for each kind of endpoint (general, api-specific, team-specific). 
    * Maybe we want this to instead be specific to the smartapi edges (IDs / semantic types) available to each endpoint 
    * Maybe the ID prefixes don't have to match what's in the smartapi edges...maybe it can match what's in the Node Normalizer? (but that seems riskier since Node Normalizer won't necessarily have the cross-mappings)  
* Maybe review: is the edges section accurate to the actual smartAPI edges for each kind of endpoint?

### Quick code check:
The [meta_knowledge_graph](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/routes/v1/meta_knowledge_graph_v1_by_api.js) endpoint (using by-api but this applies to all 3 types) seems to use this [controller](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/controllers/meta_knowledge_graph.js), which [uses this hard-coded file](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/controllers/ids.js). I think this hard-coded file is outdated (based on the old way of doing ID resolution, before using Node Normalizer). 

Note that I have a spreadsheet that might make comparing x-bte annotation to the /meta_knowledge_graph easier: https://docs.google.com/spreadsheets/d/1XY4RzytqKT2prJ4UYSsW4FlFGmGmhs_NrjMkmvoAYSE/edit?usp=sharing

---

### Example: 
MyVariant through BTE. Make a GET request to `http://localhost:3000/v1/smartapi/09c8782d9f4027712e65b95424adba79/meta_knowledge_graph`

The nodes section does not match the [actual x-bte annotation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/865938bd54c2717f3372949e3a0ccdd1948e3e87/myvariant.info/openapi_full.yml#L452) (which becomes smartAPI edges). There are no operations to Transcripts, SmallMolecules, Drugs, etc. Also no operations use "name" or "SYMBOL" as the ID prefix

Listing the node semantic types / ID prefixes based on the x-bte annotation:
* `Gene`: NCBIGene, ENSEMBL
* `Disease`: DOID, OMIM
* `SequenceVariant`: DBSNP

Listing the edges based on the x-bte annotation:
* `Gene` affects `Disease`
* `Disease` affected_by `Gene`
* `SequenceVariant` affects `Disease`
* `Disease` affected_by `SequenceVariant`
* `SequenceVariant` is_sequence_variant_of `Gene`
* `Gene` has_sequence_variant `SequenceVariant`
* `Gene` related_to `Disease`
* `Disease` related_to `Gene`
* `SequenceVariant` related_to `Disease`
* `Disease` related_to `SequenceVariant`

**Comment by colleenXu** [comment]
more notes after group meeting (also edited the opening post above):

* `/meta_knowledge_graph` `nodes` section seems to be the same between endpoints (and between different teams / apis in those specific endpoints). This is a sign that something "hard-coded" is going on.
* larger issue: are we still using "old biomedical id resolver stuff" like this ids.js file in this repo? Are we still using "old biomedical id resolver stuff" in other repos? does the actual biomedical-id-resolver module use any of the old code?
* larger issue: the by-apis and by-team endpoints have been refactored....but it's not clear if they're fully updated (threading?). Mentioned by @tokebe

**Comment by tokebe** [comment]
The `/meta_knowledge_graph` endpoints can probably do without threading as they're typically a lighter workload and shouldn't hang up the server, though it might be prudent to make them threaded. I'll have to investigate more on any other possible things we'd have to do, such as tying in behavior fixes from #448 when it's finished.

**Comment by colleenXu** [comment]
@tokebe the following /meta_knowledge_graph endpoints can kinda hang...
* `v1/meta_knowledge_graph`: currently it might have all of the metaEdges that BTE has access to with its v1/query endpoint (so the API_LIST - which includes TRAPI and x-bte annotation stuff). 
    * note the TRAPI policy here https://github.com/NCATSTranslator/ReasonerAPI/pull/320/files
* `v1/team/Service Provider/meta_knowledge_graph`: basically all the x-bte annotation stuff

**Comment by colleenXu** [comment]
@tokebe perhaps this can be an issue for the interns (Listing the node semantic types / ID prefixes correctly based off the MetaEdge info  - from x-bte annotation in most cases, but also from TRAPI stuff for the v1/query endpoint)...

I think using MetaEdge info only (not adding the prefix lists that are in SRI Node Normalizer) may be better - since cross-mapping between prefixes / namespaces isn't always done.

**Comment by rjawesome** [comment]
I have checked the code: Right now it is using ids.js for the nodes section. I suppose the intended behavior is that the nodes correspond to all nodes that are contained in the MetaKG operations?

**Comment by colleenXu** [comment]
yeah....the idea is for it to do something else (not the ids.js...)

**Comment by rjawesome** [comment]
From what I understand, for TRAPI APIs, the metakg edges are derived from predicates.json (in the Sync/AsyncOperationsBuilder), which currently contains no information on the ID prefixes. I was thinking of changing predicates.json to include this info, but that would also require changing the operation builders in smartapi-kg and potentially changing the structure of predicates.json. Is there some better way of getting this info or should I go with this course of action?

**Comment by rjawesome** [comment]
Should be fixed with the new commits/PRs. Also, just a note I found out there were a few ID prefixes from TRAPI which were the same except for some numbers, is this expected?
```
"FDBN00034",
"FDBN00002",
"FDBN00020",
"FDBN00014",
"FDBN00013",
"FDBN00021",
"FDBN00006",
"FDBN00024",
"FDBN00031",
```

**Comment by colleenXu** [comment]
@rjawesome @tokebe I haven't tested yet, since I made some posts in the bte-trapi PR asking for discussion. 

For the post [above](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/454#issuecomment-1198662807), it looks like some APIs putting incorrect information in those sections (those look like some kind of food database's IDs...). We don't want to remove all id-prefixes that don't quite fit the biolink-model (since even our KPs have some that aren't in the biolink-model yet), but we probably would want to remove stuff like that (pending the discussion stuff I've brought up...)

**Comment by colleenXu** [comment]
Coping text from [here](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/471#issuecomment-1216053607):

> Summarizing the discussion around sub-querying TRAPI KPs:
> * Current: uses the primary ID for QNode entities (from Node Normalizer output). 
>     * The assumption: TRAPI KPs have some ID-cross-mapping ability (using Node Normalizer or some internal tool), so BTE can give the TRAPI KPs the primary ID (highest priority in the id_prefixes list for that semantic type, according to Node Normalizer and biolink-model). 
> * Was proposed in discussion [here](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/471#issuecomment-1200087282): when generating MetaEdges/operations for the TRAPI KPs, take the subject/input semantic type or each MetaEdge and assign the ID prefix. The ID prefix would be the first element of the semantic type's id_prefix list in the `nodes` section of TRAPI-KP's `/meta_knowledge_graph` response.  
>     * The assumption: TRAPI KPs maybe need specific ID-namespaces for their queries. They advertise their preferences (which may not follow the biolink-model's ordering and may prefixes that aren't in the biolink-model id_prefixes lists) in the `nodes` section of their `/meta_knowledge_graph` response
> 
> However, Andrew and I decided today that the proposed change wouldn't change the final sub-queries that much (right now) and the benefits of this change are unclear / not much. 
> * CHP would likely benefit, since it may not be handling ID cross-mapping internally (with Node Normalizer or another tool). However, it has other issues (like requests to /meta_knowledge_graph endpoint timing out half-the-time...)
> * COHD seems to match the biolink-model id_prefixes lists 
> * Automat APIs likely use Node Normalizer (or have some internal tool for ID cross-mapping)
> 
> So we decided that the proposed change doesn't have to be a separate issue right now. The discussion here can be revisited if it's useful...
>

**Comment by colleenXu** [comment]
also addressed by https://github.com/biothings/smartapi-kg.js/pull/56
