### ISSUE TITLE
Stall handling for async jobs

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#455]
It would be of benefit to save some information about async queries which result in failure due to stalling.

The most important things we can get from any failed job:

- Who sent it?
- What was the query?

While it might make sense to make a cron job which dumps stalled jobs to the disk once per day, or to leverage [bull's stalled event](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#events), given that bull rather neatly stores and organizes stalled jobs for us (and that we don't want to unnecessarily duplicate these in either memory or disk, for efficiency's sake), it makes sense to write a script which can be called from the workspace to pull recent stalled jobs (perhaps from the last 24 hours?) into a file on-demand, which can then be copied for review and deleted on the server to avoid taking up space.

**Comment by colleenXu** [comment]
feel free to move this around in the biothings project (I may not have put it in the right spot)

**Comment by tokebe** [comment]
This issue can be rolled into #479 as a secondary objective.
