### ISSUE TITLE
A high-level complete sequence diagram of BTE

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#456]
It would be very useful both for debugging and for new developers to have a high-level sequence diagram for BTE's query handling, either of the general sync endpoint or just starting from the `query_graph_handler`.

Optimally, this diagram would establish an explanation of the flow of data between each of the primary handler classes, grouped by file/module. Exact methods needn't be documented however the data structures/types (using the [new vocab](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/379)) moving between each handler should be annotated.

Making this diagram would entail stepping through the entirety of the lifecycle of a request, following all major data structures as they are created or obtained, and carefully organizing the diagram to display the module-handler hierarchy and how it interacts in the lifecycle of a request.

https://mermaid-js.github.io/mermaid/#/sequenceDiagram seems like a good tool to do this using markdown so it can be version controlled

**Comment by colleenXu** [comment]
feel free to move this around in the biothings project (I may not have put it in the right spot)

**Comment by tokebe** [comment]
Resolved by #491

**Comment by colleenXu** [comment]
Comments from 8/17 group meeting:

initial Feedback: 
* make clear where the files are / when a module is being used
* Color? (issues with dark mode / browser extensions like darkreader?)
* It's awesome

Related sub-diagrams for specific behaviors:
* How we do the cron job, make MetaEdges (this is outside the scope of how-a-query-works workflow)
* How different modules work (call-apis, api-response-transform but this will be refactored??, biomedical-id-resolver)
* How caching works
