### ISSUE TITLE
Disease / PhenotypicFeature conflation 

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#462]
Translator hasn't made a decision on conflating `Disease` and `PhenotypicFeature` yet (basically the same as replacing them both with their parent `DiseaseOrPhenotypicFeature`). 

However, there have been multiple times where it would have been useful to bundle them together:
* Treat a query-graph QNode with the `"categories": ["biolink:Disease"]` or `"categories": ["biolink:PhenotypicFeature"]` as `"categories": ["biolink:DiseaseOrPhenotypicFeature"]` instead. [Example](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/444)
* There's a QNode with an ID: if the NodeNormalizer says this is a Disease or a PhenotypicFeature, treat it as a DiseaseOrPhenotypicFeature instead. 

Note: check that set operations are done so there aren't repeated semantic types in the operations / metaEdge lookup.

This is similar to #319, but bigger in scope because we cannot rely on the NodeNormalizer to "conflate" these for us.

**Comment by colleenXu** [comment]
Note (would open another issue if we decide it): we may also want to conflate SmallMolecule / Drug (and Polypeptide) -> and make them go up to ChemicalEntity...

**Comment by rjawesome** [comment]
I believe I have a solution for this issue (worked on the example query you have provided), however I am not sure if I can open a PR on the repository since I already have an open PR on https://github.com/biothings/bte_trapi_query_graph_handler/ (https://github.com/biothings/bte_trapi_query_graph_handler/pull/105)

**Comment by andrewsu** [comment]
@rjawesome fyi you can create multiple PRs by creating multiple local branches.  See for examples some of the answers at https://stackoverflow.com/questions/8450036/how-to-open-multiple-pull-requests-on-github...
