### ISSUE TITLE
creative-mode: add TRAPI-log on final number of scored results 

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#466]
Right now, the execution of each template will have a log in the TRAPI response `logs` section that looks like this:

```
        {
            "timestamp": "2022-07-13T19:03:40.626Z",
            "level": "DEBUG",
            "message": "[Template-0]: Successfully scored 1052 results, couldn't score 1 results.",
            "code": null
        },
```

It's pretty useful, but creative-mode can involve merging result-sets from different templates. 

It's then hard to tell how many of the final results (after this merge) have non-zero scores ("successfully scored"). It would be nice to have that as one of the final logs in the execution of creative-mode. 

Optional:
* May also be nice to report how many answers were "merged". At the moment, I calculate it by adding the number of results for each template and then subtracting the number of results in the final set (and I think that's accurate but maybe I'm doing simple math wrong...)

**Comment by tokebe** [comment]
This should be pretty straightforward to implement thanks to an extra feature of the `LogEntry` class. You can attach a nearly-arbitrary data object to LogEntries, requiring only a `type` property. For the LogEntry that generates this log, `type: "scoring"` and some attribute to count the number scored/not scored can be added. See [this example](https://github.com/biothings/call-apis.js/blob/30ab1d380ecd4397e713b5d1d4ebd59cf54623fc/src/query.js#L115-L126).

From there, that data can be used in the [`createSummaryLog()` method](https://github.com/biothings/bte_trapi_query_graph_handler/blob/72151319c5a33cd8e61e26594b0994d196111d00/src/index.js#L549-L582) in query_graph_handler to generate a summary of all results scored/not scored.

**Comment by tokebe** [comment]
Resolved by https://github.com/biothings/bte_trapi_query_graph_handler/pull/114
