### ISSUE TITLE
Respect canonical predicate direction

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#476]
Most details in #475. Currently, BTE responds using query direction. If it's not overly complicated, we should assemble our response to use the Biolink canonical direction for predicates.

**Comment by colleenXu** [comment]
Copied from internal Slack:

> Jackson: BTE is supposed to respond in canonical direction, but currently just responds in query direction. This means that we must have canonical templates until we can start assembling responses in canonical direction, which is a relatively low-priority fix.

> Andrew: Identified by Tyler at today's standup meeting. Agreed that this is a low priority issue, and that the simple change of adjusting the creative mode templates is more than sufficient for the moment...

> Colleen: I'm providing what I remember as the reasons why we decided not to bother with “always return canonical predicates”.
> I remember it as being a super confusing/hard problem.

---

Colleen

> we previously decided not to care about canonical predicate direction since it could mean that some KG Edges are in opposite directions of the corresponding QEdge. Which makes results binding and edge-directionality all sorts of messed-up

> At least…that's what I remember? Theoretically people won't give QEdges that result in non-canonical predicates. However, I doubt that the situation I described above never happens. Like if you ask for Gene X -> Disease (no predicate). Is it true that the KG Edges (part of answers/results) will only be canonical predicates? I think it could easily be non-canonical predicates if one has to stick to that QEdge direction (Gene X affected_by Disease Y)

> Plus. The flipping of some Edges to fit canonical predicates….would it negatively affect the ability to go from one hop to another (confusing input with output, subject with object) ?

> One way I can see “canonical predicate only” responses code working is if:
> 1. We do it at the end (like maybe after result assembly). That would allow our current code to do its thing without bugs / worrying about flipping records / edges
> 2. We could process the biolink-model and have an object where the keys are non-canonical predicates and the values are the inverses (the canonical predicates)
> 3. Then go through all the KG Edges. If the predicate for a KG Edge is a non-canonical predicate (matches a key), replace it with the canonical predicate (value) AND flip the subject and object of the Edge.
>
> I think this allows us to mutate any Edges with the canonical-predicate problem without adversely affecting query execution/results assembly

Andrew:
>  Colleen, I think your other notes here are about how we enforce using canonical predicates, regardless of what's stated in the query?  If yes, this is a very very very low priority at the moment.  Feel free to add notes to #476 that Jackson created, but I don't think we need to discuss/brainstorm further until we actually get around to addressing it.  Please correct me if I'm missing something...

**Comment by colleenXu** [comment]
This might need some refactoring due to the qualifier issue https://github.com/biothings/BioThings_Explorer_TRAPI/issues/512#issuecomment-1268698108.

Talked with Andrew about it and we agreed to put it aside for now

**Comment by colleenXu** [comment]
From Jackson / me convo 2022-10-19:
* Jackson is keeping this in mind with development and qualifier feature stuff
* having edge-attributes for the original subject/object names and relationship could be useful when we move to canonical directions. This can be through x-bte annotation, but coding could provide original subject/object IDs and biolink-model predicates...

**Comment by tokebe** [comment]
Our policy is that we'll respect whatever direction we're given; In terms of Translator requirements: We'll never receive a non-canon direction request, so we'll never return a non-canon direction answer.
