### ISSUE TITLE
Stats tracking?

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#479]
We could make use of Redis to store information about requests received by BTE, which in aggregate might be useful in future development/bug fixing. These stats could be accessible via a new GET endpoint returning a simple JSON summary. Obviously, we'd only want to keep anonymous and computationally useful stats, such as request counts, rather than request sources or anything like that. Some potentially useful values we could calculate:

- Concurrent sync request high water mark
- Rolling Average requests per hour/day (broken up by sync/async?)
- Usage of by API/team vs. general endpoints
- Average request processing time
- Request processing time high water mark
- Request failure rate (possibly comparing invalid requests to server error failures)
- Average number of resources queried per request (possibly by API to see who we hit hardest?)

We could also theoretically try to keep a log of request error messages so that we can try to determine things that might be breaking before they are reported by users.

I'm also sure there are other potentially useful stats we could track that I'm not thinking of at the moment. This issue also assumes that we'd be accessing data through a publicly-available endpoint for ease-of-implementation, but there may be stats or logs that could be useful to be able to access through a secure endpoint? I haven't thought about that much.

**Comment by rjawesome** [comment]
I've started work on the stats-tracking branch of this repo. Right now it logs # of successful, failed (server), and failed (user) requests. Please let me know if you have any feedback for the code.

**Comment by tokebe** [comment]
Looks good so far, very clean use of middlewares, though I believe you might want to hook the middleware through the response `finish` event rather than overriding the `end` method.

This issue can take lower priority than anything else you might have on your plate. Priorities within this issue I would say are definitely the Concurrent sync request high water mark and rolling average of requests per day on sync vs. async endpoints, followed by whatever seems easiest to implement from there.

**Comment by rjawesome** [comment]
Alright, right now I've coded up a concurrent request counter. For now I am just hooking it to when a request starts/ends in the middleware (see latest commit). Is that fine or do I need to modify it so it only considers the sync requests or specific types of requests?

**Comment by tokebe** [comment]
The hope was to be able to compare sync to async usage, so you might want a separate middleware for that one.

**Comment by rjawesome** [comment]
> The hope was to be able to compare sync to async usage, so you might want a separate middleware for that one.

Does the other statistics, such as request failure rate, also need to be localized for sync/async

**Comment by tokebe** [comment]
No, only the two in the original post that mention sync/async need to be broken up that way.

**Comment by rjawesome** [comment]
I did most of these although the last one "Average number of resources queried per request" requires a changes query_graph_handler as well (I will make that shortly and push commits for both repos in stats-tracking branch)

**Comment by tokebe** [comment]
Rolling the now-closed #455 as a secondary objective after the initial issue has been addressed. The endpoint used to retrieve stats could also check the Bull queues for failed queries, providing an array of links to their respective queries so the query graphs could be analyzed. Only non-expired queries would be required, limiting the length of the array to failed queries in the last week.

This secondary objective can safely be ignored for now.

**Comment by tokebe** [comment]
Superseded by #662
