### ISSUE TITLE
SRI testing harness data

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#481]
Cut from https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450#issuecomment-1176496343. 

[Add test_data_location in x-trapi](https://github.com/NCATSTranslator/ReasonerAPI/pull/339/files). Would be mostly a Colleen thing. This is [optional in the schema](https://github.com/NCATSTranslator/translator_extensions/pull/17#issuecomment-1175589830). However, it's related to the [SRI testing harness](https://github.com/TranslatorSRI/SRI_testing/tree/main/tests/onehop#configuring-the-tests) and
* [ ] TAKES A WHILE: building the test files for "one triple of each type that the KP can provide" for Service Provider (and maybe Multiomics / Text-Mining too)
* [ ] the test file for the BTE ARA is easy to update, but would need to be kept up-to-date with the API_LIST variable in the BTE's config. EDIT: good [example](https://github.com/NCATSTranslator/ReasonerAPI/pull/339#issuecomment-1241033700) of an ARA test file
* [ ] add x-trapi.test_data_location to TRAPI registrations (BTE and Service Provider)

**Comment by andrewsu** [comment]
In the [implementation tracker](https://docs.google.com/spreadsheets/d/1LEV3FyXBt3xm4bC5TQkVbrZalrr6OV2LnPtuLj1RVB4/edit#gid=1034097652), this now has an implementation date of today. Very few teams have completed this so I don't think we're "late", but internally let's shoot for initial "completion" by 2022-10-11.  For an initial implementation, let's create test data for the following three records:
* mygene.info: BRCA2 (NCBIGene:675) related_to Breast/Ovarian Cancer (MONDO:0012933) (source: http://mygene.info/v3/gene/675?fields=clingen)
* mychem.info: imatinib (InChIKey:KTUFNOKKBVMGRW-UHFFFAOYSA-N) treats CML (MESH:D015464) (source: http://mychem.info/v1/chem/KTUFNOKKBVMGRW-UHFFFAOYSA-N?fields=chembl)
* bioplanet: TP53 (NCBIGene:7157) participates_in Cell cycle progression regulation by PLK3 (bioplanet:bioplanet_68) (source: https://biothings.ncats.io/bioplanet_pathway_gene/association/bioplanet_68-7157)
 
More documentation is provided in the parent issue https://github.com/TranslatorSRI/SRI_testing/issues/56.

**Comment by andrewsu** [comment]
link to be added to Service Provider KP smartAPI registration here https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/biothings_explorer/service-provider-trapi.yaml#L29; pointing to new file in that same repo/folder
* also need to ask Multiomics and Text mining providers to add example records to the same document

**Comment by colleenXu** [comment]
Info here on the JSON structure https://github.com/TranslatorSRI/SRI_testing/tree/main/tests/onehop#configuring-the-tests

I don't really understand the "exclude_tests" optional field https://github.com/TranslatorSRI/SRI_testing/tree/main/tests/onehop#excluding-tests

**Comment by colleenXu** [comment]
The initial task outlined by Andrew's post is [done](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/481#issuecomment-1267535764). The test data is [here](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/biothings_explorer/sri-test-service-provider.json) and the test_data_location field has been [added](https://github.com/NCATS-Tangerine/translator-api-registry/commit/8be63355313ae1ae41aad7b7de499aae0f1b7cce). 

Notes: 
* I added fields to make it clearer where the edge/record came from (`underlying_api_infores` and `underlying_source_infores`) and what entities are involved (`subject_name` and `object_name`)
* I used the "raw" link for the test_data_location field, but it's not clear if the SRI testing harness would prefer the non-raw [link](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/biothings_explorer/sri-test-service-provider.json)

**Comment by andrewsu** [comment]
closing this as our initial implementation is done.  We can do more when/if the rest of the consortium moves forward on this.
