### ISSUE TITLE
scrolling POST-queries to retrieve all hits (pending biothings apis only for now)

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#483]
From 8/3 and 8/10 lab meetings on Translator

with_total Implemented in [this PR](https://github.com/newgene/biothings.api/pull/52)
Yao: deployed for biothings API ("pending APIs") at biothings.ncats.io. Not on core apis (My…dot info), waiting to see how the pending goes…

idea is to use this so we can retrieve all hits for all query-terms when doing a batch-query/POST request. 

---

(Jackson's plate of work?)

WAIT A SEC: 
* with_total gives you the largest number of matching hits for a query-term in the batch-query. (when we batch-query, we send up to 1000 query-terms and each query-term gives up-to 1000 matching hits). 
* So if the response's max_total > 1000, we know to do scrolling. (Set from=1000, then 2000, then 3000…)

With_total - could be in parameters section or request body? Try it out. CX prefers parameters a LOT since request body has a lot of stuff in it

Query-builder for biothings APIs (pending only)
* Could add with_total: true parameter to the queries it sends out (no need for x-bte annotation)
* Would be able to do above logic / scrolling behavior
* Works only on x-bte annotation that usesTemplating: true

---

Examples / limited set of pending APIs with this issue? APIs that have >1000 capping issues: Semmeddb, pfocr, multiomics drug response kp api (all use templating)

So…another reason to update x-bte annotation so they all use templating

**Comment by tokebe** [comment]
Completed: merged and deployed to all live instances
