### ISSUE TITLE
change operation listed in workflow section of response

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#485]
BTE's response has a workflow section, that currently looks like this. 

```
{
    "workflow": [
        {
            "id": "lookup"
        }
    ],
    "message": {
        "query_graph": {.....},
        "knowledge_graph": {...},
        "results":[...]
    },
    "logs": [...]
```

We want to change this "lookup" to "lookup_and_score" since that's what we're currently doing. (Internal lab [Slack](https://suwulab.slack.com/archives/CC218TEKC/p1660158191053599), internal Translator [Slack](https://ncatstranslator.slack.com/archives/C01D1V8G4PN/p1658864279438009?thread_ts=1657566687.648659&cid=C01D1V8G4PN), [translator SmartAPI extensions](https://github.com/NCATSTranslator/translator_extensions) (CTRL-F for operations))

Like below:

```
{
    "workflow": [
        {
            "id": "lookup_and_score"
        }
    ],...
```

**Comment by rjawesome** [comment]
The two PRs combined should fix the issue

**Comment by colleenXu** [comment]
and this commit is related https://github.com/biothings/BioThings_Explorer_TRAPI/commit/743cce092e680376de2973a5daa3535c32ac4f4e

**Comment by colleenXu** [comment]
Note these commits / PRs were reverted because the TRAPI validator used by ARAX's UI was marking this as "not TRAPI 1.2 compliant". 

It turns out that the TRAPI spec (1.2 and 1.3) hadn't included an updated link to the workflow operations specification. This fix was added to TRAPI 1.3 (after the release of 1.2.0-beta). (see https://github.com/NCATSTranslator/ReasonerAPI/issues/357). 

It's not clear when ARAX's UI will use a TRAPI 1.3 validator that has these latest fixes...so we can advertise / use "lookup_and_score". So we'll reopen this issue, but leave it on-hold...

**Comment by colleenXu** [comment]
We got confirmation from Eric Deutsch (TRAPI group) that it'd be appropriate to make this change ([Translator Slack link](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1711467503655459)). 

While it's not directly related to TRAPI 1.5, both involve updating the SmartAPI yamls - so I think they could go together?

Notes 
* I think we should be able to do this, because the previous blocker (TRAPI spec/validator issue) should have been fixed by now https://github.com/biothings/biothings_explorer/issues/485#issuecomment-1230906958
* may affect the CQS template https://github.com/TranslatorSRI/CQS/pull/9?

**Comment by tokebe** [comment]
@colleenXu Should BTE be advertising `lookup_and_score` alongside `lookup` in our MetaKG endpoint?

**Comment by colleenXu** [comment]
@tokebe 

Hmm...good point. I think we would for the "ARA" endpoint only (`v1/meta_knowledge_graph`)

So there's maybe 3 places to change `lookup` -> `lookup_and_score`:
* in the `v1/meta_knowledge_graph` response
* in "ARA" responses (`v1/query`) but I'm not sure how that'll work for the asyncquery responses
* in [BTE's SmartAPI yaml](https://github.com/NCATS-Tangerine/translator-api-registry/blob/afc909d427cd440038d9fa6cbfeab60f9de32999/biothings_explorer/smartapi.yaml#L23)

VS the "team-specific" and "api-specific" endpoints should still use `lookup`. If it's possible?

**Comment by tokebe** [comment]
Totally doable. Should even be possible to label `lookup_and_score` for async based on some job information.

**Comment by colleenXu** [comment]
@tokebe 

team and smartapi-specific /query (and /asyncquery) endpoints return `lookup_and_score` rather than `lookup`.

If we don't have time to fix this, I think it'd be fine not to include this in the deployments. 

Tested:
* all 3 meta_knowledge_graph endpoints: these work as-expected
* all 3 /query endpoints
* all 3 /asyncquery endpoints

**Comment by tokebe** [comment]
Whoops, missed a conditional. Fixed!

**Comment by colleenXu** [comment]
See the mentioned issue ⏫ . We are going to advertise lookup on all /meta_knowledge_graph endpoints instead.

**Comment by colleenXu** [comment]
The code was deployed today to Prod as part of the Octopus release. I tested and it's live.

However, we'll want to track https://github.com/biothings/biothings_explorer/issues/821 since it's a bug fix to this.
