### ISSUE TITLE
Deploy TRAPI 1.3

### ISSUE THREAD

**Issue by capasfield** [biothings/biothings_explorer#490]
https://arax.ncats.io/?smartapi=1 shows that Service Provider TRAPI and BioThings Explorer API have 1.2 in development (infores:service-provider-trapi and infores:biothings-explorer)

Please deploy 1.3 of these tools into development ASAP.

**Comment by colleenXu** [comment]
Both tools already have TRAPI 1.3 code deployed for their development instances (non-ITRB server). 

@andrewsu and @newgene have previously decided NOT to make new registrations for TRAPI 1.3 instances. Instead, we were planning to wait for TRAPI 1.3 deployment for all instances (all x-maturity levels), and then update our registration to advertise that all instances are on TRAPI 1.3

**Comment by colleenXu** [comment]
I notice that the 1.3 vs 1.2 test run that Mark Williams posted (internal Translator Slack [link](https://ncatstranslator.slack.com/archives/C013Q5TVC87/p1660681259430349)) is correctly using BTE's development endpoint and that endpoint is returning TRAPI 1.3 responses.

**Comment by colleenXu** [comment]
This should now be completed:
* TRAPI 1.2 instances have ITRB prod / test/ ci aka staging server urls. 
* TRAPI 1.3 instances have dev (non-ITRB) server url. 

 I'll attach screenshots from the arax dashboard below:
![Screen Shot 2022-08-17 at 4 17 59 PM](https://user-images.githubusercontent.com/43731687/185260272-d187877e-e669-44c3-8be5-04633d1ac932.png)

![Screen Shot 2022-08-17 at 4 18 08 PM](https://user-images.githubusercontent.com/43731687/185260278-9b44d0b1-463b-4b7d-88ab-55f210a1a325.png)
