### ISSUE TITLE
error on query -- TRAPI validation error

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#492]
Query from the Query of the Month call 2022-08-18

https://arax.ncats.io/?r=9f86f55e-b356-4be8-ab53-b6817ccc43c5

```
{
  "description": "InvalidQueryGraphError: Your Input Query Graph is invalid.",
  "logs": [
    {
      "code": "InvalidTRAPI",
      "level": "ERROR",
      "message": "TRAPI validator reported an error: 500 is not of type 'string'\n\nFailed validating 'type' in schema[0]:\n    {'description': 'One of a standardized set of short codes, e.g. '\n                    'Success, QueryNotTraversable, KPsNotAvailable',\n     'example': 'Success',\n     'type': 'string'}\n\nOn instance:\n    500",
      "timestamp": "2022-08-18T16:48:44.930804"
    }
  ],
  "message": {
    "knowledge_graph": {
      "edges": {},
      "nodes": {}
    },
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n0",
          "subject": "n1"
        },
        "e1": {
          "object": "n2",
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        },
        "n1": {
          "ids": [
            "NCBIGene:3605",
            "NCBIGene:10758",
            "NCBIGene:149233",
            "NCBIGene:26191",
            "NCBIGene:864",
            "NCBIGene:51561"
          ],
          "is_set": true
        },
        "n2": {
          "ids": [
            "UBERON:0002384"
          ]
        }
      }
    },
    "results": []
  },
  "status": 500,
  "validation_result": {
    "message": "TRAPI validator reported an error: 500 is not of type 'string'\n\nFailed validating 'type' in schema[0]:\n    {'description': 'One of a standardized set of short codes, e.g. '\n                    'Success, QueryNotTraversable, KPsNotAvailable',\n     'example': 'Success',\n     'type': 'string'}\n\nOn instance:\n    500 --- InvalidQueryGraphError: Your Input Query Graph is invalid.",
    "n_edges": 0,
    "n_nodes": 0,
    "provenance_summary": {
      "n_sources": 0,
      "predicate_counts": {},
      "provenance_counts": {}
    },
    "size": "1 kB",
    "status": "FAIL",
    "version": "1.2.0"
  }
}
```

(Will try to add more context/details later, but hopping to another meeting...)

**Comment by andrewsu** [comment]
also failing on https://arax.ncats.io/?r=457d390d-df3a-4d45-81e3-d3aa0bd8fbb6 for the same reason?

**Comment by colleenXu** [comment]
looks like the tool is down and is sending a 500 status code (when this happens, BTE's response isn't "TRAPI" and that's why the messages from the ARS? / ARAX? regarding TRAPI validation look odd.

**Comment by colleenXu** [comment]
should be fixed. was an issue with Node Normalizer (older [commit](https://github.com/biothings/biomedical_id_resolver.js/commit/7b624cf0e9d1ba0ff0b6577764cd78c45adffc45), newer [commit](https://github.com/biothings/biomedical_id_resolver.js/commit/0f71e871519f9b91e44234677797e565bebdef59) that was deployed.

This has been deployed in the development instance and CI [instance](https://github.com/biothings/bte-trapi-workspace/commit/ad56100e6bd6161b19a6462393c0d9ccebb5c56a). We're waiting for deployment on test/prod (have DM'd Link Brokers). 

ideally we'd have a more informative error message and would make clearer that this was an issue with Node Normalizer (I've noted in a scheduled Slack message too)

**Comment by colleenXu** [comment]
It's deployed on ITRB test and prod now. Closing the issue now...

**Comment by colleenXu** [comment]
This is the response I get from running locally. It took 52 seconds to run and has 127 results. 

[response.txt](https://github.com/biothings/BioThings_Explorer_TRAPI/files/9378744/response.txt)
