### ISSUE TITLE
profile and optimize id-to-object translation step

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#50]
In https://github.com/biothings/biothings_explorer/blob/master/jupyter%20notebooks/TIDBIT%2002%20Finding%20New%20Uses%20for%20Existing%20Drugs%20to%20Treat%20Parkinson%E2%80%99s%20Disease.ipynb, BTE seems to spend a lot of time right before the `After id-to-object translation, BTE retrieved 11391 unique objects` statement. More details from Kevin via slack:

> kevinxin  1 hour ago
> Yes. That’s very slow. It includes 1) query MyChem.info to do ID translation 2) After ID translation, merge and collapse duplicate nodes in networkx. This step could be optimized.
> 
> andrew  1 hour ago
> Do you have a sense on the relative time spent on those two steps?  I'm guessing the majority is spent on step 2?
> 
> kevinxin  1 hour ago
> That’s my guess too. Will do a time profiling on the code if that need to be prioritized.

**Comment by kevinxin90** [comment]
This step has been fully optimized in 6581f7dd415039ff9add2297ff596333981827b8
