### ISSUE TITLE
Refactor internal query graph representation

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#504]
Previously, API response records [were refactored](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/402) to streamline related code interactions and to simplify testing.

It appears that our internal representation of the query graph could use a similar treatment. Currently, the query graph (as supplied by the query) is validated and transformed into first `qNodes` and `qEdges`, and then `qXEdges` (query execution edges) are created as a "wrapper" of sorts around `qEdges`. Given the actual lifetime of a `qEdge` and limited use outside of being part of a `qXEdge`, I think it makes sense to roll the two into simply just a `qEdge`. 

Merging `qEdge` and `qXEdge` would simplify the structure and interface. Beyond this, however, refactoring the class along the lines of `Record` in order to allow freezing/unfreezing of an instance, where both the frozen and unfrozen data (and therefor class constructor) have the same structure and property names, would also dramatically simplify both testing and further development.

**Comment by rjawesome** [comment]
I could work on this. Some work started on combine-qedge branch (mega_query_edge.js is combined qedge/qxedge, is being used in query_graph.js).

**Comment by tokebe** [comment]
Deployed to Prod.
