### ISSUE TITLE
Improving API_LIST

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#519]
Our API_LIST behavior can be made more robust:

- Add support for infores IDs alongside smartAPI IDs.
  - In the event of a conflict between ID/infores, (e.g. infores in include and smartapi in exclude, or the reverse), smartapi ID takes priority
  - In any given include/exclude object, only one of either infores or smartapi ID must be specified, but one **must** be specified.
  - Match by either or both when matching to an API considered for inclusion/exclusion, in other words, it must match at least one.

**Comment by rjawesome** [comment]
Started on ``infores`` branch (smartapi-kg, query_graph_handlre)

**Comment by tokebe** [comment]
Deployed to Prod.
