### ISSUE TITLE
disable scoring for "KP endpoints" (by-api and by-team)

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#520]
We propose removing NGD scoring for by-api and by-team endpoints because they are primarily used as "KPs" (knowledge providers) by other ARAs. So it's not clear that the scoring is needed (more of an ARA function) - plus removing it would help lighten the load that the NGD scoring is dealing with. 

Then scoring (NGD stuff, future PFOCR stuff) would only need to be implemented on the v1/query (and v1/asyncquery) endpoints (which are used as an ARA). 

Chunlei and Andrew agreed with this.

(internal Slack link conversation)

**Comment by rjawesome** [comment]
See pull requests

**Comment by tokebe** [comment]
Deployed to Prod.
