### ISSUE TITLE
implement tidbit 4 as a notebook

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#53]
similar to #44, Tidbit 4 seems well aligned with BTE, might be useful to show as a demonstration.

https://ncats.nih.gov/tidbit/tidbit_04.html

**Comment by kevinxin90** [comment]
@andrewsu Seems this notebook is done through Medikanren. I did some basic research using BTE. Seems none of the resources in BTE (including SEMMED) shows any connection between NFE2L2 and PRDX1.

**Comment by kevinxin90** [comment]
But BTE does report an association between ASCORBIC ACID and NFE2L2

**Comment by andrewsu** [comment]
Does BTE return anything for the query `PRDX1 - [Gene] - [ChemicalSubstance]`?

**Comment by kevinxin90** [comment]
Yes. It will return results for the path.

**Comment by andrewsu** [comment]
It's a _very_ low priority at this stage, but a simple notebook that shows those results I think could be useful. But again, only if we've checked off everything else we wanted to accomplish...

**Comment by kevinxin90** [comment]
This jupyter notebook is available at [here](https://github.com/biothings/biothings_explorer/blob/master/jupyter%20notebooks/TIDBIT%2004%20Finding%20Marketed%20Drugs%20that%20Might%20Treat%20an%20Unknown%20Syndrome%20by%20Perturbing%20the%20Disease%20Mechanism%20Pathway.ipynb)
