### ISSUE TITLE
Mock API calls in tests

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#541]
A number of our tests use real-world API calls for integration testing. These calls should be mocked so they don't depend on external resources, which can fail either randomly or specifically because calls are coming from github automation.

This should be doable by creating a list of expected calls and then mocking them sequentially using Jest's ability to mock a function's return/resolve value, specifically for Axios in our case.

**Comment by rjawesome** [comment]
I've started mocking axios calls in call-apis.js. I will work on the other repos soon.

**Comment by rjawesome** [comment]
Currently working on BTE Trapi repo in mock-axios branch.

**Comment by tokebe** [comment]
Marking as completed, any additional changes can be tracked in new issues.
