### ISSUE TITLE
Refactor code to handle provenance edge-attributes for "primary knowledge" apis

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#549]
When @tokebe and I were reviewing the [PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/108#issuecomment-1376284759) for issue #463 , we noticed some issues with older code. 

This code was meant to address "situation C": non-TRAPI apis that are generating knowledge/inferred-associations from data and should therefore be labeled as "primary knowledge sources". They also do not provide their edge-attributes in TRAPI format (if the ydid, we could ingest their edge-attributes the same way we ingest edge-attributes from TRAPI APIs).

The desired refactoring is:
* rather than using a hard-coded list of API names (which can change as the API names change), add a property to APIs listed in the config API_LIST variable that says "this is a primary knowledge source"
* update the list of APIs fall under "situation C" (aka have the property in their API_LIST object mentioned above). There are only 3: LitVar, Multiomics EHR Risk, Multiomics Wellness
    * Note that some multiomics and text-mining APIs are NOT on this list because they provide their edge-attributes in TRAPI format: Multiomics BigGIM-DrugResponse, Multiomics ClinicalTrials, Text Mining Targeted
* Change the behavior: the `kgEdge.inforesCuries` (is this the infores of the API?) should be put into the value of a "primary knowledge source" edge-attribute along with the `kgEdge.sources`. Then there's a separate "aggregator knowledge source" edge-attribute with `infores:biothings-explorer` as the value.  

---

~Related: we want to discuss with @andrewsu if a BioThings API of a primary knowledge source then also counts as a primary knowledge source (maybe it doesn't because of the parsing / organizing of the data that happens?).~ 

Discussed with Andrew 2023-01-23. He said this is correct, that BioThings APIs usually are NOT primary knowledge sources because of the parsing / organizing of data that is done. So the small list above is correct (we only want those labeled as primary knowledge sources). 

<details>
<summary>Many BioThings APIs may be in this situation, like</summary>

* BioThings BindingDB
* BioThings GTRx
* BioThings Rhea
* BioThings SEMMEDDB
* BioThings DDInter 
* BioThings iDISK
* BioThings pfocr
* DISEASES

</details>

**Comment by tokebe** [comment]
The primary code changes would be in [knowledge_graph.js](https://github.com/biothings/bte_trapi_query_graph_handler/blob/358d8deef61c18322d539594117004b8fb2a4d44/src/graph/knowledge_graph.js#L87-L187), with some code in the query_graph_handler [index.js ](https://github.com/biothings/bte_trapi_query_graph_handler/blob/358d8deef61c18322d539594117004b8fb2a4d44/src/index.js#L499-L510)to pass the [API_LIST](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/config/apis.js) in.

**Comment by colleenXu** [comment]
@tokebe are you available to test Rohan's PRs to see if the issue is addressed?

**Comment by colleenXu** [comment]
This issue is related to the Translator priority of "having `primary_knowledge_source` set for each Edge". I'll review @rjawesome's PRs ASAP. 

First, I'll list my review of the current main-branch behavior:
* Multiomics Wellness KP API: 
    * it's the only one that uses the [current "situation C" code](https://github.com/biothings/bte_trapi_query_graph_handler/blob/358d8deef61c18322d539594117004b8fb2a4d44/src/graph/knowledge_graph.js#L87-L187) and still falls into the category of "situation C"
    * When I query it, I get Edges that **are missing a `primary_knowledge_source`** (see screenshot below). **So I'll be checking if this is fixed with the PRs.** 
* Litvar: 
    * the current behavior is fine - it has a `source` property in its x-bte annotation that's assigned as the `primary_knowledge_source` (dbsnp) while litvar itself is listed as an `aggregator_knowledge_source` (see screenshot below). **So I'll check the behavior with the PRs and probably remove the "primary knowledge source" tag for Litvar.**
* Multiomics EHR risk kp api (formerly clinical risk kp api):
    * because the name changed, BTE is incorrectly treating it as "not situation C". So when I query it, I get Edges that **are missing a `primary_knowledge_source`** (see screenshot below). **So I'll be checking if this is fixed with the PRs.**


<details>
<summary>current Multiomics Wellness KP Edge: missing primary</summary>

![Screen Shot 2023-03-09 at 12 45 40 PM](https://user-images.githubusercontent.com/43731687/224154860-3efa1218-baa8-403d-b0c5-ded70ef117a7.png)

</details>

<details>
<summary>current Litvar Edge</summary>

![Screen Shot 2023-03-09 at 1 00 15 PM](https://user-images.githubusercontent.com/43731687/224156745-3ec03dcc-36c8-4d96-a129-01be2c4f4b3f.png)

</details>

<details>
<summary>current Multiomics EHR risk KP Edge: missing primary</summary>

![Screen Shot 2023-03-09 at 1 02 53 PM](https://user-images.githubusercontent.com/43731687/224157275-0152308c-af74-49e6-9dcc-0474bcf01df4.png)

</details>

**Comment by tokebe** [comment]
Deployed to prod 🚀

**Comment by colleenXu** [comment]
I'm not sure that primary_knowledge_source is marked on all Edges. These are missing it...
* If I query CTD through BTE (SmallMolecule `MESH:C006303` -> Gene), I see that BTE isn't assigning CTD as the primary source. This is happening for all instances + my local instance (all main branches). This is related to this [PR](https://github.com/biothings/biothings_explorer/pull/589) as well
* this is happening with Multiomics Wellness and Multiomics EHR Risk too: BTE isn't assigning it as primary source (the [PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/137#issuecomment-1463373381) was previously tested and working before...)

**Comment by colleenXu** [comment]
Closing in favor of https://github.com/biothings/biothings_explorer/issues/627
