### ISSUE TITLE
update Translator Developer Documentation

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#554]
Need to update [Translator Developers Documentation](https://translator-developer-documentation.readthedocs.io/en/latest/), maintained in https://github.com/NCATSTranslator/translator-developer-documentation

Parent issue: https://github.com/NCATSTranslator/translator-developer-documentation/issues/24

**Comment by colleenXu** [comment]
From Translator consortium, not an urgent ask. Timeline: 1-2 months

Andrew / Chunlei will keep track of this / direct us to work on it. Can probably use previous [documentation](https://github.com/biothings/BioThings_Explorer_TRAPI/tree/main/docs)

**Comment by andrewsu** [comment]
This effort appears to be on hiatus. Closing this until the consortium effort is revived/reorganized.
