### ISSUE TITLE
BUG: node normalization not handling case of one PubChem ID mapping to multiple UMLS IDs

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#560]
In https://github.com/NCATSTranslator/testing/issues/249, the input query used `PUBCHEM.COMPOUND:23994` as the input ID.  Node normalizer [returns two UMLS IDs](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND:23994) (`UMLS:C0043481` and `UMLS:C0795680`), both of which should be used in queries by BTE.  It looks like the PK posted in that issue ([72895d13-60c5-497f-a635-a702c0b4d06f](https://arax.ncats.io/?r=72895d13-60c5-497f-a635-a702c0b4d06f)) only used the latter UMLS ID.  This PK ([f74cf91f-3853-4961-b29e-b9966b2966a3](https://arax.ncats.io/?r=f74cf91f-3853-4961-b29e-b9966b2966a3)) is for issuing the same query explicitly using the former UMLS ID.  The intended behavior is that BTE returns the union of those two PKs.

More results examples:
* query results when using `PUBCHEM.COMPOUND:23994`: https://api.bte.ncats.io/v1/check_query_status/j3tfOxsz3u
* query results when using `UMLS:C0043481`: https://api.bte.ncats.io/v1/check_query_status/7z8rNQqEoM
* query results when using `UMLS:C0795680`: https://api.bte.ncats.io/v1/check_query_status/12iWR8AplS

**Comment by tokebe** [comment]
This appears to be an issue between NodeNorms's Production and Development instances.

[Querying the production server](https://nodenorm.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND:23994), `UMLS:C0043481` is not returned.

[Querying the development server](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND:23994), `UMLS:C0043481` is returned.

BTE uses the Production server.

**Comment by andrewsu** [comment]
Thanks @tokebe for the more careful detective work!  Closing this issue...
