### ISSUE TITLE
Create a default BTE landing page for the running BTE instance

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#562]
Currently, anyone navigating to the home page of a BTE instance (e.g., https://api.bte.ncats.io, https://bte.transltr.io) will get redirected to the [SmartAPI registry entry for BTE](https://smart-api.info/ui/dc91716f44207d2e1287c727f281d339).  Especially as we prepare a publication that describes BTE, we'll want a proper landing page. This issue will help us brainstorm what can/should be on the home page, and track the implementation/deployment.

**Comment by marcodarko** [comment]
One question for you guys @newgene @andrewsu : How does this site: https://biothings.io/explorer/ relate to this issue? Is this issue about a brand new site or landing page for BTE within the BTE API project that ultimately points to another external site or will this new site replace the existing one and move all that functionality to this new site?

**Comment by newgene** [comment]
the site at https://biothings.io/explorer/ should be kept separated from this issue. This issue is only for the default landing page of a locally running BTE.

**Comment by andrewsu** [comment]
Just to get the ball rolling on this, I think the initial landing page could be very simple.  
* Some sort of "you have successfully installed BTE" notification
* Something like "To learn more about BTE, go to https://biothings.io/explorer/" (which we'll update in #568)
* Ideally, a text box where people can paste in TRAPI queries and submit them, together with a couple links to populate with precanned examples from https://github.com/biothings/BioThings_Explorer_TRAPI/tree/main/examples/v1.1
* A link to the github repo https://github.com/biothings/BioThings_Explorer_TRAPI

If anyone wants to look at other examples of landing pages for locally-installed web applications, that might also be useful for other ideas.  But the few items above will be a perfectly functional start...

**Comment by andrewsu** [comment]
For the "Teams" page, you can separate active team members and past team members

Active:
Jackson Callaghan
Colleen Xu
Marco Alvarado Cano
Rohan Juneja
Yao Yao
Madhumita Narayan 
Kristina Hanspers 
Ayushi Agrawal 
Alex Pico 
Chunlei Wu
Andrew Su

Past:
Jiwen Xin
Anders Riutta
Eric Zhou

**Comment by marcodarko** [comment]
Perfect, I'll update it!

**Comment by tokebe** [comment]
@marcodarko's wonderful landing page has been on Prod for some time, marking this issues as complete.
