### ISSUE TITLE
Refresh BTE web site at https://biothings.io/explorer/

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#568]
The current BTE site is hosted at https://biothings.io/explorer/ and the src code at: https://github.com/biothings/biothings_explorer_web.

We might need to refresh this website to reflect the latest features/changes of BTE API and add relevant information (e.g. about pages, example queries etc).

Related to issue #562, potentially some components can be re-used.

**Comment by andrewsu** [comment]
Components that I think can be essentially reused from the work in #562 
* the "Team" page
* the example query widget
    * will we keep the job queue selector?  If job IDs are stored in local storage, then no problem with users seeing each others' jobs/results, right?

In addition, 
* installation instructions
    * I think this should be drawn from https://github.com/biothings/BioThings_Explorer_TRAPI#local-installations, but I think that's a section we're going to update in #573 
* Somewhere, you can use these text components:
    * "a query engine for a federated knowledge graph of biomedical APIs" (as a tagline?)
    * "BioThings Explorer is an application that creates a federated knowledge graph that is composed of a network of biomedical web services. BioThings Explorer leverages semantically precise annotations of inputs and outputs for each resource, and automates the chaining of web service calls to execute multi-step graph queries.  Because there is no large, centralized knowledge graph to maintain, BioThing Explorer is distributed as a lightweight application that dynamically retrieves information at query time."
* link to this github repo
* The image in https://www.dropbox.com/s/rncf98n5zl34l8g/supp_fig_2.csv_6.pdf?dl=0, possibly with this caption "A visualization of the meta-knowledge graph for BioThings Explorer.  The nodes in this graph are the semantic types that BioThings Explorer can query on (limited to the top 10 most common semantic types).  The edges between nodes represent mappings between node types that are provided by the APIs accessed by BioThings Explorer.  The edge width reflects the number of APIs for each meta-edge, which is also shown as the edge label."

**Comment by marcodarko** [comment]
The jobs saved would only be seen by people using the same computer only saved to a particular machine's local cache. 
Other items look good, I'll let you guys know if I run into any issues or have any questions.

**Comment by marcodarko** [comment]
@newgene  where's the code for this the BTE main web app? I tried to look for it but maybe I missed it

**Comment by newgene** [comment]
@marcodarko this one: https://github.com/biothings/biothings_explorer_web?

**Comment by marcodarko** [comment]
That's the old one I think the new one is this one: https://github.com/biothings/bte_schema_web_react  (thanks to Andrew for finding it).  I remember it was built in React, the old one is the old python/jinja combo

**Comment by andrewsu** [comment]
... and just because I made that mistake multiple times, I went ahead and archived https://github.com/biothings/biothings_explorer_web...

**Comment by andrewsu** [comment]
With the current beautiful and information-rich website at https://explorer.biothings.io, I'm going to close this issue!
