### ISSUE TITLE
Migrate documentation to workspace, additional cleanup

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#573]
BTE is primarily run from the [workspace](https://github.com/biothings/bte-trapi-workspace) now, and as such it should be made the home of all primary documentation regarding running and using BTE. This will involve moving the present README to the workspace, editing for clarity, and ensuring that it's up to date (correct instructions, environment variables, etc.).

Additionally, this repository could use some cleanup, specifically removing deployment files such as `Dockerfile`, which are now stale and unused.

**Comment by andrewsu** [comment]
good point from @newgene on slack, worth more thought and discussion:
> most of our BTE issues are on that BTE TRAPI repo, is that right? If so, another option would be bringing workspace back to this repo, maybe rename it too (we can evaluate pros and cons after more closer looks)

**Comment by colleenXu** [comment]
@tokebe 

Here's some documentation that may be useful:
* https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/README-useful-info-for-devs.md, particularly the "getting started" section (vocab + diagram links?) and the bottom section of "How to do certain BTE dev tasks" with config links 
* https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/smartapi.yaml: current and past versions may contain custom parameters for endpoints

(there's other docs in that directory but I'm not sure how relevant they are to your task)

**Comment by tokebe** [comment]
Marking as completed as the primary task is done. There's further work to do with room for more documentation, but that can be an ongoing project or separate issues.
