### ISSUE TITLE
Normalize scores

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#576]
BTE result scores currently have no upper bound. These scores should be normalized and bound to [0,1].

@andrewsu proposed a sigmoid function to cause scores to asymptotically approach 1. This makes a lot of sense, given that [NGD scoring is unbound](https://en.wikipedia.org/wiki/Normalized_Google_distance#Properties). We can simply clamp the low end at 0 as well.

Tagging @andrewsu @newgene for dicsussion.

**Comment by andrewsu** [comment]
I was thinking of a relatively crude transformation like this (and we can just eyeball the "right" value for the `TUNING_PARAM`)

https://colab.research.google.com/drive/1FgLR_iOon5W4gJv4-LZtbRkrJDJe7Y4x?usp=sharing

![image](https://user-images.githubusercontent.com/2635409/223553130-e72d61e4-f20a-4bf6-8d70-606afa224252.png)

**Comment by tokebe** [comment]
We could dynamically set the tuning parameter using some statistic of the untransformed set of scores?

**Comment by andrewsu** [comment]
My gut says we'd want to set a global tuning parameter to allow for the scenario where the answers for one query are truly much better/worse than another.  That's how I'd propose we start by implementing it, and then we can examine how it works in practice.

**Comment by tokebe** [comment]
Deployed to Prod.
