### ISSUE TITLE
Deploying Biolink 3.1.x to Prod: Organizing Items

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#578]
Translator expects Biolink 3.1.1 and the new creative mode templates support to be deployed to Prod, with deployment requests going out by March 17. So, this issue stands to organize all related things to try and get done for this deployment request.

## Summary of (Guaranteed) Changes

*This section is to organize the changes so we can essentially copy-and-paste into our Change Request.*

- Multiple dependency upgrades for stability+security
- Test rewrites to support testing of new features (irrelevant to deployment)
- Final additions for qualifier support, upgrade to Biolink 3.1.1 (https://github.com/biothings/biolink-model.js/pull/32)
- Support for new creative mode queries ([PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/132))
- Fixes for existing creative mode queries ([PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/135))
- Fix to attribute merging ([PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/108))
- Fix to is_set property when using node expansion ([PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/134))

## PRs currently on Dev waiting to be merged (aside from any of the above)

*This section is subject to discussion regarding which PRs should be merged and bundled with this deployment*

- Edge primary_knowledge source fix for situation C ([Issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/549), [PR1](https://github.com/biothings/bte_trapi_query_graph_handler/pull/137), [PR2](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/567))
  - Doesn't break anything on demotests, but needs some spot testing that correct APIs get primary_knowledge_source @colleenXu 
- https://github.com/biothings/BioThings_Explorer_TRAPI/issues/420
  - @andrewsu Do we want this to move forward to production?
- https://github.com/biothings/smartapi-kg.js/pull/72 & https://github.com/biothings/BioThings_Explorer_TRAPI/pull/574
  - Works (passes demotests), doesn't touch many things, should just be added.

## Issues that should be addressed and added before the deployment

*These should probably be fixed before deployment, though it's up for discussion*

- https://github.com/biothings/BioThings_Explorer_TRAPI/issues/577
- https://github.com/biothings/BioThings_Explorer_TRAPI/issues/576
- https://github.com/biothings/bte_trapi_query_graph_handler/pull/138
  - Requires some quick testing/demotests
 - Optimization: Basic refactoring at least, preferably thread limits as well.
 - Timeout async queries after 2 hours

**Comment by andrewsu** [comment]
I think this looks like a great plan to me.  on #420, unless there is any reason to hold it up that I'm not remembering, yes, I think deploying that to prod would be good.

**Comment by colleenXu** [comment]
The coordination of updating code vs updating SmartAPI yamls + refreshing the registry:
* @tokebe would prefer removing overrides from code ([dev](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/dev/src/config/smartapi_overrides.json), [main](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/config/smartapi_overrides.json)) ➡️  auto-deploy to CI (with other fixes) ➡️  make ITRB request to update test/prod based on CI
* When @tokebe deploys to dev/CI, also merge these PRs ([biolink3](https://github.com/NCATS-Tangerine/translator-api-registry/pull/106), [biolink3-text-mining](https://github.com/NCATS-Tangerine/translator-api-registry/pull/107)) to update the SmartAPI yamls. Then ping @colleenXu or Chunlei to refresh the SmartAPI registry. 
    * test/prod will be able to handle the SmartAPI yaml updates but creative-mode will be a bit wonky + the instances won't use qualifiers (this support is added with the other updates in the ITRB request)

**Comment by colleenXu** [comment]
Update: 
* 1:16PM Pacific time @tokebe: The changes have been deployed, with overrides removed, to Dev and CI
* now: I finished merging the PRs + refreshing the registrations. [Also did a quick fix of BTE/Service Provider's test_data_locations. ](https://github.com/NCATS-Tangerine/translator-api-registry/commit/da813088ca189761f0f3a2f597fe67e095832d7d)

**Comment by tokebe** [comment]
All changes deployed to Prod 🚀
