### ISSUE TITLE
CTD processing 1: pipe-delimited string of PMIDs -> array

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#583]
### Intro

CTD is an external API that we're ingesting through x-bte annotation in its [SmartAPI yaml](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/CTD/smartapi.yaml). It's currently accessible through BTE's api-specific endpoints like `v1/smartapi/0212611d1c670f9107baf00b77f0889a/query`). 

However, there are several issues with how BTE handles CTDs' responses. I think these issues can be addressed with post-query processing, perhaps with the [api-response-transform module](https://github.com/biothings/api-respone-transform.js) (custom handler) or [JQ](https://github.com/biothings/api-respone-transform.js/pull/38) (which hasn't been incorporated into BTE yet... )

(tagging @newgene @rjawesome for their input) 

### 1. pipe-delimited string of PMIDs -> array

CTD provides PMIDs in the `pubmed: data.PubMedIDs` field, and the values are `|`-delimited string. BTE isn't processing this correctly into an array (really a set of unique values) some of the time. I'm not sure why sometimes it processes it correctly and sometimes it doesn't. 

Example:

<details>
<summary>BTE query</summary>

POST to http://localhost:3000/v1/smartapi/0212611d1c670f9107baf00b77f0889a/query

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MESH:C006303"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```

</details>

<details>
<summary>CTD's raw response</summary>

During execution, BTE should generate [this query](http://ctdbase.org/tools/batchQuery.go?inputType=chem&inputTerms=C006303&inputTermSearchType=directAssociations&report=genes_curated&format=json) to CTD, and part of the response will be these 3 "records". 2 records have pipe-delimited `pubmed: data.PubMedIDs` values. 

```
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "Organism": "Bos taurus",
        "OrganismId": "9913",
        "PubMedIds": "15629191"
    },
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "Organism": "Mus musculus",
        "OrganismId": "10090",
        "PubMedIds": "15629191|19419996"
    },
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "PubMedIds": "1673268|1678558|19419996"
    }
```

</details>

<details>
<summary>BTE's current flawed response</summary>

Currently, BTE correctly merges these 3 records into one Edge, but doesn't handle the `pubmed: data.PubMedIDs` values as-desired...

```
               "006f724ebdc9389dc3429ffb181e2150": {
                    "predicate": "biolink:related_to",
                    "subject": "PUBCHEM.COMPOUND:294641",
                    "object": "NCBIGene:2678",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer",
                                "infores:ctd"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:15629191",
                                "PMID:15629191|19419996",
                                "PMID:1673268|1678558|19419996"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxon",
                            "value": [
                                "9913",
                                "10090"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxonName",
                            "value": [
                                "Bos taurus",
                                "Mus musculus"
                            ]
                        }
                    ]
                },
```

</details>

<details>
<summary>desired format for BTE's response</summary>

Instead, an array (set of unique values) like this would be the desired format:
```
               "006f724ebdc9389dc3429ffb181e2150": {
                    "predicate": "biolink:related_to",
                    "subject": "PUBCHEM.COMPOUND:294641",
                    "object": "NCBIGene:2678",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer",
                                "infores:ctd"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:15629191",
                                "PMID:19419996",
                                "PMID:1673268",
                                "PMID:1678558"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxon",
                            "value": [
                                "9913",
                                "10090"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxonName",
                            "value": [
                                "Bos taurus",
                                "Mus musculus"
                            ]
                        }
                    ]
                },
```

</details>

(note: originally discovered when writing the CTD processing issues, as part of https://github.com/biothings/BioThings_Explorer_TRAPI/issues/558#issuecomment-1467465374)

**Comment by colleenXu** [comment]
### 1. pipe-delimited string of PMIDs -> array

CTD provides PMIDs in the `pubmed: data.PubMedIDs` field, and the values are `|`-delimited string. BTE isn't processing this correctly into an array (really a set of unique values). 

Example:

<details>
<summary>BTE query</summary>

POST to http://localhost:3000/v1/smartapi/0212611d1c670f9107baf00b77f0889a/query

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MESH:C006303"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```

</details>

<details>
<summary>CTD's raw response</summary>

During execution, BTE should generate [this query](http://ctdbase.org/tools/batchQuery.go?inputType=chem&inputTerms=C006303&inputTermSearchType=directAssociations&report=genes_curated&format=json) to CTD, and part of the response will be these 3 "records". 2 records have pipe-delimited `pubmed: data.PubMedIDs` values. 

```
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "Organism": "Bos taurus",
        "OrganismId": "9913",
        "PubMedIds": "15629191"
    },
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "Organism": "Mus musculus",
        "OrganismId": "10090",
        "PubMedIds": "15629191|19419996"
    },
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "PubMedIds": "1673268|1678558|19419996"
    }
```

</details>

<details>
<summary>BTE's current flawed response</summary>

Currently, BTE correctly merges these 3 records into one Edge, but doesn't handle the `pubmed: data.PubMedIDs` values as-desired...

```
               "006f724ebdc9389dc3429ffb181e2150": {
                    "predicate": "biolink:related_to",
                    "subject": "PUBCHEM.COMPOUND:294641",
                    "object": "NCBIGene:2678",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer",
                                "infores:ctd"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:15629191",
                                "PMID:15629191|19419996",
                                "PMID:1673268|1678558|19419996"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxon",
                            "value": [
                                "9913",
                                "10090"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxonName",
                            "value": [
                                "Bos taurus",
                                "Mus musculus"
                            ]
                        }
                    ]
                },
```

</details>

<details>
<summary>desired format for BTE's response</summary>

Instead, an array (set of unique values) like this would be the desired format:
```
               "006f724ebdc9389dc3429ffb181e2150": {
                    "predicate": "biolink:related_to",
                    "subject": "PUBCHEM.COMPOUND:294641",
                    "object": "NCBIGene:2678",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer",
                                "infores:ctd"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:15629191",
                                "PMID:19419996",
                                "PMID:1673268",
                                "PMID:1678558"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxon",
                            "value": [
                                "9913",
                                "10090"
                            ]
                        },
                        {
                            "attribute_type_id": "inTaxonName",
                            "value": [
                                "Bos taurus",
                                "Mus musculus"
                            ]
                        }
                    ]
                },
```

</details>

**Comment by colleenXu** [comment]
### 2. processing batch-queries correctly

The current x-bte-kgs-operations aren't written as batch-queries, even though the CTD API does allow batch-querying. 

The problem is how BTE handles the batch-query responses. The API response is an array of associations (objects) - and each association matched to one of the input IDs. Each association has an "Input" field where the value is the matched input ID (all lowercase, has an ID-prefix for diseases (MESH or OMIM) and pathways (REACT or KEGG)).

However, BTE's default api-response-transform isn't correctly handling this - instead, it's linking the first input ID to every possible output ID.

Example:

<details>
<summary>Edit x-bte operations</summary>

In a local copy of the [SmartAPI yaml](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/CTD/smartapi.yaml), copy-paste the following into the `chemical2gene` operation. It's changing the `supportBatch` and `queryInputs` info. 

```
    - supportBatch: true
      useTemplating: true
      inputs:
      - id: MESH
        semantic: SmallMolecule
      outputs:
      - id: NCBIGene
        semantic: Gene
      parameters:
        inputType: chem
        inputTerms: "{{ queryInputs | joinSafe('|') }}"
        inputTermSearchType: directAssociations
        report: genes_curated
        format: json
      predicate: related_to
      response_mapping:
        "$ref": "#/components/x-bte-response-mapping/chemical2gene"
```

</details>

<details>
<summary>BTE query</summary>

Set up a local instance of BTE to override and use your local copy of the CTD yaml. Then POST to that specific api (v1/smartapi/{id}/query endpoint):

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MESH:C006303", "MESH:D015250"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```

During execution, BTE should generate [this query with two input IDs](http://ctdbase.org/tools/batchQuery.go?inputType=chem&inputTerms=C006303|D015250&inputTermSearchType=directAssociations&report=genes_curated&format=json) to CTD.

In CTD's raw response, some genes are only linked to the second ID D015250 / Aclarubicin, like PARP1. 

```
    {
        "CasRN": "57576-44-0",
        "ChemicalId": "D015250",
        "ChemicalName": "Aclarubicin",
        "GeneId": "142",
        "GeneSymbol": "PARP1",
        "Input": "d015250",
        "Organism": "Homo sapiens",
        "OrganismId": "9606",
        "PubMedIds": "20399885"
    },
```

</details>

<details>
<summary>BTE's current flawed response</summary>

BTE links every output gene with only the first ID C006303 / acivicin / `PUBCHEM.COMPOUND:294641`. It's easier to see through the console log:

```
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:836 has 4 +1ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:1080 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:10800 has 1 +1ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:2678 has 3 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:834 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:841 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:1676 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:2623 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:2950 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:3145 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:4778 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:2908 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:142 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:6582 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:6607 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:6647 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:331 has 1 +0ms
```

</details>

<details>
<summary>desired format for BTE's response</summary>

Instead, BTE should correctly link each input ID / entity with its associations. The console log should look like this: 

* some results have the first input ID C006303 / acivicin / `PUBCHEM.COMPOUND:294641`
* other results have the second input ID D015250 / Aclarubicin / `PUBCHEM.COMPOUND:451415`
* PARP1 (NCBIGene:142) is only linked to the second ID: `PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:142`. Most genes are linked to only one of the input IDs.  

```
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:836 has 1 +1ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:1080 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:10800 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:294641_&_n1-NCBIGene:2678 has 3 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:834 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:836 has 3 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:841 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:1676 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:2623 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:2950 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:3145 has 1 +1ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:4778 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:2908 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:142 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:6582 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:6607 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:6647 has 1 +0ms
  bte:biothings-explorer-trapi:QueryResult result ID: n0-PUBCHEM.COMPOUND:451415_&_n1-NCBIGene:331 has 1 +0ms
```

</details>

**Comment by colleenXu** [comment]
### 3. handling output IDs when multiple ID prefixes are possible

Some operations are commented-out because BTE isn't properly handling the output IDs when multiple ID prefixes are possible. This happens when the output is a disease ID (which can be MESH or OMIM) or a pathway ID (which can be REACT or KEGG). 

For example, BTE will fail to recognize that the API response returned both MESH and OMIM Disease IDs and will instead assign all the Disease IDs to the one ID-prefix assigned by the operation.

Example:

In a local copy of the [SmartAPI yaml](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/CTD/smartapi.yaml), uncomment the `chemical2disease_1` and `chemical2disease_2` operations (lines 125, 127, 211-231, 253-273, 548-551, 556-559).  

<details>
<summary>BTE query</summary>

Set up a local instance of BTE to override and use your local copy of the CTD yaml. Then POST to that specific api (v1/smartapi/{id}/query endpoint):

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MESH:D004317"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}

```

During execution, BTE should generate [this query](http://ctdbase.org/tools/batchQuery.go?inputType=chem&inputTerms=D004317&inputTermSearchType=directAssociations&report=diseases_curated&format=json) to CTD.

In CTD's raw response, some Disease IDs are MESH like `MESH:D015746`/ Abdominal Pain and others are OMIM like `OMIM:610141` / QT INTERVAL, VARIATION IN.

```
    {
        "CasRN": "23214-92-8",
        "ChemicalID": "D004317",
        "ChemicalName": "Doxorubicin",
        "DirectEvidence": "marker/mechanism",
        "DiseaseCategories": "Signs and symptoms",
        "DiseaseID": "MESH:D015746",
        "DiseaseName": "Abdominal Pain",
        "Input": "d004317",
        "PubMedIDs": "3712578|6542584"
    },


    {
        "CasRN": "23214-92-8",
        "ChemicalID": "D004317",
        "ChemicalName": "Doxorubicin",
        "DirectEvidence": "marker/mechanism",
        "DiseaseCategories": "Cardiovascular disease|Pathology (process)",
        "DiseaseID": "OMIM:610141",
        "DiseaseName": "QT INTERVAL, VARIATION IN",
        "Input": "d004317",
        "PubMedIDs": "12597018|7919046"
    },
```

</details>

<details>
<summary>BTE's current flawed response</summary>

BTE will do the operation with MESH-Disease-outputs and find the OMIM ID in CTD's response. It'll then strip the OMIM ID prefix off, and then assign it as a MESH ID. This will result in a flawed record -> Edge to `MESH:610141` (when the original ID was `OMIM:610141` / QT INTERVAL, VARIATION IN). 

```
                "034d46e56b095c750619cc51ee2cb1bf": {
                    "predicate": "biolink:related_to",
                    "subject": "PUBCHEM.COMPOUND:31703",
                    "object": "MESH:610141",
```

Then it'll do similar behavior with the operation with OMIM-Disease outputs and the MESH IDs in CTD's response. So there'll be flawed records -> Edges like this to `OMIM:D015746` (when the original ID was `MESH:D015746`/ Abdominal Pain). 

```
                "0ca3845c254a304918933c581de85ae4": {
                    "predicate": "biolink:related_to",
                    "subject": "PUBCHEM.COMPOUND:31703",
                    "object": "OMIM:D015746",
```

</details>

I know Biolink API / Monarch's post-query processing + SmartAPI yaml response-mapping (which is to fields that exist only after the post-processing) is able to handle this situation, so maybe a solution like that will work here. However, it's perhaps not ideal that multiple operations are written + the same query is done repeatedly for different post-query processing. 

This problem is related to [past discussions](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/548) on supporting multiple ID prefixes/namespaces as input / output. I'm not sure how much refactoring of code / x-bte annotation would be needed for a general solution...

**Comment by colleenXu** [comment]
### 4. less important: handling gene -> gene's response

I haven't written an operation for a gene->gene query, because the direction of the response's data isn't consistent. It's not super-important because the source of this info is BioGRID and Biolink API / Monarch also covers this information.

For example, [if I query for gene CYSLTR1 (10800)](http://ctdbase.org/tools/batchQuery.go?inputType=gene&inputTerms=10800&inputTermSearchType=directAssociations&report=genes_curated&format=json)...

<details>
<summary>some associations have CYSLTR1 in the source fields</summary>

source = src

```
    {
        "Assay": "Co-localization",
        "Input": "10800",
        "InteractionType": "physical",
        "PubMedId": "21203429",
        "SrcGeneId": "10800",
        "SrcGeneSymbol": "CYSLTR1",
        "SrcOrganism": "Homo sapiens",
        "SrcOrganismId": "9606",
        "TgtGeneId": "57105",
        "TgtGeneSymbol": "CYSLTR2",
        "TgtOrganism": "Homo sapiens",
        "TgtOrganismId": "9606",
        "Throughput": "low"
    },
    {
        "Assay": "Affinity Capture-Western",
        "Input": "10800",
        "InteractionType": "physical",
        "PubMedId": "17693579",
        "SrcGeneId": "10800",
        "SrcGeneSymbol": "CYSLTR1",
        "SrcOrganism": "Homo sapiens",
        "SrcOrganismId": "9606",
        "TgtGeneId": "57105",
        "TgtGeneSymbol": "CYSLTR2",
        "TgtOrganism": "Homo sapiens",
        "TgtOrganismId": "9606",
        "Throughput": "low"
    },
```

</details> 

<details>
<summary>but others have CYSLTR1 in the target fields</summary>

target = tgt

```
    {
        "Assay": "Affinity Capture-Western",
        "Input": "10800",
        "InteractionType": "physical",
        "PubMedId": "21203429",
        "SrcGeneId": "57105",
        "SrcGeneSymbol": "CYSLTR2",
        "SrcOrganism": "Homo sapiens",
        "SrcOrganismId": "9606",
        "TgtGeneId": "10800",
        "TgtGeneSymbol": "CYSLTR1",
        "TgtOrganism": "Homo sapiens",
        "TgtOrganismId": "9606",
        "Throughput": "low"
    },
    {
        "Assay": "Affinity Capture-Western",
        "Input": "10800",
        "InteractionType": "physical",
        "PubMedId": "19561298",
        "SrcGeneId": "2840",
        "SrcGeneSymbol": "GPR17",
        "SrcOrganism": "Mus musculus",
        "SrcOrganismId": "10090",
        "TgtGeneId": "10800",
        "TgtGeneSymbol": "CYSLTR1",
        "TgtOrganism": "Mus musculus",
        "TgtOrganismId": "10090",
        "Throughput": "low"
    }
```

</details> 

I think Biolink API / Monarch's post-query processing + SmartAPI yaml response-mapping (which is to fields that exist only after the post-processing) is able to handle this situation, so maybe a solution like that will work here.

**Comment by rjawesome** [comment]
Fixed in JQ PR. Issue seems to be that sometimes CTD returns fields capitalized (ie. PubMedIDs) but for certain other requests the fields are lowercased (ie. PubMedIds) -- I'm pretty sure this depends on the input/output types. I wrote the JQ transformer to handle both cases.

This probably could be fixed in the custom ctd javascript transformer by checking PubMedIDs and PubMedIds. I also saw the wrapper was using DiseaseIDs so I made it check DiseaseIds just in case.

**Comment by colleenXu** [comment]
@rjawesome I want to check that we're on the same page, after reviewing your commit. 

* I don't understand what the DiseaseId/DiseaseID parsing is for, since I haven't noticed cases where there are multiple Disease IDs in one association object. I think it can be removed.  
* However, I have noticed cases of pipe-delimited values in the `data.DirectEvidence` field. It'd be helpful to have JQ-processing there to turn it into an array of strings
* It sounds like the JQ post-processing is not changing how the fields themselves are spelled for the [x-bte-response-mapping](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/CTD/smartapi.yaml#L537), is that correct?
    * I spelled the fields the way I saw them in my examples. Looking again, I can see different spellings in different operations (ChemicalID/ChemicalId, GeneID/GeneId) - but I see a consistent spelling for DiseaseID and PathwayID.

**Comment by rjawesome** [comment]
I just adapted the DiseaseID parsing from the previous ctd javascript wrapper, so I guess that might have not been updated (now that I look at that, I'm pretty sure it was just removing the id prefix [ie. MESH, MONDO] from the disease). I can change it to handle pipe delimted values in the DirectEvidence.

The current JQ wrappers do not change how the fields are used in the response mapping, however it could be used to achieve that (maybe the post processing could standardize the capitalization?)

**Comment by colleenXu** [comment]
Closing this issue since the changes have been deployed to Prod with the Feb 2024 release. 

I've confirmed that I can query CTD through BTE prod `[https://bte.transltr.io/v1/team/Service Provider/query](https://bte.transltr.io/v1/smartapi/0212611d1c670f9107baf00b77f0889a/query)` with the example in https://github.com/biothings/biothings_explorer/issues/583#issue-1622873383 and get the expected response (no |-delimited PMIDs).
