### ISSUE TITLE
create notebook to demonstrate query across multiple intermediate nodes

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#59]
the existing notebooks are all based on metapath queries with three nodes, two edges.  Create a notebook with at least four nodes, three edges...

**Comment by andrewsu** [comment]
created by @kevinxin90 in 5589264 here: https://github.com/biothings/biothings_explorer/blob/master/jupyter%20notebooks/Multi%20intermediate%20nodes%20query.ipynb

**Comment by andrewsu** [comment]
@kevinxin90 can you update this notebook to be colab-friendly?  just need to add the `!pip install` command(s) in a code cell at the top, plus an appropriate direct link to colab...

**Comment by kevinxin90** [comment]
Sure. Will be ready in ~ 1hr.

**Comment by kevinxin90** [comment]
Done.
1. Colab link added.
2. pip install command also added.

Available at: https://github.com/biothings/biothings_explorer/blob/master/jupyter%20notebooks/Multi%20intermediate%20nodes%20query.ipynb
