### ISSUE TITLE
Biothings transformer support for arbitrary complex queries

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#592]
Currently, the Biothings transformer gets input IDs from POST queries by [passing the query associated with a hit into `generateCurie()`](https://github.com/biothings/api-respone-transform.js/blob/75c613902f5c58cc780e5260852faf516a433689/src/transformers/biothings_transformer.ts#L11). This only supports queries formatted with the input ID at the very end of the string, as `generateCurie()` splits a string by `:` and takes the last item.

Complex query strings can easily cause problems if they don't leave the ID at the end of the string. After discussion with @colleenXu, the most doable fix at the moment is to run through `queryInputs` (accessible in that code section via `this.edge`) and check for inclusion in the query string, taking the first item that matches, and then passing that to `generateCurie()`.

**Comment by tokebe** [comment]
Note that there could be similar issues in other transformers, and further review is required to determine how this might interact with the [JQ](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/489) PRs. @rjawesome , do you have any insight?

**Comment by rjawesome** [comment]
The JQ has access to this.edge, so a fix for this could be implemented by modifying the JQ transformers for biothings.

**Comment by rjawesome** [comment]
I just pushed a fix for this on jq branch with a generateCurieWithInputs jq function that takes in the curie input so this can easily be used for any other APIs as well. 

@tokebe Just wanted to know, is the field "query" returned by biothings ever an array as currently my code doesn't handle that.

**Comment by tokebe** [comment]
I don't believe so, @colleenXu or @erikyao might be able to answer with more certainty.

**Comment by colleenXu** [comment]
@rjawesome not sure if you mean "queryInputs" for "the curie input" mentioned in your [post](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/592#issuecomment-1489525088). 

I don't pay a lot of attention to what's in the "query" field...so I don't know. Maybe @erikyao or @newgene would know..

**Comment by colleenXu** [comment]
Also @tokebe I wonder if you could check @rjawesome's commit? https://github.com/biothings/api-respone-transform.js/commit/ea9db147795f69884ef05983c4f038a511a60772

I'm not sure that I'm understanding it correctly, but it seems to be doing something with prefixes and upper-case.

---

<details>
<summary>This may not be relevant, but I'll note some things about prefixes, IDs, and letter-capitalization here</summary>

* we're still figuring out the ID prefix stuff #591 , but most elements in queryInputs probably don't have prefixes?
* not all biolink-model/Translator prefixes are all-caps and some have special characters like the "." (ncats.bioplanet, UniProtKB are two common examples)
* some IDs (not the prefixes!) have letters in them (DBSNP has rs, UMLS and NCIT has C, MESH has D, CHEMBL has CHEMBL)
    * I think the BioThings APIs have the "correct" letter capitalizations for these IDs, and that they're biolink-model/Translator-compliant. However, I'm not sure because I haven't asked. I remember asking for particular IDs before and not getting a straightforward answer...
* FYI: Other APIs (TRAPI and external = non-TRAPI/non-BioThings) sometimes have different capitalizations for prefixes and IDs. It'd be nice if we were able to handle these gracefully (convert to our desired format?). I notice that SRI Node Norm seems case-agnostic for inputs but provides outputs in the desired format for capitalization ([example](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=mesh%3Ad014867&conflate=true) with MESH ID)

</details>

**Comment by rjawesome** [comment]
I just converted everything to uppercase when checking for inclusion so that casing wouldn't be an issue. Currently my code assumes queryInputs doesn't have a prefix but the case of a prefix could be handled by just splitting by ":".

**Comment by colleenXu** [comment]
This is tied to the JQ work #489  and https://github.com/biothings/api-respone-transform.js/pull/38

**Comment by colleenXu** [comment]
@tokebe Is it okay to close this issue? Isn't this only deployed on Dev/CI instances? (so we can't adjust the registered SmartAPI yamls if we want)

**Comment by tokebe** [comment]
This was auto-closed by commit-linking, whoops!

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
