### ISSUE TITLE
phase 3 / as-needed: update SmartAPI yamls for BTE + Service Provider

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#594]
The SmartAPI yamls for BTE + Service Provider are based on the TRAPI spec, so they'll need updating to TRAPI 1.4. The `info.x-trapi.version` value will change to `1.4.0`. 

* timing: later, during the deployment process
* priority: lower
* responsible dev: me

Some things are a bit unclear to me, but they're not big deals...
* when to do these updates, given the gradual updating of instances/servers. 
    * We maybe want to update yamls as the [async-endpoint changes](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/602) go live on the instances/servers...
* how to report what TRAPI version the different instances/servers are on (related to the discussion [here](https://github.com/NCATSTranslator/translator_extensions/issues/22))

**one solution** is to do what we did in the [TRAPI 1.3 rollout](https://github.com/NCATS-Tangerine/translator-api-registry/commit/16dee366f5caac78625644a967887d12c7d08acf): separate yamls for TRAPI 1.3 and 1.4 and we put some server/instance urls in one yaml and some in the other.

<details><summary>Will cover these changes</summary>

From the the [changelog](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.4/ChangeLog.md)

* (1) Edge.predicate switched to nullable false and made required, Edge.subject and Edge.object switched to nullable false https://github.com/NCATSTranslator/ReasonerAPI/pull/377/files
* UPDATED in 1.4 branch of TRAPI [to use 1.3.4](https://github.com/NCATSTranslator/ReasonerAPI/pull/427/files). (2) External workflow schema updated from version 1.0.0 to version 1.3.2 https://github.com/NCATSTranslator/ReasonerAPI/pull/365/files 
* (3) Node.categories clarified that they SHOULD be Biolink Model categories and MUST NOT be of type 'abstract' or 'mixin'. 'deprecated' categories SHOULD also be avoided. https://github.com/NCATSTranslator/ReasonerAPI/pull/383/files
* (6) Constrain Qualifier.qualifier_type_id to be a biolink CURIE https://github.com/NCATSTranslator/ReasonerAPI/pull/391/files
* (9) Switch all cases of "allOf" to "oneOf" to be compatible with actual schema semantics and TRAPI (JSONSchema) validation https://github.com/NCATSTranslator/ReasonerAPI/pull/403/files
* (11) Everyone should be tagging at 1.4.0: https://github.com/NCATSTranslator/ReasonerAPI/pull/419/files

</details>

**Comment by colleenXu** [comment]
Updated links + details due to updates to TRAPI 1.4 during this "beta phase".

When changes to TRAPI 1.4 happen, they should be on [this branch](https://github.com/NCATSTranslator/ReasonerAPI/commits/1.4) and documented in this branch's [changelog](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.4/ChangeLog.md)

**Comment by colleenXu** [comment]
Note: TRAPI is currently on v1.4.0-beta4 -> would update to this or whatever is the latest version when it's time to

**Comment by colleenXu** [comment]
SmartAPI yaml bits that I need to ask others about...

for @tokebe:

* [BTE's version is "2.8.1"](https://github.com/NCATS-Tangerine/translator-api-registry/blob/bbb89d08e43c361741a0dc04e610cd8a554e72dd/biothings_explorer/smartapi.yaml#L4), which I think comes from the npm versioning which is defunct...Do you suggest using some kind of new versioning with BTE / putting something else there?
* [`info.x-trapi` section](https://github.com/NCATS-Tangerine/translator-api-registry/blob/bbb89d08e43c361741a0dc04e610cd8a554e72dd/biothings_explorer/smartapi.yaml#L17): could you review this vs the [TRAPI spec](https://github.com/NCATSTranslator/ReasonerAPI/blob/bdf380129c12df4e277dfe427be50ee5255b4cd2/TranslatorReasonerAPI.yaml#L24), and suggest edits if needed? Some edits I could think of are...
    * adding a `batch_size_limit`
    * adjusting the `rate_limit`
    * editing the comments 
* [`servers` section's comments (on what these instances are and how they're deployed)](https://github.com/NCATS-Tangerine/translator-api-registry/blob/bbb89d08e43c361741a0dc04e610cd8a554e72dd/biothings_explorer/smartapi.yaml#L32): could you review them and suggest edits?
    * perhaps this info doesn't need to be in this yaml, and instead it's somewhere else in documentation?
* are there BTE-specific parameters for the endpoints, that we want to advertise in this yaml? I'm thinking of optional parameters that aren't `smartapi_id` / `team_name` for the api-specific/team-specific endpoints. Right now...
    * `/meta_knowledge_graph` endpoints don't have any
    * [`/query` and `asyncquery` endpoints have two](https://github.com/NCATS-Tangerine/translator-api-registry/blob/bbb89d08e43c361741a0dc04e610cd8a554e72dd/biothings_explorer/smartapi.yaml#L137): `caching` and `dryrun`
* [`check_query_status` endpoint](https://github.com/NCATS-Tangerine/translator-api-registry/blob/bbb89d08e43c361741a0dc04e610cd8a554e72dd/biothings_explorer/smartapi.yaml#LL432C4-L432C22): does this endpoint spec need adjustments? I dunno if this endpoint is still accessible in our TRAPI 1.4 instances or if its behavior has changed...
* `asyncquery_status` endpoint: does this endpoint spec need any adjustments (aka BTE-specific stuff)?

Questions for Translator:
* is it fine to change [BTE's operation to `lookup_and_score`](https://github.com/NCATS-Tangerine/translator-api-registry/blob/bbb89d08e43c361741a0dc04e610cd8a554e72dd/biothings_explorer/smartapi.yaml#L20)? Can ARS/validator/etc handle this?

**Comment by colleenXu** [comment]
Changes made so far:
* updated TRAPI 1.3 registrations ([reorder fields to match TRAPI](https://github.com/NCATS-Tangerine/translator-api-registry/commit/bbb89d08e43c361741a0dc04e610cd8a554e72dd), [change repo name in urls](https://github.com/NCATS-Tangerine/translator-api-registry/commit/4fe1f4f2085e582c7e3d0858b3133b3b13d444d6), remove dev instance)
* [update BTE's SRI Testing JSON](https://github.com/NCATS-Tangerine/translator-api-registry/commit/04200e3ca4c084bb24e200aeae7cfcdcfd7c3715) to match changes made to API_LIST in BTE
* [created TRAPI 1.4 yamls](https://github.com/NCATS-Tangerine/translator-api-registry/commit/2014610eb900497e856a58e290f480f121ef397f) and registrations for dev instances (and this [commit](https://github.com/NCATS-Tangerine/translator-api-registry/commit/0420b43a33655a4bd29c3e3834ebd4dd01e9d400) to fix uptime check)
* made a TRAPI 1.4 yaml local copy in this BTE branch https://github.com/biothings/biothings_explorer/pull/641/commits/f8d1905a1b07edaa11bc5289a8f27b0f56a22f93

Now BTE + Service Provider show up as having TRAPI 1.3 and 1.4 instances

![Screen Shot 2023-05-12 at 9 38 18 PM](https://github.com/biothings/biothings_explorer/assets/43731687/94f61873-c85d-4f15-a2e7-2f292a28c412)

![Screen Shot 2023-05-12 at 9 38 02 PM](https://github.com/biothings/biothings_explorer/assets/43731687/9b2a8da4-7000-429a-8db6-49690535d69e)

**Comment by tokebe** [comment]
Note that in the new yaml, `check_query_status` should be removed as it is no longer supported. We may wish to detail the operation of `asyncquery_response` as well, but that's entirely optional as it's technically only TRAPI-compliant when accessed via a response from `asyncquery_status`.

**Comment by colleenXu** [comment]
@tokebe 

I've removed the /check_query_status endpoint from all the TRAPI 1.4 yamls: https://github.com/NCATS-Tangerine/translator-api-registry/commit/744c9424f9ec1f8ac6affc8e44d5e462b6cd43a7 and https://github.com/biothings/biothings_explorer/commit/fd9bf29407cb289cb2e7914e0f1a0a55da20a4eb

I know that your other point on asyncquery_response and my [questions](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1546522475) above haven't been addressed yet. I think they're lower-priority but may be good to discuss sometime...

**Comment by tokebe** [comment]
I'll try to respond to those in order:

- Since we haven't dealt with versioning for a while, there isn't a very straightforward answer here, especially because I haven't been able to find anything that directly relates to that version number. I think we should go of our repository, with the last tag being v1.3.0 -- based on the rules of [semantic versioning](https://semver.org/), we'd probably want to bump up to v2.0.0 for TRAPI 1.4. That said, we don't really have a release system in current use, so there's room for discussion about this (and how to manage versioning moving forward). Tagging @andrewsu for opinions.
- Rate limit (and associated comments) is already correct, I'd recommend adding a batch size limit of 200.
- Comments on servers already look fine. Maybe add something about ITRB requiring a Change Request to deploy to Test/Prod from Staging?
- `asyncquery_response` accepts a urlquery `log_level` which filters the logs to the given level or higher, other than that, I don't think so...
- `asyncquery_response` is otherwise the same as asyncquery_status, but: if the job is done, it instead responds with literally just what a synchronous TRAPI response would look like.

**Comment by colleenXu** [comment]
Update:
* registered yamls have been updated to advertise that CI instances have been updated to TRAPI 1.4 (and registrations have been refreshed) https://github.com/NCATS-Tangerine/translator-api-registry/commit/6e78adf958a275359a99e5e66ca3d5b177978bd8
* also updated the tool versions https://github.com/NCATS-Tangerine/translator-api-registry/commit/45693df92aa6bbe7d4342bee78982fe448d603cd and internal lab slack [thread](https://suwulab.slack.com/archives/CC218TEKC/p1684795417382209?thread_ts=1684773595.501029&cid=CC218TEKC)
* I didn't update the local copy of the SmartAPI yaml in biothings_explorer. I don't think it will cause issues to leave this not-updated for now (wait until all instances are on TRAPI 1.4? or some other update is needed to this spec?)

**Comment by colleenXu** [comment]
The TRAPI 1.4 instances will be released as another tool version (4.0.0)

<details><summary>Copied from internal lab slack thread</summary>

> **Jackson Callaghan**
>  Regarding deployment of TRAPI 1.4 to CI: We obviously are going to want a 1.3 branch that holds the current main prior to the 1.4 merge. I was wondering if we wanted a tag? I checked and it looks like we haven't used tags since 2021, so I just wanted to check if we cared about version tagging at all?
> 
> **andrew**
> in principle that sounds like a good idea to me. But I defer to you and Chunlei on if there is a better way to accomplish that intent...
> 
> **Jackson Callaghan**
> For now I'll tag it based on semantic versioning against the previous tag...we can decide if we want to do anything different later
> 
> **chunleiwu**
> :+1: good with me on this plan
> 
>  **chunleiwu**
> previously, Kevin makes official release to docker hub, that tag should match each release, but we did not continue doing that (after workspace conversion)
> 
> **Jackson Callaghan**
> Note that I'm rolling a lot of tags up a major version because things have had breaking changes either in trapi versioning or in internal api (moving to records class, etc)
> 
> **colleenxu**
> hmmm note that I updated the "version" for BTE to 3.0.0 [in the SmartAPI yamls](https://github.com/NCATS-Tangerine/translator-api-registry/commit/45693df92aa6bbe7d4342bee78982fe448d603cd) since that's the latest tag for the biothings_explorer repo.
> However, I see that 3.0.0 = 1.3 branch. So once we get all instances to trapi 1.4 (and that code is kinda stable?), maybe we'll want another tag?
> 
> **Jackson Callaghan**
> Yeah, TRAPI 1.4 will bring us to BTE 4.0.0 probably

</details>

**Comment by colleenXu** [comment]
Updated TRAPI specs to 1.4.2 using https://github.com/NCATSTranslator/ReasonerAPI/compare/v1.4.0-beta...v1.4.2

* registry https://github.com/NCATS-Tangerine/translator-api-registry/commit/4924791d682ed26b81fe7e784559fd6c2a1033f5
* https://github.com/biothings/biothings_explorer/commit/c293b5ea8454352b7f66e4ea503fadca69c13aac

EDIT with note: [TRAPI version should still be reported as 1.4.0 (Translator Slack link)](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1689132957810699) even though we actually updated our specs to 1.4.2. Update 2023/07/25: confirmed to keep doing this ([Translator Slack](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1690306315726549))

**Comment by colleenXu** [comment]
This issue is basically complete:
* now that TRAPI 1.4.0 is deployed to all instances, the [original registrations for BTE / Service Provider are now updated to the TRAPI 1.4.2 yaml](https://github.com/NCATS-Tangerine/translator-api-registry/pull/124) and the temporary TRAPI 1.4 registrations have been deleted. 
* The local copy was [fully updated earlier](https://github.com/biothings/biothings_explorer/commit/c293b5ea8454352b7f66e4ea503fadca69c13aac), as noted in the [previous post](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1629687393))
* SmartAPI exclusions had been added to handle the temporary TRAPI 1.4 registrations, and they've now been removed https://github.com/biothings/biothings_explorer/commit/8c0b758df4c4cbb49dcad9c34e646ef56d76fe2b (CI only, but the continued existence of these exclusions on dev/test/prod shouldn't be an issue for now)... 

What is still hanging:
* Updating comments and SmartAPI yamls based on [Jackson's earlier comments](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1551802813)

Going to leave this issue open under my to-dos....until this last task is resolved...

**Comment by tokebe** [comment]
@colleenXu I leave it to your judgement whether we should close this and track the few remaining stray parts in a new issue, or just continue using this issue to track it (or if they're low-enough priority that they don't really need tracking...).

**Comment by colleenXu** [comment]
Closing. Linked the old questions/comments in the new issue, for potentially reviewing as part of that effort.
