### ISSUE TITLE
phase 3: use qualifier-hierarchy when processing QGraph qualifier-constraints -> picking MetaEdges

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#598]
We'd like to be able to traverse the qualifier hierarchy (similar to what we do with predicates and node categories), so we can correctly retrieve all the operations/MetaEdges that correspond to a particular qualifier-constraint from the original query QEdge...

this may come up as a potential issue as more querying is done with qualifier-constraints
* timing: phase 3. this is a "making existing functionality better" thing
* priority: high priority within phase 3?

Notes: 
* this is for non-creative-mode QEdges only (no "inferred" knowledge_type)
* involves parsing the biolink-model enums that have is_a relationships https://github.com/biolink/biolink-model/blob/0165bc0a35a5c189f8b81e7fc0ae45bb6747f53e/biolink-model.yaml#L10483 like:
    * DirectionQualifierEnum (upregulated is a child of increased)
    * ChemicalOrGeneOrGeneProductFormOrVariantEnum
    * GeneOrGeneProductOrChemicalEntityAspectEnum
    * CausalMechanismQualifierEnum 
* Other context: we put this aside during [our earlier work on Biolink 3.1.1/TRAPI-1.3 support](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/512#issuecomment-1306337458)
* when this feature is developed, we'll want to modify the creative-mode templates...

**Comment by colleenXu** [comment]
Update notes: opening post was last updated 4/4 evening

**Comment by rjawesome** [comment]
PRs made for this issue. The qualifier expansion is currently used for non-TRAPI APIs in the PR.

<details><summary>Example Query I tested with (in the smartapi yaml for DGIdb, the constraints say activity, and biolink:causes respectively):</summary>

```json
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["CHEMBL.COMPOUND:CHEMBL266510"]
                },
                "n1": {
                    "categories":["biolink:Gene"]
               }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "qualifier_constraints": [
                        { 
                            "qualifier_set": [
                                {
                                    "qualifier_type_id": "object_aspect_qualifier",
                                    "qualifier_value": "activity_or_abundance"
                                },
                                {
                                    "qualifier_type_id": "qualified_predicate",
                                    "qualifier_value": "biolink:contributes_to"
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

</details>

**Comment by colleenXu** [comment]
Hmm. I think it's fine that "qualifier" expansion isn't done with TRAPI KPs right now. I think we'd need #597 addressed, and then we could think if qualifier expansion is needed to match the qualifier-constraints to MetaEdges from TRAPI KPs that have qualifier info...

**Comment by colleenXu** [comment]
Appears to work. 

In this [testing](https://github.com/biothings/biothings_explorer/issues/597#issuecomment-1642887378), BTE had console logs showing that `object_direction_qualifier` was correctly expanded from `decreased` to `decreased` and its child `downregulated`. 

[Automat hetio's meta_knowledge_graph](https://automat.transltr.io/hetio/1.4/meta_knowledge_graph) shows that there's a SmallMolecule - regulates - `downregulated` (qualifier) Gene MetaEdge. So BTE likely used that MetaEdge to generate the sub-query; this shows that qualifier-hierarchy expansion is working (since I queried for the parent qualifier `decreased`). 

<details><summary>console logs showing the qualifier hierarchy expansion</summary>

```
  bte:biothings-explorer-trapi:QEdge Expanded edges: affects_response_to,increases_response_to,decreases_response_to,regulates,disrupts,ameliorates,treats,exacerbates,has_adverse_event,has_side_effect,affects +2ms
  bte:biothings-explorer-trapi:QEdge Expanded edges: affects_response_to,increases_response_to,decreases_response_to,regulates,disrupts,ameliorates,treats,exacerbates,has_adverse_event,has_side_effect,affects +0ms
  bte:biothings-explorer-trapi:qedge2btedge KG Filters: {
  bte:biothings-explorer-trapi:qedge2btedge   "input_type": [
  bte:biothings-explorer-trapi:qedge2btedge     "SmallMolecule"
  bte:biothings-explorer-trapi:qedge2btedge   ],
  bte:biothings-explorer-trapi:qedge2btedge   "output_type": [
  bte:biothings-explorer-trapi:qedge2btedge     "Gene"
  bte:biothings-explorer-trapi:qedge2btedge   ],
  bte:biothings-explorer-trapi:qedge2btedge   "predicate": [
  bte:biothings-explorer-trapi:qedge2btedge     "affects_response_to",
  bte:biothings-explorer-trapi:qedge2btedge     "increases_response_to",
  bte:biothings-explorer-trapi:qedge2btedge     "decreases_response_to",
  bte:biothings-explorer-trapi:qedge2btedge     "regulates",
  bte:biothings-explorer-trapi:qedge2btedge     "disrupts",
  bte:biothings-explorer-trapi:qedge2btedge     "ameliorates",
  bte:biothings-explorer-trapi:qedge2btedge     "treats",
  bte:biothings-explorer-trapi:qedge2btedge     "exacerbates",
  bte:biothings-explorer-trapi:qedge2btedge     "has_adverse_event",
  bte:biothings-explorer-trapi:qedge2btedge     "has_side_effect",
  bte:biothings-explorer-trapi:qedge2btedge     "affects"
  bte:biothings-explorer-trapi:qedge2btedge   ],
  bte:biothings-explorer-trapi:qedge2btedge   "qualifiers": [
  bte:biothings-explorer-trapi:qedge2btedge     {
  bte:biothings-explorer-trapi:qedge2btedge       "object_direction_qualifier": [
  bte:biothings-explorer-trapi:qedge2btedge         "downregulated",
  bte:biothings-explorer-trapi:qedge2btedge         "decreased"
  bte:biothings-explorer-trapi:qedge2btedge       ]
  bte:biothings-explorer-trapi:qedge2btedge     }
  bte:biothings-explorer-trapi:qedge2btedge   ]
  bte:biothings-explorer-trapi:qedge2btedge } +0ms
```

</details> 

Closing issue
