### ISSUE TITLE
Add schema_version and biolink_version properties to every Response 

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#605]
From bullet 10 of the [changelog](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.4/ChangeLog.md):
> New properties Response.schema_version and Response.biolink_version to aid in TRAPI (JSONSchema) validation https://github.com/NCATSTranslator/ReasonerAPI/pull/405/files

With TRAPI 1.4, tools can specify the TRAPI version (`schema_version`) and biolink-model version (`biolink_version`) as top-level properties in their Response objects which are `/query` endpoint responses (but it'd probably be good to put in our `Response` objects from async endpoint stuff too). This appears to be optional (not required). 
* timing: phase 3. seems to be optional, not clear if any ARAs will use it 
* priority: lowest priority

Notes:
* We can probably get the values for these from the SmartAPI yaml. However, I note some issues in #594 in knowing what instances have what trapi/biolink versions so we may get these values from somewhere else (hard-coded and adjusted as needed?)...

**Comment by colleenXu** [comment]
Update notes: opening post was last updated 4/4 evening

* TRAPI 1.4 may still change. When those changes happen, they should be on [this branch](https://github.com/NCATSTranslator/ReasonerAPI/commits/1.4) and documented in this branch's [changelog](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.4/ChangeLog.md)

**Comment by tokebe** [comment]
Moving this one back to the todo list -- while it's covered in most places, the information is missing in some error messages (addressed partially by #675)
