### ISSUE TITLE
phase 3: add qualifier info from TRAPI KPs to general-ARA `/meta_knowledge_graph` response

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#609]
From bullet 4 of the [changelog](https://github.com/NCATSTranslator/ReasonerAPI/blob/1.4/ChangeLog.md):
> In MetaKnowledgeGraph component, added MetaEdge.qualifiers as list of new MetaQualifier types https://github.com/NCATSTranslator/ReasonerAPI/pull/387/files

With TRAPI 1.4, tools can specify qualifiers in their `/meta_knowledge_graph` endpoint responses (`edges` section). We probably want to use this format to advertise the qualifier info we get from the TRAPI KPs we ingest. This only affects the general-ARA endpoint (`v1/meta_knowledge_graph`). 
* timing: after [the issue on ingesting qualifier info from TRAPI KPs we use](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/597)
* priority: medium (relative to other phase 3 issues)

Other notes: 
* Maybe relevant: older discussion of our `/meta_knowledge_graph` endpoints and qualifier info: [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/512#issuecomment-1306285943) and [reply](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/512#issuecomment-1306337458)

**Comment by colleenXu** [comment]
Restating some info from above: this issue is probably on-hold because it (1) depends on the issue 597 (already linked), (2) is affected by the "qualifier-set merging" discussion, and (3) probably won't be used by anyone

**Comment by tokebe** [comment]
Assigning to @rjawesome if he has time.

**Comment by rjawesome** [comment]
See https://github.com/biothings/biothings_explorer/pull/628 and https://github.com/biothings/smartapi-kg.js/pull/77 (Also fixes the issue on the PRs which would add trapi qualifiers to be used in query filtering). I am keeping this in the same PRs with the other TRAPI qualifier issue because they both use the same code to check TRAPI metakg responses for qualifiers.

**Comment by tokebe** [comment]
Oh, I had missed that this functionality was added by those PRs - awesome, thanks!
