### ISSUE TITLE
Remove "installation successful" from front page

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#620]
As the front page is going to operate as the front page on our live instances, the "installation successful" message may appear a bit strange and should be removed, along with the "is Ready!" text.

**Comment by marcodarko** [comment]
@tokebe so do I need to clone new repo before I make this PR?

**Comment by tokebe** [comment]
Yes, you'll need to clone the new repo and run `npm run setup`, after which you should be good to go.

**Comment by marcodarko** [comment]
Addressed in https://github.com/biothings/biothings_explorer/pull/622

**Comment by andrewsu** [comment]
looks complete on prod https://bte.transltr.io/
