### ISSUE TITLE
Add a URL query parameter to allow arbitrary creative mode limits

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#625]
Presently, BTE hard-caps creative mode at 500 results. [We've received a request to be able to override this,](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1681497786504329?thread_ts=1681495905.809199&cid=C022EL8D3AB) use-case copied here:

> Hey Jackson, sure, I'm working both with O&O examining ranking and score distributions and with a group looking into clinical validation of biomedical translator's ARA ranking. So I can imagine two potential use cases:
(1) I set the number of returned drug-disease pairs to some high but reasonable number (like 5000) just to aggregate more scores
(2) I set the number to some arbitrarily high threshold that would be impossible to reach (like 1e9) and I just aggregate over every possible result from BTE (this is what I'm doing with the ROBOKOP ARA and ARAX ARA)

A URL query parameter that passes this information query->query_graph_handler->inferred_mode_handler should address this pretty easily.

Tagging @andrewsu for discussion/prioritization.

**Comment by colleenXu** [comment]
Recording my musings:

I interpret this to mean: 
* they want to send a LOT of queries (a large set of diseases for the drug-treats-disease creative-mode)
* for each query they want to get back a LOT of results
* then an analysis will be done regarding scoring and checking (do the "real" / "known" answers show up)

I wonder about load / performance and how long these queries will take...

**Comment by tokebe** [comment]
I think if we were to support this, I'd recommend only supporting it on the async endpoint to limit concurrency (especially given that these types of queries would be long-running anyway...)

**Comment by tokebe** [comment]
@andrewsu I'd like to briefly re-visit this issue to ask if we can mark it as not planned. It seems like we don't have any desire to allow for user-increased creative limit unless they're running their own instance?

**Comment by andrewsu** [comment]
👍 agreed, it's currently low enough on the priority list that we can call it not planned for the foreseeable future. If anyone wants to ask us to revisit that prioritization in the future, please add additional comments or use cases to this closed issue...
