### ISSUE TITLE
minor issue: logs on the number of APIs in the response are incorrect when cached records are used

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#626]
If I run the same one-hop basic query twice in short succession, the second query's response has logs that are missing the API information.

```
        {
            "timestamp": "2023-04-18T04:45:24.237Z",
            "level": "INFO",
            "message": "Execution Summary: (6) nodes / (4) edges / (4) results; (0/0) queries (1 cached qEdges) returned results from (0) unique APIs ",
            "code": null
        },
        {
            "timestamp": "2023-04-18T04:45:24.237Z",
            "level": "INFO",
            "message": "APIs: ",
            "code": null
        }
```

I was running a query to our ITRB prod instance `https://bte.transltr.io/v1/smartapi/43af91b3d7cae43591083bff9d75c6dd/query`. It was Gene `["UniProtKB:Q93099", "UniProtKB:Q9Y6P5"]` -> MolecularActivity

**Comment by rjawesome** [comment]
See PR

**Comment by tokebe** [comment]
Deployed to Prod for some time, marking as complete.
