### ISSUE TITLE
Query graph node id is blank 

### ISSUE THREAD

**Issue by ayushi-agrawal-gladstone** [biothings/biothings_explorer#636]
The below query was run on ARAX (https://arax.ncats.io/). The results JSON is attached as a text file and can also be found at: https://arax.ncats.io/api/arax/v1.3/response/ac618af3-1b52-40f9-9c22-a4f3d760a262. 

In the query_graph of the JSON results, "ids" for node n2 (i.e. IMATINIB MESYLATE) is blank but that for n0 (i.e. Asthma) is populated; even when ids for both nodes n2 and n0 were specified in the input query below. 

**Input query:**
```
{
  "edges": {
    "e0": {
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2",
      "object": "n1"
    },
    "e1": {
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n1",
      "object": "n0"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0004979"
      ],
      "categories": [
        "biolink:Disease"
      ],
      "name": "asthma"
    },
    "n1": {
      "categories": [
        "biolink:Gene"
      ]
    },
    "n2": {
      "ids": [
        "CHEMBL.COMPOUND:CHEMBL1642"
      ],
      "categories": [
        "biolink:SmallMolecule"
      ],
      "name": "IMATINIB MESYLATE"
    }
  }
}
```

**Screenshot from results JSON:**

<img width="342" alt="highlighted_issue_result_json" src="https://user-images.githubusercontent.com/88406934/235534110-478e58d3-1c5a-4e06-9e7b-6ca9bcd463a7.png">

**JSON results text file:**
[result.txt](https://github.com/biothings/biothings_explorer/files/11368100/result.txt)

**Comment by colleenXu** [comment]
EDIT: what Ayushi provided above is a good start, but it looks like there's an error with BTE's async endpoints that may be unrelated. 

I think this is an issue with ARAX. The link that Ayushi provides above is ARAX's and that tool has obviously mutated BTE's response (the validation section comes from ARAX). Compare to the [version of that PK response from ARS](https://ars-prod.transltr.io/ars/api/messages/ac618af3-1b52-40f9-9c22-a4f3d760a262)...this shows the original IDs (and the BTE-mutated query-graph, same as below). 

---

I don't see an issue when querying...
* local instance of BTE (`/query` endpoint without threading, `http://localhost:3000/v1/query`)
* BTE-prod (`/query` endpoint `https://bte.transltr.io/v1/query`)
* [ARAX UI](https://arax.ncats.io/) to BTE-prod `/query` endpoint (replace the External url with `https://bte.transltr.io/v1` and then click the `Post to OTHER` button in the Query { JSON } area. 

<details><summary>I had to put the query Ayushi provided into the full TRAPI format when querying BTE directly</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e0": {
                    "predicates": ["biolink:related_to"],
                    "subject": "n2",
                    "object": "n1"
                },
                "e1": {
                    "predicates": ["biolink:related_to"],
                    "subject": "n1",
                    "object": "n0"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0004979"],
                    "categories": ["biolink:Disease"],
                    "name": "asthma"
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                },
                "n2": {
                    "ids": ["CHEMBL.COMPOUND:CHEMBL1642"],
                    "categories": [ "biolink:SmallMolecule"],
                    "name": "IMATINIB MESYLATE"
                }
            }
        }
    }
}
```

</details> 

<details><summary>Query graph in the response</summary>

```
    "message": {
        "query_graph": {
            "edges": {
                "e0": {
                    "predicates": [
                        "biolink:related_to"
                    ],
                    "subject": "n2",
                    "object": "n1"
                },
                "e1": {
                    "predicates": [
                        "biolink:related_to"
                    ],
                    "subject": "n1",
                    "object": "n0"
                }
            },
            "nodes": {
                "n0": {
                    "ids": [
                        "MONDO:0004979",
                        "MONDO:0001491",
                        "MONDO:0004765",
                        "MONDO:0004766",
                        "MONDO:0004784",
                        "MONDO:0005405",
                        "MONDO:0022742",
                        "MONDO:0025556"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ],
                    "name": "asthma",
                    "is_set": true
                },
                "n1": {
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n2": {
                    "ids": [
                        "CHEMBL.COMPOUND:CHEMBL1642"
                    ],
                    "categories": [
                        "biolink:SmallMolecule",
                        "biolink:ChemicalMixture"
                    ],
                    "name": "IMATINIB MESYLATE"
                }
            }
        },
```

</details> 

In the response, the query-graph is mutated because we add the categories from node-normalizer and descendant IDs from our node-expansion module. But the original starting IDs are there... 

full response from the local instance query here: [response.txt](https://github.com/biothings/biothings_explorer/files/11403683/response.txt)

**Comment by colleenXu** [comment]
Also note that the "missing QNode IDs" is also happening with other tools, which makes me think it is not a BTE issue and is instead an ARAX issue. 

The link Ayushi provides has a "ref" to the ARS's PK which is 37507274-7247-4960-b877-6c09954ad626. Looking at this PK in ARAX, I can see that two tools, Aragorn and ARAX, returned responses with results. However...both tools show the same "missing QNode IDs" behavior

Aragorn: 
* the ARAX response is missing the QNode IDs: [UI link](https://arax.ncats.io/?r=2e756e1e-eaf8-4f90-95c7-f1f872c3b59b) and [JSON link](https://arax.ncats.io/api/arax/v1.3/response/2e756e1e-eaf8-4f90-95c7-f1f872c3b59b)
* [the ARS storage of Aragorn's response](https://ars-prod.transltr.io/ars/api/messages/2e756e1e-eaf8-4f90-95c7-f1f872c3b59b) has the QNode IDs (search the text for `query_graph` to find the right section)

ARAX:
* the ARAX response is missing the QNode IDs: [UI link](https://arax.ncats.io/?r=135470) and [JSON link](https://arax.ncats.io/api/arax/v1.3/response/cfad4062-72a8-491b-8c94-25ba9f237256)
* [the ARS storage of Aragorn's response](https://ars-prod.transltr.io/ars/api/messages/cfad4062-72a8-491b-8c94-25ba9f237256)...I can't interpret this to see where the entire original QGraph is...

**Comment by colleenXu** [comment]
Noting that this is related to the #538 issue

**Comment by colleenXu** [comment]
Noting this, which may be related: https://github.com/NCATSTranslator/reasoner-validator/releases/tag/v3.5.3

**Comment by colleenXu** [comment]
@ayushi-agrawal-gladstone Eric Deutsch has mentioned a different ARAX URL that can be used in the meantime, that may not have this issue. https://github.com/RTXteam/RTX/issues/2027#issuecomment-1542690282

**Comment by colleenXu** [comment]
Theoretically, this issue should now be addressed (ARAX deploying with later verisons of reasoner-validator that don't remove this info). 

Maybe we want to follow up, and if we don't notice the problem / can work around it, we can close this issue...

**Comment by ayushi-agrawal-gladstone** [comment]
Thanks @colleenXu. I will test it later this week and close out this issue accordingly.

**Comment by ayushi-agrawal-gladstone** [comment]
No longer seeing this issue with the newer validator.
