### ISSUE TITLE
BTE prod instance async endpoint seems to hit an error, doesn't return a full response

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#637]
Copied from Slack:

> colleenxu
>   [13 hours ago](https://suwulab.slack.com/archives/CC218TEKC/p1683291602249479)
> Is something odd going on with BTE ITRB instances? When looking into the [issue](https://github.com/biothings/biothings_explorer/issues/636#issuecomment-1535753424) Ayushi posted, it shows that BTE hit an error and didn't return a full response. VS I can send the same query to /query endpoints and get a 1MB response. I think that error is probably separate from the "missing IDs" described in Ayushi's issue (since the IDs are NOT missing in these errorred responses).
> 
> I encountered basically the same error when I query BTE prod's async endpoint directly (https://bte.transltr.io/v1/asyncquery) or query ARS prod (which seems hooked up to the same async endpoint).
> 
> - BTE asyncquery direct: http://bte.transltr.io/v1/check_query_status/SgkO4xhmG0
> - From [querying ARS prod](https://ars-prod.transltr.io/ars/api/messages/711c0dde-5a92-4d23-800a-b082010fc7e3) (can't get BTE's internal job status ID)
> 
> ```
>             "status": "JobQueuingError",
>             "description": "TypeError: Cannot read properties of undefined (reading 'length')"
> ```

**Comment by colleenXu** [comment]
Copied from Slack: later comments from Jackson

> Jackson Callaghan
> :zzz:  [12 hours ago](https://suwulab.slack.com/archives/CC218TEKC/p1683295562828269?thread_ts=1683291602.249479&cid=CC218TEKC)
> Well that's concerning...I'll have to see where this error is happening and push out a fix to deploy to prod next week
> 
> 
> Jackson Callaghan
> :zzz:  [9 hours ago](https://suwulab.slack.com/archives/CC218TEKC/p1683304882337449?thread_ts=1683291602.249479&cid=CC218TEKC)
> This is an interesting one...it appears to be a problem with a specific record node not unfreezing from cache correctly. Still haven't pinpointed why that's happening, though.
> 
> 
> Jackson Callaghan
> :zzz:  [9 hours ago](https://suwulab.slack.com/archives/CC218TEKC/p1683305088368309?thread_ts=1683291602.249479&cid=CC218TEKC)
> I would also like to once again emphasize the importance of making a github issue when confirmed misbehavior/bug arises in a BTE live instance (outside of dev), as it just makes tracking easier -- if something like this were to this come up at a time where a lot of other messages were happening at once, I could lose track of the slack message, while a github issue stays in the issue tracker until solved.
> 
> 
> Jackson Callaghan
> :zzz:  [7 hours ago](https://suwulab.slack.com/archives/CC218TEKC/p1683313606228119?thread_ts=1683291602.249479&cid=CC218TEKC)
> Ok, turns out this is caused by a TRAPI API returning result with node expansion using query_id -- since we don't support it, the record should be dropped, but it wasn't due to minor changes in some data structure. I've pushed a fix to handle it and tested that it doesn't do anything else.

**Comment by colleenXu** [comment]
@tokebe I'll leave it to Jackson to link the commits that handle this issue and close this issue when it's fully addressed. 

I think the commit that handles the issue may be this one? https://github.com/biothings/api-respone-transform.js/compare/138f482a2031...87d773deb5c7

**Comment by tokebe** [comment]
Confirmed, the above commit fixes the issue. I'll close the issue as soon as the fix is on Prod.

**Comment by tokebe** [comment]
Fix deployed to Prod.
