### ISSUE TITLE
try getting ngd endpoint / support in semmeddb2

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#642]
discussed in today's group meeting. We are considering whether to move completely from [semmeddb](https://biothings.ncats.io/semmeddb) to [semmeddb2](https://biothings.ncats.io/semmeddb2) stuff)....

However, we currently get NGD scores (aka a part of BTE's scoring process) from semmeddb. @andrewsu asked @erikyao if we could move the NGD functionality in semmeddb to semmeddb2. This issue is to track how this is going.

**Comment by andrewsu** [comment]
Closing because I believe this one is done.  Please re-open and comment if not...
