### ISSUE TITLE
TRAPI 1.4 validation issue

### ISSUE THREAD

**Issue by maximusunc** [biothings/biothings_explorer#643]
I'm hitting service-provider-trapi dev and getting a validation issue:
It looks like in your results.analyses, you're returning a `reasoner_id` when the key should be `resource_id`

**Comment by tokebe** [comment]
Will fix ASAP

**Comment by tokebe** [comment]
@maximusunc Fix has been deployed on Dev, can you confirm you're not seeing this error anymore?

**Comment by maximusunc** [comment]
Yes, it looks good now. Thanks for the quick turnaround!
