### ISSUE TITLE
adjusting "edge hash" so BTE preserves all records from multiomics KPs

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#647]
This will be a work-in-progress, since Multiomics KP owners may adjust their edge-attribute attribute_type_ids....

BTE won't have Edges for all of the records in the Multiomics KP, likely because these records only differ by their edge-attributes.

**Comment by colleenXu** [comment]
Note that I tested the linked PR with the Multiomics Wellness situation I was working on https://github.com/biothings/pending.api/issues/118#issuecomment-1563712049, and it works, yay! However, I think the edge-attribute type_ids need adjusting, which is why I'd rather leave the PR and this issue open

I had 6 records with the same subject-ID, object-ID: https://biothings.ncats.io/multiomics_wellness_kp/query?q=subject.LOINC:%22LOINC:13457-7%22%20AND%20object.HMDB:%22HMDB:HMDB07218%22 and they weren't all appearing in the test TRAPI queries I was running (see the pending repo comment, part 3). But with the changes here, all 6 records become 6 separate edges in BTE's TRAPI response...

**Comment by colleenXu** [comment]
Note: going to merge the linked PR before the end of my work day...so Jackson can get it deployed and in a change request to ITRB for our Test instance tomorrow morning...

AKA it'll be part of the code we try to get fully deployed to all TRAPI 1.4 instances before the Relay. 

It's possible that things will still be in-flux after, so I'll move this issue to "on-hold" after the merge...

**Comment by colleenXu** [comment]
As part of the effort before the June Relay, we got answers from all Multiomics KP owners on which edge-attributes to put in here ([Translator Slack link](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1685646974169519)), and we added them (commits [1](https://github.com/biothings/bte_trapi_query_graph_handler/commit/18fac2c3653496efa5efd9265f59dfbedd8470ef),[2](https://github.com/biothings/bte_trapi_query_graph_handler/commit/9908af4b6ec46042bfb92928cc5fbea285412a0b),[3](https://github.com/biothings/bte_trapi_query_graph_handler/commit/5fe71acd563c57a6da4685ae4b17cf48cd135574))

This code is being moved forward along with everything else for TRAPI 1.4 support / other features for this spring/summer...

**Comment by tokebe** [comment]
@colleenXu can this issue be marked as completed?

**Comment by colleenXu** [comment]
Multiomics and Text-Mining teams have been informed of this config and the need to keep it updated as they update their KPs. 

This issue can be closed as complete
