### ISSUE TITLE
many identical aux-graphs in a non-creative-mode response

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#648]
<details><summary>query</summary>

Look at my saved response file below.

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["MONDO:0005377"],
                    "categories":["biolink:DiseaseOrPhenotypicFeature"],
                    "name": "noonan"
                },
                "n1": {
                    "categories":["biolink:Gene"],
                    "is_set": true
                },
                "n2": {
                    "categories":["biolink:ChemicalEntity"]
               }
            },
            "edges": {
                "eA": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:caused_by"]
                },
                "eB": {
                    "subject": "n1",
                    "object": "n2",
                    "predicates": ["biolink:regulated_by", "biolink:affected_by"]
                }
            }
        }
    }
}
```

Notes: 
* took 2 min 15 s to run on my local, all main branches
* same as the example query in this [issue](https://github.com/biothings/biothings_explorer/issues/603#issue-1645161397)

</details> 

Saved response: 
[response.txt](https://github.com/biothings/biothings_explorer/files/11608832/response.txt)

In the response, I notice multiple instances of identical aux-graphs...and this looks like a bug...

Examples:

A. `MONDO:0005377-caused_by-UMLS:C0754893-via_subclass` edge has 7 support-graphs linked to it. But they all seem to be identical, since there are 7 instances of the following (json snippet starts with part of the string label for the aux-graph):

```
-MONDO:0005377-caused_by-UMLS:C0754893-via_subclass": {
                "edges": [
                    "36f73e1ee7fcbe12d887f1bf05d528fa",
                    "expanded-MONDO:0002350-subclass_of-MONDO:0005377"
                ]
            },
```

B. `MONDO:0005377-caused_by-NCBIGene:4868-via_subclass` edge has 552 support-graphs linked to it. Of those aux-graphs, I notice 184 instances of the following:

```
-MONDO:0005377-caused_by-NCBIGene:4868-via_subclass": {
                "edges": [
                    "feb531bc295da7854d0df9e2f58ec2f1",
                    "expanded-MONDO:0002350-subclass_of-MONDO:0005377"
                ]
```

**Comment by tokebe** [comment]
Should be addressed by https://github.com/biothings/bte_trapi_query_graph_handler/commit/8a71a8dccd941bf04d9979f8c9f798c55ba7ca8a, https://github.com/biothings/bte_trapi_query_graph_handler/commit/836e01c94219602e6328a7207eb6cde3b6129aa4, https://github.com/biothings/bte_trapi_query_graph_handler/commit/e66ca287ef60716a1e31b8747ab1c855dc53b060
