### ISSUE TITLE
small bug? error when a query terminates because no records were found by sub-queries

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#649]
I'm noticing that when I send queries to the api-specific endpoint, and the query terminates because no records were found by sub-queries during a hop, rather than give me a valid TRAPI response (with empty KG, results, and auxilliary_graph sections).....BTE instead returns a 500 error. 

I'm using the latest main branches (so TRAPI 1.4 code). 

<details><summary>Example query</summary>

Post to the api-specific endpoint for Text Mining Targeted, like `http://localhost:3000/v1/smartapi/978fe380a147a8641caf72320862697b/query`

This query uses a valid gene ID but the API doesn't have any matching data

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"],
                    "ids": ["UniProtKB:P36148"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

</details> 

Response:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:Gene",
                        "biolink:BiologicalEntity"
                    ],
                    "ids": [
                        "UniProtKB:P36148"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        },
        "knowledge_graph": {
            "nodes": {},
            "edges": {}
        },
        "results": []
    },
    "status": 500,
    "description": "TypeError: Cannot read properties of undefined (reading 'length')",
    "trace": "TypeError: Cannot read properties of undefined (reading 'length')\n    at TRAPIQueryHandler.getResponse (/Users/colleenxu/Desktop/biothings_explorer/packages/@biothings-explorer/query_graph_handler/built/index.js:300:77)\n    at task (/Users/colleenxu/Desktop/biothings_explorer/src/routes/v1/query_v1_by_api.js:52:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async runTask (/Users/colleenxu/Desktop/biothings_explorer/src/controllers/threading/threadHandler.js:238:22)\n    at async /Users/colleenxu/Desktop/biothings_explorer/src/routes/v1/query_v1_by_api.js:23:28"
}
```

Note: I haven't tested the TRAPI 1.3 code/instance to see if this is an issue with them.

**Comment by rjawesome** [comment]
See PR

**Comment by colleenXu** [comment]
@andrewsu @tokebe @newgene FYI

this has been causing issues during the Relay, as I try to teach others how to query their KPs (TRAPI query) through BTE. It looks like something mysterious in BTE is broken or something is wrong with their x-bte annotation. When in reality...sometimes it's this (no results but it did run everything and check!)

If this is a quick review / fix, it'd be great if we could deploy it to as many instances as possible quickly...

**Comment by rjawesome** [comment]
I also found a similar bug for creative mode queries, where if there is no result it throws an error ("TypeError: Cannot convert undefined or null to object"). Made a PR

**Comment by colleenXu** [comment]
Discussion with Jackson: this issue should be entirely addressed for all endpoints (even though team-specific endpoints, non-creative mode v1/query endpoint wasn't the focus).

**Comment by tokebe** [comment]
> Discussion with Jackson: this issue should be entirely addressed for all endpoints (even though team-specific endpoints, non-creative mode v1/query endpoint wasn't the focus).

Clarification: The fixes made to this issue fix all possible instances, regardless of endpoint. No additional work need be done to address other endpoints.

Marking this issue as completed, as the fixes have been deployed to Prod.
