### ISSUE TITLE
BTE returns biolink:NamedThing for some nodes

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#652]
First Identified in [this issue.](https://github.com/NCATSTranslator/Feedback/issues/214)

This is likely a bug with the TRAPI 1.4 subclassing code, possibly from `addQueryNodes()`.

Example query:

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "sn": {
          "categories": [
            "biolink:ChemicalEntity"
          ]
        },
        "on": {
          "categories": [
            "biolink:Disease",
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "ids": [
            "MONDO:0005301"
          ]
        }
      },
      "edges": {
        "t_edge": {
          "subject": "sn",
          "object": "on",
          "predicates": [
            "biolink:treats"
          ],
          "knowledge_type": "inferred"
        }
      }
    }
  }
}
```

**Comment by tokebe** [comment]
This appears to be caused by a change in behavior by NodeNormalizer: it appears that SRIEntry is now returning the property `type` in reverse order from previous, where BTE operates on the assumption that lower-indexed entries are always more specific.

**Comment by colleenXu** [comment]
I dunno if that was surfaced elsewhere during the Relay...

But I notice that [Node Normalizer dev](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UMLS%3AC0001617&conflate=true) is returning in our old expected way (most-specific first).

vs
* [CI](https://nodenorm.ci.transltr.io/1.3/get_normalized_nodes?curie=UMLS%3AC0001617&conflate=true) and [prod](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=UMLS%3AC0001617&conflate=true) is using some other order, but small molecule is last.
* [test](https://nodenorm.test.transltr.io/1.3/get_normalized_nodes?curie=UMLS%3AC0001617&conflate=true) looks roughly least -> most specific, so small molecule is last 

---

@tokebe 

maybe we could use dev Node Norm (although I guess that's kinda risky...)

Also, could you bring this up in the Translator Slack? (but maybe search first to see if it's been brought up already?)

**Comment by tokebe** [comment]
It's already being worked on on their side and should be deployed relatively soon. I've added [a fix on our side](https://github.com/biothings/biomedical_id_resolver.js/commit/9d047a913b700aec9546c5462fccef15f7b7240f) that doesn't fully address the issue, but should mitigate it to some extent (handles cases where the order is totally reversed).

**Comment by colleenXu** [comment]
I'm asking [Translator Architecture (Slack link)](https://ncatstranslator.slack.com/archives/C013Q5TVC87/p1689042005923419) about this, since this still seems to be an issue, particularly for NCBIGene IDs
