### ISSUE TITLE
add link to preprint on explorer.biothings.io

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#655]
Add a link to https://arxiv.org/abs/2304.09344 somewhere on explorer.biothings.io.  Perhaps something like this?

![image](https://github.com/biothings/biothings_explorer/assets/2635409/1a935770-2514-4877-9673-6b1d59b5938f)

**Comment by marcodarko** [comment]
Link added to a prominent section right below. https://explorer.biothings.io/
