### ISSUE TITLE
update BTE documentation page on Translator wiki

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#658]
Update https://github.com/NCATSTranslator/Translator-All/wiki/Exploring-Agent, as tracked in https://github.com/NCATSTranslator/Feedback/issues/343. Target deadline June 30.

**Comment by colleenXu** [comment]
Perhaps related to https://github.com/biothings/biothings_explorer/issues/554?

**Comment by andrewsu** [comment]
#554 addresses developer documentation, whereas this ticket is about documentation about the methods presented to end users through the Translator UI.  So they are related but separate issues...

**Comment by andrewsu** [comment]
Addressed in https://github.com/biolink/biolink-model/pull/1342 and updates to https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-Explorer-(BTE) and https://github.com/NCATSTranslator/Translator-All/wiki/Exploring-Agent
