### ISSUE TITLE
Integrate BTE with Sentry

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#662]
BTE currently lacks a proper monitoring system for live exception logging/tracing and response time tracking. As Biothings already makes use of Sentry, integrating BTE with sentry makes sense.

Main goals:
- Exception tracking
- Query execution time tracking
- Feasibility of capturing query logs?

**Comment by rjawesome** [comment]
I completed some work on the ``sentry`` branch (BTE/query graph repos).
Right now, I have it set up so it measures the time of sync/async queries. These are also broken up into spans (see the image below, spans include "loadMetaKG", "edgeExecution", etc.). Let me know if there are any ideas for other "spans" I should add.
![image](https://github.com/biothings/biothings_explorer/assets/16053597/47581c5e-8156-4b8b-b472-7aad4aac977f)

Sentry allows tracking of average times, and I have it set up so sync/async and by api vs general endpoints are tracked seperately

Also, each transaction stores the query data like so: (I think it might be possible to attach query logs here as well)
![image](https://github.com/biothings/biothings_explorer/assets/16053597/b1a8f51c-d179-4cfc-b643-8032b35567b5)

NOTE: I am currently seeing some issues where sentry transactions are randomly not being recorded (usually I have to restart BTE 1+ times to solve the problem)

I am working on making sure errors are attached to the transactions so failiure rates for different endpoints can be seen and erros can be better tracked.

**Comment by tokebe** [comment]
If it's possible to create spans in the `call-apis` for each API call, that could come in handy to try and track any APIs that could potentially slow down execution.

This is looking really good so far, keep up the good work!

**Comment by rjawesome** [comment]
See PRs. Notes about how Sentry is integrated located in #676

**Comment by tokebe** [comment]
@rjawesome could you make a new PR for a couple of changes? See below:

- 404 errors shouldn't be considered failures by Sentry, because that's largely our service being queried on non-existent endpoints.
- queryAborted errors should, if possible, be reported, but not reported as unhandled -- we don't need a Sentry issue opened nor a notification when these occur.
- If it's easily done, I'd like to have BTE announce whether it's on dev/ci/test/prod using INSTANCE_ENV and [Sentry environments](https://docs.sentry.io/product/sentry-basics/environments/)
