### ISSUE TITLE
Update documentation of primary sources used by BTE in NCATS wiki

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#663]
In the infores catalog, many of the URLs currently point to https://github.com/biothings. They are captured in [this spreadsheet](https://docs.google.com/spreadsheets/d/1eLaj21m8jq26-pK2JvIeFdjcv06XnOL5ugwDEGBEDus/edit#gid=1940732560).  

Translator would like to have those URLs updated to point to a page on the [NCATS Translator Wiki](https://github.com/NCATSTranslator/Translator-All/wiki), and that URL will be shown on the UI. I created three examples:
* https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-DGIdb-API
* https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-DISEASES-API
* https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-RHEA-API

We need to update the rest of them...

**Comment by andrewsu** [comment]
Updating the task here... The spreadsheet in question is here https://docs.google.com/spreadsheets/d/1eLaj21m8jq26-pK2JvIeFdjcv06XnOL5ugwDEGBEDus/edit#gid=715583491 I added rows 135 (for `infores:bindingdb`) to row 157 (for `infores:uberon`).  Links to the github wiki are in column H.  Except when noted in Column I, the links to the github wiki point to non-existent pages.  These need to be created by 8/18.  The wiki pages should generally follow this template:

```
### 

**Website**: 

**High-level description of data source(s)**: 

**Example record**: 

**License/restrictions**: 
```

Examples of completed templates are here:
* https://github.com/NCATSTranslator/Translator-All/wiki/bindingdb 
* https://github.com/NCATSTranslator/Translator-All/wiki/bioplanet

The information to complete the template can generally be found by web searching and copying from the original data resource's website.

**Comment by colleenXu** [comment]
Finished the 10 assigned to me. If @andrewsu reviews and considers this issue done, it can probably be closed. 

I'll bring up in Translator Slack that the [infores catalog's info on GTRx is incorrect](https://github.com/biolink/biolink-model/blob/cfd18406cb7b6d2d2e04935b159c03cf5fefdaeb/infores_catalog.yaml#L1635) and I updated the ncats rare-source wiki url...

**Comment by tokebe** [comment]
Can this be closed as completed?

**Comment by andrewsu** [comment]
Looks good to me!
