### ISSUE TITLE
TRAPI 1.4: Fixing tests

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#665]
As a result of the TRAPI 1.4 upgrade, BTE has a number of failing tests as they have not been updated to expect the new behaviors.

To support future development these tests should be updated to work with current behavior.

**Comment by tokebe** [comment]
@mnarayan1 assigning this to you. If you could look through all the packages and update tests to match current behavior, that'd be great. Let me know if any questions come up; some tests may be completely unnecessary given new behaviors.

**Comment by mnarayan1** [comment]
@tokebe I believe all the tests should be updated now. Let me know if there's anything else I need to fix.

**Comment by tokebe** [comment]
Great work so far! There are still some failing tests in [`packages/biomedical_id_resolver`](https://github.com/biothings/biomedical_id_resolver.js) and the main workspace that I'm seeing.

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
