### ISSUE TITLE
TRAPI 1.4: "missing a primary knowledge source" logs for KPs tagged "primarySource"

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#667]
BTE is producing console and TRAPI logs that state that the TRAPI 1.3 "primary knowledge source" edge-attribute is missing. I think we can remove this behavior...

---

Do any query, and it'll have TRAPI logs like:

```
        {
            "timestamp": "2023-07-07T05:03:44.405Z",
            "level": "WARNING",
            "message": "Edge b9519d391cca9d1294dc2e55c12b0b63 (APIs: PharmGKB REST API) is missing a primary knowledge source",
            "code": null
        },
```

and console logs like this:

```
  bte:biothings-explorer-trapi:Graph Edge bfcb0f2c739647ca46879769cdf86aac (APIs: PharmGKB REST API) is missing a primary knowledge source +0ms
```

**Comment by colleenXu** [comment]
Found while testing x-bte annotation changes for PharmGKB, [discussed here](https://github.com/biothings/biothings_explorer/issues/661#issuecomment-1622728725) and commit here https://github.com/NCATS-Tangerine/translator-api-registry/commit/f61c1d01d20a23e4fa3c6c3d22976abc004acd94

**Comment by tokebe** [comment]
This warning was changed to operate on TRAPI 1.4 sources. I'll check if the logic is somehow broken -- would we want to remove it anyway?

**Comment by tokebe** [comment]
I've confirmed that this log is not happening in error -- if you check the response of the test query (which I assume is the same as in #668), every edge has a source object with `"resource_role": "primary_knowledge_source"` and no `resource_id`.

We've seen this before, where it was a problem with the KP not providing the appropriate attribute/annotation IIRC.

**Comment by colleenXu** [comment]
oh okay oops. This resource would need the primarySource tag for the sources to be rendered correctly. In the testing, the [config](https://github.com/biothings/biothings_explorer/issues/556#issuecomment-1474686499) file would need to be used (rather than overrides) to test...I guess. 

~Maybe we can just close this issue?~ See below, maybe there's still an issue...

**Comment by colleenXu** [comment]
actually wait....it looks like the "primarySource" tag in the config file isn't changing behavior as-desired....so this log happens...

EDIT: 
* CTD is the only API BTE uses with the primarySource tag and it also has this problem
* PharmGKB also has this problem when it's been added to the [config](https://github.com/biothings/biothings_explorer/issues/556#issuecomment-1474686499)

**Comment by tokebe** [comment]
Welp, looks like that config isn't being used by BTE properly. I'll look into fixing it...

**Comment by tokebe** [comment]
Addressed by https://github.com/biothings/biothings_explorer/commit/53d333cfa6e463576fc594fb68b84f454a6395f9

**Comment by tokebe** [comment]
Marking as complete as the code fixes for this issue were deployed to Prod.
