### ISSUE TITLE
bug: "biolink:null" for starting entity and "input_name" response-mapping not working

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#668]
to recreate the behavior:
* use a local instance or query BTE dev/ci. Issue doesn't seem to be in the prod instance
* query PharmGKB through BTE with URL like this: `https://bte.ci.transltr.io/v1/smartapi/bde72db681ec0b8f9eeb67bb6b8dd72c/query`
* query

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["PHARMGKB.PATHWAYS:PA2023"],
                    "categories": ["biolink:Pathway"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            }
        }
    }
}

```

The response will look like this:

```
                "PHARMGKB.PATHWAYS:PA2023": {
                    "categories": [
                        "biolink:null"
                    ],
                    "name": "PHARMGKB.PATHWAYS:PA2023",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:xref",
                            "value": [
                                "PHARMGKB.PATHWAYS:PA2023"
                            ]
                        },
                        {
                            "attribute_type_id": "biolink:synonym",
                            "value": [
                                "PHARMGKB.PATHWAYS:PA2023"
                            ]
                        }
                    ]
                },
```

When it should look like this (look at "categories" and "name"). It should be taking info from [this operation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/f61c1d01d20a23e4fa3c6c3d22976abc004acd94/pharmgkb/smartapi.yaml#L1630) + its [`input_name` response-mapping](https://github.com/NCATS-Tangerine/translator-api-registry/blob/f61c1d01d20a23e4fa3c6c3d22976abc004acd94/pharmgkb/smartapi.yaml#L1964)(SRI Node Norm doesn't recognize these kinds of IDs):

```
                "PHARMGKB.PATHWAYS:PA2023": {
                    "categories": [
                        "biolink:Pathway"
                    ],
                    "name": "ACE Inhibitor Pathway, Pharmacodynamics",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:xref",
                            "value": [
                                "PHARMGKB.PATHWAYS:PA2023"
                            ]
                        },
                        {
                            "attribute_type_id": "biolink:synonym",
                            "value": [
                                "PHARMGKB.PATHWAYS:PA2023"
                            ]
                        }
                    ]
                },
```

Note: Found while testing x-bte annotation changes for PharmGKB, [discussed here](https://github.com/biothings/biothings_explorer/issues/661#issuecomment-1622728725) and commit here https://github.com/NCATS-Tangerine/translator-api-registry/commit/f61c1d01d20a23e4fa3c6c3d22976abc004acd94

**Comment by tokebe** [comment]
This appears to be caused by handling when NodeNorm cannot resolve the entity. BTE doesn't currently do anything that intelligent with unresolvable entities. We could theoretically just default to the user-provided categories in cases like this, though it might require changes in several places in our code.

**Comment by colleenXu** [comment]
I thought we were adding the category from the operation / QNode, which was particularly helpful in cases like this where NodeNorm doesn't resolve the entity? And that this behavior was discussed / implemented earlier in https://github.com/biothings/biothings_explorer/issues/418#issuecomment-1061312156

Maybe I am mistaken?

**Comment by tokebe** [comment]
Ah, ok, there's definitely a bug here then. I'll look into retaining the user category. It looks like it might have been one of the more recent changes around internal node management that might have caused this regression in behavior.

**Comment by rjawesome** [comment]
https://github.com/biothings/bte_trapi_query_graph_handler/blob/91ef8748e79314e91a40ef657da7d1aaf1372ff0/src/index.js#L269

This seems to be the issue for both input_name and categories. It's generating the KG Node before the request even happens so input name can't be added. Also category is set here based on node normalizer rather than user specification
(This code is only called when the node has a specified id in the original query graph, which is why it is showing up here)

**Comment by tokebe** [comment]
Ah, this regression was created by some code I added for subclassing, fun. I'll see about fixing it.

**Comment by rjawesome** [comment]
another potential issue that could be fixed with this:
From what I undestand, with the current behavior in generating KG Nodes, even if it is not a query node, it will only use the input name from the first API which is processed.
(ie. if Record 1/2 have a shared node such that
Record 1 from API 1 has name = undefined (because not resolved by node normalizer)
Record 2 from API 2 has name = "some input_name from api"
Then if Record 1 is processed first, the name will be set to undefined rather than "some input_name from api"
)

**Comment by tokebe** [comment]
@rjawesome Would you be able to take this issue on, with priority over #662? You seem to have a good grasp of what's going wrong here.

Just to note, the reason I added [this step](https://github.com/biothings/bte_trapi_query_graph_handler/blob/91ef8748e79314e91a40ef657da7d1aaf1372ff0/src/index.js#L255-L283) was to ensure that the original query nodes end up in the final graph regardless of whether there are records directly referring to them (that way, we can still bind to the original query node when subclassing occurs)

**Comment by rjawesome** [comment]
Alright, I will work on it. (I'll make sure to keep that section but just override the names/categories if not there in SRI)

**Comment by rjawesome** [comment]
See PR.

**Comment by colleenXu** [comment]
Hmmm I'm not sure that this issue is addressed @rjawesome @tokebe 

@lucyzhang95 and I noticed that this was still happening while testing some of her x-bte annotation. And I reran the test in the opening post and had the same bugged behavior (no different behavior)...

**Comment by colleenXu** [comment]
EDIT: actually maybe I hadn't checked out query_handler main branch....it seems to be working now

**Comment by tokebe** [comment]
@colleenXu does that mean this issue can be marked as complete? The relevant PR has been deployed on prod for some time.

**Comment by colleenXu** [comment]
Quickly tested with bioplanet pathway IDs + pharmgkb IDs as starting points, and it seemed to work fine on local and prod instances. So we decided to close it
