### ISSUE TITLE
SmartAPI yaml with x-bte annotation for BioThings FoodData Central

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#683]
Information on the creation and deployment of this API is here: https://github.com/biothings/pending.api/issues/66

**Comment by andrewsu** [comment]
example record https://biothings.ncats.io/fooddata/association/333008-1267

```
{
  "_id": "333008-1267",
  "_version": 1,
  "object": {
    "chebiId": "CHEBI:140951",
    "nutrientAmount": 0.048,
    "nutrientAmountUnits": "g",
    "nutrientId": 1267,
    "nutrientName": "SFA 20:0",
    "nutrientRank": 11100
  },
  "relation": {
    "code": "A",
    "description": "Analytical",
    "nutrientMaxAmount": 0.052,
    "nutrientMedianAmount": 0.048,
    "nutrientMinAmount": 0.046,
    "sourceCode": "1",
    "sourceDescription": "Analytical or derived from analytical"
  },
  "subject": {
    "description": "Cookies, oatmeal, soft, with raisins",
    "fdcId": 333008,
    "foodCategory": "Baked Products",
    "foodOnId": "FOODON_00003294",
    "ndbNumber": 100192
  }
}
```

**Comment by colleenXu** [comment]
Related infores stuff is ready but not deployed yet:
* new infores catalog entry for FoodData Central and BioThings FoodData Central API in PR https://github.com/biolink/biolink-model/pull/1429 (BioThings API entry is probably not important because it isn't the primary infores)
* made new infores page for [FoodData Central (primary knowledge source)](https://github.com/NCATSTranslator/Translator-All/wiki/FoodData-Central)
* added a [placeholder infores page for BioThings FoodData Central](https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-FoodData-Central-API)

**Comment by colleenXu** [comment]
Here's the [SmartAPI yaml w/ x-bte annotation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/fooddata_central/smartapi.yaml) for [BioThings FoodData Central](https://biothings.ncats.io/fooddata). This yaml is registered in [SmartAPI Registry](https://smart-api.info/registry?q=895ec14a3650ec7ad85959a2d1554e2f). 

**I haven't made a PR to add this to BTE's regular use** (for the [config](https://github.com/biothings/bte-server/blob/main/src/config/apis.js) file, `API_LIST variable`): I'm waiting until **we address the next step below** and we're closer to the next release cycle to make a PR with all the KPs we want to add.

<details><summary>Example query</summary>
<p>

send a POST request to the api-specific endpoint, BioThings FoodData Central only. Like `http://localhost:3000/v1/smartapi/895ec14a3650ec7ad85959a2d1554e2f/query`. This works even when the KP isn't included in BTE's config 

Put this in the request body: It's querying with Beta-sitosterol (aka `CHEBI:27693`)

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["CHEBI:27693"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Food"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

You should get a response with this edge (from this [data in the BioThings API](https://biothings.ncats.io/fooddata/query?q=object.chebiId:%22CHEBI:27693%22%20AND%20object.nutrientAmount:%3E0), based on this [operation's example](https://github.com/NCATS-Tangerine/translator-api-registry/blob/8e6b904a0c11104450297fe32fe00003e77b3f91/fooddata_central/smartapi.yaml#L641):

* subject: beta-Sitosterol (primary ID in SRI NodeNorm `PUBCHEM.COMPOUND:222284`, CHEBI in BioThings API is `CHEBI:27693`)
* object: "Oil, peanut" (`FOODON:FOODON_03309857`, not recognized by SRI NodeNorm)

```
                "85a6e63f1ae130c8fbb78d0906427573": {
                    "predicate": "biolink:food_component_of",
                    "subject": "PUBCHEM.COMPOUND:222284",
                    "object": "FOODON:FOODON_03309857",
                    "attributes": [],
                    "sources": [
                        {
                            "resource_id": "infores:fooddata-central",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:biothings-fooddata-central",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:fooddata-central"
                            ]
                        },
                        {
                            "resource_id": "infores:service-provider-trapi",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:biothings-fooddata-central"
                            ]
                        }
                    ]
                },
```

</p>
</details> 

---

### Next steps: DONE

EDIT: this change has been deployed to all instances of pending BioThings APIs (our instance biothings.ncats.io up to ITRB prod biothings.transltr.io; we are currently using ITRB prod). 

**We will need to make a parser change / use post-processing on the FOODON IDs.** 

Biolink-model folks have told us to use the BioRegistry regex strings for ID-format, and [BioRegistry shows that FOODON IDs should be 8-digit numeric](https://bioregistry.io/registry/foodon). Right now our IDs all start with "FOODON_". We hadn't heard this policy clarification when [we were setting up this API and wondering about the ID format](https://github.com/biothings/pending.api/issues/66#issuecomment-1205665860). 

---

#### And some small notes:

* API has association-based records, yay! 
* For our operations, I've set [object.nutrientAmount > 0](https://biothings.ncats.io/fooddata/query?q=object.nutrientAmount:%3E0). We then cover 4717 / 6011 records (78% of dataset) where the nutrient was actually found in the food. 
* I included some notes for fields that could be possible future edge-attributes [in the yaml](https://github.com/NCATS-Tangerine/translator-api-registry/blob/8e6b904a0c11104450297fe32fe00003e77b3f91/fooddata_central/smartapi.yaml#L573) 
* I didn't use the more-specific "has_nutrient / nutrient_of" predicates because it wasn't clear that all the chemicals are nutrients. The FoodData Central [website](https://fdc.nal.usda.gov/index.html) says "nutrient" a lot, but it also says "Provides a broad snapshot in time of the nutrients **and other components** found in a wide variety of foods and food products" (emphasis mine).

**Comment by colleenXu** [comment]
After discussion with Andrew yesterday, I've opened an issue for the next steps.

However, it should be fine if these next steps aren't done by the time we add this API to BTE's regular use - we can still go forward with deploying.

**Comment by colleenXu** [comment]
Edited the post above: the FOODON ID edit is done. So this is ready to deploy

**Comment by colleenXu** [comment]
Added to the PR linked above to add this to BTE's regular use (for the [config](https://github.com/biothings/bte-server/blob/main/src/config/apis.js) file, API_LIST variable). 

We'll try to get it into Translator's Lobster release (dev/CI -> Test this Friday)

**Comment by tokebe** [comment]
Deployed to Prod.
