### ISSUE TITLE
BTE failing some subqueries with code error

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#685]
Moving this to a fresh issue for specific tracking.

---

> Note that I'm not sure that CHP's TRAPI 1.4 instance is working (dev only; `http://chp.thayer.dartmouth.edu/query`). When querying it directly, I'm getting either an empty response or a malformed error response. Looks like BTE is handling this somewhat...but I dunno if it could handle it more gracefully / intelligently?
> 
> BTE log example:
> ```
>         {
>             "timestamp": "2023-05-30T20:10:35.710Z",
>             "level": "ERROR",
>             "message": "call-apis: Failed POST http://chp.thayer.dartmouth.edu (1 ID): Gene > expressed_in > GrossAnatomicalStructure: (TypeError: Cannot read properties of undefined (reading 'id'))",
>             "code": null
>         },
> ```
> 
> <details><summary>query 1</summary>
> 
> ```
> {
>     "message": {
>         "query_graph": {
>             "nodes": {
>                 "n0": {
>                     "ids": ["NCBIGene:672"],
>                     "categories": ["biolink:Gene"]
>                 },
>                 "n1": {
>                     "categories": [
>                         "biolink:GrossAnatomicalStructure"
>                     ]
>                 }
>             },
>             "edges": {
>                 "e0": {
>                     "subject": "n0",
>                     "object": "n1",
>                     "predicates": ["biolink:expressed_in"]
>                 }
>             }
>         }
>     }
> }
> ```
> 
> </details> 
> 
> <details><summary>response to query 1: empty KG/results</summary>
> 
> ```
> {
>     "message": {
>         "query_graph": {
>             "nodes": {
>                 "n0": {
>                     "ids": [
>                         "NCBIGene:672"
>                     ],
>                     "categories": [
>                         "biolink:Gene"
>                     ],
>                     "is_set": false,
>                     "constraints": []
>                 },
>                 "n1": {
>                     "ids": null,
>                     "categories": [
>                         "biolink:GrossAnatomicalStructure"
>                     ],
>                     "is_set": false,
>                     "constraints": []
>                 }
>             },
>             "edges": {
>                 "e0": {
>                     "subject": "n0",
>                     "object": "n1",
>                     "knowledge_type": null,
>                     "predicates": [
>                         "biolink:expressed_in"
>                     ],
>                     "attribute_constraints": [],
>                     "qualifier_constraints": []
>                 }
>             }
>         },
>         "knowledge_graph": null,
>         "results": [
>             {
>                 "node_bindings": {
>                     "n0": [],
>                     "n1": []
>                 },
>                 "analyses": [
>                     {
>                         "resource_id": "infores:connections-hypothesis",
>                         "edge_bindings": {
>                             "e0": []
>                         },
>                         "score": null,
>                         "support_graphs": null,
>                         "scoring_method": null,
>                         "attributes": null
>                     }
>                 ]
>             }
>         ],
>         "auxiliary_graphs": null
>     },
>     "logs": [
>         {
>             "timestamp": "2023-05-30T20:14:12.898845",
>             "level": "INFO",
>             "message": "Running message.",
>             "code": null
>         },
>         {
>             "timestamp": "2023-05-30T20:14:12.898853",
>             "level": "INFO",
>             "message": "Getting message templates.",
>             "code": null
>         },
>         {
>             "timestamp": "2023-05-30T20:14:12.898917",
>             "level": "INFO",
>             "message": "Checking template matches for gene_specificity",
>             "code": null
>         },
>         {
>             "timestamp": "2023-05-30T20:14:12.900685",
>             "level": "INFO",
>             "message": "Detected 1 matches for gene_specificity",
>             "code": null
>         },
>         {
>             "timestamp": "2023-05-30T20:14:12.900690",
>             "level": "INFO",
>             "message": "Constructing queries on matching templates",
>             "code": null
>         },
>         {
>             "timestamp": "2023-05-30T20:14:12.900972",
>             "level": "INFO",
>             "message": "Sending 1 consistent queries",
>             "code": null
>         },
>         {
>             "timestamp": "2023-05-30T20:14:12.905156",
>             "level": "INFO",
>             "message": "Wildcard detected",
>             "code": null
>         },
>         {
>             "timestamp": "2023-05-30T20:14:12.905312",
>             "level": "INFO",
>             "message": "Received responses from gene_specificity",
>             "code": null
>         }
>     ],
>     "trapi_version": "1.4",
>     "biolink_version": "3.1.2",
>     "status": "Success",
>     "id": "2adeb7ba-6b70-429b-97b1-384f8e9c80f1",
>     "workflow": [
>         {
>             "id": "lookup"
>         }
>     ]
> }
> ```
> 
> </details> 
> 
> <details><summary>query 2</summary>
> 
> uses an ID they list in the example response of the /curies endpoint
> ```
> {
>     "message": {
>         "query_graph": {
>             "nodes": {
>                 "n0": {
>                     "ids": ["ENSEMBL:ENSG00000106665"],
>                     "categories": ["biolink:Gene"]
>                 },
>                 "n1": {
>                     "categories": [
>                         "biolink:GrossAnatomicalStructure"
>                     ]
>                 }
>             },
>             "edges": {
>                 "e0": {
>                     "subject": "n0",
>                     "object": "n1",
>                     "predicates": ["biolink:expressed_in"]
>                 }
>             }
>         }
>     }
> }
> ```
> 
> </details> 
> 
> <details><summary>query 2 response: malformed error</summary>
> 
> very long, only including snippets that seem useful
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
>     return view_func(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/home/chp_api/web/dispatcher/views.py", line 45, in post
>     return dispatcher.get_response(message)
>   File "/home/chp_api/web/dispatcher/base.py", line 167, in get_response
>     responses = get_app_response_fn(consistent_app_queries, self.logger)
>   File "/usr/local/lib/python3.8/site-packages/gene_specificity/app_interface.py", line 25, in get_response
>     response = interface.get_response(consistent_query, logger)
>   File "/usr/local/lib/python3.8/site-packages/gene_specificity/trapi_interface.py", line 142, in get_response
>     self._add_results(message, subject_mapping, qg_subject_id, [curie], subject_category, predicate, qg_edge_id, object_mapping, qg_object_id, object_curies, object_category, vals)
> 
> Exception Type: TypeError at /query
> Exception Value: _add_results() missing 2 required positional arguments: &#x27;object_category&#x27; and &#x27;vals&#x27;
> ```
> 
> ```
> 	<div id="explanation">
> 		<p>
> 			You’re seeing this error because you have <code>DEBUG = True</code> in your
> 			Django settings file. Change that to <code>False</code>, and Django will
> 			display a standard page generated by the handler for this status code.
> 		</p>
> 	</div>
> 
> </body>
> 
> </html>
> ```
> 
> </details> 
> 
> ---
> 
> EDIT: I found a query that works. However, (a) BTE wouldn't send a sub-query like this (where the ID is the object) and (b) BTE may not be able to process the response (only 1 result that contains all 30 "answers", as if`is_set: true` was on the Gene QNode...)
> 
> <details><summary>query that works</summary>
> 
> This is the example given for their /query endpoint
> 
> ```
> {
>     "message": {
>         "query_graph": {
>             "nodes": {
>                 "n0": {
>                     "categories": ["biolink:Gene"]
>                 },
>                 "n1": {
>                     "ids": ["UBERON:0009835"],
>                     "categories": ["biolink:GrossAnatomicalStructure"]
>                 }
>             },
>             "edges": {
>                 "e0": {
>                     "subject": "n0",
>                     "object": "n1",
>                     "predicates": ["biolink:expressed_in"]
>                 }
>             }
>         }
>     }
> }
> ```
> 
> </details> 
> 
> query response: 
> [response2.txt](https://github.com/biothings/biothings_explorer/files/11609059/response2.txt)

_Originally posted by @colleenXu in https://github.com/biothings/biothings_explorer/issues/614#issuecomment-1569520281_

**Comment by colleenXu** [comment]
Hmmm, from what I recall:
* I wasn't sure if we could process CHP's response properly, when we do successfully get a response (the EDIT at the end of my post with details)
* Maybe we could let CHP's team know that we're encountering issues when testing our tool with theirs. Maybe they could provide good test queries, explain the query / response formats their KP may be using......and they should know about any bugs or errors we're noticing...

To explore their KP in more detail, I suggest querying their KP directly first. I looked through their tool's YAML (in SmartAPI Registry) + meta_knowledge_graph response to try building queries that their KP would respond to. From what I recall, their KP may only work with ENSEMBL gene IDs, not NCBIGene...

**Comment by tokebe** [comment]
Regardless of this, BTE is producing an error that implies code is improperly handling whatever is returned, so we have some minor fix to do on our side.
