### ISSUE TITLE
update source of FDA orphan drug data

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#709]
Currently, in https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/openapi_full.yml#L1910, we use `infores:drugcentral` as the source for data drawn from the `fda_orphan_drug` section of mychem.info ([example records](https://mychem.info/v1/query?q=_exists_:fda_orphan_drug&fields=fda_orphan_drug)).  However, that data comes from the FDA's "[Orphan Drug Product designation database](https://www.accessdata.fda.gov/scripts/opdlisting/oopd/)", which was ingested into mychem.info in https://github.com/biothings/mychem.info/issues/96.  We'll need to create an infores catalog entry, then update the SmartAPI record accordingly...

**Comment by colleenXu** [comment]
I have everything ready to make this change:
* yaml PR https://github.com/NCATS-Tangerine/translator-api-registry/pull/138
* new infores catalog entry for fda-orphan-drug-db in https://github.com/biolink/biolink-model/pull/1429
* made new infores page for [FDA Orphan Drug Project designation database (primary knowledge source)](https://github.com/NCATSTranslator/Translator-All/wiki/FDA-Orphan-Drug)

However, we may need to wait until the UI is using the new infores catalog entries....before we merge the PR / refresh MyChem's SmartAPI registration...

**Comment by colleenXu** [comment]
The infores stuff is being deployed for this release cycle! 

So we are deploying this change during this release cycle. 
I decided to use an [override](https://github.com/biothings/bte-server/commit/28e5b58938769616cc37aae303d1935eabde5eab) to the yaml in the PR, just in case it takes a while for the UI team to deploy the infores catalog changes in all instances. 

---

I think we can close this issue once:
* the override is deployed to Prod
* the UI is using the updated infores catalog in all instances
* I merge the [yaml PR](https://github.com/NCATS-Tangerine/translator-api-registry/pull/138)

We'll then have a separate process to remove the overrides (not needed once the yaml PRs are all merged / registrations refreshed).

**Comment by colleenXu** [comment]
@tokebe 

I double-checked and it's not working on CI, probably because of the larger cache-update issues ([recent lab Slack convo](https://suwulab.slack.com/archives/CC218TEKC/p1702673534285579))

<details><summary>My test</summary>
<p>

POST to `https://bte.ci.transltr.io/v1/team/Service Provider/query`

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:SmallMolecule"],
                    "ids": ["PUBCHEM.COMPOUND:24889392"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats"]
                }
            }
        }
    }
}
```

ctr-F the response for "infores:fda-orphan-drug-db". There should be edges that have that infores, because they're from the adjusted operations/MetaEdges. (from this [testExample](https://github.com/NCATS-Tangerine/translator-api-registry/blob/77ae9e9dbab7411c4044459d026e8f84cdbbcd3b/mychem.info/openapi_full.yml#L1911))

</p>
</details>

**Comment by tokebe** [comment]
The issue should now be addressed by https://github.com/biothings/biothings_explorer/commit/3019cecf670e5b0fc04877c31956b2bbbc3d7e4e, please test again

**Comment by colleenXu** [comment]
Now it's working on BTE CI! Yay!

**Comment by colleenXu** [comment]
I've confirmed that things work as-expected after the Prod deployment. Closing issue, updating the registered yamls and registrations, and opening another issue for removing the overrides.

Example: POST to https://bte.transltr.io/v1/smartapi/8f08d1446e0bb9c2b323713ce83e2bd3/query, will get a response with `infores:fda-orphan-drug-db` on 1 edge

Query:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:SmallMolecule"],
                    "ids": ["PUBCHEM.COMPOUND:24889392"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats"]
                }
            }
        }
    }
}
```

Edge:
```
                "7b2c53d93e7fe9374115a9f5fbf1d4f2": {
                    "predicate": "biolink:treats",
                    "subject": "PUBCHEM.COMPOUND:24889392",
                    "object": "MONDO:0018874",
                    "attributes": [],
                    "sources": [
                        {
                            "resource_id": "infores:fda-orphan-drug-db",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:mychem-info",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:fda-orphan-drug-db"
                            ]
                        },
                        {
                            "resource_id": "infores:service-provider-trapi",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:mychem-info"
                            ]
                        }
                    ]
                }
```
