### ISSUE TITLE
Allow for disabling of cache time limit by setting the limit to 0

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#720]
It's currently possible to [set a custom cache limit](https://github.com/biothings/biothings_explorer/blob/main/docs/REFERENCE.md#redis_key_expire_time), but not disable the cache limit altogether. This would be a useful feature for some types of testing where we want to eliminate potential KP-induced variables.

Implementation would be centered around changing the [expire handling in the cache handler](https://github.com/biothings/bte_trapi_query_graph_handler/blob/f68184d7c048c5568b50377165855b5c424ed60d/src/cache_handler.js#L248). Setting `REDIS_KEY_EXPIRE_TIME` to `0` should cause an expiry to not be added.

It'd probably also be worth changing the name of the environment variable to something more specific, like `QEDGE_CACHE_TIME_S`, and updating it in the [reference doc](https://github.com/biothings/biothings_explorer/blob/main/docs/REFERENCE.md#redis_key_expire_time).

**Comment by rjawesome** [comment]
See PRs

**Comment by tokebe** [comment]
Deployed to Prod.
