### ISSUE TITLE
Retry after SRIResolverFailure

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#723]
Currently, if BTE encounters an `SRIResolverFailure`, it gives up and the query fails. We should instead retry SRI a few times before giving up. Should only require changes to the [SRI resolver file.](https://github.com/biothings/biomedical_id_resolver.js/blob/main/src/sri.ts)

Might be worth further discussion about potential fallbacks in a future issue.

**Comment by colleenXu** [comment]
Perhaps we can fix the typo for the error or rename the error while we are at it? 

I think the error is currently spelled `SRIResolverFailiure` (failure is misspelled). 

But the tool isnt called the resolver right? maybe it’s maybe more accurate to call it `SRINodeNormFailure`?

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
