### ISSUE TITLE
NodeNorm is sometimes not resolving entities/IDs

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#730]
I've noticed a case of "result merging" not working as-expected. After digging into it this week, I think this originates from something downstream of BTE (ARAX?) and the differences between what they do and the Node Norm response we get for "mitoxantrone" IDs. 

### Basics

There's an [automatic-testing effort](https://arax.ncats.io/devLM/index.html?systest=1) (SRI / NCATS / ARAX?) that includes a "Semantic-Smoke-Test" for multiple sclerosis at the bottom of the page. (Probably based on these [two](https://github.com/NCATSTranslator/SmokeTesting/blob/main/test_sys/test_ars/ars-requests/Drug_may_treat_multipleSclerosis.json) [jsons](https://github.com/NCATSTranslator/SmokeTesting/blob/main/test_sys/test_ars/ars-requests/answers.json)). 

BTE's response in the ARAX UI has 5 results with the same "answer" node ("mitoxantrone" `PUBCHEM.COMPOUND:4212`) but different edges: # 38, 65, 160, 162, 355. 
* [ARAX-UI link](https://arax.ncats.io/devLM/index.html?r=9770eb79-a769-4029-b9cb-01abb06aa981) for BTE's response. Sometimes this page doesn't load, so this is the downloaded response-json [9770eb79-a769-4029-b9cb-01abb06aa981.txt](https://github.com/biothings/biothings_explorer/files/12732247/9770eb79-a769-4029-b9cb-01abb06aa981.txt)
* Note: This issue has likely occurred more than once. I first noticed this 9/20 ([internal lab Slack thread](https://suwulab.slack.com/archives/CC218TEKC/p1695225687638399)). But my investigation this week has been based on a run done 9/21. 

HOWEVER, [BTE's original response (linked in the logs)](https://bte.test.transltr.io/v1/asyncquery_response/XjVq91KcZn) has 5 different answer nodes for those 5 results/edges. 

* 38 has UNII:BZ114NVM5P
* 65 has DRUGBANK:DB01204
* 160 has PUBCHEM.COMPOUND:4212
* 162 has UMLS:C0026259 (only one with a name "mitoxantrone" which comes from BTE's input/output-name addition)
* 355 has CHEMBL.COMPOUND:CHEMBL58

Now it's understandable why BTE wouldn't merge these 5 results. But something downstream of BTE has mutated BTE's response to make those 5 nodes look identical...

#### Node Norm

* BTE's querying NodeNorm prod and [getting no info for these IDs](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=UNII%3ABZ114NVM5P&curie=DRUGBANK%3ADB01204&curie=PUBCHEM.COMPOUND%3A4212&curie=UMLS%3AC0026259&curie=CHEMBL.COMPOUND%3ACHEMBL58&conflate=true). This is why BTE is keeping these 5 IDs as 5 separate results/answers. 
    * specifically, [BTE may be using `https://nodenorm.transltr.io/get_normalized_nodes`](https://github.com/biothings/biomedical_id_resolver.js/blob/b994a4c763e55599f179a0d1a62d585fffe50688/src/sri.ts#L22). That seems like a stable-link way to query NodeNorm prod (https://nodenorm.transltr.io/docs uses the server url `https://nodenorm.transltr.io/1.3`, and this server url is also listed in NodeNorm's [SmartAPI registration](https://smart-api.info/ui/400f7c11028ff36f460af4ea85dc72f5))
    * [NodeNorm CI has the same response, no info](https://nodenorm.ci.transltr.io/1.3/get_normalized_nodes?curie=UNII%3ABZ114NVM5P&curie=DRUGBANK%3ADB01204&curie=PUBCHEM.COMPOUND%3A4212&curie=UMLS%3AC0026259&curie=CHEMBL.COMPOUND%3ACHEMBL58&conflate=true)
* VS [NodeNorm test seems to recognize all 5 IDs as "mitoxantrone" IDs (1 entity)](https://nodenorm.test.transltr.io/1.3/get_normalized_nodes?curie=UNII%3ABZ114NVM5P&curie=DRUGBANK%3ADB01204&curie=PUBCHEM.COMPOUND%3A4212&curie=UMLS%3AC0026259&curie=CHEMBL.COMPOUND%3ACHEMBL58&conflate=true). **I suspect that whatever is happening downstream of BTE is using NodeNorm test**
* I've asked what instance of NodeNorm / server url our tools **should** be using, since I think that's unclear...([Translator Slack thread](https://ncatstranslator.slack.com/archives/CSS752SB0/p1695763598422659))
    * I think this [Translator Slack post from Chris Bizon](https://ncatstranslator.slack.com/archives/CSS752SB0/p1660854756686229) is the guidance we've been following (why we're using the "version-independent prod instance url" for Node Norm) 

#### ARS

I can't tell if the ARS is causing this mutation or not. 

* For the semantic-smoke-test, it seems like "BTE's response in the ARS and before ARAX-UI" is mutated. 
    * trying to view the BTE's response through ARS in ARAX-UI: https://arax.ncats.io/?r=9770eb79-a769-4029-b9cb-01abb06aa981. I can see that result 38 is labeled "mitoxantrone", which is a sign of the mutation. 
    * [ARS-link for BTE's response](https://ars.test.transltr.io/ars/api/messages/9770eb79-a769-4029-b9cb-01abb06aa981). It's tricky to view, but I can ctrl-f and see that there's multiple results with `PUBCHEM.COMPOUND:4212`, which is a sign of the mutation. 
* HOWEVER, today I reran the multiple-sclerosis query through ARS [prod](https://arax.ncats.io/?r=ee72cf48-c6eb-4750-953e-895f9d4c547c) and [test](https://arax.ncats.io/?r=e90dd01c-a8ab-4e8f-aa5d-282fb4f3ae14) (but sent to the ARS through Postman). In both cases, BTE's original response in the ARAX-UI seems to be intact (result 38 is UNII:BZ114NVM5P)

#### Haven't asked about or looked into yet

* ARAX
* UI (are there any downstream effects like "multiple results with the same drug"?)

**Comment by tokebe** [comment]
Superseded by #731, as this issue is otherwise entirely external.
