### ISSUE TITLE
Use instance-equivalent NodeNorm instances

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#731]
Supersedes #730 

BTE presently uses the NodeNorm Production instance in all cases. For clarity in consortium-level testing, BTE should instead use the appropriate instance level of NodeNorm equivalent to the instance BTE is running on, using `INSTANCE_ENV` to decide.

The (known) servers are as follows:

```js
{
ci: "https://nodenorm.ci.transltr.io/1.3",
test: "https://nodenorm.test.transltr.io/1.3",
prod: "https://nodenorm.transltr.io/1.3",
}
``` 

A dev is not advertised, so Dev should probably use the production server if NodeNorm's dev server can't be identified or it is recommended that we don't use it.

**Comment by tokebe** [comment]
Update: The dev instance is `https://nodenormalization-sri.renci.org`, though there is an alternate instance here: `https://nodenormalization-dev.apps.renci.org/1.4`

**Comment by colleenXu** [comment]
Noting the SmartAPI registration of NodeNorm: https://smart-api.info/ui/400f7c11028ff36f460af4ea85dc72f5

**Comment by colleenXu** [comment]
EDIT: these are maybe parameters to consider setting for NodeNorm (that may differ by instance?). But this may also be a side-small-issue or something we don't really consider for now:

<details><summary>conflate=true</summary>
<p>

> 
> And a note @tokebe 
> 
> I think we are not setting `conflate=true` in our queries (a parameter related to gene/protein conflation). 
> 
> However, right now, it looks like we depend on the default behavior which is to conflate 
> * compare this w/ no parameter set: https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=UniProtKB%3AQ08722 UniProtKB ID is a Gene first 
> * w/ this where `conflate=false`: https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=UniProtKB%3AQ08722&conflate=false UniProtKB ID is set to Protein
> 
> EDIT:
> * I'm not sure if we want to set this explicitly or not...

</p>
</details> 

<details><summary>dev has special parameters right now, that might roll out to higher instances over time</summary>
<p>

> @tokebe 
> 
> The [dev](https://nodenormalization-sri.renci.org/docs#/) [instances](https://nodenormalization-dev.apps.renci.org/docs#/default/get_normalized_node_handler_get_normalized_nodes_get) right now have other parameters `drug_chemical_conflate` and `description` (set to `false` by default)
> 
> Right now, I'm not sure we need to worry about them. It's not clear if this issue involves using these non-advertised dev instances. And I think those parameters are used by UI auto-complete input and ARS only right now?
> 
> But in the future, when these parameters are in the ITRB instances, I think we'll want to use `drug_chemical_conflate` aka set it to `true`. Since there's been feedback to "merge all results for the same drug together"...

</p>
</details>

**Comment by colleenXu** [comment]
@tokebe 

The [dev](https://nodenormalization-sri.renci.org/docs#/) [instances](https://nodenormalization-dev.apps.renci.org/docs#/default/get_normalized_node_handler_get_normalized_nodes_get) right now have other parameters `drug_chemical_conflate` and `description` (set to `false` by default)

Right now, I'm not sure we need to worry about them. It's not clear if this issue involves using these non-advertised dev instances. And I think those parameters are used by UI auto-complete input and ARS only right now?

But in the future, when these parameters are in the ITRB instances, I think we'll want to use `drug_chemical_conflate` aka set it to `true`. Since there's been feedback to "merge all results for the same drug together"...

**Comment by colleenXu** [comment]
<details><summary>Note: this is the info from Translator NodeNorm devs, pasted from Translator Slack</summary>
<p>

[Slack link](https://ncatstranslator.slack.com/archives/CSS752SB0/p1695820067047389?thread_ts=1695763598.422659&cid=CSS752SB0)

> Chris Bizon (SRI, Ranking Agent)
> 9/27
> Each component is supposed to be using the nodenorm in that environment.  i.e. prod ars (or prod bte) should call prod nodenorm, dev ars (or dev bte) should call dev nodenorm.    I cannot confirm what is actually happening though.  The smoke tests (MS result) are running in Test, so the relevant nodenorm should be of course, the one in test. https://nodenorm.test.transltr.io/docs

> Gaurav Vaidya (SRI)
> 9/27
> Chris is correct: every environment should be using that environment’s NodeNorm/NameRes. For batch processing and other behind-the-scenes uses, I would default to the production NodeNorm (https://nodenorm.transltr.io/docs) since that should be the most stable and most accurate one. Once the federal government reboots, our top priority will be to make sure we can deploy both NodeNorm and NameRes to ITRB with less than two hours downtime and then to get all the environments updated to our latest changes, which will allow us to push changes much more frequently. I’ll announce breaking changes in [#general](https://ncatstranslator.slack.com/archives/CSS752SB0) and non-breaking changes in [#babel-tools](https://ncatstranslator.slack.com/archives/C05MX1RJ8F4) as they happen.

</p>
</details>

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
