### ISSUE TITLE
x-bte operations: replace BioThings `list_filter` with `jmespath`

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#733]
I've heard that `jmespath` should be used in replacement of `list_filter` for BioThings API querying ([internal lab Slack thread](https://suwulab.slack.com/archives/CC19LHAF2/p1694708538684359?thread_ts=1694707200.488869&cid=CC19LHAF2)). At the moment, `list_filter` behavior is still working and @newgene said a switch-over was not urgent. 

However, to do this replacement / use `jmespath` moving forward, I'd need to review the documentation. I have some links here (some are internal lab slack threads): 
* https://github.com/biothings/biothings.api/commit/31898fac7cd86b5c05520622885a3c0852f2494c
* https://github.com/biothings/pending.api/issues/139
* Slack discussions [here](https://suwulab.slack.com/archives/CC19LHAF2/p1691700201291939?thread_ts=1691601972.355889&cid=CC19LHAF2) and [here](https://suwulab.slack.com/archives/CC218TEKC/p1692990973170839)

I'm not sure if there is other documentation / info out there, or other info I'd need to adjust existing x-bte annotation and use this going forward...

---

`list_filter` was used for https://github.com/biothings/pending.api/issues/101, and was considered part of https://github.com/biothings/pending.api/issues/100 and https://github.com/biothings/mychem.info/issues/153. 

I had asked about an enhancement / update to `list_filter`: https://github.com/biothings/pending.api/issues/101#issuecomment-1450688489 and [this internal lab slack thread](https://suwulab.slack.com/archives/CC19LHAF2/p1694707200488869) and was told that `jmespath` could potentially address this...

**Comment by colleenXu** [comment]
Note: saw [post](https://github.com/biothings/biothings_explorer/issues/489#issuecomment-1741268969) on jmespath design in the JQ stuff, the info may be helpful here. In particular, there's a link to a function's doc string (which may be helpful for understanding what to do for jmespath): https://github.com/biothings/biothings.api/blob/7b83617c40c2f12513a7db6842e5d14adf694039/biothings/web/query/formatter.py#L400

**Comment by colleenXu** [comment]
Rohan mentioned in this [post](https://github.com/biothings/biothings_explorer/issues/316#issuecomment-1740147929) (a reply to [this comment](https://github.com/biothings/biothings_explorer/issues/316#issuecomment-1353669762)) and starting [here](https://github.com/biothings/biothings_explorer/issues/489#issuecomment-1741590832) that JQ may be able to do similar behavior. 

My impression is that:
* JQ can be used for non-BioThings APIs
* BioThings jmespath may be better to use for BioThings APIs? 

But we'd need more discussion before deciding how to proceed + what we want to cover with this issue

**Comment by newgene** [comment]
@colleenXu that sounds like a good plan to proceed.

**Comment by colleenXu** [comment]
Narrowing the scope of this issue to just replacing `list_filter`. Using `jmespath` to write new issues can be >=1 new issues. Same with using JQ to write new operations.

**Comment by colleenXu** [comment]
Note: jmespath seems to be like list_filter, where the fields being acted upon must be included in the initial response (using the parameters.fields). See internal Slack discussion [here](https://suwulab.slack.com/archives/CC19LHAF2/p1675276778761619?thread_ts=1675150823.953269&cid=CC19LHAF2)

> because list_filter is a post-query action, the field we filter on MUST be in the response. So yes, this is required

**Comment by colleenXu** [comment]
There's only 1 API/situation where we are using `list_filter`: MyChem `drugcentral.bioactivity` chem -> gene operations (they were a first use-case). 

Progress so far:
* Should be able to update all the current operations. I could make queries with both `filter` and `jmespath` to retrieve only the parts of records where the action_type is the desired value. Ex: https://github.com/NCATS-Tangerine/translator-api-registry/commit/efd09ee0c323e01b890be4d400212fd100d02e03
* Have a problem with creating equivalent reverse operations. I can create a query with jmespath set to the desired action_type (```drugcentral.bioactivity|[?action_type==`ACTIVATOR`]```) OR to the desired ID (```drugcentral.bioactivity.uniprot|[?contains(uniprot_id, `O75343`)]```) but not both at the same time. 


<details><summary>Example query without the jmespath param set</summary>
<p>

```
curl --location 'https://mychem.info/v1/query?size=20&fields=drugcentral.bioactivity%2Cdrugcentral.xrefs&with_total=true&filter=drugcentral.bioactivity.action_type%3AACTIVATOR&jmespath_exclude_empty=true' \
--header 'Content-Type: application/json' \
--data '{
    "q": ["O75343"],
    "scopes": "drugcentral.bioactivity.uniprot.uniprot_id"
}'
```

</p>
</details>

**Comment by colleenXu** [comment]
Done updating all current operations to use filter/jmespath. ([1 operation](https://github.com/NCATS-Tangerine/translator-api-registry/commit/efd09ee0c323e01b890be4d400212fd100d02e03), [rest of operations](https://github.com/NCATS-Tangerine/translator-api-registry/commit/0a80c628ded1c424562d277a3588b31103d56ceb), [merging/adding new chem -> gene operations](https://github.com/NCATS-Tangerine/translator-api-registry/commit/a15459bc5aecd307c0313712f1ba5c9297f62b5f))

Going to open a different issue to track writing reverse operations (have a possible way to do it). There's also a separate issue for chem-gene data that doesn't have the action_type field #904
