### ISSUE TITLE
Implement OpenTelemetry alongside Sentry

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#741]
The consortium has decided to move forward with teams implementing OpenTelemetry for better interoperable time and error tracing. We should implement this alongside Sentry so that we're interoperable, but still able to get more fine-grained performance metrics.

**Comment by tokebe** [comment]
A few notes, as development in the `bte-concurrency` branches across the workspace has changed how this should be approached:

Development should be done in branches based off the `bte-concurrency` branches. These branches created a new package, `bte-utils`, which centralizes interactions with telemetry wherever possible. This requires non-standard setup to ensure all packages are installed:

```bash
git clone https://github.com/biothings/biothings_explorer
cd biothings_explorer
git checkout bte-concurrency
pnpm run clone
pnpm git checkout bte-concurrency
pnpm i
```

From there, any package that requires changes can be based off that branch (new branches should all use the same name), for example, `bte-server`:

```bash
# from workspace root
cd packages/bte-server
git checkout -b otel
```

Note that most existing span instrumentation for Sentry is done like so:
```js
// If in commonjs: 
// const { Telemetry } = require("@biothings-explorer/utils");
import { Telemetry } from '@biothings-explorer/utils';

const span = Telemetry.startSpan({ description: "someSpanDescription" });
// whatever processing
// optional chaining is important; telemetry should fail silently rather than disrupt execution.
span?.finish();
```

If feasible, it's best to try and handle any manual OTel instrumentation through `packages/utils/src/telemetry.ts`, so that most interactions across the workspace with OTel are abstracted through it, rather than requiring multiple calls to both Sentry and OTel.

**Comment by tokebe** [comment]
Update: for now, the manual instrumentation should be ignored, as we just want a minimal implementation working. Additionally, see the [Translator OTel Development Docs](https://ncatstranslator.github.io/TranslatorTechnicalDocumentation/deployment-guide/monitoring/) for more information on testing and integration with Translator.

**Comment by rjawesome** [comment]
Note: The development docs seem to mention a URL with port 6831 but on the jaeger docker image requests using opentelemetry need to be sent to port 4318 via HTTP. 
Also, I should have a base implementation done by Monday.

**Comment by rjawesome** [comment]
Base implementation located at otel branch, bte-server & biothings_explorer repository

**Comment by tokebe** [comment]
@rjawesome The `otel` branch does not appear to exist in the `bte-server` repository.

**Comment by andrewsu** [comment]
I think that one was a branch on his fork of that repo: https://github.com/rjawesome/bte-server/tree/otel

**Comment by tokebe** [comment]
After review, the code looks promising. @rjawesome Feel free to make a PR as soon as you feel it's ready.

**Comment by tokebe** [comment]
@rjawesome I've merged your PRs. I think the next step is seeing if it's possible to ensure that an instance of `EXEC /v1/query` exists as a child of a given `POST /v1/query` -- there should be a way to manually retrieve and pass the context in from the parent thread to the child thread. You can pass this information via the [initial job creation data](https://github.com/biothings/bte-server/blob/b470ada9acba87ae0329939b0c255672da879ef7/src/controllers/threading/threadHandler.js#L101C15-L101C15).

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
