### ISSUE TITLE
BTE occasionally fails to set TTL for cached qEdges

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#757]
It's been demonstrated that BTE will occasionally "hold onto" some cached qEdges beyond their expected expire time. The most likely explanation for this is that BTE is failing to set an expire time, likely by way of being restarted prior to the expire time being set.

There is a likely better way to handle this, but as redis does not store key age, the simplest naive approach is to just add a cron job that eliminates all cached qEdges after some interval (once a day at midnight?).

**Comment by colleenXu** [comment]
I wonder if this is related to https://github.com/biothings/biothings_explorer/issues/761

EDIT: also linking to our old Slack discussion on [this topic](https://suwulab.slack.com/archives/CC218TEKC/p1698689156638109) and the [slack post](https://suwulab.slack.com/archives/CC218TEKC/p1698785274514469) where @tokebe tried to fix this

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
