### ISSUE TITLE
Recent queries in CI returning validation errors Service Provided SemMedDB attribute_type_ids

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#761]
original issue: https://github.com/NCATSTranslator/Feedback/issues/639

> This recent result:
> https://arax.ci.transltr.io/?r=663047cb-3be8-4d5b-accf-9e269b16528b
> 
> Shows validation errors for multiple actors. At least some of them seem to be traceable to Service Provider:
> ```
> Errors:
> * Knowledge Graph Edge Attribute Type Id Not:
> => Edge has a value that is not a CURIE for attribute_type_id
> 	$ infores:semmeddb -> infores:biothings-semmeddb -> infores:service-provider-trapi -> infores:arax
> 		# original_object_name:
> 		- edge_id: 
> 			PUBCHEM.COMPOUND:72941511[biolink:ChemicalEntity]--biolink:treats->MONDO:0007147[biolink:Disease]
> 			CHEBI:50847[biolink:ChemicalEntity]--biolink:treats->MONDO:0007147[biolink:Disease]
> 			PUBCHEM.COMPOUND:9852188[biolink:Drug|biolink:ChemicalEntity|biolink:MolecularMixture]--biolink:treats->MONDO:0007147[biolink:Disease]
> 			MESH:D007166[biolink:ChemicalEntity]--biolink:treats->MONDO:0007147[biolink:Disease]
> 			UBERON:0008826[biolink:ChemicalEntity]--biolink:treats->MONDO:0007147[biolink:Disease]
> 			CHEBI:26537[biolink:ChemicalEntity]--biolink:treats->MONDO:0007147[biolink:Disease]
> 			MESH:D012739[biolink:ChemicalEntity]--biolink:treats->MONDO:0007147[biolink:Disease]
> ```
> 
> i.e. "original_object_name" is not a CURIE.
>

**Comment by rjawesome** [comment]
This is probably because the SmartAPI yaml for semmedb was outdated (previously there was fields for original_object_name but now that is not the yaml)
The corn job for syncing every 10 minutes only happens in production: https://github.com/biothings/bte-server/commit/3f9d646e2c46e3a3592232d3b6ab7f6b18608105

**Comment by colleenXu** [comment]
Hmmmm the only way I can see this happening is if BTE CI was somehow using the default saved data/predicates files (https://github.com/biothings/bte-server/tree/main/data), which are kinda old (late May 2023). Was there a refresh/restart done on this instance right before this query?

VS in July, original_object_name was removed as an edge-attribute with this commit https://github.com/NCATS-Tangerine/translator-api-registry/commit/bd4d5bc4be44ffed8659bdbd94951aec2edb9aea (see the `semmeddb/version_without_operations.yaml` x-bte-response-mapping changes). 

EDIT:
Or something was going on with SmartAPI Registry at the time? 

I notice the logs within BTE's response are a bit odd. It's listing a lot of TRAPI 1.3 apis, which were removed from the registry months ago (I think? I found a commit where we switched over to using automat trapi 1.4 instances https://github.com/biothings/bte-server/commit/67aacb551dcc4325f7f9608198c186dcae486788) 

![Screen Shot 2023-11-27 at 2 58 34 PM](https://github.com/biothings/biothings_explorer/assets/43731687/2e9749cd-34df-4e41-a94a-ab357f48988e)

**Comment by colleenXu** [comment]
(Note: this post is similar to https://github.com/biothings/biothings_explorer/issues/766#issuecomment-1858703041, but I ran a different test here to check if this issue has been addressed. I think the two issues are basically duplicates though...)

I think this issue with BioThings SEMMEDB is related to cache-update issues: either QEdges https://github.com/biothings/biothings_explorer/issues/757 or smartapi-specs ([recent lab Slack convo](https://suwulab.slack.com/archives/CC218TEKC/p1702673534285579)). 

---

Now that we've deployed code changes to CI, I sent the query in the original issue (included below) to ARS CI. https://arax.ci.transltr.io/?r=bab69f65-6745-4848-ae60-c865b1669c6e

I don't see those validation errors for ARAX or BTE (Aragorn had a 598 error, maybe from a timeout?). And the edges from BioThings SEMMEDDB in BTE's response look correct (has PMIDs, no outdated edge-attributes).

But I think this was "fixed" by the smartapi-specs update in https://github.com/biothings/bte-server/pull/6. I'm not sure if the larger cache-update issues were fixed yet, given the [recent lab Slack convo](https://suwulab.slack.com/archives/CC218TEKC/p1702673534285579)

<details><summary>TRAPI query set to ARS in my test and the original issue</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "t_edge": {
                    "object": "on",
                    "predicates": [
                        "biolink:treats"
                    ],
                    "subject": "sn"
                }
            },
            "nodes": {
                "on": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0007147"
                    ]
                },
                "sn": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                }
            }
        }
    }
}
```

</p>
</details>

**Comment by tokebe** [comment]
Issue should now be completely addressed by https://github.com/biothings/biothings_explorer/commit/3019cecf670e5b0fc04877c31956b2bbbc3d7e4e

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
