### ISSUE TITLE
Implement a maximum batch size

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#762]
In a recent Sentry error, BTE had to terminate a worker thread as it exceeded the NodeJS maximum heap size. The request body was so large that Sentry had truncated it, so it's safe to say that there were a number of IDs that we might want to consider unreasonable.

We should discuss and assign a reasonable maximum for query batch size, such that we can cancel queries which would otherwise disrupt server stability with an HTTP 413 code.

**Comment by colleenXu** [comment]
Adding a quick clarification (? but @tokebe should confirm): this is about TRAPI queries. In this case, they were sent to Service Provider (?) from Aragorn. 

We've previously discussed batch query size (number of IDs per query node?) with the team before (Slack group DMs? I wasn't part of these discussions.)

Note: We currently don't share a batch_size_limit in our TRAPI specs for [Service Provider](https://github.com/NCATS-Tangerine/translator-api-registry/blob/2e38d18cdb809c3b5586fbdd61d07ded2c79d146/biothings_explorer/service-provider-trapi.yaml#L30) or [BTE](https://github.com/NCATS-Tangerine/translator-api-registry/blob/2e38d18cdb809c3b5586fbdd61d07ded2c79d146/biothings_explorer/smartapi.yaml#L24). It might be helpful if we did

**Comment by colleenXu** [comment]
I've [updated the BTE/Service Provider's yamls](https://github.com/NCATS-Tangerine/translator-api-registry/commit/ce1da5a274065803c5455c7d8eca8cc3b2c17fe2) and refreshed their registrations, so we are now advertising the batch-size-limit of 150 (for non-creative-mode queries)

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
