### ISSUE TITLE
Investigate PFOCR options (strict, synonyms, all) for BTE use

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#778]
See convo in https://github.com/biothings/pending.api/issues/148

Currently, the new BioThings PFOCR API with a parameter to choose between strict, synonyms, and all options is on BioThings-Translator-CI  https://biothings.ci.transltr.io/pfocr

We'll want to choose what to use for BTE's regular use (x-bte annotation). And maybe think about the [result-augmentation module](https://github.com/biothings/biothings_explorer/issues/420)? 

Note: also consider adding [pfocrUrl field](https://github.com/biothings/biothings_explorer/issues/510) to x-bte annotation for use. EDIT: see Alex Pico's advice on urls here https://github.com/NCATS-Tangerine/translator-api-registry/issues/132

**Comment by colleenXu** [comment]
These PFOCR options were [defined earlier](https://github.com/biothings/biothings_explorer/issues/510#issuecomment-1730157901):

> The smallest file (suffix, "strict") only includes gene mentions that match an current, official ncbigene symbol. The next largest (suffix, "synonyms") additionally includes matches to known synonyms of individual genes. And the largest (suffix, "all") additionally includes matches to names of complexes, families and other less precise (yet common) references to one or more genes.
> 
> Depending on the use case, I might prefer one over the other. None is universally "better" than the others, imo. For BTE, I might recommend "all" since we want to maximize coverage. However, if the performance becomes an issue, the smaller sets will run faster.

My previous opinion ([lab Slack link](https://suwulab.slack.com/archives/CC218TEKC/p1695331260847869?thread_ts=1695323907.137209&cid=CC218TEKC)) was to use `strict` for BTE one-hops and for any result-augmentation module:

> - we've previously had confusion over "these figures don't actually have these genes in them"
> - we want any pfocr-related-result augmenting / grouping effort to be very performant...since it'll search 1000s of results against a good chunk of the api contents for each query maybe...

**Comment by colleenXu** [comment]
Current examples:

- https://biothings.transltr.io/pfocr/query?q=associatedWith.pmc:PMC3255783&all
- https://biothings.transltr.io/pfocr/query?q=associatedWith.pmc:PMC3255783&synonyms
- https://biothings.transltr.io/pfocr/query?q=associatedWith.pmc:PMC3255783&strict

**Comment by AlexanderPico** [comment]
I vote for using "all" to maximize coverage and possible aggregate-based, pathway-level insights.

As @colleenXu said above, if performance becomes an issue, then we can dial back to "synonyms" and then to "strict". But these are not preferred for biological research reasons.

**Comment by AlexanderPico** [comment]
@ayushi-agrawal-gladstone @khanspers Please share your votes and reasoning on this issue...

**Comment by khanspers** [comment]
Assuming we are voting on "BTE's regular use", I agree with Alex to use "all" unless performance is an issue. But for results-augmentation module, Colleen's point about "these figures don't actually have these genes in them" makes a lot of sense and would argue for "strict" in that usage.

**Comment by ayushi-agrawal-gladstone** [comment]
I agree with Alex and Kristina and vote for using "all" provided there are no performance issues.

**Comment by andrewsu** [comment]
great, let's go with "all" then.  @everaldorodrigo what is the default if no additional parameter is provided (e.g., https://biothings.transltr.io/pfocr/query?q=associatedWith.pmc:PMC3255783)?

**Comment by everaldorodrigo** [comment]
Hi @andrewsu and everybody!

The default is `all`.

Reference:
- https://github.com/biothings/pending.api/blob/8e5a31dea91954f7e101e15b903e35eb3c2bcbf4/config_web/pfocr.py#L29
