### ISSUE TITLE
check README for accuracy

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#78]
@kevinxin90 can you do a review of https://github.com/biothings/biothings_explorer/blob/master/README.md to make sure everything is accurate with the latest changes?  That list of APIs is out of date, right? And are the mapping files drawn from the [NCATS Translator API registry repo](https://github.com/NCATS-Tangerine/translator-api-registry/tree/openapi_2.0)? I thought they were retrieved via a query on the SmartAPI API?

**Comment by kevinxin90** [comment]
README has been updated

https://github.com/biothings/biothings_explorer/blob/master/README.md
