### ISSUE TITLE
Feb 2024 - Remove overrides/changes that are no longer needed

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#784]
Now that the code for the following issues has been deployed in Prod (Feb Translator release), I've merged the SmartAPI yaml changes into the master branch (registered yamls). 
* https://github.com/NCATS-Tangerine/translator-api-registry/pull/136 for https://github.com/biothings/biothings_explorer/issues/640#issuecomment-1858537361
* https://github.com/NCATS-Tangerine/translator-api-registry/pull/134 for https://github.com/biothings/biothings_explorer/issues/584#issuecomment-1842376052
* https://github.com/NCATS-Tangerine/translator-api-registry/pull/138 for https://github.com/biothings/biothings_explorer/issues/709#issuecomment-1858505647

We can now go through the process of removing the overrides https://github.com/biothings/bte-server/pull/4 and https://github.com/biothings/bte-server/commit/28e5b58938769616cc37aae303d1935eabde5eab

**Comment by colleenXu** [comment]
We should be able to add the removal of the [v3 Monarch API](https://github.com/biothings/biothings_explorer/issues/774#issuecomment-1956074150) override https://github.com/biothings/bte-server/pull/16 to this issue + PR. 

It depends on how the timeline of the v3 Monarch API special deployment goes, VS the next release's deployments.

**Comment by colleenXu** [comment]
Adding the revert of https://github.com/biothings/bte_trapi_query_graph_handler/pull/178/, which is no longer needed due to the changes in https://github.com/biothings/api-respone-transform.js/pull/63. See https://github.com/biothings/biothings_explorer/issues/783#issuecomment-1960840587

**Comment by colleenXu** [comment]
So right now we have two PRs to address this issue:
* https://github.com/biothings/bte-server/pull/17
* https://github.com/biothings/bte_trapi_query_graph_handler/pull/180

**Comment by colleenXu** [comment]
The v3 Monarch changes have been deployed to BTE prod and the yaml/registration has been updated. So we can continue the plan to remove the override with this PR. https://github.com/biothings/bte-server/pull/17

However, I've added an additional chore to this PR: updating name of API in API_LIST https://github.com/biothings/bte-server/commit/067b8206b05aff8b2971e7ac3fcf065d28fdc2e6: from "Biolink API" -> "Monarch API" to reflect the SmartAPI yaml update

**Comment by colleenXu** [comment]
Note that we basically probably remove these overrides just to replace them with new overrides for #788

**Comment by tokebe** [comment]
This issue may as well stay open as a rolling issue-- we'll almost constantly have a stream of new overrides that need to be removed as releases make it to Prod.

**Comment by colleenXu** [comment]
Jackson and I discussed this and decided to close this. I'll make another issue for removing the temporary changes and we'll see if the "rolling" format works.

**Comment by colleenXu** [comment]
Now that this is deployed to Prod, I went through and deleted the old SmartAPI yaml branches that were used for overrides.
