### ISSUE TITLE
TRAPI 1.5: update SmartAPI yamls for BTE + Service Provider

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#802]
The SmartAPI yamls for BTE + Service Provider are based on the TRAPI spec, so they'll need updating to TRAPI 1.5. 

Let's wait until we've implemented the major + other minor features of TRAPI 1.5 in Dev/CI, then:
* translator-api-registry repo: make branch/PR with updated SmartAPI yamls + dev/CI server urls. Remove dev/CI server urls from master branch yamls. 
* SmartAPI registry: register those yamls as separate, temporary registrations
* BTE: 
    * copy BTE's updated yaml into bte-server (branch w/ TRAPI 1.5 features)
    * add smartapi exclusions for the temporary registrations

EDIT: did this additional piece - reviewing / addressing-if-still-relevant the old [questions](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1546522475) and [comments](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1551802813) from TRAPI 1.4 issue

**Comment by colleenXu** [comment]
First step of creating the updated yamls is done in branch https://github.com/NCATS-Tangerine/translator-api-registry/pull/149. It also changes BTE's workflow operation to lookup_and_score for https://github.com/biothings/biothings_explorer/issues/485

We'll do the next steps (including removing dev/CI server urls from the master ranch yamls) when we're ready to advertise that we do TRAPI 1.5 for dev/CI instances.

**Comment by colleenXu** [comment]
To address the old [questions](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1546522475)/[comments](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1551802813), I made minor changes to the current yamls ([commit](https://github.com/NCATS-Tangerine/translator-api-registry/commit/56ad649dba0e164e904ae768fa18681d2f9027bf)) and yamls on this branch ([merge](https://github.com/NCATS-Tangerine/translator-api-registry/commit/169b3ce857e327d195d85a217b87cc60e8123038)):
* adjusted BTE yaml's `servers` comments, added short explanation of how test/prod instances are updated
* BTE-specific parameters: 
    * removed [caching](https://github.com/biothings/biothings_explorer/issues/224) (replaced with TRAPI [bypass_cache](https://github.com/biothings/biothings_explorer/issues/799) property?)
    * commented out [dryrun](https://github.com/biothings/biothings_explorer/issues/278) - needs testing to see if it's still working
* add `asyncquery_response` endpoint ([feature PR](https://github.com/biothings/biothings_explorer/pull/612))

**Comment by colleenXu** [comment]
Small, not-important question for Jackson @tokebe: 

It's not clear to me if `log_level` for `asyncquery_response` (and other endpoints like `asyncquery_status`?) is one of our custom request parameters or not. 
* I saw your [old comment](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1551802813) saying it's a "urlquery" and [previous issues](https://github.com/biothings/biothings_explorer/issues/751) / [PRs](https://github.com/biothings/biothings_explorer/pull/393).
* But TRAPI queries have a [log_level property](https://github.com/NCATSTranslator/ReasonerAPI/blob/2b7a0e0a18b1ee97b0ab0c5d6283ab86b83ce12b/TranslatorReasonerAPI.yaml#L275) in the request-body (same level as message, workflow, submitter, etc). 

If it's a custom request parameter, I could add it to our tool's yamls if I know what endpoints it works for / how it behaves. There seems to be some info in that [PR](https://github.com/biothings/biothings_explorer/pull/393)

**Comment by tokebe** [comment]
Yes, we have a custom url query parameter that mimics the TRAPI-spec `log_level` behavior on `/v1/asynquery_status` and `/v1/asyncquery_response`.

**Comment by colleenXu** [comment]
The tasks above are complete:
* dev/ci instances urls are now advertised in the new, temporary TRAPI 1.5.0-beta registrations ([BTE](http://smart-api.info/registry?q=8d97ee37572eaaf9e74df447763fd0c5), [Service Provider](http://smart-api.info/registry?q=a0595049c9a250003c2eced0946d84f6)). They use the [branch PR](https://github.com/NCATS-Tangerine/translator-api-registry/pull/149) yamls
* prod/test instance urls are still in the main TRAPI [1.4.2](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1629687393) registrations  ([BTE](http://smart-api.info/registry?q=dc91716f44207d2e1287c727f281d339), [Service Provider](http://smart-api.info/registry?q=36f82f05705c317bac17ddae3a0ea2f0)). They use the [master](https://github.com/NCATS-Tangerine/translator-api-registry/tree/master/biothings_explorer) branch yamls
* BTE dev/ci is updated ([PR](https://github.com/biothings/bte-server/pull/26)):
    *  using TRAPI 1.5.0-beta yaml as its local copy (has all instance yamls so it doesn't need to be updated later!)
    * smartapi exclusions: add the temporary registrations

View in [ARAX-UI](https://arax.ncats.io/)'s "SmartAPI info" tab (left column menu):

![Screen Shot 2024-04-12 at 2 35 07 PM](https://github.com/biothings/biothings_explorer/assets/43731687/e8b4a41b-4086-43bb-ab33-694c714e605d)

![Screen Shot 2024-04-12 at 2 35 16 PM](https://github.com/biothings/biothings_explorer/assets/43731687/30e59630-0e1a-42df-b863-bcc3d9710f33)


---

**Next steps:** As TRAPI 1.5 is deployed to test/prod, we'll adjust the yamls/registrations.

**Comment by colleenXu** [comment]
I've also updated the BTE/Service Provider yamls to add the log_level parameter ([master branch](https://github.com/NCATS-Tangerine/translator-api-registry/commit/c4129db49f57c082f0abf95ffb751c505edcae00), y[amls on this branch](https://github.com/NCATS-Tangerine/translator-api-registry/pull/149/commits/057acebdc91b1ce00663a58a17aeb8cb46693588)). 

So I'm done following up on the old [questions](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1546522475)/[comments](https://github.com/biothings/biothings_explorer/issues/594#issuecomment-1551802813). Yay!

**Comment by colleenXu** [comment]
TRAPI 1.5 and other features were deployed to Test yesterday. 

So I've updated the yamls/registrations, moving the test instances to the temporary TRAPI 1.5 registrations ([BTE](http://smart-api.info/registry?q=8d97ee37572eaaf9e74df447763fd0c5), [Service Provider](http://smart-api.info/registry?q=a0595049c9a250003c2eced0946d84f6)). They use the [branch PR](https://github.com/NCATS-Tangerine/translator-api-registry/pull/149) yamls.

I also changed the TRAPI version we advertise from "1.5.0-beta" -> "1.5.0". 

View in [ARAX-UI](https://arax.ncats.io/)'s "SmartAPI info" tab (left column menu):

![Screen Shot 2024-05-09 at 12 45 57 PM](https://github.com/biothings/biothings_explorer/assets/43731687/78e51846-ce41-44d8-baa0-41cb81068cc9)


![Screen Shot 2024-05-09 at 12 46 04 PM](https://github.com/biothings/biothings_explorer/assets/43731687/664b756c-34bb-4a4e-b44a-55641b0e449e)

**Comment by colleenXu** [comment]
### Notes on next steps

We may need to update the [TRAPI 1.5 yamls](https://github.com/NCATS-Tangerine/translator-api-registry/pull/149) when TRAPI 1.5 final (not beta) is released which should be at the end of this current sprint ([Translator Slack link](https://ncatstranslator.slack.com/archives/CSS752SB0/p1715277763477829)).

When TRAPI 1.5 is released in Prod:
* registry:
    * add Prod instance to [TRAPI 1.5 yamls](https://github.com/NCATS-Tangerine/translator-api-registry/pull/149), then merge this PR -> this updates the original registrations to TRAPI 1.5
    * delete the temp registrations, refresh the original registrations
* bte-server: **not sure if this needs to be a hot-fix or not**
    * remove the temp registrations from config/smartapi_exclusions.yaml
    * update the local docs/smartapi.yaml (at least will update the TRAPI version from 1.5.0-beta to 1.5.0)

**Comment by colleenXu** [comment]
### Update

TRAPI 1.5.0 final was released today. I've updated the [TRAPI 1.5 yamls](https://github.com/NCATS-Tangerine/translator-api-registry/pull/149) with its [minor updates](https://github.com/NCATS-Tangerine/translator-api-registry/pull/149/commits/8d6286069682cb7f627ad9873fc155aa2c6a39c9) ([compare to TRAPI 1.5.0-beta](https://github.com/NCATSTranslator/ReasonerAPI/compare/v1.5.0-beta...v1.5.0)). And refreshed the temporary registrations using these yamls. 

I've also [updated the local docs/smartapi.yaml](https://github.com/biothings/bte-server/compare/397d8ac49567...6b794a9bd934) but I'm not sure if it's been deployed to CI.

**Comment by colleenXu** [comment]
Update: sprint 2/Octopus has deployed to Prod. 

The registry updates are done and the [chore issue](https://github.com/biothings/biothings_explorer/issues/811#issuecomment-2167365852)'s been updated with removing the SmartAPI exclusions 
* added prod instance urls to https://github.com/NCATS-Tangerine/translator-api-registry/pull/149, then merged this PR -> this updates the original registrations to TRAPI 1.5
* deleted the temp registrations, refreshed the original registrations

---

However, we have an update to the bte-server local copy (see previous comment). I've double-checked, and it's only been deployed on CI right now. 

There's also potential changes to this local copy, if we update the biolink-model version. I'd also like to do a cosmetic edit ("1.5.0" -> 1.5.0 for x-trapi.version) (also noted in https://github.com/biothings/biothings_explorer/issues/788#issuecomment-2162297862)

**Comment by tokebe** [comment]
Related [commit](https://github.com/biothings/bte-server/commit/6b794a9bd9347e86948d70381e4ee11216a83009) deployed to Prod.
