### ISSUE TITLE
document OpenAPI extensions used by BioThings Explorer 

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#81]
Here are a few examples I can find:
 
  - https://docs.microsoft.com/en-us/connectors/custom-connectors/openapi-extensions
  - https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html
  - https://app.swaggerhub.com/help/apis/vendor-extensions

**Comment by kevinxin90** [comment]
BTE extensions are documented here: https://x-bte-extension.readthedocs.io/en/latest/

Since SmartAPI will be used as the Translator registry, all future translator related extensions will be documented here: https://github.com/NCATSTranslator/translator_extensions
