### ISSUE TITLE
KP is returning a curie that wasn't asked for without a query id

### ISSUE THREAD

**Issue by maximusunc** [biothings/biothings_explorer#815]
I can send this curl:
```text
curl -X POST https://api.bte.ncats.io/v1/team/Service%20Provider/query \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": {
    "query_graph": {
      "nodes": {
        "e": {
          "ids": [
            "CHEBI:8382",
            "PUBCHEM.COMPOUND:22420",
            "PUBCHEM.COMPOUND:10150081",
            "CHEBI:4911",
            "CHEBI:74947",
            "UNII:4F4X42SYQ6",
            "CHEBI:28748",
            "CHEBI:63635",
            "UNII:T4H8FMA7IM",
            "CHEBI:9168",
            "CHEBI:52717",
            "CHEBI:10110",
            "CHEBI:28445",
            "CHEBI:72690",
            "PUBCHEM.COMPOUND:135565884"
          ],
          "categories": ["biolink:ChemicalEntity"],
          "set_interpretation": "BATCH",
          "constraints": []
        },
        "i": {
          "ids": null,
          "categories": ["biolink:BiologicalEntity"],
          "set_interpretation": "BATCH",
          "constraints": []
        }
      },
      "edges": {
        "edge_2": {
          "subject": "i",
          "object": "e",
          "knowledge_type": null,
          "predicates": ["biolink:affects"],
          "attribute_constraints": [],
          "qualifier_constraints": [
            {
              "qualifier_set": [
                {
                  "qualifier_type_id": "biolink:object_aspect_qualifier",
                  "qualifier_value": "activity_or_abundance"
                },
                {
                  "qualifier_type_id": "biolink:object_direction_qualifier",
                  "qualifier_value": "decreased"
                }
              ]
            }
          ]
        }
      }
    }
  }
}' > service_provider_response.json
```
And one of the results has CHEBI:4027 as a result for `e` without a query id, even though it was not asked for.

**Comment by tokebe** [comment]
`CHEBI:4027` is obtained from the node normalizer as a primary equivalent of `PUBCHEM.COMPOUND:22420`, with options `conflate:true` and `drug_chemical_conflate:true`, so while it was not explicitly asked for, it was covered by what was explicitly asked for.

**Comment by andrewsu** [comment]
Just a quick note that this equivalency is specifically from the dev instance of nodenorm: https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=PUBCHEM.COMPOUND:22420&drug_chemical_conflate=true -- doesn't appear to be found in ci / test / prod nodenorm, so I wouldn't expect you'd see that result from the other instances of BTE...

**Comment by tokebe** [comment]
I've confirmed that this equivalency is not seen on BTE Prod.

**Comment by colleenXu** [comment]
Found [relevant info (Translator Slack link)](https://ncatstranslator.slack.com/archives/C05MX1RJ8F4/p1713501646885249): NodeNorm Dev was updated 4/19 to use an updated "preferred prefix order", so CHEBI is now preferred over PUBCHEM.COMPOUND. This explains the different primary ID for Dev vs other instances.

**Comment by tokebe** [comment]
@maximusunc Is this sufficient explanation that this issue may be closed?

**Comment by maximusunc** [comment]
No, I think that even if you're giving the primary equivalent back, it's still not giving back what was asked and PUBCHEM.COMPOUND:22420 should be listed as the `query_id`.

**Comment by tokebe** [comment]
Updating from internal discussion, example node binding:

```
{ "id": "CHEBI:4027", "query_id": "PUBCHEM.COMPOUND:22420", "attributes": [] }
```

This can be implemented as a post-pass on node bindings after results assembly.

@maximusunc In the interest of prioritization, can you say how critically this issue affects your team?

**Comment by maximusunc** [comment]
This issue has pointed out that we need to do some extra error checking on our end to make sure all results are expected. We're currently throwing out the entire response, but I think the plan is to just remove any specific results that can't be linked back to the query graph. We're also going to add the drug_conflation flag to our node norm calls. So this isn't super high priority from our end.

**Comment by colleenXu** [comment]
@maximusunc 

To double-check, is this a problem Aragorn is encountering? Or some other tool? 
And NodeNorm is updating to CI later today....so maybe these problems will start happening on CI afterwards? 

I'm wondering if there's a way for your tool to use/send the same primary IDs that our tool is using (we're using the NodeNorm instance corresponding to our tool's instance + setting conflate to true for gene/protein and drug/chem). (Note that we made a change a few months ago to set drug_chemical_conflate to true, after asking Chris Bizon in Slack about it ([issue](https://github.com/biothings/biothings_explorer/issues/787), [Translator Slack link](https://ncatstranslator.slack.com/archives/C013Q5TVC87/p1709141462004739)).) 

Of course, you make a valid point that `query_id` should be used. I wasn't aware of that `query_id` was/should be used this way (oops >.<).

**Comment by maximusunc** [comment]
Aragorn is encountering this, and we're also using the node norm corresponding to the same env, but we're missing the drug/chem conflation flag. We're going to be adding that flag in soon so that our primary IDs will match, so this specific issue will be resolved, but I think it's also good that we uncovered the `query_id` issue as well.

**Comment by tokebe** [comment]
Reopening until deployed to Prod.

**Comment by colleenXu** [comment]
This looks good, based on two quick tests (non-creative mode only):
* used non-primary ID for chemical bortezomib in MVP2 template 1 [bortezomib_decrease_template1_noncanonicalinput.json](https://github.com/user-attachments/files/16556849/bortezomib_decrease_template1_noncanonicalinput.json)
* used non-primary ID for gene HBB in MVP2 template 1 [HBB_decreased_template1_noncanonicalinput.json](https://github.com/user-attachments/files/16556854/HBB_decreased_template1_noncanonicalinput.json)

**Comment by colleenXu** [comment]
Did another quick check and it looks fine (no issues) when "subclassing" is happening: [asthma-direct.json.zip](https://github.com/user-attachments/files/16686117/asthma-direct.json.zip)

<details><summary>TRAPI query</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "creativeQuerySubject": {
                    "categories":["biolink:ChemicalEntity"]
                },
                "creativeQueryObject": {
                    "ids":["HP:0002099"],
                    "categories":["biolink:DiseaseOrPhenotypicFeature"]
               }
            },
            "edges": {
                "eA": {
                    "subject": "creativeQuerySubject",
                    "object": "creativeQueryObject",
                    "predicates": ["biolink:treats_or_applied_or_studied_to_treat"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>Example result with query_id and subclassing edges</summary>
<p>

```
        "results": [
            {
                "node_bindings": {
                    "creativeQuerySubject": [
                        {
                            "id": "CHEBI:2549",
                            "attributes": []
                        }
                    ],
                    "creativeQueryObject": [
                        {
                            "id": "MONDO:0004979",
                            "attributes": [],
                            "query_id": "HP:0002099"
                        }
                    ]
                },
                "analyses": [
                    {
                        "resource_id": "infores:biothings-explorer",
                        "edge_bindings": {
                            "eA": [
                                {
                                    "id": "CHEBI:2549-in_clinical_trials_for-MONDO:0004979-via_subclass",
                                    "attributes": []
                                },
                                {
                                    "id": "b3eefef90eafbee8c08fbcb533b969f8",
                                    "attributes": []
                                },
                                {
                                    "id": "138b157a96461d80ed4b5df893e0fca7",
                                    "attributes": []
                                },
                                {
                                    "id": "CHEBI:2549-preventative_for_condition-MONDO:0004979-via_subclass",
                                    "attributes": []
                                },
                                {
                                    "id": "6ed1883aa125893402e006470efdc1a3",
                                    "attributes": []
                                },
                                {
                                    "id": "dc9a71414fa6fc78f4c163fe11da3537",
                                    "attributes": []
                                },
                                {
                                    "id": "ab1f9ae18d5a1169fe3129b9a792b326",
                                    "attributes": []
                                },
                                {
                                    "id": "CHEBI:2549-treats_or_applied_or_studied_to_treat-MONDO:0004979-via_subclass",
                                    "attributes": []
                                },
                                {
                                    "id": "45a5eb2a6f86e3d1c30b3e0e5cd2b634",
                                    "attributes": []
                                }
                            ]
                        },
                        "score": 0.8807904522443328
                    }
                ]
            },
```

</p>
</details>

**Comment by colleenXu** [comment]
Note: this fix only works for non-creative-mode queries. I tried a creative-mode query and BTE used the primary ID and didn't provide any query_id fields.

**Comment by NeuralFlux** [comment]
@tokebe should I add the fix for creative-mode queries too?

**Comment by tokebe** [comment]
Please do -- you'll have to rebase the branch from main and make a new PR, the fix will have to go to CI next sprint.

**Comment by colleenXu** [comment]
I made a new issue for tracking this change/the new PR. Since its deployment timing will be different. 

So put links/discussion there?

**Comment by tokebe** [comment]
Relevant changes deployed to Prod. Tracking additional work in #855
