### ISSUE TITLE
BTE is failing TRAPI 1.5 validation in CI

### ISSUE THREAD

**Issue by maximusunc** [biothings/biothings_explorer#816]
Looking at this query:
https://ars.ci.transltr.io/ars/api/messages/0cc6b8e1-1814-48b7-b461-98a06574681e
Results from `infores:biothings-explorer` do not have attributes in their result.analyses.edge_bindings.
This is a required field: https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L772

**Comment by maximusunc** [comment]
Result node_bindings are also required to have attributes: https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L679

**Comment by maximusunc** [comment]
Auxiliary Graphs are also required to have attributes:
https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L804

**Comment by tokebe** [comment]
@maximusunc [We're aware of this requirement](https://github.com/biothings/biothings_explorer/issues/801), there must have been a build/deployment error with CI as the related PR is already merged. I'm looking into it.

**Comment by tokebe** [comment]
Confirmed, it was a build issue. [Fixed](https://github.com/biothings/biothings_explorer/commit/a69a7754259c8f42c94113cd6d64dd805e5f4bcc) and changes confirmed.

Closing this issue as it affects the build system rather than deployed images.
