### ISSUE TITLE
TRAPI 1.5: update registrations for TRAPI KPs used

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#817]
@tokebe 

I think dev/CI need updating to use the TRAPI 1.5 registrations of TRAPI KPs. I noticed today that my local instance in "CI" mode retrieves the TRAPI 1.4 Test instances of the TRAPI KPs during the smartapi_sync. 

Basically all the TRAPI KPs now have their Dev/CI instances in new TRAPI 1.5 registrations, which we can see in the "SmartAPI Info" tab of the [ARAX-UI](https://arax.ncats.io/). (Connections Hypothesis Provider only has their dev instance, but I think we can basically ignore that for now. We won't be able to use this registration in CI)

I'm making a PR to address this. Can you see if any other places in the code need adjusting? 
I think it works okay (I used it when [testing Pathfinder earlier](https://github.com/biothings/biothings_explorer/issues/794#issuecomment-2089668086)). 

As for BTE's Test instance....I think we'd have to wait until the TRAPI 1.5 KP registrations advertise the Test instances. Then we may need to ask for a deployment so BTE Test can use those registrations...

**Comment by colleenXu** [comment]
@tokebe I noticed [another part of the code where 1.4 shows up](https://github.com/biothings/bte-server/blob/59c226090138a36791e74c3785dbb79c00566e22/src/controllers/threading/taskHandler.ts#L59) and I couldn't tell if it was a TRAPI 1.4 thing that needed adjustment or not. If it needs adjusting, maybe it can be added to this issue/the PR?

**Comment by tokebe** [comment]
Added a commit to the PR for that, thanks for catching it.

**Comment by colleenXu** [comment]
We aren't using the TRAPI 1.5 registration for CHP (only has the dev instance on it). We'll wait until later when CI/Test instances are added to the registration, and then request patches to Test when needed. 

For all the other TRAPI KPs, we've updated to use their TRAPI 1.5 registrations (dev/CI instances included right now, should add Test instances right after the coordinated-deployment to Test is done).

**Comment by colleenXu** [comment]
Update:
In Dev/CI, we are now using the TRAPI 1.5 registration for CHP. It has dev/CI instances. 

We're not in a hurry to patch this to Test, because the registration currently doesn't have test instances. BTE Test would therefore skip/not use this tool...

**Comment by colleenXu** [comment]
The [TRAPI 1.5 registration for CHP ](https://smart-api.info/ui/412af63e15b73e5a30778aac84ce313f)now has the Test instance ([ARAX-UI view](https://arax.ncats.io/?smartapi=1)). 

![Screen Shot 2024-05-28 at 5 26 32 PM](https://github.com/biothings/biothings_explorer/assets/43731687/75d57069-d9ad-4321-84a0-09046402fc93)

**Comment by colleenXu** [comment]
To make clear...
* The switch to CHP TRAPI 1.5 is **only on CI** right now. https://github.com/biothings/bte-server/pull/29
* But after today's Octopus deployment to Prod, BTE Prod is using TRAPI 1.5 registrations for the other TRAPI KPs. But BTE won't use them if they don't have prod server urls (ref: https://github.com/biothings/biothings_explorer/issues/442).

**Comment by tokebe** [comment]
Related PRs deployed to Prod. @colleenXu good to close this issue?
