### ISSUE TITLE
Deprecate TRAPI v0.9.2 support

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#82]
Should have /query endpoint have the same implementation as /v1/query. 

Probably should use regex when specifying routing. e.g. (v1)?/query

See expressjs routing mechanism: https://expressjs.com/en/guide/routing.html

**Comment by kevinxin90** [comment]
Current implementation: '(/v1)?/query' 

It works, now /query and /v1/query endpoint have the same behavior.

However, the problem is SwaggerValidation no longer works. 

It seems the Swagger Validation middleware we currently use don't support regex as route path.

Need to explore other options to facilitate that.

https://www.npmjs.com/package/express-openapi-validator

**Comment by colleenXu** [comment]
closing since it's probably not relevant now.
