### ISSUE TITLE
`/meta_knowledge_graph` MetaEdge `knowledge_types` cannot be `lookup_and_score`?

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#821]
@andrewsu @tokebe (Follow up on [Andrew's Slack thread](https://suwulab.slack.com/archives/CC218TEKC/p1716587107739779))

According to the [current TRAPI spec](https://github.com/NCATSTranslator/ReasonerAPI/blob/2b7a0e0a18b1ee97b0ab0c5d6283ab86b83ce12b/TranslatorReasonerAPI.yaml#L1338), the `/meta_knowledge_graph` MetaEdges can only have the values `lookup` and/or `inferred` in their `knowledge_types` array. 

But in the code we're deploying to address https://github.com/biothings/biothings_explorer/issues/485, we changed BTE-ARA's`/meta_knowledge_graph` response to use `lookup_and_score` (which is technically correct!). Note that the team-specific / api-specific endpoints still use `lookup`. 

So....there's a question of what to do next:
* bring this up with the TRAPI group? (EDIT: [asked in Translator Slack](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1716922839503729))
* change to use `lookup` for BTE-ARA's `/meta_knowledge_graph` endpoint? (Does this involve changing the SmartAPI yamls?)
* does this need to be a hotfix/patch to Test? It's not clear to me how urgent this is - since it only affects the ARA endpoint
* ~does Retriever also need adjusting?~ DONE: see Jackson's next post.

**Comment by tokebe** [comment]
Retriever has already been adjusted since it doesn't do scoring. This shouldn't be too involved to patch quickly, so I guess it's a matter of what the TRAPI group says.

**Comment by colleenXu** [comment]
We should change this to `lookup`, according to Eric Deutsch (TRAPI group, [Translator Slack link](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1716940052135609)). 

While it doesn't seem to matter much, I imagine we don't want to push the use of `lookup_and_score` to Prod....so we'll want to make changes + deploy them up to Test in the next week or so? @tokebe

**Comment by colleenXu** [comment]
See https://github.com/biothings/bte-server/compare/c5aecdd860e4...397d8ac49567

Not sure of its deployment status right now

**Comment by colleenXu** [comment]
I double-checked and this is deployed on CI right now. But we want this to be deployed to all instances as a fix...

**Comment by tokebe** [comment]
Related PRs deployed to Prod.
