### ISSUE TITLE
Reduce scoring time by limiting NGD timeout

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#826]
*Child of: https://github.com/biothings/biothings_explorer/issues/793*

Currently, individual calls to NGD have no timeout, which means a particularly lengthy NGD call can hold up BTE significantly. We should impose a timeout on individual calls.

It's worth some discussion what we should use as a cutoff -- personally, I think somewhere in the range of 5-10s is reasonable.
Pinging @andrewsu @colleenXu for discussion RE: reducing NGD timeout cutoff.

**Comment by andrewsu** [comment]
What would be the proposed behavior when an NGD call times out?

**Comment by tokebe** [comment]
Whatever NGD scores we were hoping to get back from that particular batch wouldn't be used in the set of NGD scores that we use for edge scoring. So, we'd lose some information useful to scoring, but scoring would continue. Worst case scenario, we'd be scoring without NGD scores, but more likely is that we'd have some UMLS-pair scores, but not for every UMLS pair represented in our response KG.

**Comment by andrewsu** [comment]
... and in the case where some edges in a path have an NGD score and others do not, how does BTE handle that?  Am I remembering correctly that BTE essentially sums up `1/NGD` for all edges, so in cases where NGD was not available, then NGD would essentially be treated as `Inf`? So timeouts would effectively reduce the scores for paths containing those edges.  Do I have that right?

The exact answer isn't important for moving forward with an NGD call-specific timeout -- I think we should move forward with that regardless.  Just want to be sure we have an intuitive understanding of the effect documented in this issue...

**Comment by tokebe** [comment]
For a given edge, we take the average of `1/NGD` for all NGD scores available for the pairs represented in that edge, and then multiply that average by the NGD weight (0.25). This value is then added to the edge score. 

So, some missing scores reduce the quality of the NGD score contributed, but not necessarily the score itself. If an edge has no NGD scores, then the value added to the edge is 0, so it does reduce the score of an edge relative to an edge that does have NGD scores.

We could add something like 0.125 if there are no NGD scores (effectively giving a 'default `1/NGD` score' of 0.5), which would mean actual NGD scores have the capacity to raise *or* lower the edge score?

**Comment by andrewsu** [comment]
super, thanks @tokebe .  Right now, I favor the simplest solution possible, so I suggest _NOT_ having a default value for missing NGD scores.  I think missing an NGD score for a given edge is fine, and the average of the rest of the NGD pairs should be used. In the case where there are _NO_ NGD scores for a given edge, then I'm fine with the score having a zero value for the NGD component...

**Comment by tokebe** [comment]
@rjawesome Could you also add some logs in the case of NGD timeout/other errors?

**Comment by rjawesome** [comment]
> @rjawesome Could you also add some logs in the case of NGD timeout/other errors?

Done.
ex. ``bte:biothings-explorer-trapi:score 306 successful queries, 0 errored queries, 772296 timed out queries. +10s``
There are already existing logs that print the specific error that occurred if applicable (except timeout)

**Comment by tokebe** [comment]
Thanks!

**Comment by tokebe** [comment]
@rjawesome The new log seems to be inaccurate; It's stating `queryPairs.length - sucessCount - errCount` for the number of timed out queries, however, `queryPairs.length` is not representative of the number of queries made, only the number of pairs queried. Could you edit the log to state the actual number of timed out queries, and possible in parentheses the number of pairs? Something along the lines of:

```
# / # / # queries successful / errored / timed out, representing # / # / # pairs
```

**Comment by rjawesome** [comment]
Log is fixed. ex.
``19 / 0 / 3072 queries successful / errored / timed out, representing 4750 / 0 / 767849 pairs``

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
