### ISSUE TITLE
BTE creative-mode: inferred edges should include the qualifier-set from the starting query QEdge

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#834]
Currently: for MVP2 queries (chem - affects - gene), BTE's response has inferred edges with predicate `affects` and no qualifiers. 

![Screen Shot 2024-07-18 at 2 56 27 PM](https://github.com/user-attachments/assets/57a2555d-4574-4343-b634-7174ea048fe7)

However, it looks like the inferred edge should include the qualifier-set specified in the starting query:
* https://github.com/NCATSTranslator/Feedback/issues/758#issuecomment-2123390114 - context: UnSecret
* https://github.com/NCATSTranslator/Feedback/issues/744 - context: Aragorn, but it's tricky to read through and understand
* https://github.com/NCATSTranslator/Feedback/issues/855 - context: discussion here may be related to this

Jackson @tokebe and I agree that it makes sense to make this change. 

----

I've posted to the related Feedback issues involving BTE:
* should be fixed: https://github.com/NCATSTranslator/Feedback/issues/914#issuecomment-2282358299
* should be basically fixed: https://github.com/NCATSTranslator/Feedback/issues/894#issuecomment-2282359112
* **only partially** fixed: https://github.com/NCATSTranslator/Feedback/issues/855#issuecomment-2282352972

**Comment by colleenXu** [comment]
An example:

<details><summary>MVP2-type query - QEdge has `qualifier_constraints.qualifier_set`</summary>
<p>

```
{
  "nodes": {
    "ON": {
      "ids": [
        "NCBIGene:154"
      ],
      "categories": [
        "biolink:Gene"
      ]
    },
    "SN": {
      "categories": [
        "biolink:ChemicalEntity"
      ]
    }
  },
  "edges": {
    "t_edge": {
      "object": "ON",
      "subject": "SN",
      "predicates": [
        "biolink:affects"
      ],
      "knowledge_type": "inferred",
      "qualifier_constraints": [
        {
          "qualifier_set": [
            {
              "qualifier_type_id": "biolink:qualified_predicate",
              "qualifier_value": "biolink:causes"
            },
            {
              "qualifier_type_id": "biolink:object_aspect_qualifier",
              "qualifier_value": "activity_or_abundance"
            },
            {
              "qualifier_type_id": "biolink:object_direction_qualifier",
              "qualifier_value": "decreased"
            }
          ]
        }
      ]
    }
  }
}

```

</p>
</details> 

<details><summary>Current BTE inferred edge in response to this query</summary>
<p>

```
{
  "subject": "CHEBI:15903",
  "object": "NCBIGene:154",
  "predicate": "biolink:affects",
  "sources": [
    {
      "resource_id": "infores:biothings-explorer",
      "resource_role": "primary_knowledge_source"
    }
  ],
  "attributes": [
    {
      "attribute_type_id": "biolink:support_graphs",
      "value": [
        "inferred-CHEBI:15903-affects-NCBIGene:154-support0"
      ]
    },
    {
      "attribute_type_id": "biolink:knowledge_level",
      "value": "prediction"
    },
    {
      "attribute_type_id": "biolink:agent_type",
      "value": "computational_model"
    }
  ]
}

```

</p>
</details> 

<details><summary>What we want: BTE inferred edge with qualifier-set from starting query</summary>
<p>

```
{
  "subject": "CHEBI:15903",
  "object": "NCBIGene:154",
  "predicate": "biolink:affects",
  "qualifiers": [
    {
      "qualifier_type_id": "biolink:qualified_predicate",
      "qualifier_value": "biolink:causes"
    },
    {
      "qualifier_type_id": "biolink:object_aspect_qualifier",
      "qualifier_value": "activity_or_abundance"
    },
    {
      "qualifier_type_id": "biolink:object_direction_qualifier",
      "qualifier_value": "decreased"
    }
  ],
  "sources": [
    {
      "resource_id": "infores:biothings-explorer",
      "resource_role": "primary_knowledge_source"
    }
  ],
  "attributes": [
    {
      "attribute_type_id": "biolink:support_graphs",
      "value": [
        "inferred-CHEBI:15903-affects-NCBIGene:154-support0"
      ]
    },
    {
      "attribute_type_id": "biolink:knowledge_level",
      "value": "prediction"
    },
    {
      "attribute_type_id": "biolink:agent_type",
      "value": "computational_model"
    }
  ]
}

```

</p>
</details>

**Comment by tokebe** [comment]
Deployed to dev. Appears to be behaving properly.

**Comment by colleenXu** [comment]
I see one issue on our end: **the inferred edge's qualified_predicate has a formatting issue (missing biolink prefix)**. 

response: [permethin_increases_gene.json.zip](https://github.com/user-attachments/files/16555546/permethin_increases_gene.json.zip)
You'll need to use jless to view this, since [ARAX-CI UI](https://arax.ci.transltr.io/) isn't properly showing the inferred edge qualifier sets. 

<details><summary>example inferred edge, look at qualified_predicate value</summary>
<p>

This is the first result's inferred edge `"inferred-CHEBI:34911-affects-NCBIGene:7124"`

```
{
  "subject": "CHEBI:34911",
  "object": "NCBIGene:7124",
  "predicate": "biolink:affects",
  "sources": [
    {
      "resource_id": "infores:biothings-explorer",
      "resource_role": "primary_knowledge_source"
    }
  ],
  "attributes": [
    {
      "attribute_type_id": "biolink:support_graphs",
      "value": [
        "inferred-CHEBI:34911-affects-NCBIGene:7124-support0"
      ]
    },
    {
      "attribute_type_id": "biolink:knowledge_level",
      "value": "prediction"
    },
    {
      "attribute_type_id": "biolink:agent_type",
      "value": "computational_model"
    }
  ],
  "qualifiers": [
    {
      "qualifier_type_id": "qualified_predicate",
      "qualifier_value": "causes"
    },
    {
      "qualifier_type_id": "object_aspect_qualifier",
      "qualifier_value": "activity_or_abundance"
    },
    {
      "qualifier_type_id": "object_direction_qualifier",
      "qualifier_value": "increased"
    }
  ]
}
```

</p>
</details> 

<details><summary>Query I ran</summary>
<p>

from an example in https://github.com/biothings/biothings_explorer/issues/842#issue-2439391488

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "start": {
                    "categories": ["biolink:ChemicalEntity"],
                    "ids": ["CHEBI:34911"]
                },
                "end": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "t_edge": {
                    "subject": "start",
                    "object": "end",
                    "predicates": ["biolink:affects"],
                    "knowledge_type": "inferred",
                    "qualifier_constraints": [
                        {
                            "qualifier_set": [
                                {
                                    "qualifier_type_id": "biolink:qualified_predicate",
                                    "qualifier_value": "biolink:causes"
                                },
                                {
                                    "qualifier_type_id": "biolink:object_aspect_qualifier",
                                    "qualifier_value": "activity_or_abundance"
                                },
                                {
                                    "qualifier_type_id": "biolink:object_direction_qualifier",
                                    "qualifier_value": "increased"
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

</p>
</details> 

FYI: This ARAX UI issue is happening even if I fix the qualified_predicate values (use `sed` to find-replace, adding the biolink-prefix). I've let Eric Deutsch know in this [Translator Slack thread](https://ncatstranslator.slack.com/archives/CSS752SB0/p1723175512352939?thread_ts=1723148060.767219&cid=CSS752SB0) and attached the fixed json.

**Comment by colleenXu** [comment]
It looks good and [is deployed to CI](https://github.com/biothings/biothings_explorer/commit/63c7b1936554ea2113e5577dcf45af40461982cc)! Now response's creative-mode inferred edges have `qualified_predicate` values with the biolink prefix (`biolink:causes`). 

I did local testing, using the latest main branches (key commit is [this one](https://github.com/biothings/bte_trapi_query_graph_handler/commit/6a8d1e52cfc0b1b4ed659fda1dfabc468bf152ee)?).

I also tested after deploying, sending a query to the UI-CI and it worked as-intended. See https://github.com/NCATSTranslator/Feedback/issues/914#issuecomment-2282358299

I've posted to the related Feedback issues involving BTE:
* should be fixed: https://github.com/NCATSTranslator/Feedback/issues/914#issuecomment-2282358299
* should be basically fixed: https://github.com/NCATSTranslator/Feedback/issues/894#issuecomment-2282359112
* **only partially** fixed: https://github.com/NCATSTranslator/Feedback/issues/855#issuecomment-2282352972

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
