### ISSUE TITLE
update Translator documentation

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#836]
Update https://ncatstranslator.github.io/TranslatorTechnicalDocumentation/ (repo at https://github.com/NCATSTranslator/TranslatorTechnicalDocumentation)

Deadline Aug 23 (Sprint 5)

**Comment by colleenXu** [comment]
Notes from weekly meeting today:

JC @tokebe: can get done during a dedicated 1-on-1 with CX @colleenXu 
- Under "Autonomous Relay Agents", need a BTE page
- [Service Provider page](https://ncatstranslator.github.io/TranslatorTechnicalDocumentation/architecture/kp/service_provider/) - copy what's in [wiki](https://github.com/NCATSTranslator/Translator-All/wiki/Service-Provider/)

**Comment by andrewsu** [comment]
The to-be-created BTE page can also be copied from the [corresponding page on the wiki](https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-Explorer-(BTE))...

**Comment by tokebe** [comment]
PR made here: https://github.com/NCATSTranslator/TranslatorTechnicalDocumentation/pull/59
