### ISSUE TITLE
Creative-mode results: handling "direct edges" that "don't match" the starting query QEdge

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#839]
### Background

Currently in creative-mode, BTE creates "inferred" edges and support-graphs for template results that are "multi-hop" (longer than the starting QGraph that is 1-edge long). However, if the template result is also 1-edge long ("direct edge"), BTE doesn't do this - instead, it binds the "direct edge" to the starting QEdge. (From [this issue](https://github.com/biothings/biothings_explorer/issues/615#issuecomment-1542718923))

This works fine when the "direct edge" matches the starting QEdge's predicate (and qualifier-constraints if present). Matches = exact or descendant in biolink-model (for predicate and qualifier value) and all qualifier types in the constraint set are present

### Problem + Ask

But we are getting feedback that this is confusing when the "direct edge" doesn't match:
* https://github.com/NCATSTranslator/Feedback/issues/872#issuecomment-2240023337
* https://github.com/NCATSTranslator/Feedback/issues/871#issuecomment-2240027490

<details><summary>This "not matching" happens because some of our "direct edge" query-templates use more general predicates than the starting query QEdge</summary>
<p>

* [1st "treats" template](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/data/templates/Drug-treats-Disease/Chem-treats-DoP.json) uses `treats_or_applied_or_studied_to_treat` rather than `treats`
* [5th "chem affects gene" template](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/data/templates/Chem-physically_interacts-Gene.json) uses `physically_interacts_with` rather than affects+qualifer-set. 

</p>
</details> 

So we're being asked to treat these "not-matching direct edges" as "inferences" with "inferred" edges and support-graphs (like the multi-hop template results). 

Previously noted in https://github.com/NCATSTranslator/Feedback/issues/744#issuecomment-2230146117

----

Related Feedback issues involving BTE:
* our part should be fixed (cystic fibrosis): https://github.com/NCATSTranslator/Feedback/issues/871#issuecomment-2290944295
* our part should be fixed (cystic fibrosis): https://github.com/NCATSTranslator/Feedback/issues/872#issuecomment-2290946702
* our part should be fixed: https://github.com/NCATSTranslator/Feedback/issues/865#issuecomment-2290953128
* partially fixed: https://github.com/NCATSTranslator/Feedback/issues/907#issuecomment-2292897329

**Comment by colleenXu** [comment]
Potential complications/side-issues:
* what about the "inferred edges" made when BTE has a "direct edge" to a descendant ID (subclass)? We currently assign these "inferred edges" the same predicate/qualifier-set (?) as their underlying direct edges....but if they are bound to the starting QEdge, they may also not match it...
* ~I recall wanting to consolidate: creating only 1 "inferred" edge for each creative-mode result, maybe merging "support-graphs" so not as many are made....but I can't find a previous issue/github comment discussion.~

EDIT: after Thurs 7/25 discussion, Jackson and I agreed that my 2nd point isn't happening/isn't relevant:
* we do only create 1 "inferred" edge for each creative-mode result. 
* That "inferred" edge has separate support-graphs for each original template result, and that's useful for debugging / keeping the different reasoning of each template separate

**Comment by tokebe** [comment]
My recollection is that we didn't want direct edges hidden behind inferred edges in the past, mostly because we didn't expect this situation and it seemed redundant...I think, given current circumstances, it makes sense to change this.

> what about the "inferred edges" made when BTE has a "direct edge" to a descendant ID (subclass)? We currently assign these "inferred edges" the same predicate/qualifier-set (?) as their underlying direct edges....but if they are bound to the starting QEdge, they may also not match it...

Currently, if this happens with an otherwise single-hop template, we just bind the (subclass-)inferred edge normally, which runs into the potential mismatch problem you describe. If it happens in a multi-hop template, we just end up with nested support graphs and everything's fine. If we change behavior for single-hop templates, it'd just end up being nested support graphs again, which isn't a problem? UI can't currently handle nested support graphs, but (AFAIK) they [intend to](https://github.com/NCATSTranslator/Feedback/issues/831#issuecomment-2239776752).

> I recall wanting to consolidate: creating only 1 "inferred" edge for each creative-mode result, maybe merging "support-graphs" so not as many are made....but I can't find a previous issue/github comment discussion.

I'm not sure what you mean by this...we already do consolidate same-answers under the same result (except for direct edges), though we don't merge support graphs. We _could_ do that, but it might cause increased complexity for other things (I'm mostly thinking of Pathfinder).

---

Personally, I'm of the opinion that we just remove the special handling for one-hop templates in the inferred-mode merging code and leave it at that; No extra complexity added, minimal implementation effort.

**Comment by colleenXu** [comment]
### Clarifying and Examples 

(from Thurs 7/25 discussion with Jackson)

We've been doing "special handling" for single-hop templates so their results aren't "wrapped"/nested in support-graphs on inferred edges. 

Given this issue, we could change to ONLY doing this "special handling" in "match" scenarios like these....
Notes: 2nd example uses **descendant predicate**. 4th example uses **descendant qualifier** (activity, vs starting QEdge uses activity_or_abundance)

```
Chem    -"treats"->    Disease 

Chem    -"ameliorates_condition"->    Disease 

Chem    -"treats" (support-graph for subclassing)->    Disease  
Chem    -"treats"->    Subclass Disease    -"subclass_of"->   Disease

Chem    -"affects" + "qualifiers: causes increased activity"->    Gene
```

---

And for "non-match" scenarios, we don't want special handling. So the "wrapping"/nesting should happen, like this: 

```
Chem    -"treats" (NEW support-graph)->    Disease  
Chem    -"treats_or_applied..."->    Disease 

Chem    -"treats" (NEW support-graph)->    Disease  
Chem    -"treats_or_applied..." (support-graph for subclassing)->    Disease  
Chem    -"treats_or_applied..."->    SubclassDisease    -"subclass_of"->    Disease

Chem    -"affects" + qualifiers: same as starting QEdge (NEW support-graph)->    Gene
Chem    -"physically_interacts_with"->    Gene
```

**Comment by tokebe** [comment]
I'm a little confused at how qualifiers work into this...so, special handling if predicate+qualifiers match/are descendant, and no special handling if qualifiers don't match? Or...?

We didn't exactly discuss qualifiers during our discussion, though it makes sense to take them into account...

**Comment by colleenXu** [comment]
I assume you're asking about the last examples in each set? Does the following help clarify things?

---

I was thinking of not keeping special handling when `Chem    -"physically_interacts_with"->    Gene`.
Because this "direct" edge can come from MVP2 template 5 (used by increases + decreases) and is more general than the starting query. 
So I think it makes sense to wrap it in a `Chem    -"affects" + qualifiers: same as starting QEdge (NEW support-graph)->    Gene`

As for keeping special handling for `Chem    -"affects" + "qualifiers: causes increased activity"->    Gene`...
I was assuming that this entire set of qualifier types is present in the starting QEdge + the values are either exact matches or descendant (ex: activity). 
But on re-reading, I guess it's fine to do: "all types in the starting QEdge should be present in the KG edge w/ value matching, but don't need the vice versa". AKA "the actual KG edge can have more types and that's okay"

**Comment by colleenXu** [comment]
I don't think all requirements are being met. 

In this response [permethin_increases_gene.json.zip](https://github.com/user-attachments/files/16556525/permethin_increases_gene.json.zip), **I see 4 cases** where matching "direct" edges are being wrapped in a support-graph on the inferred edge - rather than being specially handled. 

You can paste into [ARAX-CI GUI](https://arax.ci.transltr.io/) to view these cases. 

<details><summary>99th result NR1I2 - Support-graph contains two matching "direct" edges, one of which uses "activity"</summary>
<p>

Trace:
99th result is NR1I2 (NCBIGene:8856)
Result edge binding is `inferred-CHEBI:34911-affects-NCBIGene:8856`
Look at first support-graph: `inferred-CHEBI:34911-affects-NCBIGene:8856-support0`...

In this support graph are two "direct" edges that are both matching:
* one is an exact match (causes increased activity_or_abundance)
* one uses "activity" which is a descendant of activity_or_abundance ([ref](https://github.com/biolink/biolink-model/blob/0ad36e8a62173d33e8848cefa7b3d3cdf35b7a4e/biolink-model.yaml#L11529))

</p>
</details> 

<details><summary>60th result GFAP - Support-graph contains two matching "direct" edges, one of which uses "expression"</summary>
<p>

Trace:
60th result is GFAP (NCBIGene:2670)
Result edge binding is `inferred-CHEBI:34911-affects-NCBIGene:2670`
Look at first support-graph: `inferred-CHEBI:34911-affects-NCBIGene:2670-support0`...

In this support graph are two "direct" edges that are both matching:
* one is an exact match (causes increased activity_or_abundance)
* one uses "expression" which is a descendant of activity_or_abundance ([ref](https://github.com/biolink/biolink-model/blob/0ad36e8a62173d33e8848cefa7b3d3cdf35b7a4e/biolink-model.yaml#L11531))

</p>
</details> 

<details><summary>41st SOD1 and 114th ESR1 - Support-graph contains one matching "direct" edge, which uses "activity"</summary>
<p>

Trace:
41st result is SOD1 (NCBIGene:6647), 114th result is ESR1 (NCBIGene:2670)
Look at inferred edges' first support-graphs: `inferred-CHEBI:34911-affects-NCBIGene:6647-support0` or `inferred-CHEBI:34911-affects-NCBIGene:2670-support0`

These support graphs have 1 "direct" edge that is a match: it uses "activity" which is a descendant of activity_or_abundance ([ref](https://github.com/biolink/biolink-model/blob/0ad36e8a62173d33e8848cefa7b3d3cdf35b7a4e/biolink-model.yaml#L11529))

</p>
</details>

**Comment by colleenXu** [comment]
@tokebe 

I ended up [deploying the latest main code to CI](https://github.com/biothings/biothings_explorer/commit/63c7b1936554ea2113e5577dcf45af40461982cc), but **now things seem worse** - with all "direct" edges wrapped in a support-graph.

I tested the latest main branches (key commit is https://github.com/biothings/bte_trapi_query_graph_handler/commit/29bab451c2f4b19a75cb85fb9aeed709599d8291?). 

In [permethrin_increases_08_10.json.zip](https://github.com/user-attachments/files/16571285/permethrin_increases_08_10.json.zip):
* 1st result (TNF) now has a support-graph wrapping a direct, exact-match edge (`inferred-CHEBI:34911-affects-NCBIGene:7124-support0` ➡️  `b0eeb947231761bc663b6c9b91cd84c5`)
* all the previous examples still exist (just diff rankings):
    * 93rd result is NR1I2 
    * 58th is GFAP
    * 38th SOD1, 110th ESR1

The first result of [HBB_decreased_8_10.json](https://github.com/user-attachments/files/16571291/HBB_decreased_8_10.json), bortezomib (CHEBI:52717), also shows a support-graph wrapping a direct, exact-match edge: `inferred-CHEBI:52717-affects-NCBIGene:3043-support0` ➡️ `3dd44869ab41a7d078a1f2e52a72e122`. 

You can also see this in CI after deployment: look at the 2nd result (INS) of https://arax.ci.transltr.io/?r=8285b0ac-9200-4c50-8aab-27c2cc331536. This was run from UI-CI.

**Comment by tokebe** [comment]
Pushed another fix. I screwed up some of the qualifier handling logic which led to this behavior >.<

**Comment by colleenXu** [comment]
In MVP1 cases, I think the direct "treats" edges are still wrapped in support-graphs, when they should be specially-handled (not in support-graphs) instead. 

response: [cystic-fibrosis.json](https://github.com/user-attachments/files/16595870/cystic-fibrosis.json)

<details><summary>Example</summary>
<p>

Trace:
In the first result (mannitol, CHEBI:16899), the first-level edge has the support-graph `inferred-CHEBI:16899-treats-MONDO:0009061-support0`
Inside that support-graph, one of the edges is `52b96aa533453d5c7d01b26b84d27bb0` which is  "treats" - a direct match. The other edges are fine and should be in the support-graph ([parent or cousin predicates](https://biolink.github.io/biolink-model/treats_dag.html) of treats, not matching). 

![Screen Shot 2024-08-13 at 12 32 49 AM](https://github.com/user-attachments/assets/df31608a-ae17-4588-bec2-e782b3d7d705)

</p>
</details> 

The 3rd result (Elexacaftor, PUBCHEM.COMPOUND:134587348) is a similar example. It's "direct matching" edge is `6334c1255e89922ed09333ff76811af3`. 

----

In MVP2 cases, I think it's working as-intended.

<details><summary>Ex 2: direct matching edges aren't wrapped, but direct non-matching `physically_interacts_with` edge is</summary>
<p>

response: [HBB_decreased_fixed.json](https://github.com/user-attachments/files/16595390/HBB_decreased_fixed.json)

1st result (bortezomib, CHEBI:52717) has a direct-match edge (predicate + qualifier-set) that is specially-handled - not wrapped. 

![Screen Shot 2024-08-12 at 11 51 24 PM](https://github.com/user-attachments/assets/91e9a0ee-db1c-479f-9d7e-2fca3f4cf96e)

VS 11th result (gallic acid, CHEBI:30778) has an inferred edge/support graph for a direct "physically interacts with" edge, `7b4f6b078afbbd4aefab6e576cb93daa`

![Screen Shot 2024-08-12 at 11 52 08 PM](https://github.com/user-attachments/assets/c856d61f-a64e-4a7c-aeed-4c7d2a603dd8)

And there's another interesting example from another query's first result (F2, NCBIGene:2147):
[lepirudin-decreases.json](https://github.com/user-attachments/files/16595777/lepirudin-decreases.json)
* direct edge isn't wrapped - and it has an extra qualifier (causal mechanism)
* inferred edge has two physically_interacts_with edges inside. 

![Screen Shot 2024-08-13 at 12 19 11 AM](https://github.com/user-attachments/assets/2e0e7bd2-caba-42de-98f5-086fd668d214)

![Screen Shot 2024-08-13 at 12 19 32 AM](https://github.com/user-attachments/assets/f9ef06f9-48f9-49eb-ad1d-df0c750b98da)

</p>
</details> 


<details><summary>Ex 3: direct matching edges (descendant qualifier values) aren't wrapped</summary>
<p>

response: [permethrin_increases_fixed.json.zip](https://github.com/user-attachments/files/16595456/permethrin_increases_fixed.json.zip)

38th SOD1 has a direct "causes increased **activity**" edge that isn't wrapped.  

![Screen Shot 2024-08-12 at 11 53 56 PM](https://github.com/user-attachments/assets/f7137557-1463-46e3-b593-0266b2f34a38)

</p>
</details>

**Comment by colleenXu** [comment]
@tokebe 

And I notice something odd with Example 3 (permethrin). In my [previous](https://github.com/biothings/biothings_explorer/issues/839#issuecomment-2277211828) comments, I noted two "direct matching" edges each for NR1I2 and GFAP. But in the [latest "fixed" run](https://github.com/biothings/biothings_explorer/issues/839#issuecomment-2285462320), there's only 1 "direct matching" edge each. 

I wonder if somehow only 1 of the "direct edges" for a result is being kept. And this reminds me of the "direct edge sometimes has different sources" phenomenon we previously discussed. 

<details><summary>Details</summary>
<p>

For GFAP, the two previous "direct matching" edges were: 
* `a3bbb5a9a1473ae3e12b482d2faec6f6`: causes increased **expression**, from automat ctd. **Latest response only has this direct edge.** 
* `622392a94555d597c25d80f6aa3e7b3a`: causes increased **activity_or_abundance**, from text-mining targeted

For NR1I2, the two previous "direct matching" edges were: 
* `a53ef5c02903fd22ba74c48f498b6b57`: causes increased **activity**, from automat ctd. **Latest response only has this direct edge.** 
* `f894dc372b092cff4406af11a9af5a51`: causes increased **activity_or_abundance**, from text-mining targeted

</p>
</details>

**Comment by tokebe** [comment]
I'm unable to replicate this. On both CI and local on the latest main branches, I see mannitol as the second result, with **only** a direct-edge, not nested behind an inferred edge. What I do see is that said edge has the wrong KL/AT, presumably because that's being applied without consideration for special handling.

**Comment by colleenXu** [comment]
Summarizing the situation so far...
* Before this issue: with one-hop templates, we kept their results' edges as-is (no wrapping in "creative-mode" support-graphs). This caused issues for the UI: 
    * "non-matching" edges would show up in the "lookup" section 
    * our data would be in a separate path in the "inferred" section, rather than merged with the other ARAs
* We tried to address this, but...first, BTE wasn't keeping the "matching" edges as-is (no wrapping) - noted [here](https://github.com/biothings/biothings_explorer/issues/839#issuecomment-2282344806) and [here](https://github.com/biothings/biothings_explorer/issues/839#issuecomment-2285462320)

Then we discovered that the "direct" edges were missing/being dropped, due to a faulty assumption/design when [implementing support-graphs](https://github.com/biothings/biothings_explorer/issues/615#issuecomment-1542718923) last year. Jackson will describe this in more detail in another comment.

**Comment by colleenXu** [comment]
I've tested creative-mode after the latest [commit](https://github.com/biothings/bte_trapi_query_graph_handler/commit/5789f6c0ff426fbcbcbf01a5fa061687f094ea56) was [deployed to CI](https://github.com/biothings/biothings_explorer/commit/5741c21c8e38e331a86dfd67d279258a2e7021a0) (Aug 14th ~9:20 AM pacific time)

And everything looks as-intended, YAY! 

### Testing MVP1 treats

Responses: [cystic-fibrosis-fixed.json.zip](https://github.com/user-attachments/files/16629832/cystic-fibrosis-fixed.json.zip) and [skin-vascular-disease.json.zip](https://github.com/user-attachments/files/16629848/skin-vascular-disease.json.zip)

#### "Matches" are kept as-is, not wrapped in creative-mode way
<details><summary>treats</summary>
<p>

![Screen Shot 2024-08-15 at 12 53 57 AM](https://github.com/user-attachments/assets/b3ca9f8e-018b-4446-90be-3e6528cac5c4)

</p>
</details>  
<details><summary>Descendant of treats (ameliorates, preventative)</summary>
<p>

![Screen Shot 2024-08-15 at 12 57 06 AM](https://github.com/user-attachments/assets/767bfa4e-72e7-453e-9eba-2221002dd426)

</p>
</details> 
<details><summary>treats subclass</summary>
<p>

Notice the KL/AT for the "inferred" edge - this is a set ONLY for subclassing, not for "creative-mode". So BTE has handled this properly by not wrapping it more. 

![Screen Shot 2024-08-15 at 1 08 15 AM](https://github.com/user-attachments/assets/b17f9c21-1944-492c-aec5-0a38ed61f2fa)

</p>
</details> 

#### "Non-matches" are wrapped

<details><summary>"other treats predicates"</summary>
<p>

![Screen Shot 2024-08-15 at 12 54 56 AM](https://github.com/user-attachments/assets/0cd35453-b9a6-4417-acc4-30be4346a0dc)

</p>
</details> 
<details><summary>"other treats predicates" subclass</summary>
<p>

Hard to show in screenshots because ARAX-CI UI doesn't show this nested subclassing properly. 

All of the wrapped edges here are in-turn wrapping their own subclass stuff. 
![Screen Shot 2024-08-15 at 1 21 55 AM](https://github.com/user-attachments/assets/3856aabb-0628-49ce-bdfa-c445ec2e9ad7)

Here's one of those edges, which has its own support-graphs from subclassing (nested support-graphs). 

![Screen Shot 2024-08-15 at 1 27 21 AM](https://github.com/user-attachments/assets/454dd398-2d54-4d2d-88c1-dd4aff99b1cf)

</p>
</details> 


### Testing MVP2 chem affects gene

Queries:  [I'm having trouble uploading files. I'll upload them later if I remember to.]
* [increases-ADRB2-fixed.json.zip](https://github.com/user-attachments/files/16629854/increases-ADRB2-fixed.json.zip)
* [decreases-HBB-fixed.json.zip](https://github.com/user-attachments/files/16629857/decreases-HBB-fixed.json.zip)
* [permethrin-increases-fixed.json.zip](https://github.com/user-attachments/files/16629861/permethrin-increases-fixed.json.zip)
* [lepirudin-decreases-fixed.json](https://github.com/user-attachments/files/16629876/lepirudin-decreases-fixed.json)


#### "Matches" are kept as-is, not wrapped in creative-mode way

<details><summary>Exact</summary>
<p>

![Screen Shot 2024-08-15 at 1 44 00 AM](https://github.com/user-attachments/assets/18938c71-d719-4947-bcc8-8b3135e5a4b1)

</p>
</details> 
<details><summary>Uses descendant qualifier values, extra qualifier values</summary>
<p>

"activity" as a descendant of "abundance_or_activity"
extra qualifier value is causal mechanism

![Screen Shot 2024-08-15 at 1 44 29 AM](https://github.com/user-attachments/assets/83542e37-88e2-4a20-976d-7207b11a2254)

also

![Screen Shot 2024-08-15 at 2 04 04 AM](https://github.com/user-attachments/assets/5d824f52-06af-4738-a734-f41ef2b23fcc)

</p>
</details> 

#### "Non-matches" are wrapped

<details><summary>physically interacts with</summary>
<p>

![Screen Shot 2024-08-15 at 1 49 35 AM](https://github.com/user-attachments/assets/a526eeae-ed2d-47de-8092-39ce48d1f042)

also
![Screen Shot 2024-08-15 at 2 04 34 AM](https://github.com/user-attachments/assets/0e790170-1c93-4cb0-87f3-24dda6d2e813)

</p>
</details>

**Comment by tokebe** [comment]
More detail on the dropped-edges problem:

We're considering this a sub-issue of this one. In the initial implementation of direct-edge special handling, it was erroneously assumed that one-hop template results would only bind one edge. This means that all other edges were not added to the merged result. Because scoring is merged and not re-calculated, this means that scores appeared incorrect for the new number of edges on a given result.

This problem is solved in the related code.

**Comment by colleenXu** [comment]
Note: In the opening post, I'm collecting the feedback issues that would be addressed partially or fully by this issue's fix. Others can edit that post to add more.

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
