### ISSUE TITLE
Investigate mongodb as a persistant data storage

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#84]
It's a good feature to store user request persistently, so users can come back and look up their results just using the answer id we assign to them.

We could also hook this up with the web interface. Given an answer id, the UI can fetch results directly from mongodb and display the results as graph/table for exploration.

**Comment by kevinxin90** [comment]
This should also be done using MongoDB docker image.

Along with .env to store all credentials/urls

**Comment by colleenXu** [comment]
Not sure if this is still relevant or not

**Comment by andrewsu** [comment]
given our current ongoing work with a redis cache, going to close this issue.
