### ISSUE TITLE
BTE raising odd TypeError, not doing sub-queries for some automated test queries

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#842]
During automated test runs, BTE sometimes raises this error: `TypeError: Cannot read properties of undefined (reading 'endsWith') while configuring query.`Then, BTE appears to skip constructing some sub-queries and continue execution. In some cases, it'll terminate the template query it's on because it doesn't execute any sub-queries/find any records for the QEdge it's executing. 

Based on limited looking, this is only happening to MVP2 queries (chem-increases or decreases - gene) and with Automat KP MetaEdges. This has been happening since 7/7. **I think this has caused us to sporadically fail tests.** 

Note: Jackson and I have wondered if there's something going on with the SmartAPI registry or those Automat KP meta_knowledge_graph data and ingestion...

**Examples**

<details><summary>All cases from the latest run, 7/28</summary>
<p>

chem decreases CYP2D6 (NCBIGene:1565)
ARAX PK: [aa28c8cc-4b77-41b4-b056-f6ace6e1d8d9](https://arax.ncats.io/?r=aa28c8cc-4b77-41b4-b056-f6ace6e1d8d9)
BTE PK: `8f6388dd-1f7d-454b-a2f7-8b2cbc5b9c58`
BTE asyncquery link: https://bte.ci.transltr.io/v1/asyncquery_response/X5U5rbzo0b

lepirudin (CHEBI:142437) decreases gene
ARAX PK: [239f3820-2e67-4334-b401-46a039c1660a](https://arax.ncats.io/?r=239f3820-2e67-4334-b401-46a039c1660a)
BTE PK: `36719645-96a4-49a7-8f9c-bfa3a4fc0150`
BTE asyncquery link: https://bte.ci.transltr.io/v1/asyncquery_response/ZC5XyKkYor

chem decreases HBB (NCBIGene:3043)
ARAX PK: [e869a9dd-aa1b-45a9-9b6b-d682cd0c8beb](https://arax.ncats.io/?r=e869a9dd-aa1b-45a9-9b6b-d682cd0c8beb)
BTE PK: `e869a9dd-aa1b-45a9-9b6b-d682cd0c8beb`
BTE asyncquery link: https://bte.ci.transltr.io/v1/asyncquery_response/FiOIhXvOyl

clofibric acid (CHEBI:34648) increases gene
ARAX PK: [4e4392ce-76c2-45e5-9e85-7967b1b6c820](https://arax.ncats.io/?r=4e4392ce-76c2-45e5-9e85-7967b1b6c820)
BTE PK: `ba4f2ec9-615c-4d52-a4a2-e27e40286985`
BTE asyncquery link: https://bte.ci.transltr.io/v1/asyncquery_response/q1uUGXU4OY

permethrin (CHEBI:34911) increases gene
ARAX PK: [337bea2d-b335-4569-a40f-c8efd6f205b7](https://arax.ncats.io/?r=337bea2d-b335-4569-a40f-c8efd6f205b7)
BTE PK: `ecbae7c0-006b-479e-839c-d7c237589902`
BTE asyncquery link: https://bte.ci.transltr.io/v1/asyncquery_response/PTlHweWtRY

</p>
</details> 

<details><summary>Older examples</summary>
<p>

**7/14** semaglutide (CHEBI:167574) increases gene
ARAX PK: [7a11602e-27ca-4faa-9556-235bfe95ea2a](https://arax.ncats.io/?r=7a11602e-27ca-4faa-9556-235bfe95ea2a)
BTE PK: `5d8b0746-6261-433c-9aeb-7a50279ffe54`
BTE asyncquery link: https://bte.ci.transltr.io/v1/asyncquery_response/gV67Lf6zfH

**7/7** chem decreases CYP2D6 (NCBIGene:1565)
ARAX PK: [2216ddd9-3a09-4a34-afc5-38416798d4ac](https://arax.ncats.io/?r=2216ddd9-3a09-4a34-afc5-38416798d4ac)
BTE PK: `2216ddd9-3a09-4a34-afc5-38416798d4ac`
BTE asyncquery link: https://bte.ci.transltr.io/v1/asyncquery_response/907szwXb3d

</p>
</details>

**Comment by colleenXu** [comment]
This was also noted in https://github.com/biothings/biothings_explorer/issues/835#issuecomment-2237995242, as a potential contributor

**Comment by colleenXu** [comment]
@tokebe Was this supposed to be closed? 

I thought Test/Prod may also have this issue and need this code deployed?

**Comment by colleenXu** [comment]
Fix seems to work, based on a quick check. 

I ran two example queries locally (main branches) and looked at the logs: it looks like Automat APIs are being queried now and we now have Automat edges in our response sometimes. 
* permethrin (CHEBI:34911) increases gene - I see Automat edges in the response
* chem decreases HBB (NCBIGene:3043) - I don't see Automat edges in the response, but I see logs that they were queried.

**Comment by tokebe** [comment]
Relevant changes deployed to Prod.
