### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by NeuralFlux** [biothings/biothings_explorer#846]
Refactor code and/or tests to pass test runs

1. bte-server
    - [x] updated workflow config
    - [ ] all checks passing
3. api-response-transform
    - [x] updated workflow config
    - [x] all checks passing
5. call-apis
    - [x] updated workflow config
    - [x] all checks passing
7. query-graph-handler
    - [x] updated workflow config
    - [x] all checks passing
9. node-expansion
    - [x] updated workflow config
11. biomedical-id-resolver
    - [x] updated workflow config
    - [x] all checks passing

**Comment by tokebe** [comment]
(Just noting for anyone else, this is regarding the jest tests that are run by github actions, not the testing harness)

**Comment by rjawesome** [comment]
Note: Currently, the github actions fails in most pull requests before tests are even run (ie. https://github.com/biothings/bte_trapi_query_graph_handler/actions/runs/10256692101/job/28376308388 ). In this example the branch `fix-record-filter` only exists on the query_graph_handler repo.

My guess at why it is failing is because in the GitHub Actions script, it expects the branch to exist on the main biothings_explorer repository: however, the branch may only exist on one of the packages (ie. query graph handler). Line: https://github.com/biothings/bte_trapi_query_graph_handler/blob/f6eaa70444e76504bb161cb8d0ecfe061ea7a1f8/.github/workflows/test_ws_codecov.yml#L19

**Comment by NeuralFlux** [comment]
For that particular issue, I feel these are potential solutions:

1. Leave as is, make sense of tests on common branches only, like `main` and `dev`
2. Default to pulling `main` from the main repo if branch does not exist
3. Create the branch on the main repo (note: seems unwise to do this in a GitHub Action)

**Comment by tokebe** [comment]
This is absolutely a mistake on my part in writing the github actions -- @NeuralFlux's solution 2 is the intended behavior and should be implemented as the fix. 

The point originally was that, since we require the entirety of the BTE workspace to adequately test individual monorepo packages, the workspace must be cloned and set up; Because fixes/new features often depend on multiple packages, branches addressing the same issue should have the same name, so they can be checked out together for testing. If the main repo doesn't have the given branch, it should default to main, just like every other monorepo package.

**Comment by NeuralFlux** [comment]
Also, I found that some tests in `api-response-transform` package aren't going through. [Example](https://github.com/biothings/biothings_explorer/actions/runs/10270155003/job/28417248769#step:6:571)

```ts
> @biothings-explorer/api-response-transform@1.12.0 test-cov /home/runner/work/biothings_explorer/biothings_explorer/packages/api-response-transform
> jest --coverage --env node

PASS __test__/base_transformer.test.ts (42.784 s)
PASS __test__/transformers.test.ts (43.739 s)
PASS __test__/biothings_transformer.test.ts (44.802 s)
PASS __test__/record.test.ts
PASS __test__/semmed_transformer.test.ts
PASS __test__/ctd_transformer.test.ts
FAIL __test__/biolink_transformers.test.ts (6.574 s)
  ● test biolink transformer › test biolink wrapper

    expect(received).toBe(expected) // Object.is equality

    Expected: "10956"
    Received: undefined

      23 |     const tf = new jq_tf(input, { type: "biolink" });
      24 |     const res = await tf.wrap(response);
    > 25 |     expect(res.associations[0].object.HGNC).toBe("10956");
         |                                             ^
      26 |     expect(res.associations[0].publications[0].id).toBe("21685912");
      27 |     expect(res.associations[1]).not.toHaveProperty("publications");
      28 |     expect(res.associations[1]).not.toHaveProperty("provided_by");

      at Object.<anonymous> (__test__/biolink_transformers.test.ts:25:45)

  ● test biolink transformer › test biolink wrapper if no object id should be prefixed

    expect(received).toEqual(expected) // deep equality

    Expected: "MONDO:12345"
    Received: undefined

      46 |       ],
      47 |     });
    > 48 |     expect(res.associations[0].object.MONDO).toEqual("MONDO:12345");
         |                                              ^
      49 |   });
      50 |
      51 |   test("test biolink wrapper if no object field present", async () => {

      at Object.<anonymous> (__test__/biolink_transformers.test.ts:48:46)

  ● test biolink transformer › test biolink jsonTransform function

    expect(received).toEqual(expected) // deep equality

    Expected: "10956"
    Received: undefined

      84 |     const res: JSONDoc = tf.jsonTransform(wrapped_response);
      85 |     expect(res).toHaveProperty("related_to");
    > 86 |     expect(res.related_to[0].HGNC).toEqual("10956");
         |                                    ^
      87 |     expect(res.related_to[0].pubmed[0]).toEqual("21685912");
      88 |     expect(res.related_to[0].relation).toEqual("contributes to condition");
      89 |     expect(res.related_to[0].source[0]).toEqual("https://archive.monarchinitiative.org/#gwascatalog");

      at Object.<anonymous> (__test__/biolink_transformers.test.ts:86:36)

```

**Comment by NeuralFlux** [comment]
I am able to fix the first two tests using
```ts
// test 1
expect(res.associations[0].object.id).toBe("HGNC:10956");
expect(res.associations[0].publications[0].id).toBe("PMID:21685912");

// test 2
expect(res.associations[0].object.id).toEqual("MONDO:12345");
```

For the last one, I get
```ts
res.related_to[0] = {
   "pubmed":[
      "PMID:21685912",
      "PMID:30089514"
   ],
   "relation":"contributes to condition",
   "source":[
      "https://archive.monarchinitiative.org/#gwascatalog"
   ],
   "taxid":"NCBITaxon:9606"
}
```

It doesn't have `HGNC` anywhere. Could this be due to changes in the biolink transform function?

**Comment by NeuralFlux** [comment]
I noticed @rjawesome [got rid of some tests](https://github.com/biothings/api-respone-transform.js/commit/71df55149d34b6c6ebc1afb199965100bd9fbbb4#diff-4bc6ebccf8cde00bb6341701b601b2659a973545954fb14aa900d21f93bc0958) in the package repo. I believe that solves the issue too.

**Comment by tokebe** [comment]
For now, you can ignore/remove the biolink transformer tests.

**Comment by tokebe** [comment]
Deployed all to dev, merged those without src changes or failing tests directly. Those with code changes will be merged tomorrow assuming Sentry doesn't catch anything strange.

**Comment by NeuralFlux** [comment]
edit: task list added to issue's root comment

Could not resolve failing checks in `bte-server` despite thorough debugging of requests and responses to/from CI. Checks pass on local machine. Check for `push` [passes](https://github.com/biothings/bte-server/pull/35) on copied fix branch, whereas that for `pr` [passes](https://github.com/biothings/bte-server/pull/33) on fix branch. Failing checks fail by throwing `403 Forbidden` from CI.

**Comment by NeuralFlux** [comment]
Fixed tests for all packages except for `bte-server`. Closing issue for now as it is not priority.
