### ISSUE TITLE
PFOCR result-augmentation: adding chem/disease support

### ISSUE THREAD

**Issue by AlexanderPico** [biothings/biothings_explorer#847]
We've been assessing the result-level enrichment/augmentation with PFOCR hits. The output today has some consistent issues:
 * Too many hits (burden on performance?)
 * Low quality, irrelevant hits

In parallel, we've been assessing the edge retrieval hits on the same queries and have been pleasantly surprised by the quality. This observation suggests some specific refinements we might pursue...

Using an MVP2 query of "Genes increased by Bivalirudin" as an example, currently, we [`traverseResultForNodes`](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/src/results_assembly/pfocr.ts#L148C10-L148C32) to collect a set of genes, including subject and object (answer) nodes, along with any intermediate nodes (from 2-hop), and then perform an intersection. We require a `MATCH_COUNT_MIN` = 2 and calculate a score based on precision and recall.

This is too relaxed. We end up with a ton of hits having 2 matching CURIES, sometimes not include either of the original subject or object nodes. Each of these on their own is a fairly weak and useless finding for researchers.

Proposals:
1. Focus on subject _and_ object nodes. **Once we are able to consider chemicals and diseases**, then we could perform an  intersection where `resultCuries` are restricted to just those two nodes. This would dramatically reduce the number of PFOCR hits, while dramatically increasing their relevance.
   * We could follow-up these hits with a secondary intersection including the other nodes from `traverseResultForNodes` in order to get a total `resultGenesInFigure` to be used in the calculation of precision, i.e., for scoring. Both the traversal and the secondary intersection would _only_ be performed on the subset of figures that pass the first intersection, so this might be faster as well.
2. I suspect the calculation of [`resultGenesInOtherFigures`](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/src/results_assembly/pfocr.ts#L272) is time consuming. If so, we could skip it and rely solely on precision to calculate a score.

**Comment by AlexanderPico** [comment]
Alt proposal:  We keep the current enrichment algo as-is, applied to all nodes from `traverseResultForNodes` and then add a secondary filter to only keep hits that contain both the input entity (subject) and answer (object).  

Advantages: 
 * Easier to implement given existing code base, i.e., just add a filter step 
 * More flexible solution that could be adapted to require only input entity _or_ answer, for example

Disadvantages:
 * Might be slower? Not sure about this actually.

**Comment by tokebe** [comment]
Given the times we're seeing with the present queries to BioThings PFOCR (>15 seconds per batch), it makes more sense to me to reduce back down to just querying for subject and object, and then doing a secondary `traverseResultsForNodes` for better scoring.

**Comment by tokebe** [comment]
As of https://github.com/biothings/bte_trapi_query_graph_handler/pull/211, we are no longer traversing the entire result for nodes, instead just looking at direct result-bound nodes. We do traverse results after to increase the node pool, which is used for relevancy ranking. Additionally, the scoring function has been made less expensive in https://github.com/biothings/bte_trapi_query_graph_handler/pull/207

So, the scope of this issue is changed to two objectives:
- [ ] Fix behavior in creative mode so enrichment only occurs at the end (this will prevent template-related figures that are not necessarily matching the creative-result nodes) (https://github.com/biothings/bte_trapi_query_graph_handler/pull/217)
- [ ] Add additional node type support so we can do enrichment on more types of queries

**Comment by AlexanderPico** [comment]
We have a positive control query for this use case. 

Query: What gene's activity may be increased by D-glucose (mesh:D005947)
https://ui.transltr.io/results?l=D-glucose&i=CHEBI:4167&t=3&r=0&q=016a2584-62b1-45b7-b9e3-e83fc6ffbe0c 

One of the top results from BTE is EGFR (ncbigene:1956) and I can confirm that the PFOCR KP includes at least 82 figures that contain both the chemical and gene, e.g., https://biothings.ci.transltr.io/pfocr/query?q=associatedWith.pmc:PMC7718646

As expected, as of today, we are not returning any PFOCR results for this query due to the limitation of node type support (i.e., ncbigene only). Once we have the expanded node type support including chemicals, then this query would serve as a positive control.

**Comment by colleenXu** [comment]
Update! 

chebi (chem) and doid (disease) fields are live on pending-BioThings CI right now. 

Here are examples:
* [have both chebi + mesh IDs for chem](https://biothings.ci.transltr.io/pfocr/query?q=_exists_:associatedWith.mentions.chemicals.chebi%20AND%20_exists_:associatedWith.mentions.chemicals.mesh)
* [have both doid + mesh IDs for disease](https://biothings.ci.transltr.io/pfocr/query?q=_exists_:associatedWith.mentions.diseases.doid%20AND%20_exists_:associatedWith.mentions.diseases.mesh)

**Comment by colleenXu** [comment]
adding chem and disease support is more complex than genes were:
* more namespaces involved: mesh/chebi (chem only)/doid (disease only)
* more biolink categories involved (chem = lots of categories, not sure about disease - prob not)

---

UPDATE!

We also have support for DiseaseOrPhenotypicFeature and all its descendants (not just Disease). It works the same way as Disease (some entities aren't Disease according to NodeNorm. But they have MESH/DOIDs that are found in PFOCR's data under `disease`). 

The mappings:

```
const SUPPORTED_TYPES = {
  Gene: 'genes',
  ChemicalEntity: 'chemicals',
  DiseaseOrPhenotypicFeature: 'diseases',
};
```

**Comment by colleenXu** [comment]
## Testing MVP2 

<details><summary>I used this query: "chem that decrease CYP2D6"</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "start": {
                    "categories": ["biolink:ChemicalEntity"]
                },
                "end": {
                    "categories": ["biolink:Gene"],
                    "ids": ["NCBIGene:1565"]
                }
            },
            "edges": {
                "t_edge": {
                    "subject": "start",
                    "object": "end",
                    "predicates": ["biolink:affects"],
                    "knowledge_type": "inferred",
                    "qualifier_constraints": [
                        {
                            "qualifier_set": [
                                {
                                    "qualifier_type_id": "biolink:qualified_predicate",
                                    "qualifier_value": "biolink:causes"
                                },
                                {
                                    "qualifier_type_id": "biolink:object_aspect_qualifier",
                                    "qualifier_value": "activity_or_abundance"
                                },
                                {
                                    "qualifier_type_id": "biolink:object_direction_qualifier",
                                    "qualifier_value": "decreased"
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

</p>
</details> 

According to the console logs:
```
  bte:biothings-explorer-trapi:pfocr 56 PFOCR figures match at least 2 nodes from any TRAPI result +4ms
  bte:biothings-explorer-trapi:pfocr 0 results had pfocr figures truncated to max of 20 (0 unique figures removed, 0 not appearing elsewhere in results). +52ms
  bte:biothings-explorer-trapi:pfocr 24 results successfully enriched with 56 unique PFOCR figures. +0ms
```

[Saved response](https://github.com/user-attachments/files/17548745/10_28_decreasesCYP2D6.json.zip)


### Observations (no problems with these)


#### (1) matchedCuries may include multiple IDs for the same entity (and these may not include the primary ID). 

This happens with chem/disease entities because they may have multiple IDs that are matched/found in a PFOCR figure (think of multiple CHEBI/MESH IDs for 1 chem, multiple DOID/MESH for 1 disease). 
Reminder: we do ensure that at least 1 ID for the chem/disease MUST be present in the figure. 

<details><summary>Ex: 252nd result, 1st figure</summary>
<p>

For the Chemical node `CHEBI:9463`, the figure had the IDs `CHEBI:17347` and `MESH:D013739` (these are equivalent/synonymous IDs of the primary ID). 

```
{
  "figureUrl": "https://europepmc.org/articles/PMC2677552/bin/nihms108007f3.jpg",
  "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC2677552__nihms108007f3.html",
  "pmc": "PMC2677552",
  "matchedCuries": [
    "CHEBI:17347",
    "MESH:D013739",
    "NCBIGene:1565"
  ],
  "matchedKGNodes": [
    "CHEBI:9463",
    "NCBIGene:1565"
  ],
  "score": 0.23076923076923075
}
```

</p>
</details> 

#### (2) Sometimes figures with more matching IDs can be scored lower than those with less matching IDs

That's fine; score may be lower if the figure with more matching IDs has a lot more total IDs. See [presentation slide 9](https://docs.google.com/presentation/d/1BZ-yTtnhDX8lpm9Xtj4tlpFpli1S_O6690SBp8Ac7QU/edit#slide=id.g30e856abb99_0_210)

<details><summary>Ex: 3rd result, compare 1st figure to 9th figure</summary>
<p>

First figure:
```
{
  "figureUrl": "https://europepmc.org/articles/PMC2998292/bin/ijmeg0001-0332-f2.jpg",
  "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC2998292__ijmeg0001-0332-f2.html",
  "pmc": "PMC2998292",
  "matchedCuries": [
    "CHEBI:41774",
    "MESH:D013629",
    "NCBIGene:1565"
  ],
  "matchedKGNodes": [
    "CHEBI:41774",
    "NCBIGene:1565"
  ],
  "score": 0.42857142857142855
}
```

9th figure:
```
{
  "figureUrl": "https://europepmc.org/articles/PMC2998292/bin/ijmeg0001-0332-f1.jpg",
  "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC2998292__ijmeg0001-0332-f1.html",
  "pmc": "PMC2998292",
  "matchedCuries": [
    "CHEBI:41774",
    "MESH:D013629",
    "NCBIGene:1565",
    "NCBIGene:1549",
    "NCBIGene:1548",
    "NCBIGene:1553"
  ],
  "matchedKGNodes": [
    "CHEBI:41774",
    "NCBIGene:1565",
    "NCBIGene:1549",
    "NCBIGene:1548",
    "NCBIGene:1553"
  ],
  "score": 0.1904761904761905
}
```

</p>
</details>

**Comment by colleenXu** [comment]
## Testing MVP1

<details><summary>I used this query: Cowden disease</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "SN": {
                    "categories":["biolink:ChemicalEntity"]
                },
                "ON": {
                    "ids":["MONDO:0016063"]
               }
            },
            "edges": {
                "e01": {
                    "subject": "SN",
                    "object": "ON",
                    "predicates": ["biolink:treats"],
                    "knowledge_type": "inferred"
                }
            }
        }
    }
}
```

</p>
</details> 

According to the console logs:

```
  bte:biothings-explorer-trapi:pfocr 11 PFOCR figures match at least 2 nodes from any TRAPI result +3ms
  bte:biothings-explorer-trapi:pfocr 0 results had pfocr figures truncated to max of 20 (0 unique figures removed, 0 not appearing elsewhere in results). +333ms
  bte:biothings-explorer-trapi:pfocr 19 results successfully enriched with 11 unique PFOCR figures. +0ms
```

[Saved response](https://github.com/user-attachments/files/17553063/10_28_Cowden.json.zip)

### Observations

#### (1) matchedCuries has multiple IDs for the chemical and disease in the main node-binding

<details><summary>Ex: 81st result</summary>
<p>

In `matchedCuries`:
* For the chemical (Ketamine), both the primary "CHEBI:6121" and "MESH:D007649" were found in the figure
* For the main disease in the node-binding, both "DOID:6457" and "MESH:D006223" were found in the figure

```
{
  "node_bindings": {
    "SN": [
      {
        "id": "CHEBI:6121",
        "attributes": []
      }
    ],
    "ON": [
      {
        "id": "MONDO:0016063",
        "attributes": []
      }
    ]
  },
  "analyses": [
    {
      "resource_id": "infores:biothings-explorer",
      "edge_bindings": {
        "e01": [
          {
            "id": "inferred-CHEBI:6121-treats-MONDO:0016063",
            "attributes": []
          }
        ]
      },
      "score": 0.9898295903965358
    }
  ],
  "pfocr": [
    {
      "figureUrl": "https://europepmc.org/articles/PMC7102936/bin/nihms-1559311-f0007.jpg",
      "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC7102936__nihms-1559311-f0007.html",
      "pmc": "PMC7102936",
      "matchedCuries": [
        "CHEBI:6121",
        "MESH:D007649",
        "DOID:6457",
        "DOID:1826",
        "MESH:D006223",
        "MESH:D001321",
        "MESH:D004827",
        "NCBIGene:6794",
        "NCBIGene:207",
        "NCBIGene:2475",
        "NCBIGene:5728"
      ],
      "matchedKGNodes": [
        "CHEBI:6121",
        "MONDO:0016063",
        "MONDO:0005027",
        "MONDO:0005260",
        "NCBIGene:6794",
        "NCBIGene:207",
        "NCBIGene:2475",
        "NCBIGene:5728"
      ],
      "score": 0.23404255319148937
    }
  ]
}
```

</p>
</details> 

#### (2) Matching intermediate Disease in subgraph 

<details><summary>Ex: 27th result</summary>
<p>

In `matchedCuries`:
* first two IDs for the chemical in the node-binding
* 3rd ID is for the disease in the node-binding
* 4th ID is the MESH ID for an intermediate disease (actually a phenotype of the disease in the node-binding, but NodeNorm says it's a disease itself)

```
{
  "node_bindings": {
    "SN": [
      {
        "id": "CHEBI:27899",
        "attributes": []
      }
    ],
    "ON": [
      {
        "id": "MONDO:0016063",
        "attributes": []
      }
    ]
  },
  "analyses": [
    {
      "resource_id": "infores:biothings-explorer",
      "edge_bindings": {
        "e01": [
          {
            "id": "inferred-CHEBI:27899-treats-MONDO:0016063",
            "attributes": []
          }
        ]
      },
      "score": 0.9919252577408234
    }
  ],
  "pfocr": [
    {
      "figureUrl": "https://europepmc.org/articles/PMC8457357/bin/nihms-1729236-f0001.jpg",
      "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC8457357__nihms-1729236-f0001.html",
      "pmc": "PMC8457357",
      "matchedCuries": [
        "CHEBI:27899",
        "MESH:D002945",
        "MESH:D006223",
        "MESH:D009369"
      ],
      "matchedKGNodes": [
        "CHEBI:27899",
        "MONDO:0016063",
        "MONDO:0005070"
      ],
      "score": 0.13559322033898305
    }
  ]
}
```

</p>
</details>

**Comment by colleenXu** [comment]
## Testing Pathfinder

<details><summary>I used this query: Pathfinder example 5</summary>
<p>

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["NCBIGene:3458"],
          "name": "IFNG (interferon gamma gene)"
        },
        "un": {
          "categories": ["biolink:NamedThing"]
        },
        "n2": {
          "ids": ["CHEBI:16828"],
          "name": "Tryptophan"
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "un",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e1": {
          "subject": "un",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e2": {
          "subject": "n0",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        }
      }
    }
  }
} 
```

</p>
</details> 

According to the console logs:
```
  bte:biothings-explorer-trapi:pfocr 5 PFOCR figures match at least 2 nodes from any TRAPI result +1ms
  bte:biothings-explorer-trapi:pfocr 0 results had pfocr figures truncated to max of 20 (0 unique figures removed, 0 not appearing elsewhere in results). +51ms
  bte:biothings-explorer-trapi:pfocr 61 results successfully enriched with 5 unique PFOCR figures. +0ms
```

[Saved response](https://github.com/user-attachments/files/17553159/10_28_pf5.json.zip)


### Observations

#### (1) PFOCR result-augmentation can happen when only 2 Nodes are supported (out of 3 total Nodes in node-bindings) 

<details><summary>Ex: 287th result</summary>
<p>

In the node-bindings, 1 Node isn't a supported type: `UniProtKB:P26718` (Protein). 

```
{
  "n0": [
    {
      "id": "NCBIGene:3458",
      "attributes": []
    }
  ],
  "n2": [
    {
      "id": "CHEBI:16828",
      "attributes": []
    }
  ],
  "un": [
    {
      "id": "UniProtKB:P26718",
      "attributes": []
    }
  ]
}
```

The matched figures use the other two Nodes in the node-bindings:

```
{
  "figureUrl": "https://europepmc.org/articles/PMC3748765/bin/toxsci_kft140_f0001.jpg",
  "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC3748765__toxsci_kft140_f0001.html",
  "pmc": "PMC3748765",
  "matchedCuries": [
    "CHEBI:16828",
    "MESH:D014364",
    "NCBIGene:3458"
  ],
  "matchedKGNodes": [
    "CHEBI:16828",
    "NCBIGene:3458"
  ],
  "score": 0.3529411764705882
}
```

</p>
</details> 

---

Note: I also got PFOCR result-augmentation when running Pathfinder example 3. There were other Pathfinder queries that didn't have any PFOCR result-augmentation when I ran them. 

<details><summary>Query</summary>
<p>

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["MONDO:0005011"],
          "name": "Crohn disease"
        },
        "un": {
          "categories": ["biolink:NamedThing"]
        },
        "n2": {
          "ids": ["MONDO:0005180"],
          "name": "Parkinsons disease"
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "un",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e1": {
          "subject": "un",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e2": {
          "subject": "n0",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        }
      }
    }
  }
}
```

</p>
</details> 

[Saved response](https://github.com/user-attachments/files/17553236/latest-pf3-bug.json.zip)

**Comment by tokebe** [comment]
Related changes deployed to Prod as of 11/13
