### ISSUE TITLE
allow users to specify which APIs to include (or exclude)

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#85]
BTE currently executes queries against all available APIs. I think that should remain the default, but the ability for users to manually specify filters to include (or exclude) might be a useful feature.

**Comment by kevinxin90** [comment]
This is one solution to this feature: https://github.com/biothings/biothings_explorer/blob/smartapi-comply/jupyter%20notebooks/Demo%20of%20Including%20Or%20Excluding%20APIs%20in%20BTE.ipynb

**Comment by andrewsu** [comment]
This looks great. Anything else you wanted to accomplish in this issue?  If not, I think adding a mention of this feature to https://biothings-explorer.readthedocs.io/en/latest/ would be the only thing to do before closing...

**Comment by kevinxin90** [comment]
In our [TRAPI Interface](https://smart-api.info/ui/dc91716f44207d2e1287c727f281d339), we currently have two endpoints:

1. /smartapi/{smartapi_id}/query
2. /source/{source_name}/query

which allow users to perform queries based on specific API (1), or based on specific data source (2)
