### ISSUE TITLE
using query_id for creative-mode when input ID isn't the primary one

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#855]
#815's fix addressed non-creative-mode queries, which is currently the main situation where BTE gets non-primary IDs in queries (other ARAs querying "Service-Provider" endpoints and not using primary IDs). 

[But it didn't address creative-mode queries.](https://github.com/biothings/biothings_explorer/issues/815#issuecomment-2306670025) This is an edge-case, since right now BTE mainly receives creative-mode queries from the UI -> ARS - and the UI only sends primary IDs (relies on NameResolver). Theoretically we could get creative-mode queries w/ non-primary IDs if someone queried the ARS or BTE directly.

**Comment by NeuralFlux** [comment]
@colleenXu can you please add the query you tried [here](https://github.com/biothings/biothings_explorer/issues/815#issuecomment-2306670025)?

**Comment by colleenXu** [comment]
@NeuralFlux 

<details><summary>Here's a quick one (runs in <20 s)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "start": {
                    "categories": ["biolink:ChemicalEntity"],
                    "ids": ["UNII:Y43GF64R34"]
                },
                "end": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "t_edge": {
                    "subject": "start",
                    "object": "end",
                    "predicates": ["biolink:affects"],
                    "knowledge_type": "inferred",
                    "qualifier_constraints": [
                        {
                            "qualifier_set": [
                                {
                                    "qualifier_type_id": "biolink:qualified_predicate",
                                    "qualifier_value": "biolink:causes"
                                },
                                {
                                    "qualifier_type_id": "biolink:object_aspect_qualifier",
                                    "qualifier_value": "activity_or_abundance"
                                },
                                {
                                    "qualifier_type_id": "biolink:object_direction_qualifier",
                                    "qualifier_value": "decreased"
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

</p>
</details> 

The starting entity is lepirudin `UNII:Y43GF64R34`, when the primary ID from NodeNorm is currently `CHEBI:142437`. 

Note that NodeNorm CI is updating soon, so primary IDs might change:

> Hi everybody! I'm planning to upgrade [NodeNorm CI](https://nodenorm.ci.transltr.io/docs) and [NameLookup CI](https://name-lookup.ci.transltr.io/docs) to the Guppy release this Monday, August 26 starting at 5pm ET. We should be down for around 4 hours, during which both node normalization and UI autocorrect will be down. If this is a bad time for CI to be down, please let me know and I'll reschedule! I'll provide updates to [#outages](https://ncatstranslator.slack.com/archives/C05V62WGV9P).

**Comment by colleenXu** [comment]
@NeuralFlux Let me know if you want more. Maybe one starting with gene or starting with disease ID.

**Comment by NeuralFlux** [comment]
Great, thank you!

**Comment by NeuralFlux** [comment]
The fix from #815 is working while debugging, but looks like the result is not updating in-place [here](https://github.com/biothings/bte_trapi_query_graph_handler/blob/fc8e3c8c24bb379b0d6484bf6a6b3b059d4fecbc/src/index.ts#L356). Is this a JavaScript gotcha?

Value of result while debugging:
```js
{
  node_bindings: {
    creativeQuerySubject: [
      {
        id: "CHEBI:142437",
        attributes: [
        ],
        query_id: "UNII:Y43GF64R34",  // successfully catching this
      },
    ],
    creativeQueryObject: [
      {
        id: "NCBIGene:2147",
        attributes: [
        ],
      },
    ],
  },
  analyses: [
    {
      resource_id: "infores:biothings-explorer",
      edge_bindings: {
        eA: [
          {
            id: "701b1490ed6dbffe714c412332892737",
            attributes: [
            ],
          },
          {
            id: "75ca9d529dab136edc273c9001f5a797",
            attributes: [
            ],
          },
          {
            id: "18756253678c8883183d857d6c606064",
            attributes: [
            ],
          },
          {
            id: "5f9c4cf6b7e1e437f1bd4c0a706d7d1d",
            attributes: [
            ],
          },
          {
            id: "3749f65d563b7f3be1d908f6147a8030",
            attributes: [
            ],
          },
        ],
      },
      score: 0.7800124849497231,
    },
  ],
}
```

**Comment by NeuralFlux** [comment]
Nvm, it was because `InferredQueryHandler` was not populating `query_id`

**Comment by tokebe** [comment]
Related changes deployed to Prod as of 11/13
