### ISSUE TITLE
part 1: review/add Translator resources to BTE's API list

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#865]
Long ago we made a principled decision that we would use an [API allow list](https://github.com/biothings/bte-server/blob/main/config/api_list.yaml) to define what resources BTE would include. We should revisit that decision to make sure we still agree that's the right choice.  And if so, we should review resources that are not currently being called by BTE for possible inclusion in our API allow list.

**Comment by colleenXu** [comment]
UPDATE: 

I made a [minimal list of APIs BTE isn't using right now](https://docs.google.com/spreadsheets/d/13mTPYFQ1ioDBwZQN3P7YfAYypWK7ndlE5NUdaq62je8/edit?usp=sharing). This includes TRAPI KPs and APIs with x-bte that are also tagged `translator`. 

We decided to...

**Try adding** 5 TRAPI KPs that I was able to retrieve edges from thru BTE in manual testing: https://github.com/biothings/bte-server/pull/43
* automat robokop (remove all other automats in favor of using this to access all resources)
* multiomics clinical trials (TRAPI from Plover) - see https://github.com/biothings/biothings_explorer/issues/861#issuecomment-2378816912
* multiomics drug approvals (TRAPI from Plover)
* multiomics microbiome kp (TRAPI from Plover)
* multiomics kp (TRAPI from Plover)

**Considering, see [Part 2](https://github.com/biothings/biothings_explorer/issues/885)**...
* genetics provider: ~`meta_knowledge_graph` response edges' `knowledge_types` is empty array. **Sent Translator Slack message in reasonerapi channel**. Aragorn doesn't have issues with it.~
* Knowledge Collaboratory: ~ARAX team reports that this API always errors out, takes 30s to respond with 500 error https://github.com/NCATSTranslator/Feedback/issues/946~
* OpenPredict: ~ARAX team reports that this API often errors out, takes 60s to respond with 504 error https://github.com/NCATSTranslator/Feedback/issues/947~
* MolePro: Queries to it timeout often, and adds wait time. And we may be querying it more with the record limit, parallel features.

**Wait on**...
* 2 TRAPI KPs that I had issues with during manual testing:
    * RTX-KG2: [previously identified problems with BTE's retrieved edges](https://github.com/BioPack-team/retriever/pull/2#issuecomment-2130753808). Haven't discovered cause yet. Aragorn doesn't have issues with it. 
    * text-mined co-occurrence: uncompatible TRAPI version (1.4) + `meta_knowledge_graph` response edges' `knowledge_types` is `null`. **Sent Translator Slack message in reasonerapi channel**
* 1 TRAPI KP that ARAX + Aragorn have had issues with:
    * SPOKE: ARAX team reports that this API often errors out within 1s https://github.com/NCATSTranslator/Feedback/issues/948

**Don't add (for now):** The in-limbo APIs with x-bte
* PharmGKB https://github.com/biothings/biothings_explorer/issues/556
* RaMP https://github.com/biothings/biothings_explorer/issues/705

**Comment by colleenXu** [comment]
Marc Duby has reported that Genetics KP CI has a fix for `knowledge_types` ([Translator Slack](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1727897757172549?thread_ts=1727276403.712369&cid=C0156TX0VB2)). I haven't checked yet. 

I'm assuming adding this KP would be for the next sprint, not this one...

**Comment by tokebe** [comment]
Yeah, I don't think we want to rush adding new KPs...

**Comment by colleenXu** [comment]
This issue is to track the 5 KPs we did add to BTE https://github.com/biothings/biothings_explorer/issues/865#issuecomment-2372978205
* automat robokop (remove all other automats in favor of using this to access all resources)
* multiomics clinical trials (TRAPI from Plover) - see https://github.com/biothings/biothings_explorer/issues/861#issuecomment-2378816912
* multiomics drug approvals (TRAPI from Plover)
* multiomics microbiome kp (TRAPI from Plover)
* multiomics kp (TRAPI from Plover)

**Comment by colleenXu** [comment]
Given urgent issues with BTE timeouts: going to remove MolePro. Queries to it timeout often, and adds wait time. And we may be querying it more with the record limit, parallel features. https://github.com/biothings/bte-server/pull/49

Already adjusted [main comment](https://github.com/biothings/biothings_explorer/issues/865#issuecomment-2372978205)

**Comment by tokebe** [comment]
Related changes deployed to Prod as of 11/13

**Comment by colleenXu** [comment]
Update!

In the Nov hot-fix period (deployed to all instances), we reverted some of these additions https://github.com/biothings/bte-server/pull/52. This improved how BTE did in the weekly automated test runs. 

**So here's the actual list of KPs we added to BTE:**
* multiomics clinical trials (TRAPI from Plover) - see https://github.com/biothings/biothings_explorer/issues/861#issuecomment-2378816912
* multiomics microbiome kp (TRAPI from Plover)
* multiomics kp (TRAPI from Plover)

**Comment by colleenXu** [comment]
## And here's an updated summary of APIs BTE isn't using right now...

### Haven't tested yet:
* Genetics Provider: fixed previous issue where `meta_knowledge_graph` response edges' `knowledge_types` was empty array
* Knowledge Collaboratory: had [issue](https://github.com/NCATSTranslator/Feedback/issues/946), was addressed
* OpenPredict: had [issue](https://github.com/NCATSTranslator/Feedback/issues/947), was addressed
* some individual automats (narrow down which resources help with automated-test-run performance and which don't?) 
* text-mined co-occurrence: dev/CI have been updated to TRAPI 1.5/adjusted `knowledge_types`. Other instances probably haven't been updated. 
    * Older note: uncompatible TRAPI version (1.4) + `meta_knowledge_graph` response edges' `knowledge_types` is `null`. **Sent Translator Slack message in reasonerapi channel**

### Tried but had issues and reverted use:
* MolePro: Queries to it timeout often, and adds wait time -> contribute to BTE timing out? 
* automat robokop: [had a dip in PASSING tests during automated test runs](https://github.com/biothings/bte-server/pull/52)
* multiomics drug approvals (TRAPI from Plover): [had a dip in PASSING tests during automated test runs](https://github.com/biothings/bte-server/pull/52)

### Don't add (for now)
* The in-limbo APIs with x-bte
    * PharmGKB https://github.com/biothings/biothings_explorer/issues/556
    * RaMP https://github.com/biothings/biothings_explorer/issues/705
* TRAPI KPs that I had issues with during manual testing:
    * RTX-KG2: [previously identified problems with BTE's retrieved edges](https://github.com/BioPack-team/retriever/pull/2#issuecomment-2130753808). Haven't discovered cause yet. Aragorn doesn't have issues with it. 
* TRAPI KP that ARAX + Aragorn have had issues with:
    * SPOKE: ARAX team reports that this API often errors out within 1s https://github.com/NCATSTranslator/Feedback/issues/948
