### ISSUE TITLE
PFOCR result-augmentation: adjust logic

### ISSUE THREAD

**Issue by AlexanderPico** [biothings/biothings_explorer#876]
Per [discussion notes](https://docs.google.com/document/d/1tUNVjq_3sjP4ryULHxuavL0xIzbebKTij2eyhevNa1k/edit) and [Slack thread with Gus](https://ncatstranslator.slack.com/archives/C07P6MCH38D/p1727555269841659), we have consensus on the following plans:

**1. Algorithm** - As a general policy/logic, we will identify PFOCR pathway figures that contain _all_ supported-category nodes in the node-bindings ([2 in the case of MVP1/2](https://github.com/biothings/biothings_explorer/issues/837); 3 in the case of Pathfinder). And, obviously, we skip case where there are fewer than 2 supported-category nodes. After passing this minimal requirement, we then include any additional supported-category nodes from the result's aux_graph in the calculation of an enrichment score. **This way all results are relevant to the full context of query and are scored to reflect the inclusion of aux_graph nodes as well.**

 * NOTE: Per [this issue](https://github.com/biothings/biothings_explorer/issues/847), we are expanding the "supported-category nodes" to include Chemicals and Diseases in addition to Genes.

**2. Output location** - The PFOCR hits can continue to go into `message/results/analyses`. No change. 

**3. Structure** - Per [this issue](https://github.com/biothings/biothings_explorer/issues/838), we want to include _two_ URLs per hit, like so...

```
"pfocr": [
    {"matchedCuries": [
         "NCBIGene:8445",
         "NCBIGene:1859",
         "NCBIGene:2932",
         "NCBIGene:2735"
       ],
      "score": 0.2352941176470588,
      "pmc": "PMC2743241",
      "figureUrl": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2743241/bin/nihms-104435-f0001.jpg",
      "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC5463358__fnagi-09-00176-g003.html"
    },
```

**Comment by colleenXu** [comment]
@AlexanderPico 

My understanding is that only point 1 has work that needs doing. And Points 2 + 3 are already done (@tokebe to confirm?)

Work to do:
* implementing new general logic/policy: "all that can match" must match, min 2 
* **adding chem and disease support**. includes mesh/chebi (chem only)/doid (disease only) support

**Comment by colleenXu** [comment]
@AlexanderPico

And I found your "point 1 algorithm wording" a little confusing. Here's my understanding in case it differs from yours...pending @tokebe clarifying things for both of us. 

* Pathfinder results can have **2 or 3** "supported-category" Nodes in node-bindings; both cases should trigger PFOCR result-augmentation. 
* I think from the POV of the "result": a result must have >= 2 "supported-category" Nodes in its node-bindings to **trigger** PFOCR result-augmentation. Then, all of those nodes (node-binding, supported-category) must be present in a PFOCR pathway figure for that figure to be kept as a match. 
    * MVP1/2 results only have 2 Nodes/node-bindings total so both need to be a "supported-category" for trigger, need to be in figure for match
    * **Pathfinder** results have 3 Nodes/node-bindings total. If only 2 are supported-category, then both need to be in figure. If all 3 are supported-category, then all 3 need to be in figure.
* additional nodes from aux-graphs **are included in the `matchingCuries` section** and accounted for in the enrichment scoring.

**Comment by tokebe** [comment]
RE @colleenXu's comments:
- Yes, only point 1 still needs work, and does still need work to implement "All that can match, must match, minimum 2". Currently, only the minimum is respected.
- We'll use the other issue to track adding more node type support.
- Thanks for the clarification, I see no discrepancy between @AlexanderPico's explanation and yours -- yours just gets a little more into implementation procedure and examples.

**Comment by colleenXu** [comment]
@tokebe @AlexanderPico 

I've adjusted the titles of this issue and https://github.com/biothings/biothings_explorer/issues/847 to make it clearer what work is being tracked in each. 

I think this is correct but feel free to change it if it's not correct.

**Comment by colleenXu** [comment]
@AlexanderPico 

The updated PFOCR result-augmentation (this logic + chem/disease support) is **LIVE** on BTE-CI and BTE-Test right now. Sorry for the delay in sharing this news >.<. 

**There's an important difference between the `matchedCuries` field and the new `matchedKGNodes` field!** (I'll provide examples in upcoming posts, but also look at the presentation / response linked below). 
* The UI team should probably use the new `matchedKGNodes` field. It lists the **primary IDs** of the result's KG Nodes that were found in the figure. 
* VS the `matchedCuries` lists the **EXACT** IDs that were found in the figure. This can lead to cases where...
    * The ID isn't the primary ID for the KG Node. Ex: it may include a MESH ID for a chem/disease, which usually isn't the primary ID
    * There's multiple IDs for the same entity/KG node. Ex: a chemical has both a CHEBI + MESH ID and both are in the figure's data. Both IDs will be included in this field. 

I made a [presentation](https://docs.google.com/presentation/d/1BZ-yTtnhDX8lpm9Xtj4tlpFpli1S_O6690SBp8Ac7QU/edit?usp=sharing) for the lab last Fri where I explained the current state of this feature...including examples / walking through [this response](https://github.com/user-attachments/files/17548151/newest-cowden.json.zip). Sharing in case this is helpful for you and your team.

**Comment by colleenXu** [comment]
Note: PFOCR result-augmentation will only show up in certain responses / on certain results. 

It depends on whether PFOCR has data for the combo of chem/disease/gene nodes in the node-bindings. It won't always...

**Comment by colleenXu** [comment]
Note: We also have support for DiseaseOrPhenotypicFeature and its descendants, where we search PFOCR's `disease` data for the MESH/DOIDs.

**Comment by colleenXu** [comment]
## Testing Pathfinder

<details><summary>I used this query: Pathfinder example 5</summary>
<p>

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["NCBIGene:3458"],
          "name": "IFNG (interferon gamma gene)"
        },
        "un": {
          "categories": ["biolink:NamedThing"]
        },
        "n2": {
          "ids": ["CHEBI:16828"],
          "name": "Tryptophan"
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "un",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e1": {
          "subject": "un",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e2": {
          "subject": "n0",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        }
      }
    }
  }
} 
```

</p>
</details> 

According to the console logs:
```
  bte:biothings-explorer-trapi:pfocr 5 PFOCR figures match at least 2 nodes from any TRAPI result +1ms
  bte:biothings-explorer-trapi:pfocr 0 results had pfocr figures truncated to max of 20 (0 unique figures removed, 0 not appearing elsewhere in results). +51ms
  bte:biothings-explorer-trapi:pfocr 61 results successfully enriched with 5 unique PFOCR figures. +0ms
```

[Saved response](https://github.com/user-attachments/files/17553159/10_28_pf5.json.zip)


### Observations

#### (1) PFOCR result-augmentation can happen when only 2 Nodes are supported category (out of 3 total Nodes in node-bindings) 

<details><summary>Ex: 287th result</summary>
<p>

In the node-bindings, 1 Node isn't a supported type: `UniProtKB:P26718` (Protein). 

```
{
  "n0": [
    {
      "id": "NCBIGene:3458",
      "attributes": []
    }
  ],
  "n2": [
    {
      "id": "CHEBI:16828",
      "attributes": []
    }
  ],
  "un": [
    {
      "id": "UniProtKB:P26718",
      "attributes": []
    }
  ]
}
```

The matched figures use the other two Nodes in the node-bindings:

```
{
  "figureUrl": "https://europepmc.org/articles/PMC3748765/bin/toxsci_kft140_f0001.jpg",
  "pfocrUrl": "https://pfocr.wikipathways.org/figures/PMC3748765__toxsci_kft140_f0001.html",
  "pmc": "PMC3748765",
  "matchedCuries": [
    "CHEBI:16828",
    "MESH:D014364",
    "NCBIGene:3458"
  ],
  "matchedKGNodes": [
    "CHEBI:16828",
    "NCBIGene:3458"
  ],
  "score": 0.3529411764705882
}
```

</p>
</details> 

---

Note: I also got PFOCR result-augmentation when running Pathfinder example 3. There were other Pathfinder queries that didn't have any PFOCR result-augmentation when I ran them. 

<details><summary>Query</summary>
<p>

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["MONDO:0005011"],
          "name": "Crohn disease"
        },
        "un": {
          "categories": ["biolink:NamedThing"]
        },
        "n2": {
          "ids": ["MONDO:0005180"],
          "name": "Parkinsons disease"
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "un",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e1": {
          "subject": "un",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        },
        "e2": {
          "subject": "n0",
          "object": "n2",
          "predicates": ["biolink:related_to"],
          "knowledge_type": "inferred"
        }
      }
    }
  }
}
```

</p>
</details> 

[Saved response](https://github.com/user-attachments/files/17553236/latest-pf3-bug.json.zip)

**Comment by colleenXu** [comment]
## Quirk to scoring

Scoring is based on the number of result IDs found in the figure, NOT the number of entities/Nodes found in the figure. And there can be multiple IDs for 1 entity (ex: both a CHEBI and a MESH ID for a chemical). 

This means there's a bias towards figures that have multiple IDs for the same entity. @tokebe and I decided this was fine for now. Not sure if we want to revisit this later.

**Comment by tokebe** [comment]
Related changes deployed to Prod as of 11/13
