### ISSUE TITLE
Store attribute values as array instead of set

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#880]
*First described [here](https://github.com/biothings/biothings_explorer/issues/833#issuecomment-2387227488)*

Because we store attribute values as a set, any value that is supposed to be an additive number (for instance evidence_count) can be added incorrectly if there are duplicate values (as they'd be squashed by the set).

Instead of this, we can change [attribute value storage](https://github.com/biothings/bte_trapi_query_graph_handler/blob/9f27ba7b328b658e961535f5de06848c168d1e04/src/graph/kg_edge.ts#L120-L137) to an Array, and then handle set cases for array-type TRAPI attributes in our [TRAPI attribute generation](https://github.com/biothings/bte_trapi_query_graph_handler/blob/9f27ba7b328b658e961535f5de06848c168d1e04/src/graph/knowledge_graph.ts#L149-L166).

**Comment by tokebe** [comment]
Medium-low priority.

**Comment by rjawesome** [comment]
see pr

**Comment by tokebe** [comment]
Related changes deployed to Prod as of 11/13
