### ISSUE TITLE
register cord19_scigraph_v2 APIs in SmartAPI and BTE

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#90]
Similar to #82, we could also incorporate a similar set of services (gene-chemical-disease) in the `cord19_scigraph_v2` collection from http://automat.renci.org

**Comment by kevinxin90** [comment]
Done. SmartAPI spec available at: https://raw.githubusercontent.com/biothings/biothings_explorer/smartapi-comply/biothings_explorer/smartapi/new_specs/scigraph.json.

Currently in smartapi-comply branch, will merge to master soon.
