### ISSUE TITLE
Create a module to transform TRAPI Query Graph

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#92]
1. Expand node by its id, e.g. if user provides a MONDO ID as input, we will traverse MONDO hierarchy to get all its descendants.
2. Expand node by its category, e.g. if user provides a NamedThing category, we will traverse BioLink class hierarchy to get all descendants of NamedThing class.
3. Expand predicate, e.g. if user provides a related_to predicate, we will traverse BioLink predicate hierarchy to get all descendants of related_to predicate.

**Comment by andrewsu** [comment]
1. no issue created for this yet; Per Kevin (I think), "Can add query graph expansion here: https://github.com/biothings/bte_trapi_query_graph_handler/blob/018bc2fd0b7a1f2a230069b4fecd57841739944e/src/query_graph.js#L86)
2. addressed in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/102
3. being addressed in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/167

**Comment by newgene** [comment]
close this one now. the remaining issue of node expansion is moved into a separate issue: #196
