### ISSUE TITLE
compatibility with networkx 2.4

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#95]
Per discussion with team ARAX @amykglen @dkoslicki in https://ncatstranslator.slack.com/archives/G012W7GTXFS/p1587685669006300...

BTE currently requires networkx 2.3 specifically (networkx 2.4 introduced a number of code-breaking changes to the 2.3 version).  This ticket tracks progress toward version 2.4 compatibility.

**Comment by kevinxin90** [comment]
Fixed in d6a27a097915799b870bacf0aa3495feb15f2f5b

Networkx 2.4 is supported in BTE. Passed all  tests.

@amykglen
